// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "rAIPawnEmParam.h"
#include "../shared/MtAllocator.h"
#include "../shared/MtDTI.h"
#include "../shared/MtMemoryAllocator.h"
#include "../shared/MtObject.h"
#include "../shared/cAIObject.h"
#include "../shared/nDDOUtility.h"
#include "../shared/rTbl2.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* cAIPawnEmNode::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cAIPawnEmNode::usage();

// Address: 0x01a72420 - 0x01a72428 (8 bytes)
const MtDTI& cAIPawnEmNode::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cAIPawnEmNode::DTI;
}

// No out-of-line body: 8 inlined copies in 7 functions (105 bytes)
//   in cAIPawnEmNode::MyDTI::newInstance at 0x0063f974-0x0063f986 (called at rAIPawnEmParam.cpp:60)
//   in cAIPawnEmNode::~cAIPawnEmNode at 0x0063fbcc-0x0063fbd8 (called at rAIPawnEmParam.cpp:60)
//   in _ZN14rAIPawnEmParamD1Ev at 0x0063fc69-0x0063fc75 (called at rAIPawnEmParam.cpp:60)
//   and 5 more (every copy is in <bundle>.inlined.json)
// MtAllocator* cAIPawnEmNode::getAllocator();

// No out-of-line body: no code in the ELF
// void cAIPawnEmNode::setAllocator(u32);

// No out-of-line body: 1 inlined copy in 1 function (44 bytes)
//   in cAIPawnEmNode::MyDTI::newInstance at 0x0063f974-0x0063f9a0 (called at rAIPawnEmParam.cpp:60)
// void* cAIPawnEmNode::operator new(size_t sz, u32 align);

// No out-of-line body: 1 inlined copy in 1 function (41 bytes)
//   in rTbl2<cAIPawnEmNode>::allocData at 0x01a72614-0x01a7263d (called at rTbl2.h:215)
// void* cAIPawnEmNode::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cAIPawnEmNode::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cAIPawnEmNode::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void cAIPawnEmNode::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cAIPawnEmNode::DTI)->memFree(p_addr);
}

// No out-of-line body: 5 inlined copies in 5 functions (120 bytes)
//   in _ZN14rAIPawnEmParamD1Ev at 0x0063fc69-0x0063fc81 (called at rTbl2.h:224)
//   in rAIPawnEmParam::~rAIPawnEmParam at 0x0063fd19-0x0063fd31 (called at rTbl2.h:224)
//   in rTbl2<cAIPawnEmNode>::allocData at 0x01a725c9-0x01a725e1 (called at rTbl2.h:224)
//   and 2 more (every copy is in <bundle>.inlined.json)
// void cAIPawnEmNode::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cAIPawnEmNode::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cAIPawnEmNode::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 2 inlined copies in 2 functions (242 bytes)
//   in cAIPawnEmNode::MyDTI::newInstance at 0x0063f9a0-0x0063fa11 (called at rAIPawnEmParam.cpp:60)
//   in rTbl2<cAIPawnEmNode>::allocData at 0x01a72652-0x01a72663, 0x01a72666-0x01a726d6 (called at rTbl2.h:215)
// cAIPawnEmNode::cAIPawnEmNode();

// Address: 0x0063fb90 - 0x0063fba3 (19 bytes)
// Also emitted as: _ZN13cAIPawnEmNodeD0Ev at 0x0063fbb0
cAIPawnEmNode::~cAIPawnEmNode() {
    DDON_STUB("cAIPawnEmNode::~cAIPawnEmNode")
    /* stub */
}

// No out-of-line body: 2 inlined copies in 1 function (132 bytes)
//   in _GLOBAL__sub_I_rAIPawnEmParam.cpp at 0x0063ffa0-0x0063ffe2 (called at rAIPawnEmParam.cpp:60)
//   in _GLOBAL__sub_I_rAIPawnEmParam.cpp at 0x0063ffa0-0x0063ffe2 (called at rAIPawnEmParam.h:65)
// cAIPawnEmNode::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x0063f970 - 0x0063fa19 (169 bytes)
__attribute__((weak)) MtObject* cAIPawnEmNode::MyDTI::newInstance() const {
    DDON_STUB("cAIPawnEmNode::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* rAIPawnEmParam::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void rAIPawnEmParam::usage();

// Address: 0x01a72430 - 0x01a72438 (8 bytes)
const MtDTI& rAIPawnEmParam::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return rAIPawnEmParam::DTI;
}

// No out-of-line body: 2 inlined copies in 2 functions (30 bytes)
//   in rAIPawnEmParam::MyDTI::newInstance at 0x0063fa94-0x0063faa6 (called at rAIPawnEmParam.cpp:61)
//   in rAIPawnEmParam::~rAIPawnEmParam at 0x0063fd49-0x0063fd55 (called at rAIPawnEmParam.cpp:61)
// MtAllocator* rAIPawnEmParam::getAllocator();

// No out-of-line body: no code in the ELF
// void rAIPawnEmParam::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
// inferred: parameters written where their values stand in every inlined copy
inline void* rAIPawnEmParam::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::rAIPawnEmParam::DTI)->memAlloc(sz, align, ::rAIPawnEmParam::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* rAIPawnEmParam::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* rAIPawnEmParam::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* rAIPawnEmParam::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void rAIPawnEmParam::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::rAIPawnEmParam::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void rAIPawnEmParam::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void rAIPawnEmParam::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void rAIPawnEmParam::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 1 inlined copy in 1 function (68 bytes)
//   in rAIPawnEmParam::MyDTI::newInstance at 0x0063fac0-0x0063fb04 (called at rAIPawnEmParam.cpp:61)
// rAIPawnEmParam::rAIPawnEmParam();

// Address: 0x0063fc00 - 0x0063fca1 (161 bytes)
// Also emitted as: _ZN14rAIPawnEmParamD0Ev at 0x0063fcb0
rAIPawnEmParam::~rAIPawnEmParam() {
    DDON_STUB("rAIPawnEmParam::~rAIPawnEmParam")
    /* stub */
}

// Address: 0x0063fd70 - 0x0063feba (330 bytes)
__attribute__((weak)) bool rAIPawnEmParam::loadData(MtDataReader& r, cAIPawnEmNode* pData) {
    DDON_STUB("rAIPawnEmParam::loadData")
    return {};
}

// Address: 0x01a72440 - 0x01a72448 (8 bytes)
MT_CTSTR rAIPawnEmParam::getExt() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return "pep";
}

// Address: 0x01a72550 - 0x01a72556 (6 bytes)
u32 rAIPawnEmParam::getDataVersion() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return static_cast<u32>(15);
}

// Address: 0x0063fec0 - 0x0063ff98 (216 bytes)
__attribute__((weak)) bool rAIPawnEmParam::loadCore(MtDataReader& r) {
    DDON_STUB("rAIPawnEmParam::loadCore")
    return {};
}

// Address: 0x01a72560 - 0x01a72566 (6 bytes)
f32 rAIPawnEmParam::getDistance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mDistance;
}

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_rAIPawnEmParam.cpp at 0x0063ffe2-0x0064001f (called at rAIPawnEmParam.cpp:61)
//   in _GLOBAL__sub_I_rAIPawnEmParam.cpp at 0x0063ffe2-0x0064001f (called at rAIPawnEmParam.h:142)
// rAIPawnEmParam::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x0063fa90 - 0x0063fb0c (124 bytes)
MtObject* rAIPawnEmParam::MyDTI::newInstance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return new (static_cast<u32>(16)) ::rAIPawnEmParam;
}

// Instance at 0x01a72500 - 0x01a72516 (22 bytes) of the generic rTbl2<T>::getData
// Proven from the ELF: the body oracle checks this instance (022 D5).
template cAIPawnEmNode* rTbl2<cAIPawnEmNode>::getData(unsigned int);

// Instance at 0x01a72450 - 0x01a724f3 (163 bytes) of the generic rTbl2<T>::load
// Proven from the ELF: the body oracle checks this instance (022 D5).
template bool rTbl2<cAIPawnEmNode>::load(MtStream&);

// Instance at 0x01a72350 - 0x01a723f8 (168 bytes) of the generic rTbl2<T>::loadCore
// Proven from the ELF: the body oracle checks this instance (022 D5).
template bool rTbl2<cAIPawnEmNode>::loadCore(MtDataReader&);

// Instance at 0x01a72520 - 0x01a72536 (22 bytes) of the generic rTbl2<T>::getData
// Proven from the ELF: the body oracle checks this instance (022 D5).
template const cAIPawnEmNode* rTbl2<cAIPawnEmNode>::getData(unsigned int) const;

// Instance at 0x01a72540 - 0x01a72544 (4 bytes) of the generic rTbl2<T>::getDataNum
// Proven from the ELF: the body oracle checks this instance (022 D5).
template unsigned int rTbl2<cAIPawnEmNode>::getDataNum() const;

