// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "rLandInfo.h"
#include "../shared/MtAllocator.h"
#include "../shared/MtCollection.h"
#include "../shared/MtDTI.h"
#include "../shared/MtDataReader.h"
#include "../shared/MtMemoryAllocator.h"
#include "../shared/MtObject.h"
#include "../shared/cResource.h"
#include "../shared/nDDOIO.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* rLandInfo::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void rLandInfo::usage();

// Address: 0x01a993c0 - 0x01a993c8 (8 bytes)
const MtDTI& rLandInfo::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return rLandInfo::DTI;
}

// No out-of-line body: 2 inlined copies in 2 functions (30 bytes)
//   in rLandInfo::MyDTI::newInstance at 0x00691ee4-0x00691ef6 (called at rLandInfo.cpp:27)
//   in rLandInfo::~rLandInfo at 0x00692157-0x00692163 (called at rLandInfo.cpp:27)
// MtAllocator* rLandInfo::getAllocator();

// No out-of-line body: no code in the ELF
// void rLandInfo::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
// inferred: parameters written where their values stand in every inlined copy
inline void* rLandInfo::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::rLandInfo::DTI)->memAlloc(sz, align, ::rLandInfo::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* rLandInfo::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* rLandInfo::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* rLandInfo::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void rLandInfo::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::rLandInfo::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void rLandInfo::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void rLandInfo::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void rLandInfo::operator delete[](void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// u32 rLandInfo::getMagicHeader() const;

// No out-of-line body: no code in the ELF
// u32 rLandInfo::getDataVersion() const;

// Address: 0x01a993d0 - 0x01a993d8 (8 bytes)
MT_CTSTR rLandInfo::getExt() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return "lai";
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline rLandInfo::rLandInfo() {
    this->::cResource::setAttribute(static_cast<u32>(22));
}

// Address: 0x00691ff0 - 0x006920a1 (177 bytes)
// Also emitted as: _ZN9rLandInfoD0Ev at 0x006920b0
rLandInfo::~rLandInfo() {
    DDON_STUB("rLandInfo::~rLandInfo")
    /* stub */
}

// Address: 0x00692180 - 0x00692263 (227 bytes)
__attribute__((weak)) void rLandInfo::createProperty(MtPropertyList& s) {
    DDON_STUB("rLandInfo::createProperty")
    /* stub */
}

// Address: 0x00692270 - 0x006923a3 (307 bytes)
__attribute__((weak)) bool rLandInfo::save(MtStream& out) {
    // local: MtDataWriter w;
    DDON_STUB("rLandInfo::save")
    return {};
}

// Address: 0x006923b0 - 0x00692457 (167 bytes)
bool rLandInfo::load(MtStream& in) {
    // DWARF local not rendered: u32 header;
    // DWARF local not rendered: u32 dataVersion;
    // Proven from the ELF: the body oracle checks this body (022 D5).
    MtDataReader r(in, static_cast<u32>(4096));
    if ((&r)->readU32() == static_cast<u32>(4800844)) {
        if ((&r)->readU32() == static_cast<u32>(2)) {
            ::nDDOIO::readMtArray(r, this->mLandInfo);
            return true;
        }
    }
    return false;
}

// No out-of-line body: 2 inlined copies in 1 function (130 bytes)
//   in _GLOBAL__sub_I_rLandInfo.cpp at 0x00692a90-0x00692ad1 (called at rLandInfo.cpp:27)
//   in _GLOBAL__sub_I_rLandInfo.cpp at 0x00692a90-0x00692ad1 (called at rLandInfo.h:31)
// rLandInfo::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00691ee0 - 0x00691f64 (132 bytes)
MtObject* rLandInfo::MyDTI::newInstance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return new (static_cast<u32>(16)) ::rLandInfo;
}

// No out-of-line body: no code in the ELF
// MtDTI* rLandInfo::cLandInfo::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void rLandInfo::cLandInfo::usage();

// Address: 0x01a993e0 - 0x01a993e8 (8 bytes)
const MtDTI& rLandInfo::cLandInfo::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return rLandInfo::cLandInfo::DTI;
}

// No out-of-line body: 3 inlined copies in 3 functions (45 bytes)
//   in rLandInfo::cLandInfo::MyDTI::newInstance at 0x00692464-0x00692476 (called at rLandInfo.cpp:108)
//   in rLandInfo::cLandInfo::~cLandInfo at 0x00692683-0x0069268f (called at rLandInfo.cpp:108)
//   in _ZN6nDDOIO11readMtArrayIN9rLandInfo9cLandInfoEEEvR12MtDataReaderR12MtTypedArrayIT_E at 0x01a98ff3-0x01a99002 (called at rLandInfo.cpp:108)
// MtAllocator* rLandInfo::cLandInfo::getAllocator();

// No out-of-line body: no code in the ELF
// void rLandInfo::cLandInfo::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined.
// inferred: parameters written where their values stand in every inlined copy; approximate: only approximate callers check this inline body
inline void* rLandInfo::cLandInfo::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::rLandInfo::cLandInfo::DTI)->memAlloc(sz, align, ::rLandInfo::cLandInfo::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* rLandInfo::cLandInfo::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* rLandInfo::cLandInfo::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* rLandInfo::cLandInfo::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void rLandInfo::cLandInfo::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::rLandInfo::cLandInfo::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void rLandInfo::cLandInfo::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void rLandInfo::cLandInfo::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void rLandInfo::cLandInfo::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 2 inlined copies in 2 functions (153 bytes)
//   in rLandInfo::cLandInfo::MyDTI::newInstance at 0x0069248d-0x006924cb (called at rLandInfo.cpp:108)
//   in _ZN6nDDOIO11readMtArrayIN9rLandInfo9cLandInfoEEEvR12MtDataReaderR12MtTypedArrayIT_E at 0x01a98fc8-0x01a98fe6, 0x01a9901c-0x01a99055, 0x01a99062-0x01a99066 (called at rLandInfo.cpp:108)
// rLandInfo::cLandInfo::cLandInfo();

// Address: 0x00692550 - 0x006925ed (157 bytes)
// Also emitted as: _ZN9rLandInfo9cLandInfoD0Ev at 0x006925f0
rLandInfo::cLandInfo::~cLandInfo() {
    DDON_STUB("rLandInfo::cLandInfo::~cLandInfo")
    /* stub */
}

// Address: 0x006926b0 - 0x00692842 (402 bytes)
__attribute__((weak)) void rLandInfo::cLandInfo::createProperty(MtPropertyList& s) {
    DDON_STUB("rLandInfo::cLandInfo::createProperty")
    /* stub */
}

// No out-of-line body: 1 inlined copy in 1 function (21 bytes)
//   in _ZN6nDDOIO11readMtArrayIN9rLandInfo9cLandInfoEEEvR12MtDataReaderR12MtTypedArrayIT_E at 0x01a99055-0x01a99062, 0x01a99066-0x01a9906e (called at nDDOIO.h:451)
// bool rLandInfo::cLandInfo::load(MtDataReader& r);

// No out-of-line body: 1 inlined copy in 1 function (86 bytes)
//   in rLandInfo::save at 0x0069230e-0x00692364 (called at nDDOIO.h:463)
// bool rLandInfo::cLandInfo::save(MtDataWriter& w);

// No out-of-line body: 2 inlined copies in 1 function (128 bytes)
//   in _GLOBAL__sub_I_rLandInfo.cpp at 0x00692ad1-0x00692b11 (called at rLandInfo.cpp:108)
//   in _GLOBAL__sub_I_rLandInfo.cpp at 0x00692ad1-0x00692b11 (called at rLandInfo.h:89)
// rLandInfo::cLandInfo::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00692460 - 0x006924d0 (112 bytes)
MtObject* rLandInfo::cLandInfo::MyDTI::newInstance() const {
    // Approximate from the ELF: stores ahead of a subobject's inlined constructor; the body oracle reports this body.
    return new (static_cast<u32>(16)) ::rLandInfo::cLandInfo;
}

// No out-of-line body: no code in the ELF
// MtDTI* rLandInfo::cLandInfo::cLandAreaInfo::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void rLandInfo::cLandInfo::cLandAreaInfo::usage();

// Address: 0x01a993f0 - 0x01a993f8 (8 bytes)
const MtDTI& rLandInfo::cLandInfo::cLandAreaInfo::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return rLandInfo::cLandInfo::cLandAreaInfo::DTI;
}

// No out-of-line body: 3 inlined copies in 3 functions (45 bytes)
//   in rLandInfo::cLandInfo::cLandAreaInfo::MyDTI::newInstance at 0x00692874-0x00692886 (called at rLandInfo.cpp:170)
//   in rLandInfo::cLandInfo::cLandAreaInfo::~cLandAreaInfo at 0x00692959-0x00692965 (called at rLandInfo.cpp:170)
//   in _ZN6nDDOIO11readMtArrayIN9rLandInfo9cLandInfo13cLandAreaInfoEEEvR12MtDataReaderR12MtTypedArrayIT_E at 0x01a99273-0x01a99282 (called at rLandInfo.cpp:170)
// MtAllocator* rLandInfo::cLandInfo::cLandAreaInfo::getAllocator();

// No out-of-line body: no code in the ELF
// void rLandInfo::cLandInfo::cLandAreaInfo::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
// inferred: parameters written where their values stand in every inlined copy; constant parameters of one value written in their declaration order where it stands, once each (2.7.0; rCharacterEdit's proven operator new reads memAlloc(sz, align, …))
inline void* rLandInfo::cLandInfo::cLandAreaInfo::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::rLandInfo::cLandInfo::cLandAreaInfo::DTI)->memAlloc(sz, align, ::rLandInfo::cLandInfo::cLandAreaInfo::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* rLandInfo::cLandInfo::cLandAreaInfo::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* rLandInfo::cLandInfo::cLandAreaInfo::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* rLandInfo::cLandInfo::cLandAreaInfo::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline void rLandInfo::cLandInfo::cLandAreaInfo::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::rLandInfo::cLandInfo::cLandAreaInfo::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void rLandInfo::cLandInfo::cLandAreaInfo::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void rLandInfo::cLandInfo::cLandAreaInfo::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void rLandInfo::cLandInfo::cLandAreaInfo::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 2 inlined copies in 2 functions (56 bytes)
//   in rLandInfo::cLandInfo::cLandAreaInfo::MyDTI::newInstance at 0x0069289d-0x006928b2 (called at rLandInfo.cpp:170)
//   in _ZN6nDDOIO11readMtArrayIN9rLandInfo9cLandInfo13cLandAreaInfoEEEvR12MtDataReaderR12MtTypedArrayIT_E at 0x01a99258-0x01a99267, 0x01a9929c-0x01a992b0 (called at rLandInfo.cpp:170)
// rLandInfo::cLandInfo::cLandAreaInfo::cLandAreaInfo();

// Address: 0x00692940 - 0x00692941 (1 bytes)
// Also emitted as: _ZN9rLandInfo9cLandInfo13cLandAreaInfoD0Ev at 0x00692950
rLandInfo::cLandInfo::cLandAreaInfo::~cLandAreaInfo() {
    // Empty in the binary (a single `ret`).
}

// Address: 0x00692980 - 0x00692a63 (227 bytes)
__attribute__((weak)) void rLandInfo::cLandInfo::cLandAreaInfo::createProperty(MtPropertyList& s) {
    DDON_STUB("rLandInfo::cLandInfo::cLandAreaInfo::createProperty")
    /* stub */
}

// No out-of-line body: 1 inlined copy in 1 function (10 bytes)
//   in _ZN6nDDOIO11readMtArrayIN9rLandInfo9cLandInfo13cLandAreaInfoEEEvR12MtDataReaderR12MtTypedArrayIT_E at 0x01a992b0-0x01a992ba (called at nDDOIO.h:451)
// bool rLandInfo::cLandInfo::cLandAreaInfo::load(MtDataReader& r);

// No out-of-line body: 1 inlined copy in 1 function (16 bytes)
//   in rLandInfo::save at 0x0069234b-0x0069235b (called at nDDOIO.h:463)
// bool rLandInfo::cLandInfo::cLandAreaInfo::save(MtDataWriter& w);

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in _GLOBAL__sub_I_rLandInfo.cpp at 0x00692b11-0x00692b4a (called at rLandInfo.cpp:170)
//   in _GLOBAL__sub_I_rLandInfo.cpp at 0x00692b11-0x00692b4a (called at rLandInfo.h:135)
// rLandInfo::cLandInfo::cLandAreaInfo::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00692870 - 0x006928b7 (71 bytes)
MtObject* rLandInfo::cLandInfo::cLandAreaInfo::MyDTI::newInstance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return new (static_cast<u32>(16)) ::rLandInfo::cLandInfo::cLandAreaInfo;
}

// Instance at 0x01a99140 - 0x01a99145 (5 bytes) of the generic MtTypedArray<T>::~MtTypedArray
// Proven from the ELF: the body oracle checks this instance (022 D5).
template MtTypedArray<rLandInfo::cLandInfo::cLandAreaInfo>::~MtTypedArray();

// Instance at 0x01a98eb0 - 0x01a98eb5 (5 bytes) of the generic MtTypedArray<T>::~MtTypedArray
// Proven from the ELF: the body oracle checks this instance (022 D5).
template MtTypedArray<rLandInfo::cLandInfo>::~MtTypedArray();

