// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "rPlPartsInfo.h"
#include "../shared/MtAllocator.h"
#include "../shared/MtDTI.h"
#include "../shared/MtMemoryAllocator.h"
#include "../shared/MtObject.h"
#include "../shared/cResource.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* rPlPartsInfo::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void rPlPartsInfo::usage();

// Address: 0x01aabe40 - 0x01aabe48 (8 bytes)
const MtDTI& rPlPartsInfo::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return rPlPartsInfo::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* rPlPartsInfo::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::rPlPartsInfo::DTI);
}

// No out-of-line body: no code in the ELF
// void rPlPartsInfo::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
// inferred: parameters written where their values stand in every inlined copy
inline void* rPlPartsInfo::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::rPlPartsInfo::DTI)->memAlloc(sz, align, ::rPlPartsInfo::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* rPlPartsInfo::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* rPlPartsInfo::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* rPlPartsInfo::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void rPlPartsInfo::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::rPlPartsInfo::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void rPlPartsInfo::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void rPlPartsInfo::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void rPlPartsInfo::operator delete[](void* p_addr, u32 align);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline rPlPartsInfo::rPlPartsInfo() {
    this->::cResource::setAttribute(static_cast<u32>(16));
    this->mpHeader = static_cast<rPlPartsInfo::HEADER*>(nullptr);
}

// Address: 0x006cc190 - 0x006cc1d6 (70 bytes)
// Also emitted as: _ZN12rPlPartsInfoD0Ev at 0x006cc1e0
rPlPartsInfo::~rPlPartsInfo() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    ::MtMemoryAllocator::getAllocator(::rPlPartsInfo::DTI)->memFree(static_cast<void*>(this->mpHeader));
    this->mpHeader = static_cast<rPlPartsInfo::HEADER*>(nullptr);
}

// Address: 0x006cc240 - 0x006cc271 (49 bytes)
void rPlPartsInfo::clear() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    ::rPlPartsInfo::getAllocator()->memFree(static_cast<void*>(this->mpHeader));
    this->mpHeader = static_cast<rPlPartsInfo::HEADER*>(nullptr);
}

// Address: 0x006cc280 - 0x006cc2fa (122 bytes)
__attribute__((weak)) bool rPlPartsInfo::load(MtStream& in) {
    // local: u32 size;
    DDON_STUB("rPlPartsInfo::load")
    return {};
}

// Address: 0x01aabe50 - 0x01aabe58 (8 bytes)
MT_CTSTR rPlPartsInfo::getExt() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return "psi";
}

// No out-of-line body: 1 inlined copy in 1 function (30 bytes)
//   in rPlPartsInfo::setParts at 0x006cc328-0x006cc334, 0x006cc338-0x006cc340, 0x006cc38d-0x006cc393, 0x006cc3cf-0x006cc3d3 (called at rPlPartsInfo.cpp:99)
// s16 rPlPartsInfo::getPartsID(s32 parts, s32 index);

// No out-of-line body: 1 inlined copy in 1 function (4 bytes)
//   in rPlPartsInfo::setParts at 0x006cc31b-0x006cc31f (called at rPlPartsInfo.cpp:94)
// s32 rPlPartsInfo::getPartsNum();

// Address: 0x006cc310 - 0x006cc3d4 (196 bytes)
__attribute__((weak)) void rPlPartsInfo::setParts(uModel* pModel, s32 parts, bool flag, cpEquip* pEquip) {
    // local: s32 i;
    // local: bool newFlag;
    // local: s16 id;
    DDON_STUB("rPlPartsInfo::setParts")
    /* stub */
}

// Address: 0x006cc3e0 - 0x006cc560 (384 bytes)
__attribute__((weak)) void rPlPartsInfo::setScar(uModel* pModel, s32 parts, bool flag, cpEquip* pEquip) {
    // local: u32 scarParts;
    // local: u32 dispFlag;
    // local: u32 setFlag;
    // local: cEditParam& EditParam;
    // local: cpCharacterEdit* pEdit;
    // local: bool newFlag;
    DDON_STUB("rPlPartsInfo::setScar")
    /* stub */
}

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_rPlPartsInfo.cpp at 0x006cc65f-0x006cc69c (called at rPlPartsInfo.cpp:23)
//   in _GLOBAL__sub_I_rPlPartsInfo.cpp at 0x006cc65f-0x006cc69c (called at rPlPartsInfo.h:19)
// rPlPartsInfo::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x006cc0b0 - 0x006cc10d (93 bytes)
MtObject* rPlPartsInfo::MyDTI::newInstance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return new (static_cast<u32>(16)) ::rPlPartsInfo;
}

