// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "rCharParamEnemy.h"
#include "../shared/MtAllocator.h"
#include "../shared/MtDTI.h"
#include "../shared/MtMemoryAllocator.h"
#include "../shared/MtObject.h"
#include "cCharParamEnemy.h"
#include "../shared/cResource.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* rCharParamEnemy::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void rCharParamEnemy::usage();

// Address: 0x01a7faf0 - 0x01a7faf8 (8 bytes)
const MtDTI& rCharParamEnemy::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return rCharParamEnemy::DTI;
}

// No out-of-line body: 2 inlined copies in 2 functions (30 bytes)
//   in rCharParamEnemy::MyDTI::newInstance at 0x00654e34-0x00654e46 (called at rCharParamEnemy.cpp:31)
//   in rCharParamEnemy::~rCharParamEnemy at 0x00654f96-0x00654fa2 (called at rCharParamEnemy.cpp:31)
// MtAllocator* rCharParamEnemy::getAllocator();

// No out-of-line body: no code in the ELF
// void rCharParamEnemy::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
// inferred: parameters written where their values stand in every inlined copy
inline void* rCharParamEnemy::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::rCharParamEnemy::DTI)->memAlloc(sz, align, ::rCharParamEnemy::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* rCharParamEnemy::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* rCharParamEnemy::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* rCharParamEnemy::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void rCharParamEnemy::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::rCharParamEnemy::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void rCharParamEnemy::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void rCharParamEnemy::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void rCharParamEnemy::operator delete[](void* p_addr, u32 align);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline rCharParamEnemy::rCharParamEnemy() {
    this->::cResource::setAttribute(static_cast<u32>(22));
    this->mFlgEnemyFly = false;
    this->mpCharParamEnemy = static_cast<cCharParamEnemy*>(nullptr);
}

// Address: 0x00654f20 - 0x00654f5c (60 bytes)
// Also emitted as: _ZN15rCharParamEnemyD0Ev at 0x00654f60
rCharParamEnemy::~rCharParamEnemy() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpCharParamEnemy == static_cast<cCharParamEnemy*>(nullptr)) {
        return;
    }
    delete this->mpCharParamEnemy;
    this->mpCharParamEnemy = static_cast<cCharParamEnemy*>(nullptr);
}

// Address: 0x01a7fb00 - 0x01a7fb08 (8 bytes)
MT_CTSTR rCharParamEnemy::getExt() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return "cpe";
}

// No out-of-line body: no code in the ELF
// u32 rCharParamEnemy::getMagicHeader() const;

// No out-of-line body: no code in the ELF
// u32 rCharParamEnemy::getDataVersion() const;

// Address: 0x00654fc0 - 0x00655157 (407 bytes)
__attribute__((weak)) void rCharParamEnemy::createProperty(MtPropertyList& s) {
    DDON_STUB("rCharParamEnemy::createProperty")
    /* stub */
}

// Address: 0x00655160 - 0x00655ad0 (2416 bytes)
__attribute__((weak)) bool rCharParamEnemy::load(MtStream& in) {
    // local: MtDataReader r;
    // local: cCharParamEnemyFly* pFlyData;
    // local: u32 i;
    // local: u32 i;
    DDON_STUB("rCharParamEnemy::load")
    return {};
}

// Address: 0x00655ad0 - 0x006563ae (2270 bytes)
__attribute__((weak)) bool rCharParamEnemy::save(MtStream& out) {
    // local: MtDataWriter w;
    // local: u32 i;
    // local: u32 i;
    // local: cCharParamEnemyFly* pFlyData;
    DDON_STUB("rCharParamEnemy::save")
    return {};
}

// No out-of-line body: 40 inlined copies in 34 functions (165 bytes)
//   in cEmActAtkJump::setSpeedParam at 0x000a3c83-0x000a3c87 (called at cEmActAttack.cpp:293)
//   in cEvaluationName::cEvaluation::addEvaluation at 0x001df241-0x001df245 (called at cEvaluation.cpp:475)
//   in cpCatchCtrl::getBeardownEffective at 0x00454d23-0x00454d27 (called at cpCatchCtrl.cpp:935)
//   and 37 more (every copy is in <bundle>.inlined.json)
// cCharParamEnemy* rCharParamEnemy::getCharParamEnemy();

// No out-of-line body: no code in the ELF
// bool rCharParamEnemy::getFlgEnemyFly();

// No out-of-line body: no code in the ELF
// void rCharParamEnemy::saveForce();

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_rCharParamEnemy.cpp at 0x006564af-0x006564ec (called at rCharParamEnemy.cpp:31)
//   in _GLOBAL__sub_I_rCharParamEnemy.cpp at 0x006564af-0x006564ec (called at rCharParamEnemy.h:27)
// rCharParamEnemy::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00654e30 - 0x00654e91 (97 bytes)
MtObject* rCharParamEnemy::MyDTI::newInstance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return new (static_cast<u32>(16)) ::rCharParamEnemy;
}

