// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "cAction.h"
#include "MtAllocator.h"
#include "MtDTI.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#include "cpActionManager.h"
#include "../rPawnAIAction/cpActionRequest.h"
#include "cpPivotCtrl.h"
#include "uDDOModel.h"
#include "uModel.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* cAction::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cAction::usage();

// Address: 0x0194fa10 - 0x0194fa18 (8 bytes)
const MtDTI& cAction::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cAction::DTI;
}

// No out-of-line body: 2 inlined copies in 2 functions (30 bytes)
//   in cAction::MyDTI::newInstance at 0x0001cc54-0x0001cc66 (called at cAction.cpp:28)
//   in cAction::~cAction at 0x0001cd69-0x0001cd75 (called at cAction.cpp:28)
// MtAllocator* cAction::getAllocator();

// No out-of-line body: no code in the ELF
// void cAction::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
// inferred: parameters written where their values stand in every inlined copy
inline void* cAction::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::cAction::DTI)->memAlloc(sz, align, ::cAction::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* cAction::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cAction::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cAction::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline void cAction::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cAction::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cAction::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cAction::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cAction::operator delete[](void* p_addr, u32 align);

// Address: 0x0001cd20 - 0x0001cd4e (46 bytes)
cAction::cAction() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mRno = static_cast<u32>(0);
    this->mpModel = static_cast<uDDOModel*>(nullptr);
    this->mpActReq = static_cast<cpActionRequest*>(nullptr);
    this->mpActMgr = static_cast<cpActionManager*>(nullptr);
}

// Address: 0x0001cd50 - 0x0001cd51 (1 bytes)
// Also emitted as: _ZN7cActionD0Ev at 0x0001cd60
cAction::~cAction() {
    // Empty in the binary (a single `ret`).
}

// Address: 0x0001cda0 - 0x0001cdaf (15 bytes)
void cAction::preInit() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpModel == static_cast<uDDOModel*>(nullptr)) {
        return;
    }
    this->mpModel->::uDDOModel::resetAtkAdjust();
}

// Address: 0x0001cdb0 - 0x0001ce5a (170 bytes)
__attribute__((weak)) void cAction::init() {
    // local: cState* pState;
    // local: cStateAction* pStateAction;
    DDON_STUB("cAction::init")
    /* stub */
}

// Address: 0x0001ce60 - 0x0001ce61 (1 bytes)
__attribute__((weak)) void cAction::move() {
    // Empty in the binary (a single `ret`).
}

// Address: 0x0001ce80 - 0x0001cea1 (33 bytes)
void cAction::final() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpModel == static_cast<uDDOModel*>(nullptr)) {
        return;
    }
    if (this->mpModel->mpPivotCtrl == static_cast<cpPivotCtrl*>(nullptr)) {
        return;
    }
    this->mpModel->mpPivotCtrl->setActive(false);
}

// Address: 0x0001ce70 - 0x0001ce71 (1 bytes)
__attribute__((weak)) void cAction::moveAfter() {
    // Empty in the binary (a single `ret`).
}

// Defined in the class (its body was written in a header).
// void cAction::updatePtr();

// Defined in the class (its body was written in a header).
// void cAction::updateEfcHandle();

// Defined in the class (its body was written in a header).
// void cAction::applyWorldOffset(const MtVector3& offset, const MtVector3& absolute_offset);

// Address: 0x0194fa50 - 0x0194fa53 (3 bytes)
bool cAction::checkInit() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return true;
}

// Address: 0x0194fa60 - 0x0194fa63 (3 bytes)
bool cAction::checkMove() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return true;
}

// Address: 0x0194fa70 - 0x0194fa73 (3 bytes)
bool cAction::checkFinal() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return true;
}

// Address: 0x0194fa80 - 0x0194fa83 (3 bytes)
bool cAction::checkMoveAfter() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return true;
}

// No out-of-line body: 4 inlined copies in 3 functions (48 bytes)
//   in cpActionManager::update at 0x003b3a14-0x003b3a20 (called at cpActionManager.cpp:288)
//   in _ZN15cpActionManager11callPreInitEj at 0x003b3e0e-0x003b3e1a (called at cpActionManager.cpp:573)
//   in cpActionManager::setAction at 0x003b4108-0x003b4114 (called at cpActionManager.cpp:573)
//   and 1 more (every copy is in <bundle>.inlined.json)
// void cAction::setup(cpActionManager* pActMgr, cpActionRequest* pActReq, uDDOModel* pModel);

// No out-of-line body: no code in the ELF
// const nActionManager::stActExParam* cAction::getActExParam();

// Address: 0x0001cf50 - 0x0001cf51 (1 bytes)
__attribute__((weak)) void cAction::createProperty(MtPropertyList& s) {
    // Empty in the binary (a single `ret`).
}

// Address: 0x0001cf60 - 0x0001cf79 (25 bytes)
void cAction::setEndAction(u32 ActNo) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpModel == static_cast<uDDOModel*>(nullptr)) {
        return;
    }
    if (this->mpModel->::uDDOModel::getActionRequestPtr() == static_cast<cpActionRequest*>(nullptr)) {
        return;
    }
    this->mpModel->::uDDOModel::getActionRequestPtr()->mEndAction = ActNo;
}

// Address: 0x0001cf80 - 0x0001cf99 (25 bytes)
void cAction::setLandAction(u32 ActNo) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpModel == static_cast<uDDOModel*>(nullptr)) {
        return;
    }
    if (this->mpModel->::uDDOModel::getActionRequestPtr() == static_cast<cpActionRequest*>(nullptr)) {
        return;
    }
    this->mpModel->::uDDOModel::getActionRequestPtr()->mLandAction = ActNo;
}

// Address: 0x0001cfa0 - 0x0001cfb9 (25 bytes)
void cAction::setFallAction(u32 ActNo) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpModel == static_cast<uDDOModel*>(nullptr)) {
        return;
    }
    if (this->mpModel->::uDDOModel::getActionRequestPtr() == static_cast<cpActionRequest*>(nullptr)) {
        return;
    }
    this->mpModel->::uDDOModel::getActionRequestPtr()->mFallAction = ActNo;
}

// Address: 0x0001cd90 - 0x0001cd9d (13 bytes)
void cAction::requestAction(u32 ActNo) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpActReq == static_cast<cpActionRequest*>(nullptr)) {
        return;
    }
    this->mpActReq->mRequestActionReq = ActNo;
}

// Address: 0x0001ceb0 - 0x0001cf2d (125 bytes)
__attribute__((weak)) void cAction::endAction() {
    DDON_STUB("cAction::endAction")
    /* stub */
}

// Address: 0x0001cf30 - 0x0001cf3f (15 bytes)
void cAction::endActionNoSend() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpActMgr == static_cast<cpActionManager*>(nullptr)) {
        return;
    }
    this->mpActMgr->::cpActionManager::endActionNoSend();
}

// Address: 0x0001cfc0 - 0x0001d041 (129 bytes)
__attribute__((weak)) bool cAction::isActionMotionEnd(MOT_TYPE type) {
    // local: bool result;
    DDON_STUB("cAction::isActionMotionEnd")
    return {};
}

// No out-of-line body: no code in the ELF
// bool cAction::isAttackHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isDamageHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isCheckHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isCheckedHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isCatchHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isCaughtHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isPushHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isGuardHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isGuardedHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isHealHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isHealedHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isAttackTestHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isDamageTestHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isCheckTestHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isCheckedTestHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isCatchTestHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isCaughtTestHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isGuardTestHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isHealTestHit(u32 filter);

// No out-of-line body: no code in the ELF
// bool cAction::isHealedTestHit(u32 filter);

// No out-of-line body: no code in the ELF
// void cAction::setObjColNoneThrow(bool isMyPlayerOnly);

// No out-of-line body: 1 inlined copy in 1 function (46 bytes)
//   in cAction::isActionMotionEnd at 0x0001cfcd-0x0001cffb (called at cAction.cpp:204)
// bool cAction::isFrameEnd(MOT_TYPE type);

// No out-of-line body: 1 inlined copy in 1 function (33 bytes)
//   in cAction::isActionMotionEnd at 0x0001cfff-0x0001d020 (called at cAction.cpp:204)
// bool cAction::isBlendCtrlEnable(MOT_TYPE type);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cAction::addColNodeFlag(u32 flag, bool isMyPlayerOnly);

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_cAction.cpp at 0x0001d2af-0x0001d2ec (called at cAction.cpp:28)
//   in _GLOBAL__sub_I_cAction.cpp at 0x0001d2af-0x0001d2ec (called at cAction.h:51)
// cAction::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x0001cc50 - 0x0001ccaf (95 bytes)
MtObject* cAction::MyDTI::newInstance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return new (static_cast<u32>(16)) ::cAction;
}

