// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "cCameraGameNml.h"
#include "MtAllocator.h"
#include "MtDTI.h"
#include "MtMath.h"
#include "MtMemoryAllocator.h"
#include "cCamInterporate.h"
#include "nCameraGame.h"
#include "uCameraGame.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* cCamExParamNml::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cCamExParamNml::usage();

// Address: 0x0195c680 - 0x0195c688 (8 bytes)
const MtDTI& cCamExParamNml::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cCamExParamNml::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* cCamExParamNml::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::cCamExParamNml::DTI);
}

// No out-of-line body: no code in the ELF
// void cCamExParamNml::setAllocator(u32);

// Address: 0x0003cb40 - 0x0003cb80 (64 bytes)
void* cCamExParamNml::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::cCamExParamNml::getAllocator()->memAlloc(sz, align, ::cCamExParamNml::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* cCamExParamNml::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cCamExParamNml::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cCamExParamNml::operator new[](size_t sz, void* p_addr);

// No out-of-line body: 1 inlined copy in 1 function (44 bytes)
//   in cCamExParamNml::~cCamExParamNml at 0x0195b133-0x0195b15f (called at cCameraGameNml.h:195)
// void cCamExParamNml::operator delete(void* p_addr);

// No out-of-line body: no code in the ELF
// void cCamExParamNml::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cCamExParamNml::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cCamExParamNml::operator delete[](void* p_addr, u32 align);

// Address: 0x0195b170 - 0x0195c680 (5392 bytes)
__attribute__((weak)) void cCamExParamNml::createProperty(MtPropertyList& s) {
    DDON_STUB("cCamExParamNml::createProperty")
    /* stub */
}

// No out-of-line body: 10 inlined copies in 5 functions (9804 bytes)
//   in cCamExParamNml::MyDTI::newInstance at 0x0003c75d-0x0003cb39 (called at cCameraGameNml.cpp:51)
//   in cCamExParamNml::MyDTI::newInstance at 0x0003c75d-0x0003cb39 (called at cCameraGameNml.h:192)
//   in cCamExParamNml2::MyDTI::newInstance at 0x0003cc1d-0x0003cfd8 (called at cCameraGameNml.h:377)
//   and 7 more (every copy is in <bundle>.inlined.json)
// cCamExParamNml::cCamExParamNml();

// Address: 0x0195b050 - 0x0195b0cb (123 bytes)
// Also emitted as: _ZN14cCamExParamNmlD0Ev at 0x0195b0d0
cCamExParamNml::~cCamExParamNml() {
    DDON_STUB("cCamExParamNml::~cCamExParamNml")
    /* stub */
}

// Address: 0x0195af70 - 0x0195b050 (224 bytes)
__attribute__((weak)) void cCamExParamNml::copy(const cCamExParam* pParam) {
    // local: const cCamExParamNml* pParamNml;
    DDON_STUB("cCamExParamNml::copy")
    /* stub */
}

// Address: 0x0195c690 - 0x0195c86b (475 bytes)
__attribute__((weak)) cCamImpBase* cCamExParamNml::createCamImpInstance(uCameraGame* pCamera) const {
    // local: cCamImpBase* pImp;
    DDON_STUB("cCamExParamNml::createCamImpInstance")
    return nullptr;
}

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_cCameraGameNml.cpp at 0x0003fe0b-0x0003fe48 (called at cCameraGameNml.cpp:51)
//   in _GLOBAL__sub_I_cCameraGameNml.cpp at 0x0003fe0b-0x0003fe48 (called at cCameraGameNml.h:80)
// cCamExParamNml::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x0003c730 - 0x0003cb3e (1038 bytes)
__attribute__((weak)) MtObject* cCamExParamNml::MyDTI::newInstance() const {
    DDON_STUB("cCamExParamNml::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* cCamImpNml::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cCamImpNml::usage();

// Address: 0x01959350 - 0x01959358 (8 bytes)
const MtDTI& cCamImpNml::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cCamImpNml::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* cCamImpNml::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::cCamImpNml::DTI);
}

// No out-of-line body: no code in the ELF
// void cCamImpNml::setAllocator(u32);

// Address: 0x0003c680 - 0x0003c6c0 (64 bytes)
void* cCamImpNml::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::cCamImpNml::getAllocator()->memAlloc(sz, align, ::cCamImpNml::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* cCamImpNml::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cCamImpNml::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cCamImpNml::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void cCamImpNml::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cCamImpNml::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cCamImpNml::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cCamImpNml::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cCamImpNml::operator delete[](void* p_addr, u32 align);

// Address: 0x0003d0b0 - 0x0003d249 (409 bytes)
cCamImpNml::cCamImpNml() {
    DDON_STUB("cCamImpNml::cCamImpNml")
    /* stub */
}

// Address: 0x0003d250 - 0x0003d263 (19 bytes)
// Also emitted as: _ZN10cCamImpNmlD0Ev at 0x0003d270
cCamImpNml::~cCamImpNml() {
    DDON_STUB("cCamImpNml::~cCamImpNml")
    /* stub */
}

// Address: 0x0003fc90 - 0x0003fccf (63 bytes)
__attribute__((weak)) void cCamImpNml::applyWorldOffset(const MtVector3& offset, const MtVector3& absolute_offset) {
    DDON_STUB("cCamImpNml::applyWorldOffset")
    /* stub */
}

// No out-of-line body: 4 inlined copies in 2 functions (166 bytes)
//   in cCamImpNml::initSub at 0x0003d597-0x0003d5c1 (called at cCameraGameNml.cpp:133)
//   in cCamImpNml::moveSub at 0x0003e82b-0x0003e852 (called at cCameraGameNml.cpp:386)
//   in cCamImpNml::moveSub at 0x0003e936-0x0003e93d, 0x0003e959-0x0003e980 (called at cCameraGameNml.cpp:401)
//   and 1 more (every copy is in <bundle>.inlined.json)
// f32 cCamImpNml::getDistance();

// Address: 0x0003d2b0 - 0x0003d8b5 (1541 bytes)
__attribute__((weak)) void cCamImpNml::initSub(MtVector3& cameraPos, MtVector3& targetPos, f32& angX, f32& angY) {
    // local: const uCoord* pTarget;
    // local: uHuman* pPl;
    // local: cGeneralPoint* pGp;
    // local: const cGeneralPointPtr& gp;
    // local: MtVector3 cameraVecX;
    // local: MtVector3 vec;
    DDON_STUB("cCamImpNml::initSub")
    /* stub */
}

// Address: 0x0003d8d0 - 0x0003d9b3 (227 bytes)
__attribute__((weak)) void cCamImpNml::ctrlSub(MtVector3& idealCam, MtVector3& idealTar, f32& angX, f32& angY) {
    // local: bool isCtrl;
    // local: f32 aX;
    // local: f32 aY;
    DDON_STUB("cCamImpNml::ctrlSub")
    /* stub */
}

// Address: 0x0003d9c0 - 0x0003fc4f (8847 bytes)
__attribute__((weak)) void cCamImpNml::moveSub(MtVector3& idealCam, MtVector3& idealTar, f32& angX, f32& angY) {
    // local: MtVector3 nowCam;
    // local: MtVector3 nowTar;
    // local: uPlayer* pPl;
    // local: MtVector3 plCamOfs;
    // local: f32 offsetZ;
    // local: f32 height;
    // local: const uCoord* pModel;
    // local: f32 offsetX;
    // local: Param param;
    // local: MtVector3 targetPosCenter;
    // local: MtMatrix mat;
    // local: MtVector3 cameraVecX;
    // local: f32 dis;
    // local: MtMatrix mat;
    // local: f32 rate;
    // local: f32 scale;
    // local: cpCharacterEdit* pEdit;
    // local: f32 addHeight;
    // local: MtMatrix mat;
    // local: MtVector3 vec;
    // local: MtMatrix mat;
    // local: MtVector3 vec;
    // local: MtVector3 vecUp2;
    // local: uHuman* pPl;
    // local: cGeneralPoint* pGp;
    // local: MtVector3 targetPos;
    // local: f32 aX;
    // local: f32 aY;
    // local: MtVector3 vec;
    // local: f32 fov;
    // local: f32 marginH;
    // local: f32 marginV;
    // local: f32 fov;
    // local: MtMatrix vmat;
    // local: f32 aX;
    // local: f32 aY;
    // local: MtVector3 lPos;
    // local: MtMatrix mat;
    // local: f32 aX;
    // local: f32 aY;
    // local: bool isIntersectWall;
    // local: bool isAngY;
    // local: bool isAngX;
    // local: MtCapsule c;
    // local: bool canChange;
    // local: MtVector3 plMoveVec;
    // local: MtVector3 vec;
    // local: MtVector3 checkVec;
    // local: MtVector3 vec;
    // local: MtVector3 vMove;
    // local: MtVector3 plMoveVecNml;
    // local: MtVector3 camVecXZNml;
    // local: f32 len;
    // local: MtVector3 vec;
    // local: MtVector3 vMove;
    // local: MtVector3 vec;
    // local: uHuman* pPl;
    DDON_STUB("cCamImpNml::moveSub")
    /* stub */
}

// Address: 0x0003fc50 - 0x0003fc51 (1 bytes)
__attribute__((weak)) void cCamImpNml::interporateSub(MtVector3& cameraPos, MtVector3& targetPos) {
    // Empty in the binary (a single `ret`).
}

// Address: 0x0003fc60 - 0x0003fc69 (9 bytes)
void cCamImpNml::adjustSub(MtVector3& cameraPos, MtVector3& targetPos, MtVector3& idealCam, MtVector3& idealTar) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::cCamImpBase::mpC->::uCameraGame::dodgeScroll();
}

// Address: 0x0003fc70 - 0x0003fc8e (30 bytes)
void cCamImpNml::finalSub() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->::cCamImpBase::mIsKeepAngle != false) {
        return;
    }
    this->::cCamImpBase::mpC->mAngX = this->mInitAngX;
}

// Address: 0x01959360 - 0x01959363 (3 bytes)
nCameraGame::CAMERA_TYPE cCamImpNml::getType() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return static_cast<nCameraGame::CAMERA_TYPE>(0);
}

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_cCameraGameNml.cpp at 0x0003fdce-0x0003fe0b (called at cCameraGameNml.cpp:50)
//   in _GLOBAL__sub_I_cCameraGameNml.cpp at 0x0003fdce-0x0003fe0b (called at cCameraGameNml.h:26)
// cCamImpNml::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x0003c4b0 - 0x0003c674 (452 bytes)
__attribute__((weak)) MtObject* cCamImpNml::MyDTI::newInstance() const {
    DDON_STUB("cCamImpNml::MyDTI::newInstance")
    return nullptr;
}

