// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "cCaplinkUserIgnoreListGet.h"
#include "MtAllocator.h"
#include "MtCollection.h"
#include "MtDTI.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#include "cCaplinkContext.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: 2 inlined copies in 1 function (136 bytes)
//   in sCaplinkManager::sCaplinkManager at 0x00735b52-0x00735b96 (called at sCaplinkManager.cpp:771)
//   in sCaplinkManager::sCaplinkManager at 0x00735b52-0x00735b96 (called at cCaplinkUserIgnoreListGet.h:30)
// nCaplink::UserIgnoreListGetAns::UserIgnoreListGetAns();

// Address: 0x01abf050 - 0x01abf0d4 (132 bytes)
void nCaplink::UserIgnoreListGetAns::init() {
    // Approximate from the ELF: loops the one-loop renderer refuses, rendered through regions; the body oracle reports this body.
    this->::nCaplink::ContextListener::init();
    this->mIgnoreUserInfoTbl.mAutoDelete = true;
    if (this->mIgnoreUserInfoTbl.mLength != static_cast<u32>(0)) {
        // inferred: the value the loop at 0x1abf070 carries; DWARF names no local for it
        u32 v0_0 = this->mIgnoreUserInfoTbl.mLength;
        // inferred: the counter this loop steps; DWARF names no local for it
        for (unsigned int i0_3 = static_cast<unsigned int>(0);;) {
            if (this->mIgnoreUserInfoTbl.mpArray[i0_3] != static_cast<MtObject*>(nullptr)) {
                delete this->mIgnoreUserInfoTbl.mpArray[i0_3];
                if ((i0_3 + static_cast<unsigned int>(1)) < this->mIgnoreUserInfoTbl.mLength) {
                    v0_0 = this->mIgnoreUserInfoTbl.mLength;
                    i0_3 += static_cast<unsigned int>(1);
                } else {
                    break;
                }
            } else {
                if ((i0_3 + static_cast<unsigned int>(1)) < v0_0) {
                    i0_3 += static_cast<unsigned int>(1);
                } else {
                    break;
                }
            }
        }
    }
    if (this->mIgnoreUserInfoTbl.mpArray != static_cast<MtObject* *>(nullptr)) {
        ::MtMemoryAllocator::getAllocator(::MtArray::DTI)->memFree(static_cast<void*>(this->mIgnoreUserInfoTbl.mpArray));
    }
    this->mIgnoreUserInfoTbl.mpArray = static_cast<MtObject* *>(nullptr);
    this->mIgnoreUserInfoTbl.mBufsiz = static_cast<u32>(0);
    this->mIgnoreUserInfoTbl.mLength = static_cast<u32>(0);
    this->mTotal = static_cast<s32>(0);
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void nCaplink::UserIgnoreListGetAns::setTotal(s32 total);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void nCaplink::UserIgnoreListGetAns::setIgnoreUserInfoTbl(MtArray& entry_list);

// No out-of-line body: no code in the ELF
// s32 nCaplink::UserIgnoreListGetAns::getIgnoreUserTotal() const;

// No out-of-line body: no code in the ELF
// u32 nCaplink::UserIgnoreListGetAns::getIgnoreUserCount() const;

// No out-of-line body: 3 inlined copies in 3 functions (43 bytes)
//   in uGUICaplinkFriendList::getUniqueId at 0x009bd6e6-0x009bd6f5 (called at uGUICaplinkFriendList.cpp:2107)
//   in uGUICaplinkFriendList::getNickName at 0x009bda16-0x009bda25 (called at uGUICaplinkFriendList.cpp:2107)
//   in uGUICaplinkFriendList::setupIgnoreListItem at 0x009bf56f-0x009bf57c (called at uGUICaplinkFriendList.cpp:2107)
// nCaplink::cIgnoreUserInfo* nCaplink::UserIgnoreListGetAns::getIgnoreUserInfo(s32 index) const;

