#pragma once

#include <cstdint>
#include <cstddef>

// Dependencies
#include "MtCollection.h"
#include "MtDTI.h"
#include "MtObject.h"
#include "nDDOGame.h"

// Forward declarations
class MtAllocator;
class MtDTI;
class MtProperty;
class MtPropertyList;
class MtQuaternion;
class MtUI;
class MtVector3;
class cArcLoaderBase;
class cContextCharacter;
class cContextInstHm;
class cContextInstance;
class cContextPlayerInfo;
class cCorePointMsg;
class cDamageMsg;
class cEquipData;
class cGUIUtility;
class cItemParam;
class cParentRegionStatus;
class cPlayerLoadManager;
class cpCatchCtrl;
class cpCorePointCtrl;
class cpErosionEnemySmall;
class cpHpDamageCtrl;
class cpItemThrow;
class cpJob03;
class cpJob05;
class cpJob09;
class cpPawnThink;
class cpSlave;
namespace nActionManager { struct stActExParam; }
namespace nCharacterData { struct stCharacterName; }
namespace nCharacterData { struct stEquipData; }
namespace nHuman { struct stShellRequestInfo; }
namespace nHuman { struct stShellRequestMsg; }
namespace nHumanBow { struct stNetData; }
namespace nNetMsgData { struct stNetPos; }
namespace nObjCondition { struct stHolyAbsorpReqInfo; }
namespace nObjCondition { struct stHolyAbsorpReqMsg; }
namespace nObjCondition { struct stOcdActiveData; }
namespace nObjCondition { struct stOcdActiveMsg; }
namespace nRegionStatus { struct stCorePointSlaveMsg; }
namespace nShlBase { class cShlStickContextInfo; }
class rCharacterEdit;
class sSetManager;
class uCharacter;
class uControl;
class uControlNpc;
class uDDOModel;
class uEnemy;
class uHuman;
class uNpc;
class uPlayer;

// Declarations
class cContextInterface;

// Type aliases from DWARF
using CHAR_NAME = nCharacterData::stCharacterName;
using __uint64_t = long unsigned int;
using u64 = __uint64_t;
using HP_DATATYPE = u64;
using MT_CHAR = char;
using MT_CTSTR = const MT_CHAR*;
using TICKET = cArcLoaderBase*;
using _Sizet = long unsigned int;
using f32 = float;
using s32 = int;
using size_t = _Sizet;
using u16 = unsigned short;
using u32 = unsigned int;
using u8 = unsigned char;

class cContextInterface : public MtObject
{
    // inferred: cGUIUtility::isEquipLantern names uDDOModel::mContextInterface.mpContextInstance
    friend class cGUIUtility;
    // inferred: cParentRegionStatus::setHp names uDDOModel::mContextInterface.mpContextInstance
    friend class cParentRegionStatus;
    // inferred: cpCatchCtrl::forceCancel names uDDOModel::mContextInterface.mpContextInstance
    friend class cpCatchCtrl;
    // inferred: cpCorePointCtrl::checkSlaveMsg names uDDOModel::mContextInterface.mpContextInstance
    friend class cpCorePointCtrl;
    // inferred: cpErosionEnemySmall::checkReciveMsg names uDDOModel::mContextInterface.mpContextInstance
    friend class cpErosionEnemySmall;
    // inferred: cpHpDamageCtrl::callbackHealedAfter_make names uDDOModel::mContextInterface.mpContextInstance
    friend class cpHpDamageCtrl;
    // inferred: cpItemThrow::offItemMode names uDDOModel::mContextInterface.mpContextInstance
    friend class cpItemThrow;
    // inferred: cpJob03::setIsJustShot names uDDOModel::mContextInterface.mpContextInstance
    friend class cpJob03;
    // inferred: cpJob05::callbackCatch_Shl names uDDOModel::mContextInterface.mpContextInstance
    friend class cpJob05;
    // inferred: cpJob09::setContextCS03ValueMax names uDDOModel::mContextInterface.mpContextInstance
    friend class cpJob09;
    // inferred: cpPawnThink::sortFuncCharacterHp names uDDOModel::mContextInterface.mpContextInstance
    friend class cpPawnThink;
    // inferred: cpSlave::getTargetUID names uDDOModel::mContextInterface.mpContextInstance
    friend class cpSlave;
    // inferred: sSetManager::createCharacterInstance names uControl::mContextInterface.mpContextInstance
    friend class sSetManager;
    // inferred: uCharacter::setupActPreInit names uDDOModel::mContextInterface.mpContextInstance
    friend class uCharacter;
    // inferred: uControl::sendMasterParam names uControl::mContextInterface.mpContextInstance
    friend class uControl;
    // inferred: uControlNpc::setPawnId names uControl::mContextInterface.mpContextInstance
    friend class uControlNpc;
    // inferred: uDDOModel::setTarget names uDDOModel::mContextInterface.mpContextInstance
    friend class uDDOModel;
    // inferred: uEnemy::setupContextEnemyStatusChange names uDDOModel::mContextInterface.mpContextInstance
    friend class uEnemy;
    // inferred: uHuman::setupContextEnemyClimb names uDDOModel::mContextInterface.mpContextInstance
    friend class uHuman;
    // inferred: uNpc::controlLantern names uDDOModel::mContextInterface.mpContextInstance
    friend class uNpc;
    // inferred: uPlayer::kill names uControl::mContextInterface.mpContextInstance
    friend class uPlayer;
public:
    class MyDTI;
public:
    class MyDTI : public MtDTI
    {
    public:
        MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);
        virtual MtObject* newInstance() const;  // vtable slot 2
    };
public:
    static MtDTI* getMyDTIPtr();
    static void usage();
    virtual const MtDTI& getDTI() const;  // vtable slot 5
    static MtAllocator* getAllocator();
    static void setAllocator(u32);
    static void* operator new(size_t sz, u32 align);
    static void* operator new[](size_t sz, u32 align);
    static void* operator new(size_t sz, void* p_addr);
    static void* operator new[](size_t sz, void* p_addr);
    static void operator delete(void* p_addr);
    static void operator delete[](void* p_addr);
    static void operator delete(void* p_addr, u32 align);
    static void operator delete[](void* p_addr, u32 align);
    cContextInterface();
    virtual ~cContextInterface();
    virtual void createProperty(MtPropertyList& s);  // vtable slot 4
    virtual MtUI* createUI(MtProperty& prop);  // vtable slot 2
    void setContextInstance(cContextInstance* pInst);
    cContextInstance* getContextInstance();
    void setContextCharacter(cContextCharacter* pChara);
    cContextInstHm* getContextInstHm();
    bool isExistContextInstance();
    bool isExistContextCharacter();
    bool isExistContext();
    u64 getPosReceiveTime() const;
    static u64 getPosReceiveTime(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setPosReceiveTime(u64 time);
    static void setPosReceiveTime(cContextInstance* pInst, cContextCharacter* pChara, u64 time);
    s32 getPosReceiveInterval() const;
    static s32 getPosReceiveInterval(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setPosReceiveInterval(s32 interval);
    static void setPosReceiveInterval(cContextInstance* pInst, cContextCharacter* pChara, s32 interval);
    MtVector3 getNetPos() const;
    static MtVector3 getNetPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setNetPos(const MtVector3& pos);
    static void setNetPos(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& pos);
    const nNetMsgData::stNetPos& getNetRealPos() const;
    static const nNetMsgData::stNetPos& getNetRealPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setNetRealPos(const nNetMsgData::stNetPos&);
    static void setNetRealPos(cContextInstance* pInst, const nNetMsgData::stNetPos& pos);
    f32 getNetDir() const;
    static f32 getNetDir(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setNetDir(f32 dir);
    static void setNetDir(cContextInstance* pInst, cContextCharacter* pChara, f32 dir);
    s32 getStageNo();
    static s32 getStageNo(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setStageNo(s32 StageNo);
    static void setStageNo(cContextInstance* pInst, cContextCharacter* pChara, s32 StageNo);
    u32 getUniqueId() const;
    static u32 getUniqueId(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setUniqueId(u32);
    static void setUniqueId(cContextInstance* pInst, cContextCharacter* pChara, u32 UniqueId);
    u32 getQuestId() const;
    static u32 getQuestId(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setQuestId(u32 QuestId);
    static void setQuestId(cContextInstance* pInst, cContextCharacter* pChara, u32 QuestId);
    bool getIsReqAction(u32 idx) const;
    static bool getIsReqAction(const cContextInstance* pInst, const cContextCharacter* pChara, u32 idx);
    void clrIsReqAction(u32 idx);
    static void clrIsReqAction(cContextInstance* pInst, cContextCharacter* pChara, u32 idx);
    u32 getActNo(u32 idx) const;
    static u32 getActNo(const cContextInstance* pInst, const cContextCharacter* pChara, u32 idx);
    void setActNo(u32 idx, u32 no);
    static void setActNo(cContextInstance* pInst, cContextCharacter* pChara, u32 idx, u32 no);
    u8 getActReqPrio() const;
    static u8 getActReqPrio(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setActReqPrio(u8 prio);
    static void setActReqPrio(cContextInstance* pInst, cContextCharacter* pChara, u8 prio);
    u32 getActFreeWork() const;
    static u32 getActFreeWork(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setActFreeWork(u32 work);
    static void setActFreeWork(cContextInstance* pInst, cContextCharacter* pChara, u32 work);
    u64 getAttackParamUIDForDmVec() const;
    static u64 getAttackParamUIDForDmVec(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setAttackParamUIDForDmVec(u64 uID);
    static void setAttackParamUIDForDmVec(cContextInstance* pInst, cContextCharacter* pChara, u64 uID);
    f32 getMoveSpeed() const;
    static f32 getMoveSpeed(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setMoveSpeed(f32 speed);
    static void setMoveSpeed(cContextInstance* pInst, cContextCharacter* pChara, f32 speed);
    f32 getMoveAngle() const;
    static f32 getMoveAngle(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setMoveAngle(f32 angle);
    static void setMoveAngle(cContextInstance* pInst, cContextCharacter* pChara, f32 angle);
    MtVector3 getCliffPos() const;
    static MtVector3 getCliffPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setCliffPos(const MtVector3& pos);
    static void setCliffPos(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& pos);
    const nNetMsgData::stNetPos& getCliffRealPos() const;
    static const nNetMsgData::stNetPos& getCliffRealPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    const MtVector3& getCliffNormal() const;
    static const MtVector3& getCliffNormal(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setCliffNormal(const MtVector3& vec);
    static void setCliffNormal(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& vec);
    MtVector3 getCliffStartPos() const;
    static MtVector3 getCliffStartPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setCliffStartPos(const MtVector3& pos);
    static void setCliffStartPos(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& pos);
    const nNetMsgData::stNetPos& getCliffStartRealPos() const;
    static const nNetMsgData::stNetPos& getCliffStartRealPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    MtVector3 getCliffStartOldPos() const;
    static MtVector3 getCliffStartOldPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setCliffStartOldPos(const MtVector3& pos);
    static void setCliffStartOldPos(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& pos);
    const nNetMsgData::stNetPos& getCliffStartOldRealPos() const;
    static const nNetMsgData::stNetPos& getCliffStartOldRealPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    MtVector3 getWallClimbPos() const;
    static MtVector3 getWallClimbPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setWallClimbPos(const MtVector3& pos);
    void setWallClimbPos(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& pos);
    const nNetMsgData::stNetPos& getWallClimbRealPos() const;
    static const nNetMsgData::stNetPos& getWallClimbRealPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    const MtVector3& getWallClimbNormal() const;
    static const MtVector3& getWallClimbNormal(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setWallClimbNormal(const MtVector3& pos);
    void setWallClimbNormal(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& pos);
    MtVector3 getWallClimbLandPos() const;
    static MtVector3 getWallClimbLandPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setWallClimbLandPos(const MtVector3& pos);
    void setWallClimbLandPos(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& pos);
    const nNetMsgData::stNetPos& getWallClimbLandRealPos() const;
    static const nNetMsgData::stNetPos& getWallClimbLandRealPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    u32 getTargetUid() const;
    static u32 getTargetUid(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setTargetUid(const u32 uid);
    static void setTargetUid(cContextInstance* pInst, cContextCharacter* pChara, const u32 uid);
    MtVector3 getTargetPos() const;
    static MtVector3 getTargetPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setTargetPos(const MtVector3& pos);
    static void setTargetPos(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& pos);
    const nNetMsgData::stNetPos& getTargetRealPos() const;
    static const nNetMsgData::stNetPos& getTargetRealPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    const nActionManager::stActExParam* getActParam(u32) const;
    static const nActionManager::stActExParam* getActParam(const cContextInstance* pInst, const cContextCharacter* pChara, u32 idx);
    void setActExParam(u32 idx, const nActionManager::stActExParam* pSrc);
    static void setActExParam(cContextInstance* pInst, cContextCharacter* pChara, u32 idx, const nActionManager::stActExParam* pSrc);
    u32 getClimbEnemyUId() const;
    static u32 getClimbEnemyUId(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setClimbEnemyUId(u32 no);
    static void setClimbEnemyUId(cContextInstance* pInst, cContextCharacter* pChara, u32 no);
    s32 getClimbEnemyJointNo() const;
    static s32 getClimbEnemyJointNo(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setClimbEnemyJointNo(s32 no);
    static void setClimbEnemyJointNo(cContextInstance* pInst, cContextCharacter* pChara, s32 no);
    const MtVector3& getClimbEnemyJointOffset() const;
    static const MtVector3& getClimbEnemyJointOffset(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setClimbEnemyJointOffset(const MtVector3& offset);
    static void setClimbEnemyJointOffset(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& offset);
    u16 getClimbNodeIndex() const;
    static u16 getClimbNodeIndex(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setClimbNodeIndex(u16 NodeIndex);
    static void setClimbNodeIndex(cContextInstance* pInst, cContextCharacter* pChara, u16 NodeIndex);
    u16 getClimbGeomIndex() const;
    static u16 getClimbGeomIndex(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setClimbGeomIndex(u16 NodeIndex);
    static void setClimbGeomIndex(cContextInstance* pInst, cContextCharacter* pChara, u16 GeomIndex);
    bool isDead(u32 i) const;
    static bool isDead(const cContextInstance* pInst, const cContextCharacter* pChara, u32 i);
    void setIsDead(bool isDead, u32 i);
    static void setIsDead(cContextInstance* pInst, cContextCharacter* pChara, bool isDead, u32 i);
    bool isInjured() const;
    static bool isInjured(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsInjured(const bool flg);
    static void setIsInjured(cContextInstance* pInst, cContextCharacter* pChara, const bool flg);
    bool isLost() const;
    static bool isLost(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsLost(const bool flg);
    static void setIsLost(cContextInstance* pInst, cContextCharacter* pChara, const bool flg);
    bool isRescue() const;
    static bool isRescue(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsRescue(const bool flg);
    static void setIsRescue(cContextInstance* pInst, cContextCharacter* pChara, const bool flg);
    bool isReturnTerritory() const;
    static bool isReturnTerritory(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsReturnTerritory(const bool);
    static void setIsReturnTerritory(cContextInstance* pInst, cContextCharacter* pChara, const bool flg);
    HP_DATATYPE getHp(u32 i) const;
    static HP_DATATYPE getHp(const cContextInstance* pInst, const cContextCharacter* pChara, u32 i);
    void setHp(HP_DATATYPE hp, u32 i);
    static void setHp(cContextInstance* pInst, cContextCharacter* pChara, HP_DATATYPE hp, u32 i);
    HP_DATATYPE getHpMax(u32 i) const;
    static HP_DATATYPE getHpMax(const cContextInstance* pInst, const cContextCharacter* pChara, u32 i);
    void setHpMax(HP_DATATYPE hp, u32 i);
    static void setHpMax(cContextInstance* pInst, cContextCharacter* pChara, HP_DATATYPE hp, u32 i);
    bool getIsDeadCheatCheck(u32 i) const;
    static bool getIsDeadCheatCheck(const cContextInstance* pInst, const cContextCharacter* pChara, u32 i);
    HP_DATATYPE getHpCheatCheck(u32 i) const;
    static HP_DATATYPE getHpCheatCheck(const cContextInstance* pInst, const cContextCharacter* pChara, u32 i);
    HP_DATATYPE getHpMaxCheatCheck(u32 i) const;
    static HP_DATATYPE getHpMaxCheatCheck(const cContextInstance* pInst, const cContextCharacter* pChara, u32 i);
    bool isHpMax_calc() const;
    static bool isHpMax_calc(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setHpMax_calc(bool flag);
    static void setHpMax_calc(cContextInstance* pInst, cContextCharacter* pChara, bool flag);
    HP_DATATYPE getHpRaid(u32) const;
    static HP_DATATYPE getHpRaid(const cContextInstance* pInst, const cContextCharacter* pChara, u32 i);
    void setHpRaid(HP_DATATYPE hp, u32 i);
    static void setHpRaid(cContextInstance* pInst, cContextCharacter* pChara, HP_DATATYPE hp, u32 i);
    HP_DATATYPE getHpWhite() const;
    static HP_DATATYPE getHpWhite(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setHpWhite(HP_DATATYPE hp);
    static void setHpWhite(cContextInstance* pInst, cContextCharacter* pChara, HP_DATATYPE hp);
    void setStamina(f32 stamina);
    static void setStamina(cContextInstance* pInst, cContextCharacter* pChara, f32 stamina);
    u16 getUseRegionBit() const;
    static u16 getUseRegionBit(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setUseRegionBit(u16 regionBit);
    static void setUseRegionBit(cContextInstance* pInst, cContextCharacter* pChara, u16 useRegionBit);
    bool isUseRegion(u32 regionNo) const;
    static bool isUseRegion(const cContextInstance* pInst, const cContextCharacter* pChara, u32 regionNo);
    s32 getLv() const;
    static s32 getLv(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setLv(s32 lv);
    static void setLv(cContextInstance* pInst, cContextCharacter* pChara, s32 lv);
    f32 getShakeEndurance() const;
    static f32 getShakeEndurance(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setShakeEndurance(f32 endurance);
    static void setShakeEndurance(cContextInstance* pInst, cContextCharacter* pChara, f32 endurance);
    f32 getRageShrinkEndurance() const;
    static f32 getRageShrinkEndurance(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setRageShrinkEndurance(f32 endurance);
    static void setRageShrinkEndurance(cContextInstance* pInst, cContextCharacter* pChara, f32 endurance);
    u32 getOcdActiveMsgNum() const;
    static u32 getOcdActiveMsgNum(const cContextInstance* pInst, const cContextCharacter* pChara);
    const nObjCondition::stOcdActiveMsg& getOcdActiveMsg(u32 index) const;
    static const nObjCondition::stOcdActiveMsg& getOcdActiveMsg(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    void makeOcdMsgArray();
    static void makeOcdMsgArray(cContextInstance* pInst, cContextCharacter* pChara);
    void resetOcdMsgArray();
    static void resetOcdMsgArray(cContextInstance* pInst, cContextCharacter* pChara);
    void setOcdActiveMsg(u32, const nObjCondition::stOcdActiveMsg&);
    void setOcdActiveMsg(u32, u32, const nObjCondition::stOcdActiveMsg&);
    static void setOcdActiveMsg(cContextInstance*, cContextCharacter*, u32, const nObjCondition::stOcdActiveMsg&);
    static void setOcdActiveMsg(cContextInstance*, cContextCharacter*, u32, u32, const nObjCondition::stOcdActiveMsg&);
    const nObjCondition::stOcdActiveData& getOcdActiveData(u32) const;
    const nObjCondition::stOcdActiveData& getOcdActiveData(u32 bank, u32 index) const;
    static const nObjCondition::stOcdActiveData& getOcdActiveData(const cContextInstance* pInst, const cContextCharacter* pChara, u32 OcdUID);
    static const nObjCondition::stOcdActiveData& getOcdActiveData(const cContextInstance* pInst, const cContextCharacter* pChara, u32 bank, u32 index);
    void setOcdActiveData(u32 OcdUID, const nObjCondition::stOcdActiveData& data, bool isTimerReset);
    void setOcdActiveData(u32 bank, u32 index, const nObjCondition::stOcdActiveData& data, bool isTimerReset);
    static void setOcdActiveData(cContextInstance* pInst, cContextCharacter* pChara, u32 OcdUID, const nObjCondition::stOcdActiveData& data, bool isTimerReset);
    static void setOcdActiveData(cContextInstance* pInst, cContextCharacter* pChara, u32 bank, u32 index, const nObjCondition::stOcdActiveData& data, bool isTimerReset);
    void setOcdActiveTimer(u32 OcdUID, f32 timer);
    void setOcdActiveTimer(u32 bank, u32 index, f32 timer);
    static void setOcdActiveTimer(cContextInstance* pInst, cContextCharacter* pChara, u32 OcdUID, f32 timer);
    static void setOcdActiveTimer(cContextInstance* pInst, cContextCharacter* pChara, u32 bank, u32 index, f32 timer);
    f32 getOcdActiveTimer(u32 OcdUID) const;
    f32 getOcdActiveTimer(u32, u32) const;
    static f32 getOcdActiveTimer(const cContextInstance* pInst, const cContextCharacter* pChara, u32 OcdUID);
    static f32 getOcdActiveTimer(const cContextInstance* pInst, const cContextCharacter* pChara, u32 bank, u32 index);
    void setOcdAllTimerResetFlag(bool flag);
    static void setOcdAllTimerResetFlag(cContextInstance* pInst, cContextCharacter* pChara, bool flag);
    bool isOcdAllTimerReset() const;
    static bool isOcdAllTimerReset(const cContextInstance* pInst, const cContextCharacter* pChara);
    bool isOcdTimerReset(u32 OcdUID) const;
    bool isOcdTimerReset(u32, u32) const;
    static bool isOcdTimerReset(const cContextInstance* pInst, const cContextCharacter* pChara, u32 OcdUID);
    static bool isOcdTimerReset(const cContextInstance* pInst, const cContextCharacter* pChara, u32 bank, u32 index);
    void resetOcdTimerReset();
    static void resetOcdTimerReset(cContextInstance* pInst, cContextCharacter* pChara);
    void resetOcdActiveDataAll(bool isImmuneReset);
    static void resetOcdActiveDataAll(cContextInstance* pInst, cContextCharacter* pChara, bool isImmuneReset);
    void resetOcdActiveDataGoodStatus();
    static void resetOcdActiveDataGoodStatus(cContextInstance* pInst, cContextCharacter* pChara);
    bool isOcdActive(u32 OcdUID) const;
    bool isOcdActive(u32, u32) const;
    static bool isOcdActive(const cContextInstance* pInst, const cContextCharacter* pChara, u32 OcdUID);
    static bool isOcdActive(const cContextInstance* pInst, const cContextCharacter* pChara, u32 bank, u32 index);
    bool isPlayer() const;
    static bool isPlayer(const cContextInstance* pInst);
    static bool isPlayer(const cContextInstHm* pInst);
    bool isPawn() const;
    static bool isPawn(const cContextInstance* pInst);
    static bool isPawn(const cContextInstHm* pInst);
    bool isNpc() const;
    static bool isNpc(const cContextInstance* pInst);
    static bool isNpc(const cContextInstHm* pInst);
    bool isHumanEnemy() const;
    static bool isHumanEnemy(const cContextInstance* pInst);
    static bool isHumanEnemy(const cContextInstHm* pInst);
    f32 getEnchantRate() const;
    static f32 getEnchantRate(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnchantRate(f32 rate);
    static void setEnchantRate(cContextInstance* pInst, cContextCharacter* pChara, f32 rate);
    f32 getAilmentDamage() const;
    static f32 getAilmentDamage(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setAilmentDamage(f32 ailment);
    static void setAilmentDamage(cContextInstance* pInst, cContextCharacter* pChara, f32 ailment);
    f32 getAttackBasePhys() const;
    static f32 getAttackBasePhys(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setAttackBasePhys(f32 attack);
    static void setAttackBasePhys(cContextInstance* pInst, cContextCharacter* pChara, f32 attack);
    f32 getAttackBaseMagic() const;
    static f32 getAttackBaseMagic(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setAttackBaseMagic(f32 attack);
    static void setAttackBaseMagic(cContextInstance* pInst, cContextCharacter* pChara, f32 attack);
    f32 getAttackWepPhys() const;
    static f32 getAttackWepPhys(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setAttackWepPhys(f32 attack);
    static void setAttackWepPhys(cContextInstance* pInst, cContextCharacter* pChara, f32 attack);
    f32 getAttackWepMagic() const;
    static f32 getAttackWepMagic(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setAttackWepMagic(f32 attack);
    static void setAttackWepMagic(cContextInstance* pInst, cContextCharacter* pChara, f32 attack);
    f32 getDefenceBasePhys() const;
    static f32 getDefenceBasePhys(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setDefenceBasePhys(f32 deffence);
    static void setDefenceBasePhys(cContextInstance* pInst, cContextCharacter* pChara, f32 deffence);
    f32 getDefenceBaseMagic() const;
    static f32 getDefenceBaseMagic(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setDefenceBaseMagic(f32 deffence);
    static void setDefenceBaseMagic(cContextInstance* pInst, cContextCharacter* pChara, f32 deffence);
    f32 getDefenceWepPhys() const;
    static f32 getDefenceWepPhys(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setDefenceWepPhys(f32 deffence);
    static void setDefenceWepPhys(cContextInstance* pInst, cContextCharacter* pChara, f32 deffence);
    f32 getDefenceWepMagic() const;
    static f32 getDefenceWepMagic(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setDefenceWepMagic(f32 deffence);
    static void setDefenceWepMagic(cContextInstance* pInst, cContextCharacter* pChara, f32 deffence);
    f32 getPower() const;
    static f32 getPower(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setPower(f32 power);
    static void setPower(cContextInstance* pInst, cContextCharacter* pChara, f32 power);
    f32 getWeight() const;
    static f32 getWeight(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setWeight(f32 weight);
    static void setWeight(cContextInstance* pInst, cContextCharacter* pChara, f32 weight);
    f32 getShrinkWep() const;
    static f32 getShrinkWep(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setShrinkWep(f32 ShrinkWep);
    static void setShrinkWep(cContextInstance* pInst, cContextCharacter* pChara, f32 shrink);
    f32 getBlowWep() const;
    static f32 getBlowWep(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setBlowWep(f32 BlowWep);
    static void setBlowWep(cContextInstance* pInst, cContextCharacter* pChara, f32 blow);
    f32 getDownBase() const;
    static f32 getDownBase(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setDownBase(f32 downBase);
    static void setDownBase(cContextInstance* pInst, cContextCharacter* pChara, f32 down);
    f32 getDownWep() const;
    static f32 getDownWep(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setDownWep(f32 downWep);
    static void setDownWep(cContextInstance* pInst, cContextCharacter* pChara, f32 down);
    f32 getShakeBase() const;
    static f32 getShakeBase(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setShakeBase(f32 ShakeBase);
    static void setShakeBase(cContextInstance* pInst, cContextCharacter* pChara, f32 shake);
    f32 getGuardAttackBase() const;
    static f32 getGuardAttackBase(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setGuardAttackBase(f32 guard);
    static void setGuardAttackBase(cContextInstance* pInst, cContextCharacter* pChara, f32 guard);
    f32 getGuardDefenceBase() const;
    static f32 getGuardDefenceBase(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setGuardDefenceBase(f32 guard);
    static void setGuardDefenceBase(cContextInstance* pInst, cContextCharacter* pChara, f32 guard);
    f32 getGuardDefenceWep() const;
    static f32 getGuardDefenceWep(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setGuardDefenceWep(f32 guard);
    static void setGuardDefenceWep(cContextInstance* pInst, cContextCharacter* pChara, f32 guard);
    u32 getWeaponType() const;
    static u32 getWeaponType(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setWeaponType(u32);
    static void setWeaponType(cContextInstance* pInst, cContextCharacter* pChara, u32 type);
    u32 getWeaponTypeSe() const;
    static u32 getWeaponTypeSe(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setWeaponTypeSe(u32 type);
    static void setWeaponTypeSe(cContextInstance* pInst, cContextCharacter* pChara, u32 type);
    u32 getBodySize() const;
    static u32 getBodySize(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setBodySize(u32 size);
    static void setBodySize(cContextInstance* pInst, cContextCharacter* pChara, u32 size);
    bool isServerDamage() const;
    static bool isServerDamage(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsServerDamage();
    static void setIsServerDamage(cContextInstance* pInst, cContextCharacter* pChara);
    void clrIsServerDamage();
    static void clrIsServerDamage(cContextInstance* pInst, cContextCharacter* pChara);
    MtTypedArray<cDamageMsg>* getServerDamageMsgArray() const;
    static MtTypedArray<cDamageMsg>* getServerDamageMsgArray(const cContextInstance* pInst, cContextCharacter* pChara);
    const cDamageMsg* getServerDamageMsgTop() const;
    static const cDamageMsg* getServerDamageMsgTop(const cContextInstance* pInst, cContextCharacter* pChara);
    void eraseServerDamageMsgTop();
    static void eraseServerDamageMsgTop(const cContextInstance* pInst, cContextCharacter* pChara);
    u32 getServerDamageMsgNum();
    static u32 getServerDamageMsgNum(cContextInstance* pInst, cContextCharacter* pChara);
    void addServerDamageMsg(const cDamageMsg* pMsg);
    static void addServerDamageMsg(cContextInstance* pInst, cContextCharacter* pChara, const cDamageMsg* pMsg);
    void clearServerDamageMsg();
    static void clearServerDamageMsg(cContextInstance* pInst, cContextCharacter* pChara);
    bool isSlaveDamage() const;
    static bool isSlaveDamage(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsSlaveDamage();
    static void setIsSlaveDamage(cContextInstance* pInst, cContextCharacter* pChara);
    void clrIsSlaveDamage();
    static void clrIsSlaveDamage(cContextInstance* pInst, cContextCharacter* pChara);
    MtTypedArray<cDamageMsg>* getDamageMsgArray() const;
    static MtTypedArray<cDamageMsg>* getDamageMsgArray(const cContextInstance* pInst, cContextCharacter* pChara);
    const cDamageMsg* getDamageMsgTop() const;
    static const cDamageMsg* getDamageMsgTop(const cContextInstance* pInst, cContextCharacter* pChara);
    void eraseDamageMsgTop();
    static void eraseDamageMsgTop(const cContextInstance* pInst, cContextCharacter* pChara);
    u32 getDamageMsgNum();
    static u32 getDamageMsgNum(cContextInstance* pInst, cContextCharacter* pChara);
    void addDamageMsg(const cDamageMsg* pMsg);
    static void addDamageMsg(cContextInstance* pInst, cContextCharacter* pChara, const cDamageMsg* pMsg);
    void clearDamageMsg();
    static void clearDamageMsg(cContextInstance* pInst, cContextCharacter* pChara);
    u32 getAttackUID() const;
    static u32 getAttackUID(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setAttackUID(u32);
    static void setAttackUID(cContextInstance* pInst, cContextCharacter* pChara, u32 uid);
    u64 getAttackParamUID() const;
    static u64 getAttackParamUID(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setAttackParamUID(u64);
    static void setAttackParamUID(cContextInstance* pInst, cContextCharacter* pChara, u64 uid);
    u64 getDfdCollNodeUID() const;
    static u64 getDfdCollNodeUID(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setDfdCollNodeUID(u64);
    static void setDfdCollNodeUID(cContextInstance* pInst, cContextCharacter* pChara, u64 uid);
    MtVector3 getDamageDir() const;
    static MtVector3 getDamageDir(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setDamageDir(const MtVector3&);
    static void setDamageDir(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& damage_dir);
    u32 getAttackAttr() const;
    static u32 getAttackAttr(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setAttackAttr(u32);
    static void setAttackAttr(cContextInstance* pInst, cContextCharacter* pChara, const u32 attack_attr);
    u32 getShlOwnerUID() const;
    static u32 getShlOwnerUID(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setShlOwnerUID(u32);
    static void setShlOwnerUID(cContextInstance* pInst, cContextCharacter* pChara, u32 uid);
    u16 getActAtkAdjustUniqueId() const;
    static u16 getActAtkAdjustUniqueId(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setActAtkAdjustUniqueId(u16 uid);
    static void setActAtkAdjustUniqueId(cContextInstance* pInst, cContextCharacter* pChara, u16 uid);
    u16 getAtkAdjustUniqueId() const;
    static u16 getAtkAdjustUniqueId(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setAtkAdjustUniqueId(u16);
    static void setAtkAdjustUniqueId(cContextInstance* pInst, cContextCharacter* pChara, u16 uid);
    f32 getDamage() const;
    static f32 getDamage(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setDamage(f32);
    static void setDamage(cContextInstance* pInst, cContextCharacter* pChara, f32 damage);
    bool isCatchHit() const;
    static bool isCatchHit(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsCatchHit();
    static void setIsCatchHit(cContextInstance* pInst, cContextCharacter* pChara);
    void clrIsCatchHit();
    static void clrIsCatchHit(cContextInstance* pInst, cContextCharacter* pChara);
    bool isCaughtResult() const;
    static bool isCaughtResult(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsCaughtResult();
    static void setIsCaughtResult(cContextInstance* pInst, cContextCharacter* pChara);
    void clrIsCaughtResult();
    static void clrIsCaughtResult(cContextInstance* pInst, cContextCharacter* pChara);
    u8 getCatchType() const;
    static u8 getCatchType(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setCatchType(u8 type);
    static void setCatchType(cContextInstance* pInst, cContextCharacter* pChara, u8 type);
    u8 getCatchResult() const;
    static u8 getCatchResult(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setCatchResult(u8);
    static void setCatchResult(cContextInstance* pInst, cContextCharacter* pChara, u8 result);
    u8 getCatchJointNo() const;
    static u8 getCatchJointNo(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setCatchJointNo(u8 no);
    static void setCatchJointNo(cContextInstance* pInst, cContextCharacter* pChara, u8 no);
    u32 getCatchTargetUID() const;
    static u32 getCatchTargetUID(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setCatchTargetUID(u32 uid);
    static void setCatchTargetUID(cContextInstance* pInst, cContextCharacter* pChara, u32 uid);
    MtVector3 getCatchHitPos() const;
    static MtVector3 getCatchHitPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setCatchHitPos(MtVector3& vec);
    static void setCatchHitPos(cContextInstance* pInst, cContextCharacter* pChara, MtVector3& vec);
    bool getIsOmReleaseThrow() const;
    static bool getIsOmReleaseThrow(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsOmReleaseThrow(bool isOmReleaseThrow);
    static void setIsOmReleaseThrow(cContextInstance* pInst, cContextCharacter* pChara, bool isOmReleaseThrow);
    bool getIsOmReleasePut() const;
    static bool getIsOmReleasePut(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsOmReleasePut(bool isOmReleasePut);
    static void setIsOmReleasePut(cContextInstance* pInst, cContextCharacter* pChara, bool isOmReleasePut);
    const nNetMsgData::stNetPos& getOmReleaseRealPos() const;
    static const nNetMsgData::stNetPos& getOmReleaseRealPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    MtVector3 getOmReleasePos() const;
    static MtVector3 getOmReleasePos(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setOmReleasePos(const MtVector3& pos);
    static void setOmReleasePos(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& pos);
    f32 getOmReleaseAngle() const;
    static f32 getOmReleaseAngle(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setOmReleaseAngle(f32 angle);
    static void setOmReleaseAngle(cContextInstance* pInst, cContextCharacter* pChara, f32 angle);
    MtQuaternion getOmReleaseQuat() const;
    static MtQuaternion getOmReleaseQuat(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setOmReleaseQuat(const MtQuaternion& quat);
    static void setOmReleaseQuat(cContextInstance* pInst, cContextCharacter* pChara, const MtQuaternion& quat);
    f32 getLostTimer() const;
    static f32 getLostTimer(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setLostTimer(f32 time);
    static void setLostTimer(cContextInstance* pInst, cContextCharacter* pChara, f32 time);
    void subLostTimer();
    static void subLostTimer(cContextInstance* pInst, cContextCharacter* pChara);
    bool isIsInstantDead() const;
    static bool isIsInstantDead(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsInstantDead(bool b);
    static void setIsInstantDead(cContextInstance* pInst, cContextCharacter* pChara, bool b);
    u32 getShlDelte() const;
    static u32 getShlDelte(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setShlDelte(u32 bit);
    static void setShlDelte(cContextInstance* pInst, cContextCharacter* pChara, u32 bit);
    u32 getShlNetSts(u32 index) const;
    static u32 getShlNetSts(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    bool isShlNetSts(u32 sts, u32 index) const;
    static bool isShlNetSts(const cContextInstance* pInst, const cContextCharacter* pChara, u32 sts, u32 index);
    void setShlNetSts(u32 sts, u32 index);
    static void setShlNetSts(cContextInstance* pInst, cContextCharacter* pChara, u32 sts, u32 index);
    u32 getShlUniqueId(u32 index) const;
    static u32 getShlUniqueId(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    void setShlUniqueId(u32 uid, u32 index);
    static void setShlUniqueId(cContextInstance* pInst, cContextCharacter* pChara, u32 uid, u32 index);
    u32 getShlTargetUId(u32 index) const;
    static u32 getShlTargetUId(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    void setShlTargetUId(u32 uid, u32 index);
    static void setShlTargetUId(cContextInstance* pInst, cContextCharacter* pChara, u32 uid, u32 index);
    s32 getShlGroup(u32 index) const;
    static s32 getShlGroup(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    void setShlGroup(s32 group, u32 index);
    static void setShlGroup(cContextInstance* pInst, cContextCharacter* pChara, s32 group, u32 index);
    s32 getShlIndex(u32 index) const;
    static s32 getShlIndex(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    void setShlIndex(s32 shl_index, u32 index);
    static void setShlIndex(cContextInstance* pInst, cContextCharacter* pChara, s32 shl_index, u32 index);
    bool isShlReqSlave(u32 index) const;
    static bool isShlReqSlave(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    void setIsShlReqSlave(bool flg, u32 index);
    static void setIsShlReqSlave(cContextInstance* pInst, cContextCharacter* pChara, bool flg, u32 index);
    bool isShotReqNoAct() const;
    static bool isShotReqNoAct(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsShotReqNoAct(bool flg);
    static void setIsShotReqNoAct(cContextInstance* pInst, cContextCharacter* pChara, bool flg);
    MtVector3 getShlPos(u32 index) const;
    static MtVector3 getShlPos(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    void setShlPos(const MtVector3& pos, u32 index);
    static void setShlPos(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& pos, u32 index);
    const nNetMsgData::stNetPos& getShlRealPos(u32 index) const;
    static const nNetMsgData::stNetPos& getShlRealPos(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    MtVector3 getShlTarget(u32 index) const;
    static MtVector3 getShlTarget(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    void setShlTarget(const MtVector3& pos, u32 index);
    static void setShlTarget(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& pos, u32 index);
    const nNetMsgData::stNetPos& getShlTargetRealPos(u32 index) const;
    static const nNetMsgData::stNetPos& getShlTargetRealPos(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    const MtVector3 getShlDir(u32 index) const;
    static const MtVector3 getShlDir(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    void setShlDir(const MtVector3& dir, u32 index);
    static void setShlDir(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& dir, u32 index);
    u8 getShlLockOnId(u32 index) const;
    static u8 getShlLockOnId(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    void setShlLockOnId(u8 id, u32 index);
    static void setShlLockOnId(cContextInstance* pInst, cContextCharacter* pChara, u8 id, u32 index);
    u8 getShlShotReceiveNum() const;
    static u8 getShlShotReceiveNum(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setShlShotReceiveNum(u8 num);
    static void setShlShotReceiveNum(cContextInstance* pInst, cContextCharacter* pChara, u8 num);
    bool isReqStickShl() const;
    static bool isReqStickShl(const cContextInstance* pInst, const cContextCharacter* pChara);
    void addShlStickInfo(nShlBase::cShlStickContextInfo* pinfo);
    static void addShlStickInfo(cContextInstance* pInst, cContextCharacter* pChara, nShlBase::cShlStickContextInfo* pinfo);
    void requestShlStickInfoContext();
    static void requestShlStickInfoContext(cContextInstance* pInst, cContextCharacter* pChara);
    bool isStickCreateControl() const;
    static bool isStickCreateControl(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsStickCreateControl(bool flg);
    static void setIsStickCreateControl(cContextInstance* pInst, cContextCharacter* pChara, bool flg);
    u32 getStickShlUniqueId() const;
    static u32 getStickShlUniqueId(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setStickShlUniqueId(u32);
    static void setStickShlUniqueId(cContextInstance* pInst, cContextCharacter* pChara, u32 id);
    u32 getStickUniqueId() const;
    static u32 getStickUniqueId(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setStickUniqueId(u32);
    static void setStickUniqueId(cContextInstance* pInst, cContextCharacter* pChara, u32 id);
    u8 getStickJointNo() const;
    static u8 getStickJointNo(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setStickJointNo(u8);
    static void setStickJointNo(cContextInstance* pInst, cContextCharacter* pChara, u8 no);
    u8 getStickShlGroup() const;
    static u8 getStickShlGroup(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setStickShlGroup(u8);
    static void setStickShlGroup(cContextInstance* pInst, cContextCharacter* pChara, u8 no);
    u8 getStickShlIndex() const;
    static u8 getStickShlIndex(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setStickShlIndex(u8);
    static void setStickShlIndex(cContextInstance* pInst, cContextCharacter* pChara, u8 no);
    const MtVector3 getStickJointOffset() const;
    static const MtVector3 getStickJointOffset(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setStickJointOffset(const MtVector3&);
    static void setStickJointOffset(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& offset);
    const MtVector3 getStickDirection() const;
    static const MtVector3 getStickDirection(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setStickDirection(const MtVector3&);
    static void setStickDirection(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& dir);
    bool isShlKillSync() const;
    static bool isShlKillSync(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsShlKillSync(bool flg);
    static void setIsShlKillSync(cContextInstance* pInst, cContextCharacter* pChara, bool flg);
    bool isShlSlaveKill() const;
    static bool isShlSlaveKill(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setIsShlSlaveKill(bool flg);
    static void setIsShlSlaveKill(cContextInstance* pInst, cContextCharacter* pChara, bool flg);
    u8 getSlaveKillSyncSts() const;
    static u8 getSlaveKillSyncSts(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setSlaveKillSyncSts(u8 bit);
    static void setSlaveKillSyncSts(cContextInstance* pInst, cContextCharacter* pChara, u8 bit);
    u32 getEnemyStatusGroupNum() const;
    static u32 getEnemyStatusGroupNum(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnemyStatusGroupNum(u32 groupNum);
    static void setEnemyStatusGroupNum(cContextInstance* pInst, cContextCharacter* pChara, u32 groupNum);
    bool addEnemyStatusGroup(u32 group, u32 subGroup);
    static bool addEnemyStatusGroup(cContextInstance* pInst, cContextCharacter* pChara, u32 group, u32 subGroup);
    u32 getEnemyStatusGroup(u32 idx) const;
    static u32 getEnemyStatusGroup(const cContextInstance* pInst, const cContextCharacter* pChara, u32 idx);
    void setEnemyStatusGroup(u32 idx, u32 group);
    static void setEnemyStatusGroup(cContextInstance* pInst, cContextCharacter* pChara, u32 idx, u32 group);
    u32 getEnemyStatusSubGroup(u32 idx) const;
    static u32 getEnemyStatusSubGroup(const cContextInstance* pInst, const cContextCharacter* pChara, u32 idx);
    void setEnemyStatusSubGroup(u32 idx, u32 subGroup);
    static void setEnemyStatusSubGroup(cContextInstance* pInst, cContextCharacter* pChara, u32 idx, u32 subGroup);
    bool isEnemyBitReceive() const;
    static bool isEnemyBitReceive(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnemyBitReceive(bool enable);
    static void setEnemyBitReceive(cContextInstance* pInst, cContextCharacter* pChara, bool enable);
    u64 getEnemyBitCtrlCollision() const;
    static u64 getEnemyBitCtrlCollision(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnemyBitCtrlCollision(u64 bit);
    static void setEnemyBitCtrlCollision(cContextInstance* pInst, cContextCharacter* pChara, u64 bit);
    u8 getEnemyCtrRegionSelectNo() const;
    static u8 getEnemyCtrRegionSelectNo(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnemyCtrRegionSelectNo(u8 selectNo);
    static void setEnemyCtrRegionSelectNo(cContextInstance* pInst, cContextCharacter* pChara, u8 selectNo);
    u64 getEnemyBitCtrParts() const;
    static u64 getEnemyBitCtrParts(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnemyBitCtrParts(u64 bit);
    static void setEnemyBitCtrParts(cContextInstance* pInst, cContextCharacter* pChara, u64 bit);
    u64 getEnemyWorkRate() const;
    static u64 getEnemyWorkRate(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnemyWorkRate(u64 bit);
    static void setEnemyWorkRate(cContextInstance* pInst, cContextCharacter* pChara, u64 bit);
    u64 getEnemyScale() const;
    static u64 getEnemyScale(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnemyScale(u64 bit);
    static void setEnemyScale(cContextInstance* pInst, cContextCharacter* pChara, u64 bit);
    u64 getEnemyBitCtrlMontage() const;
    static u64 getEnemyBitCtrlMontage(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnemyBitCtrlMontage(u64 bit);
    static void setEnemyBitCtrlMontage(cContextInstance* pInst, cContextCharacter* pChara, u64 bit);
    u32 getEnemyBitCtrlSyncBit() const;
    static u32 getEnemyBitCtrlSyncBit(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnemyBitCtrlSyncBit(u32 bit);
    static void setEnemyBitCtrlSyncBit(cContextInstance* pInst, cContextCharacter* pChara, u32 bit);
    bool isEnemyStatusChange() const;
    static bool isEnemyStatusChange(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnemyStatusChange(bool enable);
    static void setEnemyStatusChange(cContextInstance* pInst, cContextCharacter* pChara, bool enable);
    bool getEnemyWaitting() const;
    static bool getEnemyWaitting(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnemyWaitting(bool enable);
    static void setEnemyWaitting(cContextInstance* pInst, cContextCharacter* pChara, bool enable);
    bool isEnemyWaittingChange() const;
    static bool isEnemyWaittingChange(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnemyWaittingChange(bool enable);
    static void setEnemyWaittingChange(cContextInstance* pInst, cContextCharacter* pChara, bool enable);
    bool getEnemyStartWait() const;
    static bool getEnemyStartWait(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnemyStartWait(bool enable);
    static void setEnemyStartWait(cContextInstance* pInst, cContextCharacter* pChara, bool enable);
    bool isEnemyStartWaitChange() const;
    static bool isEnemyStartWaitChange(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setEnemyStartWaitChange(bool enable);
    static void setEnemyStartWaitChange(cContextInstance* pInst, cContextCharacter* pChara, bool enable);
    void addCorePointMsg(const cCorePointMsg* pMsg);
    static void addCorePointMsg(cContextInstance* pInst, cContextCharacter* pChara, const cCorePointMsg* pMsg);
    u32 getUnSendedCorePointMsgNum() const;
    static u32 getUnSendedCorePointMsgNum(const cContextInstance* pInst, const cContextCharacter* pChara);
    cCorePointMsg* getUnSendedTopCorePointMsg() const;
    static cCorePointMsg* getUnSendedTopCorePointMsg(const cContextInstance* pInst, const cContextCharacter* pChara);
    u32 getCorePointMsgNum() const;
    static u32 getCorePointMsgNum(const cContextInstance* pInst, const cContextCharacter* pChara);
    cCorePointMsg* getCorePointMsg(u32 index) const;
    static cCorePointMsg* getCorePointMsg(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    void eraseCorePointMsg(u32 index);
    static void eraseCorePointMsg(cContextInstance* pInst, cContextCharacter* pChara, u32 index);
    u32 getMontageFixNo() const;
    static u32 getMontageFixNo(const cContextInstance* pInst);
    void setMontageFixNo(u32);
    static void setMontageFixNo(cContextInstance* pInst, u32 fixNo);
    u32 getMontageRandom() const;
    static u32 getMontageRandom(const cContextInstance* pInst);
    void setMontageRandom(u32);
    static void setMontageRandom(cContextInstance* pInst, u32 rand);
    const nRegionStatus::stCorePointSlaveMsg& getCorePointSlaveMsg(u32) const;
    static const nRegionStatus::stCorePointSlaveMsg& getCorePointSlaveMsg(cContextInstance* pInst, cContextCharacter* pChara, u32 index);
    u32 getCorePointSlaveMsgNum() const;
    static u32 getCorePointSlaveMsgNum(cContextInstance* pInst, cContextCharacter* pChara);
    bool isSendCorePointSlaveFlag_On() const;
    static bool isSendCorePointSlaveFlag_On(cContextInstance* pInst, cContextCharacter* pChara);
    void sendCorePointSlaveFlag_On();
    static void sendCorePointSlaveFlag_On(cContextInstance* pInst, cContextCharacter* pChara);
    void sendCorePointSlaveFlag_Off();
    static void sendCorePointSlaveFlag_Off(cContextInstance* pInst, cContextCharacter* pChara);
    void addCorePointSlaveMsg(const nRegionStatus::stCorePointSlaveMsg& src);
    static void addCorePointSlaveMsg(cContextInstance* pInst, cContextCharacter* pChara, const nRegionStatus::stCorePointSlaveMsg& src);
    void clearCorePointSlaveMsg(u32);
    static void clearCorePointSlaveMsg(cContextInstance* pInst, cContextCharacter* pChara, u32 index);
    void clearCorePointSlaveMsgAll();
    static void clearCorePointSlaveMsgAll(cContextInstance* pInst, cContextCharacter* pChara);
    const nRegionStatus::stCorePointSlaveMsg& getCorePointSlaveMsgTop() const;
    static const nRegionStatus::stCorePointSlaveMsg& getCorePointSlaveMsgTop(cContextInstance* pInst, cContextCharacter* pChara);
    void clearCorePointSlaveMsgTop();
    static void clearCorePointSlaveMsgTop(cContextInstance* pInst, cContextCharacter* pChara);
    u16 getCommonWork() const;
    static u16 getCommonWork(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setCommonWork(u16 work);
    static void setCommonWork(cContextInstance* pInst, cContextCharacter* pChara, u16 work);
    void addCommonWork(u16 work);
    static void addCommonWork(cContextInstance* pInst, cContextCharacter* pChara, u16 work);
    void subCommonWork(u16 work);
    static void subCommonWork(cContextInstance* pInst, cContextCharacter* pChara, u16 work);
    bool isCommonWork(u16 work) const;
    static bool isCommonWork(const cContextInstance* pInst, const cContextCharacter* pChara, u16 work);
    u16 getCustomWork() const;
    static u16 getCustomWork(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setCustomWork(u16 work);
    static void setCustomWork(cContextInstance* pInst, cContextCharacter* pChara, u16 work);
    void addCustomWork(u16 work);
    static void addCustomWork(cContextInstance* pInst, cContextCharacter* pChara, u16 work);
    void subCustomWork(u16 work);
    static void subCustomWork(cContextInstance* pInst, cContextCharacter* pChara, u16 work);
    bool isCustomWork(u16 work) const;
    static bool isCustomWork(const cContextInstance* pInst, const cContextCharacter* pChara, u16 work);
    u32 getStateLive() const;
    static u32 getStateLive(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setStateLive(u32 state);
    static void setStateLive(cContextInstance* pInst, cContextCharacter* pChara, u32 state);
    bool isStateLiveChange() const;
    static bool isStateLiveChange(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setStateLiveChange(bool flg);
    static void setStateLiveChange(cContextInstance* pInst, cContextCharacter* pChara, bool flg);
    bool isBowUpActUpdate() const;
    static bool isBowUpActUpdate(const cContextInstance* pInst, const cContextCharacter* pChara);
    const nHumanBow::stNetData& popBowUpNetData() const;
    static const nHumanBow::stNetData& popBowUpNetData(const cContextInstance* pInst, cContextCharacter* pChara);
    void pushBowUpNetData(const nHumanBow::stNetData& d);
    static void pushBowUpNetData(cContextInstance* pInst, cContextCharacter* pChara, const nHumanBow::stNetData& d);
    void pushBowLockOnInfo(u32 index, u32 uid, u32 lockId);
    void popBowLockOnInfo(u32 index, u32& uid, u32& lockId);
    bool isBowLowActUpdate() const;
    static bool isBowLowActUpdate(const cContextInstance* pInst, const cContextCharacter* pChara);
    const nHumanBow::stNetData& popBowLowNetData() const;
    static const nHumanBow::stNetData& popBowLowNetData(const cContextInstance* pInst, cContextCharacter* pChara);
    void pushBowLowNetData(const nHumanBow::stNetData& d);
    static void pushBowLowNetData(cContextInstance* pInst, cContextCharacter* pChara, const nHumanBow::stNetData& d);
    bool isBowPeriodUpdate() const;
    static bool isBowPeriodUpdate(const cContextInstance* pInst, const cContextCharacter* pChara);
    const nHumanBow::stNetData& popBowPeriodNetData() const;
    static const nHumanBow::stNetData& popBowPeriodNetData(const cContextInstance* pInst, cContextCharacter* pChara);
    void pushBowPeriodNetData(const nHumanBow::stNetData& d);
    static void pushBowPeriodNetData(cContextInstance* pInst, cContextCharacter* pChara, const nHumanBow::stNetData& d);
    const MtVector3& getBowNetAimPos() const;
    static const MtVector3& getBowNetAimPos(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setBowNetAimPos(const MtVector3& pos);
    static void setBowNetAimPos(cContextInstance* pInst, cContextCharacter* pChara, const MtVector3& pos);
    f32 getBowMoveRadian() const;
    static f32 getBowMoveRadian(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setBowMoveRadian(f32 rad);
    static void setBowMoveRadian(cContextInstance* pInst, cContextCharacter* pChara, f32 rad);
    u32 getBowNetUpdateFlag() const;
    static u32 getBowNetUpdateFlag(const cContextInstance* pInst, const cContextCharacter* pChara);
    void setBowNetUpdateFlag(u32 rad);
    static void setBowNetUpdateFlag(cContextInstance* pInst, cContextCharacter* pChara, u32 flag);
    bool getMasterChangeFlag() const;
    static bool getMasterChangeFlag(const cContextInstance* pInst);
    void setMasterChangeFlag(bool flg);
    static void setMasterChangeFlag(cContextInstance* pInst, bool flg);
    s32 getMasterIndex();
    static s32 getMasterIndex(const cContextInstance* pInst);
    void setMasterIndex(s32 MasterIndex);
    static void setMasterIndex(cContextInstance* pInst, s32 masterIndex);
    s32 getMainEncountArea() const;
    static s32 getMainEncountArea(const cContextInstance* pInst);
    void setMainEncountArea(s32);
    static void setMainEncountArea(cContextInstance* pInst, s32 encountArea);
    bool getSendChangeMaster() const;
    static bool getSendChangeMaster(const cContextInstance* pInst);
    void setSendChangeMaster(bool);
    static void setSendChangeMaster(cContextInstance* pInst, bool flg);
    bool getSetWaitFlag() const;
    static bool getSetWaitFlag(const cContextInstance* pInst);
    void setSetWaitFlag(bool flg);
    static void setSetWaitFlag(cContextInstance* pInst, bool flg);
    bool isSessionLost() const;
    static bool isSessionLost(const cContextInstance* pInst);
    static bool isSessionLost(const cContextInstHm* pInst);
    bool isPartyLeader() const;
    static bool isPartyLeader(const cContextInstance* pInst);
    static bool isPartyLeader(const cContextInstHm* pInst);
    bool isPawnOwner() const;
    static bool isPawnOwner(const cContextInstance* pInst);
    static bool isPawnOwner(const cContextInstHm* pInst);
    s32 getPawnOwnerIndex() const;
    static s32 getPawnOwnerIndex(const cContextInstance* pInst);
    static s32 getPawnOwnerIndex(const cContextInstHm* pInst);
    u8 getIndex() const;
    static u8 getIndex(const cContextInstance* pInst);
    static u8 getIndex(const cContextInstHm* pInst);
    static void setIndex(cContextInstHm* pInst, u8 index);
    u32 getRPCID() const;
    static u32 getRPCID(const cContextInstance* pInst);
    static u32 getRPCID(const cContextInstHm* pInst);
    u32 getSex() const;
    static u32 getSex(const cContextInstance* pInst);
    static u32 getSex(const cContextInstHm* pInst);
    void setSex(u32 sex);
    static void setSex(cContextInstance* pInst, u32 sex);
    static void setSex(cContextInstHm* pInst, u32 sex);
    rCharacterEdit* getCharacterEdit() const;
    static rCharacterEdit* getCharacterEdit(const cContextInstance* pInst);
    static rCharacterEdit* getCharacterEdit(const cContextInstHm* pInst);
    static const rCharacterEdit* getCharacterEditConst(const cContextInstance*);
    static const rCharacterEdit* getCharacterEditConst(const cContextInstHm* pInst);
    s32 getFloorGroupNo() const;
    static s32 getFloorGroupNo(const cContextInstance* pInst);
    static s32 getFloorGroupNo(const cContextInstHm* pInst);
    void setFloorGroupNo(const s32);
    static void setFloorGroupNo(cContextInstance* pInst, const s32 no);
    static void setFloorGroupNo(cContextInstHm* pInst, const s32 no);
    s32 getStartPosNo() const;
    static s32 getStartPosNo(const cContextInstance* pInst);
    static s32 getStartPosNo(const cContextInstHm* pInst);
    void setStartPosNo(const s32);
    static void setStartPosNo(cContextInstance* pInst, const s32 no);
    static void setStartPosNo(cContextInstHm* pInst, const s32 no);
    const CHAR_NAME& getName() const;
    static const CHAR_NAME& getName(const cContextInstance* pInst);
    static const CHAR_NAME& getName(const cContextInstHm* pInst);
    void setName(const CHAR_NAME& name);
    static void setName(cContextInstance* pInst, const CHAR_NAME& name);
    static void setName(cContextInstHm* pInst, const CHAR_NAME& name);
    MT_CTSTR getFirstName() const;
    static MT_CTSTR getFirstName(const cContextInstance* pInst);
    static MT_CTSTR getFirstName(const cContextInstHm* pInst);
    void setFirstName(MT_CTSTR);
    static void setFirstName(cContextInstance* pInst, MT_CTSTR name);
    static void setFirstName(cContextInstHm* pInst, MT_CTSTR name);
    MT_CTSTR getLastName() const;
    static MT_CTSTR getLastName(const cContextInstance* pInst);
    static MT_CTSTR getLastName(const cContextInstHm* pInst);
    void setLastName(MT_CTSTR);
    static void setLastName(cContextInstance* pInst, MT_CTSTR name);
    static void setLastName(cContextInstHm* pInst, MT_CTSTR name);
    MT_CTSTR getClanNickName() const;
    static MT_CTSTR getClanNickName(const cContextInstance* pInst);
    static MT_CTSTR getClanNickName(const cContextInstHm* pInst);
    void setClanNickName(MT_CTSTR);
    static void setClanNickName(cContextInstance* pInst, MT_CTSTR name);
    static void setClanNickName(cContextInstHm* pInst, MT_CTSTR name);
    bool isFriend() const;
    static bool isFriend(const cContextInstance* pInst);
    static bool isFriend(const cContextInstHm* pInst);
    bool isClanMember() const;
    static bool isClanMember(const cContextInstance* pInst);
    static bool isClanMember(const cContextInstHm* pInst);
    void setOnlineStatus(const u8);
    static void setOnlineStatus(cContextInstance* pInst, const u8 status);
    static void setOnlineStatus(cContextInstHm* pInst, const u8 status);
    u8 getOnlineStatus() const;
    static u8 getOnlineStatus(const cContextInstance* pInst);
    static u8 getOnlineStatus(const cContextInstHm* pInst);
    u8 getJob() const;
    static u8 getJob(const cContextInstance* pInst);
    static u8 getJob(const cContextInstHm* pInst);
    void setJob(u8 Job);
    static void setJob(cContextInstance* pInst, u8 Job);
    static void setJob(cContextInstHm* pInst, u8 Job);
    const cEquipData& getContextEquipConst() const;
    static const cEquipData& getContextEquipConst(const cContextInstance* pInst);
    static const cEquipData& getContextEquipConst(const cContextInstHm* pInst);
    cEquipData& getContextEquip();
    static cEquipData& getContextEquip(cContextInstance* pInst);
    static cEquipData& getContextEquip(cContextInstHm* pInst);
    u16 getEquipData(u8, u8) const;
    static u16 getEquipData(const cContextInstance* pInst, u8 category, u8 type);
    static u16 getEquipData(const cContextInstHm* pInst, u8 category, u8 type);
    void setEquipData(u8, cItemParam*, u8);
    static void setEquipData(cContextInstance* pInst, u8 category, cItemParam* pItem, u8 type);
    static void setEquipData(cContextInstHm* pInst, u8 category, cItemParam* pItem, u8 type);
    void setEquipFromCharData(const nCharacterData::stEquipData&);
    static void setEquipFromCharData(cContextInstance* pInst, const nCharacterData::stEquipData& Data);
    static void setEquipFromCharData(cContextInstHm* pInst, const nCharacterData::stEquipData& Data);
    s32 getPlayerLoadWeapon() const;
    static s32 getPlayerLoadWeapon(const cContextInstance* pInst);
    static s32 getPlayerLoadWeapon(const cContextInstHm* pInst);
    void setPlayerLoadWeapon(s32);
    static void setPlayerLoadWeapon(cContextInstance* pInst, s32 wp);
    static void setPlayerLoadWeapon(cContextInstHm* pInst, s32 wp);
    s32 getPlayerLoadStatus() const;
    static s32 getPlayerLoadStatus(const cContextInstance* pInst);
    static s32 getPlayerLoadStatus(const cContextInstHm* pInst);
    void setPlayerLoadStatus(s32 status);
    static void setPlayerLoadStatus(cContextInstance* pInst, s32 status);
    static void setPlayerLoadStatus(cContextInstHm* pInst, s32 status);
    TICKET getWeaponArcTicket() const;
    static TICKET getWeaponArcTicket(const cContextInstance* pInst);
    static TICKET getWeaponArcTicket(const cContextInstHm* pInst);
    void setWeaponArcTicket(TICKET);
    static void setWeaponArcTicket(cContextInstance* pInst, TICKET ticket);
    static void setWeaponArcTicket(cContextInstHm* pInst, TICKET ticket);
    cPlayerLoadManager& getPlayerLoadMgr();
    static cPlayerLoadManager& getPlayerLoadMgr(cContextInstance* pInst);
    static cPlayerLoadManager& getPlayerLoadMgr(cContextInstHm* pInst);
    u8 getVoice() const;
    static u8 getVoice(const cContextInstance* pInst);
    static u8 getVoice(const cContextInstHm* pInst);
    void setVoice(u8);
    static void setVoice(cContextInstance* pInst, u8 Voice);
    static void setVoice(cContextInstHm* pInst, u8 Voice);
    s32 getVoicePitch() const;
    static s32 getVoicePitch(const cContextInstance* pInst);
    static s32 getVoicePitch(const cContextInstHm* pInst);
    void setVoicePitch(s32);
    static void setVoicePitch(cContextInstance* pInst, s32 pitch);
    static void setVoicePitch(cContextInstHm* pInst, s32 pitch);
    u8 getHumanType() const;
    static u8 getHumanType(const cContextInstance* pInst);
    static u8 getHumanType(const cContextInstHm* pInst);
    void setHumanType(u8);
    static void setHumanType(cContextInstance* pInst, u8 type);
    static void setHumanType(cContextInstHm* pInst, u8 type);
    u8 getPawnType() const;
    static u8 getPawnType(const cContextInstance* pInst);
    static u8 getPawnType(const cContextInstHm* pInst);
    void setPawnType(u8);
    static void setPawnType(cContextInstance* pInst, u8 type);
    static void setPawnType(cContextInstHm* pInst, u8 type);
    u32 getRawCharacterId() const;
    static u32 getRawCharacterId(const cContextInstance* pInst);
    static u32 getRawCharacterId(const cContextInstHm* pInst);
    void setCharacterId(u32);
    static void setCharacterId(cContextInstance* pInst, u32 charId);
    static void setCharacterId(cContextInstHm* pInst, u32 charId);
    u32 getPlCharacterId() const;
    static u32 getPlCharacterId(const cContextInstance* pInst);
    static u32 getPlCharacterId(const cContextInstHm* pInst);
    u32 getPawnOwnerCharacterId() const;
    static u32 getPawnOwnerCharacterId(const cContextInstance* pInst);
    static u32 getPawnOwnerCharacterId(const cContextInstHm* pInst);
    u32 getPawnId() const;
    static u32 getPawnId(const cContextInstance* pInst);
    static u32 getPawnId(const cContextInstHm* pInst);
    void setPawnId(u32);
    static void setPawnId(cContextInstance* pInst, u32 pawnId);
    static void setPawnId(cContextInstHm* pInst, u32 pawnId);
    bool checkId(u32, u32) const;
    static bool checkId(const cContextInstance* pInst, u32 characterId, u32 pawnId);
    static bool checkId(const cContextInstHm* pInst, u32 characterId, u32 pawnId);
    bool checkId(const cContextInstHm* pCheckInst) const;
    static bool checkId(const cContextInstance* pInst, const cContextInstHm* pCheckInst);
    static bool checkId(const cContextInstHm* pInst, const cContextInstHm* pCheckInst);
    s32 getMemberIndex() const;
    static s32 getMemberIndex(const cContextInstance* pInst);
    static s32 getMemberIndex(const cContextInstHm* pInst);
    void setMemberIndex(s32);
    static void setMemberIndex(cContextInstance* pInst, s32 memberIndex);
    static void setMemberIndex(cContextInstHm* pInst, s32 memberIndex);
    s32 getEncountArea(u32 index) const;
    static s32 getEncountArea(const cContextInstance* pInst, u32 index);
    static s32 getEncountArea(const cContextInstHm* pInst, u32 index);
    const s32* getEncountAreaBuff() const;
    static const s32* getEncountAreaBuff(const cContextInstance* pInst);
    static const s32* getEncountAreaBuff(const cContextInstHm* pInst);
    void setEncountArea(s32* areaArray, s32 num);
    static void setEncountArea(cContextInstance* pInst, s32* areaArray, s32 num);
    static void setEncountArea(cContextInstHm* pInst, s32* areaArray, s32 num);
    MtVector3 getLastSafePos() const;
    static MtVector3 getLastSafePos(const cContextInstance* pInst);
    static MtVector3 getLastSafePos(const cContextInstHm* pInst);
    void setLastSafePos(const MtVector3& pos);
    static void setLastSafePos(cContextInstance* pInst, const MtVector3& pos);
    static void setLastSafePos(cContextInstHm* pInst, const MtVector3& pos);
    const nNetMsgData::stNetPos& getLastSafeRealPos() const;
    static const nNetMsgData::stNetPos& getLastSafeRealPos(const cContextInstance* pInst);
    static const nNetMsgData::stNetPos& getLastSafeRealPos(const cContextInstHm* pInst);
    void setLastSafeRealPos(const nNetMsgData::stNetPos&);
    static void setLastSafeRealPos(cContextInstance* pInst, const nNetMsgData::stNetPos& pos);
    static void setLastSafeRealPos(cContextInstHm* pInst, const nNetMsgData::stNetPos& pos);
    u16 getPawnAutoMotion(u32 situation) const;
    static u16 getPawnAutoMotion(const cContextInstance* pInst, u32 situation);
    static u16 getPawnAutoMotion(const cContextInstHm* pInst, u32 situation);
    void setPawnAutoMotion(u32, u16);
    static void setPawnAutoMotion(cContextInstance* pInst, u32 situation, u16 val);
    static void setPawnAutoMotion(cContextInstHm* pInst, u32 situation, u16 val);
    u16 getPawnPersonality() const;
    static u16 getPawnPersonality(const cContextInstance* pInst);
    static u16 getPawnPersonality(const cContextInstHm* pInst);
    void setPawnPersonality(u16);
    static void setPawnPersonality(cContextInstance* pInst, u16 val);
    static void setPawnPersonality(cContextInstHm* pInst, u16 val);
    u16 getPawnTalkLv() const;
    static u16 getPawnTalkLv(const cContextInstance* pInst);
    static u16 getPawnTalkLv(const cContextInstHm* pInst);
    void setPawnTalkLv(u16);
    static void setPawnTalkLv(cContextInstance* pInst, u16 val);
    static void setPawnTalkLv(cContextInstHm* pInst, u16 val);
    u32 getPawnTalkCharId(u32 idx) const;
    static u32 getPawnTalkCharId(const cContextInstance* pInst, u32 idx);
    static u32 getPawnTalkCharId(const cContextInstHm* pInst, u32 idx);
    void setPawnTalkCharId(u32 idx, u32 charId);
    static void setPawnTalkCharId(cContextInstance* pInst, u32 idx, u32 charId);
    static void setPawnTalkCharId(cContextInstHm* pInst, u32 idx, u32 charId);
    bool getPawnTalkSituationFlag(u32 flag) const;
    static bool getPawnTalkSituationFlag(const cContextInstance* pInst, u32 flag);
    static bool getPawnTalkSituationFlag(const cContextInstHm* pInst, u32 flag);
    void setPawnTalkSituationFlag(u32 flag, bool on);
    static void setPawnTalkSituationFlag(cContextInstance* pInst, u32 flag, bool on);
    static void setPawnTalkSituationFlag(cContextInstHm* pInst, u32 flag, bool on);
    cContextPlayerInfo* getContextPlayerInfo();
    static cContextPlayerInfo* getContextPlayerInfo(cContextInstance* pInst);
    static cContextPlayerInfo* getContextPlayerInfo(cContextInstHm* pInst);
    static const cContextPlayerInfo* getContextPlayerInfo(const cContextInstHm* pInst);
    u8 getReviveStock() const;
    static u8 getReviveStock(const cContextInstance* pInst);
    static u8 getReviveStock(const cContextInstHm* pInst);
    void setReviveStock(u8);
    static void setReviveStock(cContextInstance* pInst, u8 num);
    static void setReviveStock(cContextInstHm* pInst, u8 num);
    s32 getReviveType() const;
    static s32 getReviveType(const cContextInstance* pInst);
    static s32 getReviveType(const cContextInstHm* pInst);
    void setReviveType(s32 type);
    static void setReviveType(cContextInstance* pInst, s32 type);
    static void setReviveType(cContextInstHm* pInst, s32 type);
    MtVector3 getPosFreeMarker(u32) const;
    static MtVector3 getPosFreeMarker(const cContextInstance* pInst, u32 idx);
    static MtVector3 getPosFreeMarker(const cContextInstHm* pInst, u32 idx);
    void setPosFreeMarker(const MtVector3&, u32);
    static void setPosFreeMarker(cContextInstance* pInst, const MtVector3& vPos, u32 idx);
    static void setPosFreeMarker(cContextInstHm* pInst, const MtVector3& vPos, u32 idx);
    s32 getStageNoFreeMarker(u32) const;
    static s32 getStageNoFreeMarker(const cContextInstance* pInst, u32 idx);
    static s32 getStageNoFreeMarker(const cContextInstHm* pInst, u32 idx);
    void setStageNoFreeMarker(s32, u32);
    static void setStageNoFreeMarker(cContextInstance* pInst, s32 sStageNo, u32 idx);
    static void setStageNoFreeMarker(cContextInstHm* pInst, s32 sStageNo, u32 idx);
    s32 getGroupNoFreeMarker(u32) const;
    static s32 getGroupNoFreeMarker(const cContextInstance* pInst, u32 idx);
    static s32 getGroupNoFreeMarker(const cContextInstHm* pInst, u32 idx);
    void setGroupNoFreeMarker(s32, u32);
    static void setGroupNoFreeMarker(cContextInstance* pInst, s32 sStageNo, u32 idx);
    static void setGroupNoFreeMarker(cContextInstHm* pInst, s32 sStageNo, u32 idx);
    f32 getElementGuardTime() const;
    static f32 getElementGuardTime(const cContextInstance* pInst);
    static f32 getElementGuardTime(const cContextInstHm* pInst);
    void setElementGuardTime(f32 time);
    static void setElementGuardTime(cContextInstance* pInst, f32 time);
    static void setElementGuardTime(cContextInstHm* pInst, f32 time);
    f32 getElementCoverRate() const;
    static f32 getElementCoverRate(const cContextInstance* pInst);
    static f32 getElementCoverRate(const cContextInstHm* pInst);
    void setElementCoverRate(f32 rate);
    static void setElementCoverRate(cContextInstance* pInst, f32 rate);
    static void setElementCoverRate(cContextInstHm* pInst, f32 rate);
    nDDOGame::ELEMENT_TYPE getElementCoverType() const;
    static nDDOGame::ELEMENT_TYPE getElementCoverType(const cContextInstance* pInst);
    static nDDOGame::ELEMENT_TYPE getElementCoverType(const cContextInstHm* pInst);
    void setElementCoverType(nDDOGame::ELEMENT_TYPE type);
    static void setElementCoverType(cContextInstance* pInst, nDDOGame::ELEMENT_TYPE type);
    static void setElementCoverType(cContextInstHm* pInst, nDDOGame::ELEMENT_TYPE type);
    f32 getElementCoverDamageRate() const;
    static f32 getElementCoverDamageRate(const cContextInstance* pInst);
    static f32 getElementCoverDamageRate(const cContextInstHm* pInst);
    void setElementCoverDamageRate(f32 rate);
    static void setElementCoverDamageRate(cContextInstance* pInst, f32 rate);
    static void setElementCoverDamageRate(cContextInstHm* pInst, f32 rate);
    f32 getFJobWork0() const;
    static f32 getFJobWork0(const cContextInstance* pInst);
    static f32 getFJobWork0(const cContextInstHm* pInst);
    void setFJobWork0(f32 work);
    static void setFJobWork0(cContextInstance* pInst, f32 work);
    static void setFJobWork0(cContextInstHm* pInst, f32 work);
    f32 getFJobWork1() const;
    static f32 getFJobWork1(const cContextInstance* pInst);
    static f32 getFJobWork1(const cContextInstHm* pInst);
    void setFJobWork1(f32 work);
    static void setFJobWork1(cContextInstance* pInst, f32 work);
    static void setFJobWork1(cContextInstHm* pInst, f32 work);
    s32 getSJobWork0() const;
    static s32 getSJobWork0(const cContextInstance* pInst);
    static s32 getSJobWork0(const cContextInstHm* pInst);
    void setSJobWork0(s32 work);
    static void setSJobWork0(cContextInstance* pInst, s32 work);
    static void setSJobWork0(cContextInstHm* pInst, s32 work);
    s32 getSJobWork1() const;
    static s32 getSJobWork1(const cContextInstance* pInst);
    static s32 getSJobWork1(const cContextInstHm* pInst);
    void setSJobWork1(s32 work);
    static void setSJobWork1(cContextInstance* pInst, s32 work);
    static void setSJobWork1(cContextInstHm* pInst, s32 work);
    u32 getHmRandom() const;
    static u32 getHmRandom(const cContextInstance* pInst);
    static u32 getHmRandom(const cContextInstHm* pInst);
    void setHmRandom(u32);
    static void setHmRandom(cContextInstance* pInst, u32 random);
    static void setHmRandom(cContextInstHm* pInst, u32 random);
    u8 getHmEmEditType() const;
    static u8 getHmEmEditType(const cContextInstance* pInst);
    static u8 getHmEmEditType(const cContextInstHm* pInst);
    void setHmEmEditType(u8);
    static void setHmEmEditType(cContextInstance* pInst, u8 type);
    static void setHmEmEditType(cContextInstHm* pInst, u8 type);
    u32 getHmEmPresetId() const;
    static u32 getHmEmPresetId(const cContextInstance* pInst);
    static u32 getHmEmPresetId(const cContextInstHm* pInst);
    void setHmEmPresetId(u32);
    static void setHmEmPresetId(cContextInstance* pInst, u32 random);
    static void setHmEmPresetId(cContextInstHm* pInst, u32 random);
    u32 getHmEmId() const;
    static u32 getHmEmId(const cContextInstance* pInst);
    static u32 getHmEmId(const cContextInstHm* pInst);
    void setHmEmId(u32);
    static void setHmEmId(cContextInstance* pInst, u32 id);
    static void setHmEmId(cContextInstHm* pInst, u32 id);
    bool isReturnPrepare() const;
    static bool isReturnPrepare(const cContextInstance* pInst);
    static bool isReturnPrepare(const cContextInstHm* pInst);
    void setIsReturnPrepare(bool);
    static void setIsReturnPrepare(cContextInstance* pInst, bool flag);
    static void setIsReturnPrepare(cContextInstHm* pInst, bool flag);
    bool isAreaChangePrepare() const;
    static bool isAreaChangePrepare(const cContextInstance* pInst);
    static bool isAreaChangePrepare(const cContextInstHm* pInst);
    void setIsAreaChangePrepare(bool);
    static void setIsAreaChangePrepare(cContextInstance* pInst, bool flag);
    static void setIsAreaChangePrepare(cContextInstHm* pInst, bool flag);
    bool isReqSetLostAction() const;
    static bool isReqSetLostAction(const cContextInstance* pInst);
    static bool isReqSetLostAction(const cContextInstHm* pInst);
    void reqSetLostAction(bool flag);
    static void reqSetLostAction(cContextInstance* pInst, bool flag);
    static void reqSetLostAction(cContextInstHm* pInst, bool flag);
    s32 getOldGaugeContextType() const;
    static s32 getOldGaugeContextType(const cContextInstance* pInst);
    static s32 getOldGaugeContextType(const cContextInstHm* pInst);
    void setOldGaugeContextType(s32);
    static void setOldGaugeContextType(cContextInstance* pInst, s32 type);
    static void setOldGaugeContextType(cContextInstHm* pInst, s32 type);
    bool isAbility098() const;
    static bool isAbility098(const cContextInstance* pInst);
    static bool isAbility098(const cContextInstHm* pInst);
    void setIsAbility098(bool flag);
    static void setIsAbility098(cContextInstance* pInst, bool flag);
    static void setIsAbility098(cContextInstHm* pInst, bool flag);
    bool isGutsDisable() const;
    static bool isGutsDisable(const cContextInstance* pInst);
    static bool isGutsDisable(const cContextInstHm* pInst);
    void setIsGutsDisable(bool flag);
    static void setIsGutsDisable(cContextInstance* pInst, bool flag);
    static void setIsGutsDisable(cContextInstHm* pInst, bool flag);
    bool isAbility370() const;
    static bool isAbility370(const cContextInstance* pInst);
    static bool isAbility370(const cContextInstHm* pInst);
    void setIsAbility370(bool flag);
    static void setIsAbility370(cContextInstance* pInst, bool flag);
    static void setIsAbility370(cContextInstHm* pInst, bool flag);
    bool isSyncCustomSkillGroup() const;
    static bool isSyncCustomSkillGroup(const cContextInstance* pInst);
    static bool isSyncCustomSkillGroup(const cContextInstHm* pInst);
    void setIsSyncCustomSkillGroup(bool flag);
    static void setIsSyncCustomSkillGroup(cContextInstance* pInst, bool flag);
    static void setIsSyncCustomSkillGroup(cContextInstHm* pInst, bool flag);
    void copySendData();
    void copySendData(cContextCharacter* pChara);
    const nNetMsgData::stNetPos& getSendBuffNetPos() const;
    static const nNetMsgData::stNetPos& getSendBuffNetPos(const cContextCharacter* pChara);
    f32 getSendBuffMoveSpeed() const;
    static f32 getSendBuffMoveSpeed(const cContextCharacter* pChara);
    f32 getSendBuffMoveAngle() const;
    static f32 getSendBuffMoveAngle(const cContextCharacter* pChara);
    f32 getSendBuffNetDir() const;
    static f32 getSendBuffNetDir(const cContextCharacter* pChara);
    u32 getSendBuffActNo(u32 idx) const;
    static u32 getSendBuffActNo(const cContextCharacter* pChara, u32 idx);
    u8 getSendBuffActReqPrio() const;
    static u8 getSendBuffActReqPrio(const cContextCharacter* pChara);
    u16 getSendBuffActAtkAdjustUniqueId() const;
    static u16 getSendBuffActAtkAdjustUniqueId(const cContextCharacter* pChara);
    u32 getSendBuffActFreeWork() const;
    static u32 getSendBuffActFreeWork(const cContextCharacter* pChara);
    f32 getSendBuffHp(u32 i) const;
    static f32 getSendBuffHp(const cContextCharacter* pChara, u32 i);
    HP_DATATYPE getSendBuffHpWhite() const;
    static HP_DATATYPE getSendBuffHpWhite(const cContextCharacter* pChara);
    u16 getSendBuffCommonWork() const;
    static u16 getSendBuffCommonWork(const cContextCharacter* pChara);
    u16 getSendBuffCustomWork() const;
    static u16 getSendBuffCustomWork(const cContextCharacter* pChara);
    u32 getSendBuffOcdActiveMsgNum() const;
    static u32 getSendBuffOcdActiveMsgNum(const cContextCharacter* pChara);
    const nObjCondition::stOcdActiveMsg& getSendBuffOcdActiveMsg(u32) const;
    static const nObjCondition::stOcdActiveMsg& getSendBuffOcdActiveMsg(const cContextCharacter* pChara, u32 index);
    u32 getSendBuffTargetUid() const;
    static u32 getSendBuffTargetUid(const cContextCharacter* pChara);
    const MtVector3& getSendBuffTargetPos() const;
    static const MtVector3& getSendBuffTargetPos(const cContextCharacter* pChara);
    const nObjCondition::stHolyAbsorpReqInfo& getAbsorpReqInfoTop() const;
    static const nObjCondition::stHolyAbsorpReqInfo& getAbsorpReqInfoTop(const cContextInstance* pInst, const cContextCharacter* pChara);
    void clearAbsorpReqInfoTop();
    static void clearAbsorpReqInfoTop(cContextInstance* pInst, cContextCharacter* pChara);
    const nObjCondition::stHolyAbsorpReqInfo& getAbsorpReqInfo(u32) const;
    static const nObjCondition::stHolyAbsorpReqInfo& getAbsorpReqInfo(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    void registAbsorpReqMsg(const nObjCondition::stHolyAbsorpReqMsg& srcMsg);
    static void registAbsorpReqMsg(cContextInstance* pInst, cContextCharacter* pChara, const nObjCondition::stHolyAbsorpReqMsg& srcMsg);
    u32 getAbsorpReqNum() const;
    static u32 getAbsorpReqNum(const cContextInstance* pInst, const cContextCharacter* pChara);
    void clearAbsorpReq(u32);
    static void clearAbsorpReq(cContextInstance* pInst, cContextCharacter* pChara, u32 index);
    void clearAbsorpReqArray();
    static void clearAbsorpReqArray(cContextInstance* pInst, cContextCharacter* pChara);
    bool isAbsorpNetFlagOn() const;
    static bool isAbsorpNetFlagOn(const cContextInstance* pInst, const cContextCharacter* pChara);
    void cancelAbsorpNetFlag();
    static void cancelAbsorpNetFlag(cContextInstance* pInst, cContextCharacter* pChara);
    void absorpNetFlagOn();
    static void absorpNetFlagOn(cContextInstance* pInst, cContextCharacter* pChara);
    const nObjCondition::stHolyAbsorpReqInfo& getSoulAbsorpReqInfoTop() const;
    static const nObjCondition::stHolyAbsorpReqInfo& getSoulAbsorpReqInfoTop(const cContextInstance* pInst, const cContextCharacter* pChara);
    void clearSoulAbsorpReqInfoTop();
    static void clearSoulAbsorpReqInfoTop(cContextInstance* pInst, cContextCharacter* pChara);
    const nObjCondition::stHolyAbsorpReqInfo& getSoulAbsorpReqInfo(u32) const;
    static const nObjCondition::stHolyAbsorpReqInfo& getSoulAbsorpReqInfo(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    void registSoulAbsorpReqMsg(const nObjCondition::stHolyAbsorpReqMsg& srcMsg);
    static void registSoulAbsorpReqMsg(cContextInstance* pInst, cContextCharacter* pChara, const nObjCondition::stHolyAbsorpReqMsg& srcMsg);
    u32 getSoulAbsorpReqNum() const;
    static u32 getSoulAbsorpReqNum(const cContextInstance* pInst, const cContextCharacter* pChara);
    void clearSoulAbsorpReq(u32);
    static void clearSoulAbsorpReq(cContextInstance* pInst, cContextCharacter* pChara, u32 index);
    void clearSoulAbsorpReqArray();
    static void clearSoulAbsorpReqArray(cContextInstance* pInst, cContextCharacter* pChara);
    bool isSoulAbsorpNetFlagOn() const;
    static bool isSoulAbsorpNetFlagOn(const cContextInstance* pInst, const cContextCharacter* pChara);
    void cancelSoulAbsorpNetFlag();
    static void cancelSoulAbsorpNetFlag(cContextInstance* pInst, cContextCharacter* pChara);
    void soulAbsorpNetFlagOn();
    static void soulAbsorpNetFlagOn(cContextInstance* pInst, cContextCharacter* pChara);
    const nHuman::stShellRequestInfo& getShellRequestInfoTop() const;
    static const nHuman::stShellRequestInfo& getShellRequestInfoTop(const cContextInstance* pInst, const cContextCharacter* pChara);
    void clearShellRequestInfoTop();
    static void clearShellRequestInfoTop(cContextInstance* pInst, cContextCharacter* pChara);
    const nHuman::stShellRequestInfo& getShellRequestInfo(u32) const;
    static const nHuman::stShellRequestInfo& getShellRequestInfo(const cContextInstance* pInst, const cContextCharacter* pChara, u32 index);
    void registShellRequestMsg(const nHuman::stShellRequestMsg& srcMsg);
    static void registShellRequestMsg(cContextInstance* pInst, cContextCharacter* pChara, const nHuman::stShellRequestMsg& srcMsg);
    u32 getShellRequestNum() const;
    static u32 getShellRequestNum(const cContextInstance* pInst, const cContextCharacter* pChara);
    void clearShellRequest(u32);
    static void clearShellRequest(cContextInstance* pInst, cContextCharacter* pChara, u32 index);
    void clearShellRequestArray();
    static void clearShellRequestArray(cContextInstance* pInst, cContextCharacter* pChara);
    bool isShellRequestNetFlagOn() const;
    static bool isShellRequestNetFlagOn(const cContextInstance* pInst, const cContextCharacter* pChara);
    void cancelShellRequestNetFlag();
    static void cancelShellRequestNetFlag(cContextInstance* pInst, cContextCharacter* pChara);
    void shellRequestNetFlagOn();
    static void shellRequestNetFlagOn(cContextInstance* pInst, cContextCharacter* pChara);
private:
    cContextInstance* mpContextInstance;  // offset: 0x8
    cContextCharacter* mpContextCharacter;  // offset: 0x10
public:
    static MyDTI DTI;
};
