// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "cCorePointMsg.h"
#include "MtAllocator.h"
#include "MtDTI.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* cCorePointMsg::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cCorePointMsg::usage();

// Address: 0x01962890 - 0x01962898 (8 bytes)
const MtDTI& cCorePointMsg::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cCorePointMsg::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* cCorePointMsg::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::cCorePointMsg::DTI);
}

// No out-of-line body: no code in the ELF
// void cCorePointMsg::setAllocator(u32);

// Address: 0x0006f220 - 0x0006f260 (64 bytes)
void* cCorePointMsg::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::cCorePointMsg::getAllocator()->memAlloc(sz, align, ::cCorePointMsg::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* cCorePointMsg::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cCorePointMsg::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cCorePointMsg::operator new[](size_t sz, void* p_addr);

// Address: 0x0006f290 - 0x0006f2ba (42 bytes)
__attribute__((weak)) void cCorePointMsg::operator delete(void* p_addr) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    ::cCorePointMsg::getAllocator()->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cCorePointMsg::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cCorePointMsg::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cCorePointMsg::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 10 inlined copies in 5 functions (332 bytes)
//   in cContextInstChar::addCorePointMsg at 0x000572cf-0x000572ff (called at cContextInstance.cpp:587)
//   in cContextInstChar::addCorePointMsg at 0x000572cf-0x000572ff (called at cCorePointMsg.h:22)
//   in cCorePointMsg::MyDTI::newInstance at 0x0006f1ed-0x0006f215 (called at cCorePointMsg.cpp:13)
//   and 7 more (every copy is in <bundle>.inlined.json)
// cCorePointMsg::cCorePointMsg();

// No out-of-line body: 1 inlined copy in 1 function (45 bytes)
//   in cContextInstChar::addCorePointMsg at 0x00057308-0x00057335 (called at cContextInstance.cpp:593)
// void cCorePointMsg::copy(const cCorePointMsg& msg);

// No out-of-line body: 1 inlined copy in 1 function (7 bytes)
//   in nNetMsg::cNetMsgCtrlAction::receiveMessageCore at 0x00386b7e-0x00386b85 (called at cNetMsgCtrl.cpp:2084)
// void cCorePointMsg::setRegionCorePointID(u16 ID);

// No out-of-line body: no code in the ELF
// u16 cCorePointMsg::getRegionCorePointID() const;

// No out-of-line body: 1 inlined copy in 1 function (7 bytes)
//   in nNetMsg::cNetMsgCtrlAction::receiveMessageCore at 0x00386b8e-0x00386b95 (called at cNetMsgCtrl.cpp:2085)
// void cCorePointMsg::setActiveTimer(u16 time);

// No out-of-line body: no code in the ELF
// u16 cCorePointMsg::getActiveTimer() const;

// No out-of-line body: 1 inlined copy in 1 function (7 bytes)
//   in nNetMsg::cNetMsgCtrlAction::receiveMessageCore at 0x00386ba6-0x00386bad (called at cNetMsgCtrl.cpp:2086)
// void cCorePointMsg::setCreatedTime(t64 time);

// No out-of-line body: 3 inlined copies in 2 functions (12 bytes)
//   in cCorePointInfo::eraseMyMsgFromContext at 0x0017d062-0x0017d066 (called at cpCorePointCtrl.cpp:2215)
//   in cpCorePointCtrl::receiveCorePointMsg at 0x0017f482-0x0017f486 (called at cpCorePointCtrl.cpp:2215)
//   in cpCorePointCtrl::receiveCorePointMsg at 0x0017f594-0x0017f598 (called at cpCorePointCtrl.cpp:2215)
// t64 cCorePointMsg::getCreatedTime() const;

// No out-of-line body: 2 inlined copies in 2 functions (8 bytes)
//   in cContextInstChar::getUnSendedCorePointMsgNum at 0x00057439-0x0005743d (called at cContextInstance.cpp:627)
//   in cContextInstChar::getUnSendedTopCorePointMsg at 0x00057479-0x0005747d (called at cContextInstance.cpp:653)
// bool cCorePointMsg::isSended() const;

// No out-of-line body: 3 inlined copies in 2 functions (12 bytes)
//   in cpCorePointCtrl::receiveCorePointMsg at 0x0017f47e-0x0017f482 (called at cpCorePointCtrl.cpp:2146)
//   in cpCorePointCtrl::receiveCorePointMsg at 0x0017f590-0x0017f594 (called at cpCorePointCtrl.cpp:2146)
//   in nNetMsg::cNetMsgCtrlAction::sendMessage at 0x003838fd-0x00383901 (called at cNetMsgCtrl.cpp:2070)
// void cCorePointMsg::notifySended();

// No out-of-line body: 2 inlined copies in 1 function (12 bytes)
//   in cpCorePointCtrl::receiveCorePointMsg at 0x0017f4dc-0x0017f4e2 (called at cpCorePointCtrl.cpp:2155)
//   in cpCorePointCtrl::receiveCorePointMsg at 0x0017f5ee-0x0017f5f4 (called at cpCorePointCtrl.cpp:2155)
// void cCorePointMsg::requestErace();

// No out-of-line body: 1 inlined copy in 1 function (6 bytes)
//   in cpCorePointCtrl::receiveCorePointMsg at 0x0017f69c-0x0017f6a2 (called at cpCorePointCtrl.cpp:2129)
// bool cCorePointMsg::isEraceRequest() const;

// No out-of-line body: no code in the ELF
// void cCorePointMsg::setStandby(bool);

// No out-of-line body: no code in the ELF
// bool cCorePointMsg::isStandby() const;

// No out-of-line body: 2 inlined copies in 1 function (132 bytes)
//   in _GLOBAL__sub_I_cCorePointMsg.cpp at 0x0006f2f0-0x0006f332 (called at cCorePointMsg.cpp:13)
//   in _GLOBAL__sub_I_cCorePointMsg.cpp at 0x0006f2f0-0x0006f332 (called at cCorePointMsg.h:19)
// cCorePointMsg::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x0006f1c0 - 0x0006f21a (90 bytes)
MtObject* cCorePointMsg::MyDTI::newInstance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return new (static_cast<u32>(16)) ::cCorePointMsg;
}

