// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "cpEnemyThink.h"
#include "MtAllocator.h"
#include "MtCollection.h"
#include "MtDTI.h"
#include "MtMath.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#include "cThinkMgr.h"
#include "cUnit.h"
#include "cpActionManager.h"
#include "cpComponent.h"
#include "cpThinkBase.h"
#include "nDDOIO.h"
#include "rTbl2.h"
#include "uDDOModel.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* cRage::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cRage::usage();

// Address: 0x01a59a30 - 0x01a59a38 (8 bytes)
const MtDTI& cRage::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cRage::DTI;
}

// No out-of-line body: 7 inlined copies in 6 functions (100 bytes)
//   in cRage::MyDTI::newInstance at 0x00475914-0x00475926 (called at cpEnemyThink.cpp:85)
//   in cpEnemyThink::setResourceRage at 0x004781af-0x004781be (called at cpEnemyThink.cpp:85)
//   in rTbl2<cRage>::loadCore at 0x01a59540-0x01a5954c (called at cpEnemyThink.cpp:85)
//   and 4 more (every copy is in <bundle>.inlined.json)
// MtAllocator* cRage::getAllocator();

// No out-of-line body: no code in the ELF
// void cRage::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
// inferred: parameters written where their values stand in every inlined copy
inline void* cRage::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::cRage::DTI)->memAlloc(sz, align, ::cRage::DTI.::MtDTI::getID());
}

// No out-of-line body: 1 inlined copy in 1 function (45 bytes)
//   in rTbl2<cRage>::loadCore at 0x01a59583-0x01a595b0 (called at rTbl2.h:215)
// void* cRage::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cRage::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cRage::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline void cRage::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cRage::DTI)->memFree(p_addr);
}

// No out-of-line body: 3 inlined copies in 3 functions (72 bytes)
//   in rTbl2<cRage>::loadCore at 0x01a59540-0x01a59558 (called at rTbl2.h:224)
//   in _ZN5rTbl2I5cRageED1Ev at 0x01a59835-0x01a5984d (called at rTbl2.h:224)
//   in rTbl2<cRage>::~rTbl2 at 0x01a59895-0x01a598ad (called at rTbl2.h:224)
// void cRage::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cRage::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cRage::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 6 inlined copies in 3 functions (328 bytes)
//   in cRage::MyDTI::newInstance at 0x0047593d-0x0047596b (called at cpEnemyThink.cpp:85)
//   in cRage::MyDTI::newInstance at 0x0047593d-0x0047596b (called at cpEnemyThink.h:43)
//   in cpEnemyThink::setResourceRage at 0x00478176-0x00478185, 0x004781d9-0x00478202 (called at cpEnemyThink.cpp:1566)
//   and 3 more (every copy is in <bundle>.inlined.json)
// cRage::cRage();

// Defined in the class (its body was written in a header).
// cRage::~cRage();

// No out-of-line body: 1 inlined copy in 1 function (47 bytes)
//   in cpEnemyThink::setResourceRage at 0x00478202-0x00478231 (called at cpEnemyThink.cpp:1567)
// void cRage::copy(cRage* src);

// Address: 0x004759e0 - 0x00475b02 (290 bytes)
__attribute__((weak)) bool cRage::checkRageStatus(uDDOModel* pModel) {
    // local: cpHpDamageCtrl* pDamageCtrl;
    // local: cParentRegionStatus* pMainRegion;
    // local: f64 hpmax;
    // local: f64 rate;
    // local: float hpPer;
    DDON_STUB("cRage::checkRageStatus")
    return {};
}

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_cpEnemyThink.cpp at 0x0047846c-0x004784a9 (called at cpEnemyThink.cpp:85)
//   in _GLOBAL__sub_I_cpEnemyThink.cpp at 0x0047846c-0x004784a9 (called at cpEnemyThink.h:34)
// cRage::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00475910 - 0x00475970 (96 bytes)
MtObject* cRage::MyDTI::newInstance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return new (static_cast<u32>(16)) ::cRage;
}

// No out-of-line body: no code in the ELF
// MtDTI* cpEnemyThink::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cpEnemyThink::usage();

// Address: 0x01a597c0 - 0x01a597c8 (8 bytes)
const MtDTI& cpEnemyThink::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cpEnemyThink::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* cpEnemyThink::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::cpEnemyThink::DTI);
}

// No out-of-line body: no code in the ELF
// void cpEnemyThink::setAllocator(u32);

// Address: 0x00475860 - 0x004758a0 (64 bytes)
void* cpEnemyThink::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::cpEnemyThink::getAllocator()->memAlloc(sz, align, ::cpEnemyThink::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* cpEnemyThink::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cpEnemyThink::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cpEnemyThink::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void cpEnemyThink::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cpEnemyThink::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cpEnemyThink::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cpEnemyThink::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cpEnemyThink::operator delete[](void* p_addr, u32 align);

// Address: 0x00475c40 - 0x00475d77 (311 bytes)
cpEnemyThink::cpEnemyThink() {
    DDON_STUB("cpEnemyThink::cpEnemyThink")
    /* stub */
}

// Address: 0x01a59680 - 0x01a5970a (138 bytes)
// Also emitted as: _ZN12cpEnemyThinkD0Ev at 0x01a59710
cpEnemyThink::~cpEnemyThink() {
    DDON_STUB("cpEnemyThink::~cpEnemyThink")
    /* stub */
}

// Address: 0x00475d80 - 0x00475fcc (588 bytes)
__attribute__((weak)) void cpEnemyThink::setup() {
    // local: uDDOModel* pModel;
    DDON_STUB("cpEnemyThink::setup")
    /* stub */
}

// Address: 0x00475fd0 - 0x00475fe2 (18 bytes)
void cpEnemyThink::before() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mcThink.::cThinkMgrName::cThinkMgr::NextThinkTimer(this->mpModel->::cUnit::getDeltaTime());
}

// Address: 0x00475ff0 - 0x004760f4 (260 bytes)
u32 cpEnemyThink::callbackGetAction() {
    // DWARF local not rendered: bool isUpdate;
    // Approximate from the ELF: a statement both arms of a test start with; a test after the last call or store that only chooses the result; the body oracle reports this body.
    if (this->mIsThinkStop != false) {
        this->mIsThinkStop = false;
        return static_cast<u32>(4294967295);
    } else {
        if (this->mpModel != static_cast<uDDOModel*>(nullptr)) {
            if (this->mpModel->mGuardComponent.mpActMgr != static_cast<cpActionManager*>(nullptr)) {
                if (this->::cpComponent::mActive != false) {
                    if (this->mpModel->::uDDOModel::isDead() == false) {
                        // inferred: a temporary for the result of the call at 0x47604c, used once; no DWARF local holds it
                        u32 t0 = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::getActionNo();
                        if (((this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::getActionNo() >> static_cast<u32>(8)) & static_cast<u32>(32)) == static_cast<u32>(0)) {
                            if ((this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::getActionNo() & static_cast<u32>(12288)) == static_cast<u32>(12288)) {
                                if (this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::getActionNo() != static_cast<u32>(4294967295)) {
                                    if (this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction() != false) {
                                        if (this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction() == false) {
                                            if (this->mcThink.::cThinkMgrName::cThinkMgr::isActTrue() != false) {
                                                this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                            } else {
                                                this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                                if (t0 != static_cast<u32>(4294967295)) {
                                                    return static_cast<u32>(4294967295);
                                                }
                                            }
                                        } else {
                                            this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                        }
                                        return this->::cpEnemyThink::getActionNo();
                                    } else {
                                        return static_cast<u32>(4294967295);
                                    }
                                } else {
                                    if (this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction() == false) {
                                        if (this->mcThink.::cThinkMgrName::cThinkMgr::isActTrue() != false) {
                                            this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                        } else {
                                            this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                            if (t0 != static_cast<u32>(4294967295)) {
                                                return static_cast<u32>(4294967295);
                                            }
                                        }
                                    } else {
                                        this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                    }
                                    return this->::cpEnemyThink::getActionNo();
                                }
                            } else {
                                if (this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction() == false) {
                                    if (this->mcThink.::cThinkMgrName::cThinkMgr::isActTrue() != false) {
                                        this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                    } else {
                                        this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                        if (t0 != static_cast<u32>(4294967295)) {
                                            return static_cast<u32>(4294967295);
                                        }
                                    }
                                } else {
                                    this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                }
                                return this->::cpEnemyThink::getActionNo();
                            }
                        } else {
                            if (this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::getActionNo() != static_cast<u32>(4294967295)) {
                                if (this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction() != false) {
                                    if (this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction() == false) {
                                        if (this->mcThink.::cThinkMgrName::cThinkMgr::isActTrue() != false) {
                                            this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                        } else {
                                            this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                            if (t0 != static_cast<u32>(4294967295)) {
                                                return static_cast<u32>(4294967295);
                                            }
                                        }
                                    } else {
                                        this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                    }
                                    return this->::cpEnemyThink::getActionNo();
                                } else {
                                    return static_cast<u32>(4294967295);
                                }
                            } else {
                                if (this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction() == false) {
                                    if (this->mcThink.::cThinkMgrName::cThinkMgr::isActTrue() != false) {
                                        this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                    } else {
                                        this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                        if (t0 != static_cast<u32>(4294967295)) {
                                            return static_cast<u32>(4294967295);
                                        }
                                    }
                                } else {
                                    this->mcThink.mbActEndFlg = this->mpModel->::uDDOModel::getActMgrPtr()->::cpActionManager::isEndAction();
                                }
                                return this->::cpEnemyThink::getActionNo();
                            }
                        }
                    } else {
                        return static_cast<u32>(4294967295);
                    }
                } else {
                    return static_cast<u32>(4294967295);
                }
            } else {
                return static_cast<u32>(4294967295);
            }
        } else {
            return static_cast<u32>(4294967295);
        }
    }
}

// Address: 0x00477fc0 - 0x00478005 (69 bytes)
void cpEnemyThink::updatePtr() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::cpComponent::updatePtr();
    this->mcThink.mTargetMgr.::cThinkMgrName::cThinkMgrTargetMgr::updatePtr();
    if (this->mpFsmTarget == static_cast<uDDOModel*>(nullptr)) {
        return;
    }
    if (this->mpFsmTarget->::cUnit::isEnable() != false) {
        return;
    }
    this->mpFsmTarget = static_cast<uDDOModel*>(nullptr);
}

// Address: 0x00478010 - 0x00478107 (247 bytes)
__attribute__((weak)) void cpEnemyThink::applyWorldOffset(const MtVector3& offset, const MtVector3& absolute_offset) {
    DDON_STUB("cpEnemyThink::applyWorldOffset")
    /* stub */
}

// Address: 0x004762e0 - 0x00477fb4 (7380 bytes)
__attribute__((weak)) u32 cpEnemyThink::getActionNo() {
    // local: s32 actionNo;
    // local: cpActionManager* pActMgr;
    // local: u32 i;
    // local: cThinkMgrTargetData targetData;
    // local: bool bEnable;
    // local: uDDOModel* pTarget;
    // local: MtVector3 targetPos;
    // local: MtVector3 myPos;
    // local: bool is_use_sensor;
    // local: cpAISensor* p_sensor;
    // local: MtArray out_array;
    // local: cAISensorGetParam param;
    // local: MtTypedArray<uDDOModel> targets;
    // local: u32 num;
    // local: s32 selectLv;
    // local: bool selectEnable;
    // local: u32 selectIdx;
    // local: u32 j;
    // local: cpOcdCtrl* pOcdCtrl;
    // local: uDDOModel* pDDoModel;
    // local: uCharacter* pCharacter;
    // local: uDDOModel* pDDoModel;
    // local: uEnemy* pEnemy;
    // local: bool is_use_sensor;
    // local: cpAISensor* p_sensor;
    // local: MtArray out_array;
    // local: uDDOModel* pObjModel;
    // local: cThinkMgrTargetData targetData;
    // local: cAISensorGetParam param;
    // local: MtTypedArray<uDDOModel> targets;
    // local: u32 num;
    // local: u32 i;
    // local: u32 i;
    // local: u32 i;
    // local: uDDOModel* pObjModel;
    // local: uHuman* pHuman;
    // local: bool is_use_sensor;
    // local: cpAISensor* p_sensor;
    // local: MtArray out_array;
    // local: cAISensorGetParam param;
    // local: MtTypedArray<uDDOModel> targets;
    // local: u32 num;
    // local: HP_DATATYPE selectHpDec;
    // local: bool selectEnable;
    // local: u32 selectIdx;
    // local: u32 j;
    // local: uDDOModel* pDDoModel;
    // local: uEnemy* pEnemy;
    // local: HP_DATATYPE hp;
    // local: uDDOModel* pDDoModel;
    // local: uCharacter* pChar;
    // local: uEnemy* pEnemy;
    // local: bool is_use_sensor;
    // local: cpAISensor* p_sensor;
    // local: MtArray out_array;
    // local: uDDOModel* pObjModel;
    // local: cThinkMgrTargetData targetData;
    // local: cAISensorGetParam param;
    // local: MtTypedArray<uDDOModel> targets;
    // local: u32 num;
    // local: u32 i;
    // local: u32 i;
    // local: u32 i;
    // local: u32 i;
    DDON_STUB("cpEnemyThink::getActionNo")
    return {};
}

// No out-of-line body: no code in the ELF
// bool cpEnemyThink::getThinkStop();

// No out-of-line body: 2 inlined copies in 2 functions (19 bytes)
//   in cpFsmCtrl::move at 0x0047fc50-0x0047fc57 (called at cpFsmCtrl.cpp:360)
//   in cpNpc::move at 0x004d381b-0x004d3827 (called at cpNpc.cpp:67)
// void cpEnemyThink::setThinkStop(bool enable);

// Address: 0x00476220 - 0x0047629e (126 bytes)
__attribute__((weak)) bool cpEnemyThink::isChangeRage() {
    // local: bool isRage;
    // local: bool result;
    // local: u32 i;
    // local: bool rage;
    DDON_STUB("cpEnemyThink::isChangeRage")
    return {};
}

// No out-of-line body: no code in the ELF
// void cpEnemyThink::setEnemyThinkTargetLock(uDDOModel*, const MtVector3&);

// No out-of-line body: no code in the ELF
// bool cpEnemyThink::IsFsmTarget();

// No out-of-line body: 1 inlined copy in 1 function (7 bytes)
//   in cFSMUnit::stateExitSetNeck at 0x001f2aa7-0x001f2aae (called at cFSMUnit.cpp:890)
// void cpEnemyThink::setEnemyThinkTargetLockFlg(bool enable);

// No out-of-line body: 2 inlined copies in 2 functions (98 bytes)
//   in cpEnemyThink::setup at 0x00475f92-0x00475fc1 (called at cpEnemyThink.cpp:326)
//   in cpEnemyThink::getActionNo at 0x00476305-0x00476338 (called at cpEnemyThink.cpp:678)
// void cpEnemyThink::checkThinkMode();

// Address: 0x004762a0 - 0x004762dc (60 bytes)
__attribute__((weak)) uDDOModel* cpEnemyThink::getNewTarget() {
    // local: cThinkMgr* pThinkMgr;
    // local: cThinkMgrTargetData* pTargetData;
    // local: uDDOModel* pObjModel;
    DDON_STUB("cpEnemyThink::getNewTarget")
    return nullptr;
}

// No out-of-line body: 1 inlined copy in 1 function (53 bytes)
//   in cEnemyThinkName::cEnemyThink::actTraceJump at 0x000c2795-0x000c27ca (called at cEnemyThink.cpp:2771)
// MtVector3 cpEnemyThink::getTargetJumpPos();

// No out-of-line body: 1 inlined copy in 1 function (53 bytes)
//   in cEnemyThinkName::cEnemyThink::checkCommonScript at 0x000c01e7-0x000c021c (called at cEnemyThink.cpp:511)
// void cpEnemyThink::setTargetJumpPos(MtVector3& pos);

// No out-of-line body: no code in the ELF
// f32 cpEnemyThink::getTargetJumpDir();

// No out-of-line body: 1 inlined copy in 1 function (16 bytes)
//   in cEnemyThinkName::cEnemyThink::checkCommonScript at 0x000c0221-0x000c0231 (called at cEnemyThink.cpp:512)
// void cpEnemyThink::setTargetJumpDir(f32 dir);

// Address: 0x00476100 - 0x00476209 (265 bytes)
__attribute__((weak)) bool cpEnemyThink::setTargetThinkMgr(const kTHINKDATA& tbl, MtObject* pMtObj, cThinkMgrName::cThinkMgr* pThinkmgr, u32 targetDataIdx) {
    // local: uDDOModel* pTgt;
    // local: uCharacter* pCharacter;
    // local: cThinkMgrTargetData* pTargetData;
    DDON_STUB("cpEnemyThink::setTargetThinkMgr")
    return {};
}

// Address: 0x00478110 - 0x00478325 (533 bytes)
__attribute__((weak)) void cpEnemyThink::setResourceRage(rRageTable* pRes) {
    // local: u32 i;
    // local: cRage* pRage;
    // local: cRage* pCopyRage;
    DDON_STUB("cpEnemyThink::setResourceRage")
    /* stub */
}

// No out-of-line body: no code in the ELF
// const MtVector3& cpEnemyThink::getDamagePos() const;

// No out-of-line body: no code in the ELF
// void cpEnemyThink::setDamagePos(const MtVector3&);

// No out-of-line body: 1 inlined copy in 1 function (12 bytes)
//   in cEnemyThinkName::cEnemyThink::checkCommonScript at 0x000bf422-0x000bf42e (called at cEnemyThink.cpp:407)
// bool cpEnemyThink::isBigEnemy() const;

// No out-of-line body: 1 inlined copy in 1 function (4 bytes)
//   in uEnemy::setup at 0x008f29a5-0x008f29a9 (called at uEnemy.cpp:1195)
// void cpEnemyThink::setIsBigEnemy(const bool flg);

// No out-of-line body: 19 inlined copies in 18 functions (76 bytes)
//   in cEmActDamageBase::preInit at 0x000bde19-0x000bde1d (called at cEnemyAction.cpp:642)
//   in cEnemyThinkName::cEnemyThink::actTrace at 0x000c2613-0x000c2617 (called at cEnemyThink.cpp:2656)
//   in cpEnemyReact::checkReaction at 0x00182afb-0x00182aff (called at cpEnemyReact.cpp:630)
//   and 16 more (every copy is in <bundle>.inlined.json)
// cThinkMgrName::cThinkMgr* cpEnemyThink::getcThink();

// No out-of-line body: no code in the ELF
// void cpEnemyThink::calcSetTargetQuat(const MtVector3& tag, f32 speed);

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_cpEnemyThink.cpp at 0x0047842f-0x0047846c (called at cpEnemyThink.cpp:82)
//   in _GLOBAL__sub_I_cpEnemyThink.cpp at 0x0047842f-0x0047846c (called at cpEnemyThink.h:111)
// cpEnemyThink::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x004756f0 - 0x00475852 (354 bytes)
__attribute__((weak)) MtObject* cpEnemyThink::MyDTI::newInstance() const {
    DDON_STUB("cpEnemyThink::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* rRageTable::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void rRageTable::usage();

// Address: 0x01a593d0 - 0x01a593d8 (8 bytes)
const MtDTI& rRageTable::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return rRageTable::DTI;
}

// No out-of-line body: 1 inlined copy in 1 function (18 bytes)
//   in rRageTable::MyDTI::newInstance at 0x00475b64-0x00475b76 (called at cpEnemyThink.cpp:233)
// MtAllocator* rRageTable::getAllocator();

// No out-of-line body: no code in the ELF
// void rRageTable::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
// inferred: parameters written where their values stand in every inlined copy
inline void* rRageTable::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::rRageTable::DTI)->memAlloc(sz, align, ::rRageTable::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* rRageTable::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* rRageTable::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* rRageTable::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN10rRageTableD0Ev at 0x01a593a4-0x01a593c3, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void rRageTable::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::rRageTable::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void rRageTable::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void rRageTable::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void rRageTable::operator delete[](void* p_addr, u32 align);

// Address: 0x00475b10 - 0x00475b5a (74 bytes)
bool rRageTable::loadData(MtDataReader& in, cRage* pData) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    // inferred: reference argument from the copy's one access
    // inferred: argument from a callee-saved register at the copy's entry
    ::nDDOIO::readData(in, pData->mStatusStartHpPer);
    // inferred: reference argument from the copy's one access
    // inferred: argument from a callee-saved register at the copy's entry
    ::nDDOIO::readData(in, pData->mStatusEndHpPer);
    // inferred: reference argument from the copy's one access
    // inferred: argument from a callee-saved register at the copy's entry
    ::nDDOIO::readData(in, pData->mMindStatus);
    // inferred: reference argument from the copy's one access
    // inferred: argument from a callee-saved register at the copy's entry
    ::nDDOIO::readData(in, pData->mMindStatusFrameMax);
    return true;
}

// Address: 0x01a593e0 - 0x01a593e8 (8 bytes)
MT_CTSTR rRageTable::getExt() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return "rag";
}

// Address: 0x01a594f0 - 0x01a594f6 (6 bytes)
u32 rRageTable::getDataVersion() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return static_cast<u32>(257);
}

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_cpEnemyThink.cpp at 0x004784a9-0x004784e6 (called at cpEnemyThink.cpp:233)
//   in _GLOBAL__sub_I_cpEnemyThink.cpp at 0x004784a9-0x004784e6 (called at cpEnemyThink.h:103)
// rRageTable::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00475b60 - 0x00475bc4 (100 bytes)
MtObject* rRageTable::MyDTI::newInstance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return new (static_cast<u32>(16)) ::rRageTable;
}

// Instance at 0x01a597e0 - 0x01a597e5 (5 bytes) of the generic MtTypedArray<T>::~MtTypedArray
// Proven from the ELF: the body oracle checks this instance (022 D5).
template MtTypedArray<cRage>::~MtTypedArray();

// Instance at 0x01a594a0 - 0x01a594b6 (22 bytes) of the generic rTbl2<T>::getData
// Proven from the ELF: the body oracle checks this instance (022 D5).
template cRage* rTbl2<cRage>::getData(unsigned int);

// Instance at 0x01a593f0 - 0x01a59493 (163 bytes) of the generic rTbl2<T>::load
// Proven from the ELF: the body oracle checks this instance (022 D5).
template bool rTbl2<cRage>::load(MtStream&);

// Instance at 0x01a59500 - 0x01a59672 (370 bytes) of the generic rTbl2<T>::loadCore
// Approximate from the ELF: the family's one template definition, for an instance the renderer refused (constitution 2.4.0); its verdict is reported; the body oracle reports this instance.
template bool rTbl2<cRage>::loadCore(MtDataReader&);

// Instance at 0x01a594c0 - 0x01a594d6 (22 bytes) of the generic rTbl2<T>::getData
// Proven from the ELF: the body oracle checks this instance (022 D5).
template const cRage* rTbl2<cRage>::getData(unsigned int) const;

// Instance at 0x01a594e0 - 0x01a594e4 (4 bytes) of the generic rTbl2<T>::getDataNum
// Proven from the ELF: the body oracle checks this instance (022 D5).
template unsigned int rTbl2<cRage>::getDataNum() const;

// Instance at 0x01a59810 - 0x01a59868 (88 bytes) of the generic rTbl2<T>::~rTbl2
// Approximate from the ELF: its one inlined call written as a call of the method, whose approximate generic body its family's unit holds (024 P13, D4): the recompile calls what the ELF inlined; the body oracle reports this instance.
template rTbl2<cRage>::~rTbl2();

