// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "cPlayPointInfo.h"
#include "MtAllocator.h"
#include "MtCollection.h"
#include "MtDTI.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* cPlayPointInfo::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cPlayPointInfo::usage();

// Address: 0x0197baf0 - 0x0197baf8 (8 bytes)
const MtDTI& cPlayPointInfo::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cPlayPointInfo::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* cPlayPointInfo::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::cPlayPointInfo::DTI);
}

// No out-of-line body: no code in the ELF
// void cPlayPointInfo::setAllocator(u32);

// Address: 0x00156e70 - 0x00156eb0 (64 bytes)
void* cPlayPointInfo::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::cPlayPointInfo::getAllocator()->memAlloc(sz, align, ::cPlayPointInfo::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* cPlayPointInfo::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cPlayPointInfo::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cPlayPointInfo::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void cPlayPointInfo::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cPlayPointInfo::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cPlayPointInfo::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cPlayPointInfo::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cPlayPointInfo::operator delete[](void* p_addr, u32 align);

// Address: 0x00156fe0 - 0x001570e3 (259 bytes)
cPlayPointInfo::cPlayPointInfo() {
    DDON_STUB("cPlayPointInfo::cPlayPointInfo")
    /* stub */
}

// Address: 0x001570f0 - 0x0015718d (157 bytes)
// Also emitted as: _ZN14cPlayPointInfoD0Ev at 0x00157190
cPlayPointInfo::~cPlayPointInfo() {
    DDON_STUB("cPlayPointInfo::~cPlayPointInfo")
    /* stub */
}

// Address: 0x00157250 - 0x00157293 (67 bytes)
__attribute__((weak)) cPlayPointInfo::cPlayPoint* cPlayPointInfo::getPlayPoint(u8 jobId) {
    // local: u8 i;
    DDON_STUB("cPlayPointInfo::getPlayPoint")
    return nullptr;
}

// Address: 0x001572a0 - 0x00157309 (105 bytes)
__attribute__((weak)) cPlayPointInfo::cPlayPoint* cPlayPointInfo::getMyPlayPoint() {
    // local: const cContextInstHm* pContext;
    DDON_STUB("cPlayPointInfo::getMyPlayPoint")
    return nullptr;
}

// Address: 0x00157310 - 0x00157315 (5 bytes)
MtTypedArray<cPlayPointInfo::cPlayPoint>& cPlayPointInfo::getPlayPointList() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mJobPlayPointList;
}

// Address: 0x00157320 - 0x00157482 (354 bytes)
__attribute__((weak)) void cPlayPointInfo::addPlayPoint(u8 jobId, u8 mode, u32 playpoint) {
    // local: cPlayPoint* pPP;
    DDON_STUB("cPlayPointInfo::addPlayPoint")
    /* stub */
}

// No out-of-line body: no code in the ELF
// void cPlayPointInfo::updatePlayPoint(u8 jobId, u8 mode, u32 playpoint);

// Address: 0x001574a0 - 0x001574e8 (72 bytes)
__attribute__((weak)) void cPlayPointInfo::updatePlayPointMode(u8 jobId, u8 mode) {
    // local: cPlayPoint* pPP;
    DDON_STUB("cPlayPointInfo::updatePlayPointMode")
    /* stub */
}

// Address: 0x001574f0 - 0x00157538 (72 bytes)
__attribute__((weak)) void cPlayPointInfo::updaptePlayPointValue(u8 jobId, u32 playpoint) {
    // local: cPlayPoint* pPP;
    DDON_STUB("cPlayPointInfo::updaptePlayPointValue")
    /* stub */
}

// No out-of-line body: 1 inlined copy in 1 function (3 bytes)
//   in aMenu::move at 0x00004a2a-0x00004a2d (called at aMenu.cpp:1028)
// void cPlayPointInfo::setPlayPointLimit(u32 limit);

// No out-of-line body: 1 inlined copy in 1 function (3 bytes)
//   in uGUIGaugeExp::updatePp at 0x00a9827e-0x00a98281 (called at uGUIGaugeExp.cpp:560)
// u32 cPlayPointInfo::getPlayPointLimit();

// No out-of-line body: 1 inlined copy in 1 function (3 bytes)
//   in aMenu::move at 0x00004a21-0x00004a24 (called at aMenu.cpp:1027)
// void cPlayPointInfo::setPlayPointJobLevel(u32 jobLevel);

// No out-of-line body: 1 inlined copy in 1 function (3 bytes)
//   in uGUIPPShop::initPPShop at 0x00bd9e23-0x00bd9e26 (called at uGUIPPShop.cpp:752)
// u32 cPlayPointInfo::getPlayPointJobLevel();

// No out-of-line body: 2 inlined copies in 1 function (128 bytes)
//   in _GLOBAL__sub_I_cPlayPointInfo.cpp at 0x0015763e-0x0015767e (called at cPlayPointInfo.cpp:23)
//   in _GLOBAL__sub_I_cPlayPointInfo.cpp at 0x0015763e-0x0015767e (called at cPlayPointInfo.h:40)
// cPlayPointInfo::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00156d40 - 0x00156e6c (300 bytes)
__attribute__((weak)) MtObject* cPlayPointInfo::MyDTI::newInstance() const {
    DDON_STUB("cPlayPointInfo::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* cPlayPointInfo::cPlayPoint::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cPlayPointInfo::cPlayPoint::usage();

// Address: 0x0197bb60 - 0x0197bb68 (8 bytes)
const MtDTI& cPlayPointInfo::cPlayPoint::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cPlayPointInfo::cPlayPoint::DTI;
}

// No out-of-line body: 2 inlined copies in 2 functions (33 bytes)
//   in cPlayPointInfo::cPlayPoint::MyDTI::newInstance at 0x00156f24-0x00156f36 (called at cPlayPointInfo.cpp:24)
//   in cPlayPointInfo::addPlayPoint at 0x00157392-0x001573a1 (called at cPlayPointInfo.cpp:24)
// MtAllocator* cPlayPointInfo::cPlayPoint::getAllocator();

// No out-of-line body: no code in the ELF
// void cPlayPointInfo::cPlayPoint::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
// inferred: parameters written where their values stand in every inlined copy; constant parameters of one value written in their declaration order where it stands, once each (2.7.0; rCharacterEdit's proven operator new reads memAlloc(sz, align, …))
inline void* cPlayPointInfo::cPlayPoint::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::cPlayPointInfo::cPlayPoint::DTI)->memAlloc(sz, align, ::cPlayPointInfo::cPlayPoint::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* cPlayPointInfo::cPlayPoint::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cPlayPointInfo::cPlayPoint::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cPlayPointInfo::cPlayPoint::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN14cPlayPointInfo10cPlayPointD0Ev at 0x0197bb30-0x0197bb5a, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void cPlayPointInfo::cPlayPoint::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cPlayPointInfo::cPlayPoint::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cPlayPointInfo::cPlayPoint::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cPlayPointInfo::cPlayPoint::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cPlayPointInfo::cPlayPoint::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 2 inlined copies in 1 function (58 bytes)
//   in cPlayPointInfo::addPlayPoint at 0x001573bb-0x001573d8 (called at cPlayPointInfo.cpp:132)
//   in cPlayPointInfo::addPlayPoint at 0x001573bb-0x001573d8 (called at cPlayPointInfo.h:55)
// cPlayPointInfo::cPlayPoint::cPlayPoint(u8 jobId, u8 expMode, u32 playpoint);

// No out-of-line body: 2 inlined copies in 1 function (58 bytes)
//   in cPlayPointInfo::cPlayPoint::MyDTI::newInstance at 0x00156f4d-0x00156f6a (called at cPlayPointInfo.cpp:24)
//   in cPlayPointInfo::cPlayPoint::MyDTI::newInstance at 0x00156f4d-0x00156f6a (called at cPlayPointInfo.h:61)
// cPlayPointInfo::cPlayPoint::cPlayPoint();

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in _GLOBAL__sub_I_cPlayPointInfo.cpp at 0x0015767e-0x001576b7 (called at cPlayPointInfo.cpp:24)
//   in _GLOBAL__sub_I_cPlayPointInfo.cpp at 0x0015767e-0x001576b7 (called at cPlayPointInfo.h:49)
// cPlayPointInfo::cPlayPoint::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00156f20 - 0x00156f6f (79 bytes)
MtObject* cPlayPointInfo::cPlayPoint::MyDTI::newInstance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return new (static_cast<u32>(16)) ::cPlayPointInfo::cPlayPoint;
}

// Instance at 0x0197bac0 - 0x0197bac5 (5 bytes) of the generic MtTypedArray<T>::~MtTypedArray
// Proven from the ELF: the body oracle checks this instance (022 D5).
template MtTypedArray<cPlayPointInfo::cPlayPoint>::~MtTypedArray();

