// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "cPrimTexHandle.h"
#include "MtAllocator.h"
#include "MtDTI.h"
#include "MtMemoryAllocator.h"
#include "cPrimObj.h"
#include "sPrimitive.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* cPrimTexHandle::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cPrimTexHandle::usage();

// Address: 0x01b6cdb0 - 0x01b6cdb8 (8 bytes)
const MtDTI& cPrimTexHandle::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cPrimTexHandle::DTI;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtAllocator* cPrimTexHandle::getAllocator();

// No out-of-line body: no code in the ELF
// void cPrimTexHandle::setAllocator(u32);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void* cPrimTexHandle::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cPrimTexHandle::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cPrimTexHandle::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cPrimTexHandle::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline void cPrimTexHandle::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cPrimTexHandle::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cPrimTexHandle::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cPrimTexHandle::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cPrimTexHandle::operator delete[](void* p_addr, u32 align);

// Address: 0x01060e20 - 0x01060e46 (38 bytes)
cPrimTexHandle::cPrimTexHandle() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mCurrentIdx = static_cast<u32>(0);
    this->mTextureNum = static_cast<u32>(0);
    this->mTextureSize = static_cast<u32>(0);
    this->mpTexture = static_cast<nPrim::Texture*>(nullptr);
}

// Address: 0x01060e50 - 0x01060e51 (1 bytes)
// Also emitted as: _ZN14cPrimTexHandleD0Ev at 0x01060e60
cPrimTexHandle::~cPrimTexHandle() {
    // Empty in the binary (a single `ret`).
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// u32 cPrimTexHandle::searchForTexHandle(const nPrim::Texture& tex);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// u32 cPrimTexHandle::addTexHandle(const nPrim::Texture& tex);

// Address: 0x01b5d100 - 0x01b5d211 (273 bytes)
__attribute__((weak)) u32 cPrimTexHandle::registerTexHandle(const nPrim::Texture& tex) {
    // local: s32 ret;
    DDON_STUB("cPrimTexHandle::registerTexHandle")
    return {};
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cPrimTexHandle::clear();

// No out-of-line body: no code in the ELF
// nPrim::Texture* cPrimTexHandle::getTexture(u32) const;

// Address: 0x01060e90 - 0x01060ec6 (54 bytes)
void cPrimTexHandle::reserveTexture() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mTextureSize = (::sPrimitive::mpInstance)->::sPrimitive::reserveTex(&this->mpTexture, &this->mCurrentIdx, static_cast<u32>(64));
    this->mTextureNum = static_cast<u32>(0);
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// cPrimTexHandle::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x01060d50 - 0x01060da7 (87 bytes)
__attribute__((weak)) MtObject* cPrimTexHandle::MyDTI::newInstance() const {
    DDON_STUB("cPrimTexHandle::MyDTI::newInstance")
    return nullptr;
}

