// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "cPrimTagList.h"
#include "MtAllocator.h"
#include "MtDTI.h"
#include "MtMemoryAllocator.h"
#include "cPrimObj.h"
#include "nPrim.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* cPrimTagList::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cPrimTagList::usage();

// Address: 0x01bc7b90 - 0x01bc7b98 (8 bytes)
const MtDTI& cPrimTagList::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cPrimTagList::DTI;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtAllocator* cPrimTagList::getAllocator();

// No out-of-line body: no code in the ELF
// void cPrimTagList::setAllocator(u32);

// Address: 0x0132ba20 - 0x0132ba60 (64 bytes)
void* cPrimTagList::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::MtMemoryAllocator::getAllocator(::cPrimTagList::DTI)->memAlloc(sz, align, ::cPrimTagList::DTI.::MtDTI::mID);
}

// No out-of-line body: no code in the ELF
// void* cPrimTagList::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cPrimTagList::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cPrimTagList::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline void cPrimTagList::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cPrimTagList::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cPrimTagList::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cPrimTagList::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cPrimTagList::operator delete[](void* p_addr, u32 align);

// Address: 0x0132bad0 - 0x0132bb2b (91 bytes)
cPrimTagList::cPrimTagList() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mCurrentStack = static_cast<u32>(0);
    this->mTagSize = static_cast<u32>(0);
    this->mCurrentTagSize = static_cast<u32>(0);
    this->mpCurrentIdxPtr = static_cast<cPrimTagList::IndexTag*>(nullptr);
    this->mpCurrentTagPtr = static_cast<cPrimTagList::PrimTag*>(nullptr);
    this->mpWork = static_cast<void*>(nullptr);
    this->mpSorted = static_cast<cPrimTagList::IndexTag*>(nullptr);
    this->mpTags = static_cast<cPrimTagList::PrimTag*>(nullptr);
}

// Address: 0x0132bb30 - 0x0132bb31 (1 bytes)
// Also emitted as: _ZN12cPrimTagListD0Ev at 0x0132bb40
cPrimTagList::~cPrimTagList() {
    // Empty in the binary (a single `ret`).
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// s32 cPrimTagList::addTag(const cPrimTagList::PrimTag& tag);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// s32 cPrimTagList::addTag(const cPrimTagList::PrimTag* tags, u32 n_tag);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// u32 cPrimTagList::getNumOfTags() const;

// No out-of-line body: no code in the ELF
// bool cPrimTagList::isSorted() const;

// No out-of-line body: no code in the ELF
// cPrimTagList::PrimTag* cPrimTagList::getTags(u32) const;

// No out-of-line body: no code in the ELF
// cPrimTagList::IndexTag* cPrimTagList::getSortedTags(u32) const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// cPrimTagList::IndexTag* cPrimTagList::getIndexTags(u32 tag_no) const;

// No out-of-line body: no code in the ELF
// cPrimTagList::IndexTag* cPrimTagList::getSortedTags() const;

// Address: 0x0132bbc0 - 0x0132bbc3 (3 bytes)
MtUI* cPrimTagList::createUI(MtProperty& prop) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return nullptr;
}

// Address: 0x0132bbd0 - 0x0132bcb6 (230 bytes)
__attribute__((weak)) void cPrimTagList::createProperty(MtPropertyList& prop_list) {
    DDON_STUB("cPrimTagList::createProperty")
    /* stub */
}

// No out-of-line body: no code in the ELF
// void cPrimTagList::sortTags(u32);

// No out-of-line body: no code in the ELF
// void cPrimTagList::setWorkBuffer(void*);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// u32 cPrimTagList::getRequiredWorkBuffer() const;

// Address: 0x0132bce0 - 0x0132bd23 (67 bytes)
s32 cPrimTagList::push() {
    // local: ObjState* p_stack;
    // Approximate from the ELF: a place read twice with no call between; the body oracle reports this body.
    // inferred: a temporary for the value the load at 0x132bce0 read, used 5 times; no DWARF local holds it
    u32 t0 = this->mCurrentStack;
    if (t0 <= static_cast<u32>(5)) {
        this->mStack[t0].tag_ptr = this->mpCurrentTagPtr;
        this->mStack[t0].index_ptr = this->mpCurrentIdxPtr;
        this->mStack[t0].tag_num = static_cast<u32>(0);
        this->mStack[t0].sorted = false;
        this->mCurrentStack = this->mCurrentStack + static_cast<u32>(1);
        return static_cast<s32>(0);
    } else {
        return static_cast<s32>(9);
    }
}

// Address: 0x0132bd30 - 0x0132bd70 (64 bytes)
s32 cPrimTagList::pop() {
    // local: ObjState* p_stack;
    // Approximate from the ELF: adjacent members copied one by one; the body oracle reports this body.
    // inferred: a temporary for the value the load at 0x132bd30 read, used 5 times; no DWARF local holds it
    u32 t0 = this->mCurrentStack;
    if (t0 != static_cast<u32>(0)) {
        this->mCurrentStack = t0 - static_cast<u32>(1);
        this->mpCurrentTagPtr = this->mStack[t0 - static_cast<u32>(1)].tag_ptr;
        this->mpCurrentIdxPtr = this->mStack[t0 - static_cast<u32>(1)].index_ptr;
        this->mCurrentTagSize = this->mCurrentTagSize - this->mStack[t0 - static_cast<u32>(1)].tag_num;
        return static_cast<s32>(0);
    } else {
        return static_cast<s32>(10);
    }
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cPrimTagList::assignTags(u32 n_tags, cPrimTagList::PrimTag* p_tag, cPrimTagList::IndexTag* p_itag);

// No out-of-line body: no code in the ELF
// void cPrimTagList::sort(s32 first, s32 last);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// cPrimTagList::ObjState* cPrimTagList::getCurrentState();

// Address: 0x0132bb70 - 0x0132bbb4 (68 bytes)
void cPrimTagList::clearTag() {
    // local: ObjState* p_stack;
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mCurrentTagSize = static_cast<u32>(0);
    this->mpCurrentTagPtr = this->mpTags;
    this->mpCurrentIdxPtr = this->mpSorted;
    this->mStack[0].tag_ptr = this->mpCurrentTagPtr;
    this->mStack[0].index_ptr = this->mpCurrentIdxPtr;
    this->mStack[0].tag_num = static_cast<u32>(0);
    this->mStack[0].sorted = false;
    this->mCurrentStack = static_cast<u32>(1);
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// cPrimTagList::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x0132b990 - 0x0132ba1c (140 bytes)
__attribute__((weak)) MtObject* cPrimTagList::MyDTI::newInstance() const {
    DDON_STUB("cPrimTagList::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// cPrimTagList::PrimTag::PrimTag();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// cPrimTagList::PrimTag::PrimTag(const nPrim::Material& mat, const nPrim::DepthOrder& dp, cPrimBuffer* pp, void* pm, void* va, void* ia, u32 v_cnt, u32 i_cnt);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// cPrimTagList::PrimTag& cPrimTagList::PrimTag::operator=(const cPrimTagList::PrimTag& tag);

// No out-of-line body: no code in the ELF
// cPrimTagList::IndexTag::IndexTag();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// cPrimTagList::IndexTag& cPrimTagList::IndexTag::operator=(const cPrimTagList::IndexTag& tag);

