// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "cResPath.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: 59 inlined copies in 35 functions (681 bytes)
//   in cOmComponent::initMotionSe at 0x003ab4c7-0x003ab4d5 (called at cOmControl.cpp:760)
//   in cOmComponent::initMotionSe at 0x003ab4f9-0x003ab507 (called at cOmControl.cpp:767)
//   in cOmControl::initSbc at 0x003ab9d8-0x003ab9e0, 0x003aba44-0x003aba4c, 0x003aba99-0x003abaa1, 0x003abafe-0x003abb06 (called at cOmControl.cpp:938)
//   and 56 more (every copy is in <bundle>.inlined.json)
// u64 cResPathBase::getResId() const;

// No out-of-line body: no code in the ELF
// bool cResPathBase::isNone() const;

// No out-of-line body: no code in the ELF
// void cResPathEx::setResDti(const MtDTI*);

