// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "cSoundLimitter.h"
#include "MtSynchronize.h"
#include "cSoundEffect.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// Address: 0x012eb330 - 0x012eb40b (219 bytes)
cSoundLimitter::cSoundLimitter() {
    DDON_STUB("cSoundLimitter::cSoundLimitter")
    /* stub */
}

// Address: 0x012eb420 - 0x012eb457 (55 bytes)
// Also emitted as: _ZN14cSoundLimitterD0Ev at 0x012eb460
cSoundLimitter::~cSoundLimitter() {
    DDON_STUB("cSoundLimitter::~cSoundLimitter")
    /* stub */
}

// Address: 0x012eb4a0 - 0x012eb613 (371 bytes)
__attribute__((weak)) void cSoundLimitter::execute(f32* pBuffer, const u32 sampleNum, const u32 channelNum) {
    // local: const SoundVector v_outceiling;
    // local: SoundVector* pv_buffer;
    // local: MtAutoCriticalSection acs;
    // local: u32 i;
    DDON_STUB("cSoundLimitter::execute")
    /* stub */
}

// No out-of-line body: no code in the ELF
// bool cSoundLimitter::getEnable();

// Address: 0x012eb630 - 0x012eb6e8 (184 bytes)
__attribute__((weak)) void cSoundLimitter::setEnable(const bool enable) {
    DDON_STUB("cSoundLimitter::setEnable")
    /* stub */
}

// No out-of-line body: no code in the ELF
// f32 cSoundLimitter::getThreshold();

// Address: 0x012eb700 - 0x012eb7cf (207 bytes)
__attribute__((weak)) void cSoundLimitter::setThreshold(const f32 threshold) {
    DDON_STUB("cSoundLimitter::setThreshold")
    /* stub */
}

// No out-of-line body: no code in the ELF
// f32 cSoundLimitter::getOutCeiling();

// Address: 0x012eb7e0 - 0x012eb8af (207 bytes)
__attribute__((weak)) void cSoundLimitter::setOutCeiling(const f32 outCeiling) {
    DDON_STUB("cSoundLimitter::setOutCeiling")
    /* stub */
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cSoundLimitter::updateParam();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// f32 cSoundLimitter::clamp(const f32 val, const f32 min, const f32 max);

