// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "cStateMachineBase.h"
#include "MtAllocator.h"
#include "MtCollection.h"
#include "MtDTI.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#include "cRemoteProcedure.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// Address: 0x01379300 - 0x013793ec (236 bytes)
cStateMachineBase::cStateMachineBase() {
    DDON_STUB("cStateMachineBase::cStateMachineBase")
    /* stub */
}

// Address: 0x01bdbb20 - 0x01bdbbf1 (209 bytes)
// Also emitted as: _ZN17cStateMachineBaseD0Ev at 0x01bdbc00
cStateMachineBase::~cStateMachineBase() {
    DDON_STUB("cStateMachineBase::~cStateMachineBase")
    /* stub */
}

// Address: 0x013793f0 - 0x0137942d (61 bytes)
__attribute__((weak)) void cStateMachineBase::registerStateFactory(cStateMachineBase::StateKey key, cStateMachineBase::StateBase* state) {
    DDON_STUB("cStateMachineBase::registerStateFactory")
    /* stub */
}

// No out-of-line body: no code in the ELF
// void cStateMachineBase::clearStateFactories();

// Address: 0x01379430 - 0x01379546 (278 bytes)
__attribute__((weak)) void cStateMachineBase::updateParallel() {
    // local: u32 i;
    // local: StateBase* pState;
    DDON_STUB("cStateMachineBase::updateParallel")
    /* stub */
}

// No out-of-line body: no code in the ELF
// void cStateMachineBase::updateSerial();

// No out-of-line body: no code in the ELF
// bool cStateMachineBase::isEnd();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// bool cStateMachineBase::isEmptyStack() const;

// No out-of-line body: no code in the ELF
// s32 cStateMachineBase::getStackNumber();

// No out-of-line body: no code in the ELF
// cStateMachineBase::StateBase* cStateMachineBase::addNextState(cStateMachineBase::StateKey key);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// cStateMachineBase::StateBase* cStateMachineBase::addNextState(cStateMachineBase::StateBase* state);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// cStateMachineBase::StateBase* cStateMachineBase::getCurrentState();

// No out-of-line body: no code in the ELF
// s32 cStateMachineBase::getCurrentStateId();

// Address: 0x01379580 - 0x01379626 (166 bytes)
__attribute__((weak)) cStateMachineBase::StateBase* cStateMachineBase::changeState(cStateMachineBase::StateKey key, f32 easeTime) {
    // local: StateBase* pState;
    DDON_STUB("cStateMachineBase::changeState")
    return nullptr;
}

// Address: 0x01379640 - 0x01379c8d (1613 bytes)
__attribute__((weak)) cStateMachineBase::StateBase* cStateMachineBase::changeState(cStateMachineBase::StateBase* state, f32 easeTime) {
    // local: bool IsChange;
    // local: StateBase* pPrevState;
    // local: MtArray tmparray;
    // local: MtArray tmparray;
    DDON_STUB("cStateMachineBase::changeState")
    return nullptr;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// cStateMachineBase::StateBase* cStateMachineBase::pushState(cStateMachineBase::StateKey key, f32 easeTime);

// No out-of-line body: no code in the ELF
// cStateMachineBase::StateBase* cStateMachineBase::pushState(cStateMachineBase::StateBase* state, f32 easeTime);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::popState(f32 easeTime);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::popState(cStateMachineBase::StateKey key, f32 easeTime);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::popState(cStateMachineBase::StateBase* state, f32 easeTime);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::popStateAll();

// No out-of-line body: no code in the ELF
// void cStateMachineBase::popStateAllExceptCurrent();

// Address: 0x01379da0 - 0x01379e58 (184 bytes)
__attribute__((weak)) bool cStateMachineBase::processRemoteCallInStateMachine(cRemoteCall& message, bool isParallel) {
    // local: u32 i;
    // local: StateBase* pState;
    DDON_STUB("cStateMachineBase::processRemoteCallInStateMachine")
    return {};
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// cStateMachineBase::StateBase* cStateMachineBase::makeStateFromKey(cStateMachineBase::StateKey key);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::clearTrash();

// No out-of-line body: no code in the ELF
// void* cStateMachineBase::getContextBase();

// Address: 0x01379e70 - 0x01379e78 (8 bytes)
void cStateMachineBase::initializeStateMachineBase(void* context) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mpContext = context;
}

// Address: 0x01379e80 - 0x01379f81 (257 bytes)
__attribute__((weak)) void cStateMachineBase::clearStateFactory() {
    // local: u32 i;
    // local: StateBase* pState;
    DDON_STUB("cStateMachineBase::clearStateFactory")
    /* stub */
}

// No out-of-line body: no code in the ELF
// void cStateMachineBase::popState(MtArray* pArray, cStateMachineBase::StateBase* state, f32 easeTime);

// Address: 0x013791e0 - 0x013791e3 (3 bytes)
bool cStateMachineBase::StateBase::processRemoteCallBoth(cRemoteCall& call, s32 member_id) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return false;
}

// Address: 0x013791f0 - 0x013791f3 (3 bytes)
bool cStateMachineBase::StateBase::processRemoteCall(cRemoteCall& call, bool isParallel, s32 member_id) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return false;
}

// No out-of-line body: no code in the ELF
// IStateMachineRpcReceiver* cStateMachineBase::StateBase::getRpcReceiveStateMachine();

// No out-of-line body: no code in the ELF
// bool cStateMachineBase::StateBase::IsKilledMessageActor();

// Address: 0x01379220 - 0x01379223 (3 bytes)
bool cStateMachineBase::StateBase::processRemoteCallDefault(cRemoteCall& call, bool isParallel, s32 member_id) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return false;
}

// No out-of-line body: no code in the ELF
// MtDTI* cStateMachineBase::StateBase::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cStateMachineBase::StateBase::usage();

// Address: 0x01bdbcd0 - 0x01bdbcd8 (8 bytes)
const MtDTI& cStateMachineBase::StateBase::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cStateMachineBase::StateBase::DTI;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtAllocator* cStateMachineBase::StateBase::getAllocator();

// No out-of-line body: no code in the ELF
// void cStateMachineBase::StateBase::setAllocator(u32);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void* cStateMachineBase::StateBase::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cStateMachineBase::StateBase::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cStateMachineBase::StateBase::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cStateMachineBase::StateBase::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline void cStateMachineBase::StateBase::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cStateMachineBase::StateBase::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cStateMachineBase::StateBase::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cStateMachineBase::StateBase::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cStateMachineBase::StateBase::operator delete[](void* p_addr, u32 align);

// Address: 0x0137a000 - 0x0137a02a (42 bytes)
cStateMachineBase::StateBase::StateBase() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mIsEnd = false;
    this->mFrameIndex = static_cast<u32>(0);
    this->mpStateMachine = static_cast<cStateMachineBase*>(nullptr);
    this->mpContext = static_cast<void*>(nullptr);
}

// Address: 0x0137a1d0 - 0x0137a1d1 (1 bytes)
// Also emitted as: _ZN17cStateMachineBase9StateBaseD0Ev at 0x0137a1e0
cStateMachineBase::StateBase::~StateBase() {
    // Empty in the binary (a single `ret`).
}

// Address: 0x0137a210 - 0x0137a211 (1 bytes)
__attribute__((weak)) void cStateMachineBase::StateBase::move() {
    // Empty in the binary (a single `ret`).
}

// Address: 0x0137a220 - 0x0137a221 (1 bytes)
__attribute__((weak)) void cStateMachineBase::StateBase::sync() {
    // Empty in the binary (a single `ret`).
}

// Address: 0x0137a230 - 0x0137a233 (3 bytes)
bool cStateMachineBase::StateBase::onEnter() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return false;
}

// Address: 0x0137a240 - 0x0137a241 (1 bytes)
__attribute__((weak)) void cStateMachineBase::StateBase::onLeave() {
    // Empty in the binary (a single `ret`).
}

// Address: 0x0137a250 - 0x0137a251 (1 bytes)
__attribute__((weak)) void cStateMachineBase::StateBase::onSuspend() {
    // Empty in the binary (a single `ret`).
}

// Address: 0x0137a260 - 0x0137a261 (1 bytes)
__attribute__((weak)) void cStateMachineBase::StateBase::onResume() {
    // Empty in the binary (a single `ret`).
}

// No out-of-line body: no code in the ELF
// void cStateMachineBase::StateBase::next();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::StateBase::end();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// bool cStateMachineBase::StateBase::isEnd();

// Address: 0x0137a060 - 0x0137a106 (166 bytes)
__attribute__((weak)) cStateMachineBase::StateBase* cStateMachineBase::StateBase::change(cStateMachineBase::StateKey key, f32 easeTime) {
    DDON_STUB("cStateMachineBase::StateBase::change")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// cStateMachineBase::StateBase* cStateMachineBase::StateBase::change(cStateMachineBase::StateBase* state, f32 easeTime);

// No out-of-line body: no code in the ELF
// cStateMachineBase::StateBase* cStateMachineBase::StateBase::push(cStateMachineBase::StateKey key, f32 easeTime);

// No out-of-line body: no code in the ELF
// cStateMachineBase::StateBase* cStateMachineBase::StateBase::push(cStateMachineBase::StateBase* state, f32 easeTime);

// No out-of-line body: no code in the ELF
// void cStateMachineBase::StateBase::pop(f32 easeTime);

// No out-of-line body: no code in the ELF
// void cStateMachineBase::StateBase::pop(cStateMachineBase::StateKey key, f32 easeTime);

// No out-of-line body: no code in the ELF
// void cStateMachineBase::StateBase::pop(cStateMachineBase::StateBase* state, f32 easeTime);

// No out-of-line body: no code in the ELF
// void cStateMachineBase::StateBase::popAll();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::StateBase::setId(s32 id);

// Address: 0x0137a180 - 0x0137a184 (4 bytes)
s32 cStateMachineBase::StateBase::getId() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mId;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::StateBase::setNext(cStateMachineBase::StateBase* state);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::StateBase::setPrev(cStateMachineBase::StateBase* state);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::StateBase::resetNext();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::StateBase::resetPrev();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::StateBase::setTime(f32 time);

// No out-of-line body: no code in the ELF
// f32 cStateMachineBase::StateBase::getTime() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::StateBase::setContextBase(void* context);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::StateBase::setStateMachine(cStateMachineBase* stateMachine);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void cStateMachineBase::StateBase::reset();

// No out-of-line body: no code in the ELF
// f32 cStateMachineBase::StateBase::getRate() const;

// No out-of-line body: no code in the ELF
// void cStateMachineBase::StateBase::setRate(f32 rate);

// Address: 0x0137a1b0 - 0x0137a1b5 (5 bytes)
void* cStateMachineBase::StateBase::getContextBase() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mpContext;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// cStateMachineBase* cStateMachineBase::StateBase::getStateMachine() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// cStateMachineBase::StateBase::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x01379230 - 0x0137928b (91 bytes)
__attribute__((weak)) MtObject* cStateMachineBase::StateBase::MyDTI::newInstance() const {
    DDON_STUB("cStateMachineBase::StateBase::MyDTI::newInstance")
    return nullptr;
}

