// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "cUnitDieInfo.h"
#include "MtAllocator.h"
#include "MtDTI.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* cUnitDieInfo::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cUnitDieInfo::usage();

// Address: 0x01a659a0 - 0x01a659a8 (8 bytes)
const MtDTI& cUnitDieInfo::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cUnitDieInfo::DTI;
}

// No out-of-line body: 2 inlined copies in 2 functions (30 bytes)
//   in cUnitDieInfo::MyDTI::newInstance at 0x0058e794-0x0058e7a6 (called at cUnitDieInfo.cpp:20)
//   in cUnitDieInfo::~cUnitDieInfo at 0x01a65979-0x01a65985 (called at cUnitDieInfo.cpp:20)
// MtAllocator* cUnitDieInfo::getAllocator();

// No out-of-line body: no code in the ELF
// void cUnitDieInfo::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
// inferred: parameters written where their values stand in every inlined copy; constant parameters of one value written in their declaration order where it stands, once each (2.7.0; rCharacterEdit's proven operator new reads memAlloc(sz, align, …))
inline void* cUnitDieInfo::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::cUnitDieInfo::DTI)->memAlloc(sz, align, ::cUnitDieInfo::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* cUnitDieInfo::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cUnitDieInfo::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cUnitDieInfo::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline void cUnitDieInfo::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cUnitDieInfo::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cUnitDieInfo::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cUnitDieInfo::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cUnitDieInfo::operator delete[](void* p_addr, u32 align);

// Address: 0x0058e850 - 0x0058e867 (23 bytes)
cUnitDieInfo::cUnitDieInfo() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mpHitInfo = static_cast<cHitInfoAfter*>(nullptr);
}

// Defined in the class (its body was written in a header).
// cUnitDieInfo::~cUnitDieInfo();

// No out-of-line body: 1 inlined copy in 1 function (4 bytes)
//   in cpHpDamageCtrl::requestCallBackDie at 0x00483273-0x00483277 (called at cpHpDamageCtrl.cpp:6666)
// void cUnitDieInfo::setHitInfo(cHitInfoAfter* pInfo);

// No out-of-line body: 2 inlined copies in 1 function (8 bytes)
//   in uHuman::callbackDie at 0x00c82bb9-0x00c82bbd (called at uHuman.cpp:7071)
//   in uHuman::callbackDie at 0x00c82c15-0x00c82c19 (called at uHuman.cpp:7076)
// const cHitInfoAfter* cUnitDieInfo::getHitInfo();

// No out-of-line body: 2 inlined copies in 1 function (132 bytes)
//   in _GLOBAL__sub_I_cUnitDieInfo.cpp at 0x0058e870-0x0058e8b2 (called at cUnitDieInfo.cpp:20)
//   in _GLOBAL__sub_I_cUnitDieInfo.cpp at 0x0058e870-0x0058e8b2 (called at cUnitDieInfo.h:26)
// cUnitDieInfo::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x0058e790 - 0x0058e7d8 (72 bytes)
MtObject* cUnitDieInfo::MyDTI::newInstance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return new (static_cast<u32>(16)) ::cUnitDieInfo;
}

