// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "dataformats.h"
#include "constants.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// sce::Gnm::DataFormat sce::Gnm::DataFormat::build(sce::Gnm::ZFormat);

// No out-of-line body: no code in the ELF
// void sce::Gnm::DataFormat::init(sce::Gnm::SurfaceFormat, sce::Gnm::TextureChannelType, sce::Gnm::TextureChannel, sce::Gnm::TextureChannel, sce::Gnm::TextureChannel, sce::Gnm::TextureChannel);

// No out-of-line body: no code in the ELF
// sce::Gnm::SurfaceFormat sce::Gnm::DataFormat::getSurfaceFormat() const;

// No out-of-line body: no code in the ELF
// sce::Gnm::RenderTargetFormat sce::Gnm::DataFormat::getRenderTargetFormat() const;

// No out-of-line body: no code in the ELF
// sce::Gnm::BufferFormat sce::Gnm::DataFormat::getBufferFormat() const;

// No out-of-line body: no code in the ELF
// sce::Gnm::ZFormat sce::Gnm::DataFormat::getZFormat() const;

// No out-of-line body: no code in the ELF
// sce::Gnm::TextureChannelType sce::Gnm::DataFormat::getTextureChannelType() const;

// No out-of-line body: no code in the ELF
// sce::Gnm::BufferChannelType sce::Gnm::DataFormat::getBufferChannelType() const;

// No out-of-line body: no code in the ELF
// sce::Gnm::TextureChannel sce::Gnm::DataFormat::getChannel(uint32_t) const;

// No out-of-line body: no code in the ELF
// bool sce::Gnm::DataFormat::supportsRenderTarget() const;

// No out-of-line body: no code in the ELF
// bool sce::Gnm::DataFormat::supportsBuffer() const;

// No out-of-line body: no code in the ELF
// bool sce::Gnm::DataFormat::supportsTexture() const;

// No out-of-line body: no code in the ELF
// bool sce::Gnm::DataFormat::supportsDepthRenderTarget() const;

// No out-of-line body: no code in the ELF
// bool sce::Gnm::DataFormat::getRenderTargetChannelOrder(sce::Gnm::RenderTargetChannelOrder*) const;

// No out-of-line body: no code in the ELF
// bool sce::Gnm::DataFormat::getRenderTargetChannelType(sce::Gnm::RenderTargetChannelType*) const;

// No out-of-line body: no code in the ELF
// uint32_t sce::Gnm::DataFormat::getBytesPerElement() const;

