// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "lwgfxcontext.h"
#include "basegfxcontext.h"
#include "constants.h"
#include "lwcue_graphics.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setActiveResourceSlotCount(sce::Gnm::ShaderStage, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setActiveRwResourceSlotCount(sce::Gnm::ShaderStage, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setActiveSamplerSlotCount(sce::Gnm::ShaderStage, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setActiveVertexBufferSlotCount(sce::Gnm::ShaderStage, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setActiveConstantBufferSlotCount(sce::Gnm::ShaderStage, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setActiveStreamoutBufferSlotCount(uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setGsModeOff();

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setUserResourceTable(sce::Gnm::ShaderStage, const sce::Gnm::Texture*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setUserRwResourceTable(sce::Gnm::ShaderStage, const sce::Gnm::Texture*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setUserSamplerTable(sce::Gnm::ShaderStage, const sce::Gnm::Sampler*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setUserConstantBufferTable(sce::Gnm::ShaderStage, const sce::Gnm::Buffer*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setUserVertexTable(sce::Gnm::ShaderStage, const sce::Gnm::Buffer*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::init(void*, int32_t, void*, int32_t, void*, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::init(uint32_t*, int32_t, uint32_t*, int32_t, uint32_t*, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::init(void*, int32_t, void*, int32_t, void*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::init(uint32_t*, int32_t, uint32_t*, int32_t, uint32_t*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setResourceBufferFullCallback(sce::Gnmx::AllocResourceBufferCallback, void*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::reset();

// Address: 0x01bbc5d0 - 0x01bbc69c (204 bytes)
__attribute__((weak)) void sce::Gnmx::LightweightGfxContext::setActiveShaderStages(sce::Gnm::ActiveShaderStages activeStages) {
    DDON_STUB("sce::Gnmx::LightweightGfxContext::setActiveShaderStages")
    /* stub */
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void sce::Gnmx::LightweightGfxContext::setEsShader(const sce::Gnmx::EsShader* esb, uint32_t shaderModifier, const void* fetchShader, const sce::Gnmx::InputResourceOffsets* table);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setEsShader(const sce::Gnmx::EsShader*, const sce::Gnmx::InputResourceOffsets*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setOnChipEsShader(const sce::Gnmx::EsShader*, uint32_t, uint32_t, const void*, const sce::Gnmx::InputResourceOffsets*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setOnChipEsShader(const sce::Gnmx::EsShader*, uint32_t, const sce::Gnmx::InputResourceOffsets*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setEsFetchShader(uint32_t, const void*);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void sce::Gnmx::LightweightGfxContext::setGsVsShaders(const sce::Gnmx::GsShader* gsb, const sce::Gnmx::InputResourceOffsets* gsTable);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setOnChipGsVsShaders(const sce::Gnmx::GsShader*, uint32_t, const sce::Gnmx::InputResourceOffsets*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setLsShader(const sce::Gnmx::LsShader*, uint32_t, const void*, const sce::Gnmx::InputResourceOffsets*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setLsShader(const sce::Gnmx::LsShader*, const sce::Gnmx::InputResourceOffsets*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setLsFetchShader(uint32_t, const void*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setHsShader(const sce::Gnmx::HsShader*, const sce::Gnmx::InputResourceOffsets*, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setLsHsShaders(sce::Gnmx::LsShader*, uint32_t, void*, const sce::Gnmx::InputResourceOffsets*, const sce::Gnmx::HsShader*, const sce::Gnmx::InputResourceOffsets*, uint32_t);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void sce::Gnmx::LightweightGfxContext::setVsShader(const sce::Gnmx::VsShader* vsb, uint32_t shaderModifier, const void* fetchShader, const sce::Gnmx::InputResourceOffsets* table);

// No out-of-line body: 1 inlined copy in 1 function (23 bytes)
//   in cBrowserRenderDevicePS4::SetVertexShader at 0x0001b2ba-0x0001b2d1 (called at cBrowserRenderDevicePS4_cpp.inl:411)
// void sce::Gnmx::LightweightGfxContext::setVsShader(const sce::Gnmx::VsShader* vsb, const sce::Gnmx::InputResourceOffsets* table);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setVsFetchShader(uint32_t, const void*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setEmbeddedVsShader(sce::Gnm::EmbeddedVsShader, uint32_t);

// No out-of-line body: 1 inlined copy in 1 function (19 bytes)
//   in cBrowserRenderDevicePS4::SetFragmentShader at 0x0001b30a-0x0001b31d (called at cBrowserRenderDevicePS4_cpp.inl:419)
// void sce::Gnmx::LightweightGfxContext::setPsShader(const sce::Gnmx::PsShader* psb, const sce::Gnmx::InputResourceOffsets* table);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setEmbeddedPsShader(sce::Gnm::EmbeddedPsShader);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setCsShader(const sce::Gnmx::CsShader*, const sce::Gnmx::InputResourceOffsets*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setCsVsShaders(const sce::Gnmx::CsVsShader*, uint32_t, void*, const sce::Gnmx::InputResourceOffsets*, uint32_t, void*, const sce::Gnmx::InputResourceOffsets*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setAsynchronousComputeShader(const sce::Gnmx::CsShader*, uint32_t, void*, const sce::Gnmx::InputResourceOffsets*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setOnChipEsGsLdsLayout(uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setStreamoutBuffers(int32_t, int32_t, const sce::Gnm::Buffer*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setAppendConsumeCounterRange(sce::Gnm::ShaderStage, uint32_t, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setGdsMemoryRange(sce::Gnm::ShaderStage, uint32_t, uint32_t);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void sce::Gnmx::LightweightGfxContext::setConstantBuffers(sce::Gnm::ShaderStage stage, uint32_t startSlot, uint32_t numSlots, const sce::Gnm::Buffer* buffers);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void sce::Gnmx::LightweightGfxContext::setVertexBuffers(sce::Gnm::ShaderStage stage, uint32_t startSlot, uint32_t numSlots, const sce::Gnm::Buffer* buffers);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setBuffers(sce::Gnm::ShaderStage, uint32_t, uint32_t, const sce::Gnm::Buffer*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setRwBuffers(sce::Gnm::ShaderStage, uint32_t, uint32_t, const sce::Gnm::Buffer*);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void sce::Gnmx::LightweightGfxContext::setTextures(sce::Gnm::ShaderStage stage, uint32_t startSlot, uint32_t numSlots, const sce::Gnm::Texture* textures);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setRwTextures(sce::Gnm::ShaderStage, uint32_t, uint32_t, const sce::Gnm::Texture*);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void sce::Gnmx::LightweightGfxContext::setSamplers(sce::Gnm::ShaderStage stage, uint32_t startSlot, uint32_t numSlots, const sce::Gnm::Sampler* samplers);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setUserSrtBuffer(sce::Gnm::ShaderStage, const void*, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setGlobalResourceTableAddr(void*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setGlobalDescriptor(sce::Gnm::ShaderGlobalResourceType, const sce::Gnm::Buffer*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setBoolConstants(sce::Gnm::ShaderStage, uint32_t, uint32_t, const uint32_t*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setFloatConstants(sce::Gnm::ShaderStage, uint32_t, uint32_t, const float*);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void sce::Gnmx::LightweightGfxContext::drawIndexAuto(uint32_t indexCount);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::drawIndexAuto(uint32_t, uint32_t, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::drawOpaque();

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::drawOpaque(uint32_t, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::drawIndexInline(uint32_t, const void*, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::drawIndexInline(uint32_t, const void*, uint32_t, uint32_t, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::drawIndex(uint32_t, const void*);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::drawIndex(uint32_t, const void*, uint32_t, uint32_t);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void sce::Gnmx::LightweightGfxContext::drawIndexOffset(uint32_t indexOffset, uint32_t indexCount);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::drawIndexOffset(uint32_t, uint32_t, uint32_t, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::drawIndirect(uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::drawIndirectMulti(uint32_t, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::drawIndirectMulti(uint32_t, uint32_t, sce::Gnm::ShaderStage, uint8_t, uint8_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::drawIndexIndirect(uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::drawIndexIndirectMulti(uint32_t, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::drawIndexIndirectMulti(uint32_t, uint32_t, sce::Gnm::ShaderStage, uint8_t, uint8_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::dispatch(uint32_t, uint32_t, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::dispatchIndirect(uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setEsGsRingBuffer(void*, uint32_t, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setGsVsRingBuffers(void*, uint32_t, const uint32_t*, uint32_t);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setTessellationDataConstantBuffer(void*, sce::Gnm::ShaderStage);

// No out-of-line body: no code in the ELF
// void sce::Gnmx::LightweightGfxContext::setTessellationFactorBuffer(void*);

// No out-of-line body: no code in the ELF
// int32_t sce::Gnmx::LightweightGfxContext::submit();

// No out-of-line body: no code in the ELF
// int32_t sce::Gnmx::LightweightGfxContext::submitAndFlip(uint32_t, uint32_t, uint32_t, int64_t);

// No out-of-line body: no code in the ELF
// int32_t sce::Gnmx::LightweightGfxContext::validate();

