#pragma once

#include <cstdint>
#include <cstddef>

// Dependencies
#include "MtCollisionDefine.h"
#include "MtMath.h"

// Forward declarations
class MtAABB;
class MtAABB2D;
class MtAABB4;
class MtAABB4Compress;
class MtAABBCompress;
class MtCapsule;
namespace MtCollisionUtil { class MtRect3DC; }
namespace MtCollisionUtil { class MtSoaVector1; }
namespace MtCollisionUtil { class MtSoaVector3; }
namespace MtCollisionUtil { class MtVectorU4; }
class MtCylinder;
class MtLine;
class MtLine4;
class MtLineSegment;
class MtLineSegment4;
class MtOBB;
class MtPlane;
class MtPlane4;
class MtPlaneXZ;
class MtRay;
class MtRayY;
class MtRect3D;
class MtRect3D_XZ;
class MtSegment;
class MtSphere;
class MtTriangle;
class MtTriangle2D;
class MtTriangle4;
class MtVector2;
class MtVector3;
class MtVector4;

// Declarations
class MtCollision;
struct MtContact;

// Type aliases from DWARF
using f32 = float;
using u32 = unsigned int;

class MtCollision
{
public:
    static bool intersect(const MtVector3&, const MtLine&, f32);
    static bool intersect(const MtVector3&, const MtRay&, f32);
    static bool intersect(const MtVector3& pos, const MtLineSegment& ls, f32 epsilon);
    static bool intersect(const MtVector3&, const MtSphere&);
    static bool intersect(const MtVector3&, const MtCapsule&);
    static bool intersect(const MtVector3& pos, const MtCylinder& cylinder);
    static bool intersect(const MtVector3& pos, const MtAABB& aabb);
    static bool intersect(const MtVector3&, const MtOBB&);
    static bool intersect(const MtVector3&, const MtTriangle&);
    static bool intersectFast(const MtVector3& pos, const MtRect3D_XZ& rect3dXZ);
    static bool intersectFast(const MtVector3& pos, const MtCollisionUtil::MtRect3DC& rect3D);
    static bool intersect(const MtLine& line, const MtVector3& pos, f32 epsilon);
    static bool intersect(const MtLine& line0, const MtLine& line1, f32 epsilon);
    static bool intersect(const MtLine& line, const MtRay& ray, f32 epsilon);
    static bool intersect(const MtLine& line, const MtLineSegment& ls, f32 epsilon);
    static bool intersect(const MtLine& line, const MtSphere& s0);
    static bool intersect(const MtLine& line, const MtCapsule& capsule);
    static bool intersect(const MtLine& line, const MtCylinder& cylinder);
    static bool intersect(const MtLine& line, const MtAABB& aabb);
    static bool intersect(const MtLine& line, const MtOBB& obb);
    static bool intersect(const MtLine& line, const MtPlane& plane);
    static bool intersect(const MtLine& line, const MtTriangle& tri);
    static bool intersect(const MtLine& line, const MtPlane& plane, f32& t);
    static bool intersect(const MtLine&, const MtRect3D_XZ&, bool);
    static bool intersect(const MtLine&, const MtRect3D&, bool);
    static bool intersect(const MtLine&, const MtCollisionUtil::MtRect3DC&, bool);
    static bool intersect(const MtLine&, const MtRect3D_XZ&, MtVector3&, f32&, bool);
    static bool intersect(const MtLine&, const MtRect3D&, MtVector3&, f32&, bool);
    static bool intersect(const MtLine&, const MtCollisionUtil::MtRect3DC&, MtVector3&, f32&, bool);
    static bool intersect(const MtRay& ray, const MtVector3& pos, f32 epsilon);
    static bool intersect(const MtRay& ray, const MtLine& line, f32 epsilon);
    static bool intersect(const MtRay& ray0, const MtRay& ray1, f32 epsilon);
    static bool intersect(const MtRay& ray, const MtLineSegment& ls, f32 epsilon);
    static bool intersect(const MtRay& ray, const MtSphere& s0);
    static bool intersect(const MtRay& ray, const MtCapsule& capsule);
    static bool intersect(const MtRay& ray, const MtCylinder& cylinder);
    static bool intersect(const MtRay& ray, const MtAABB& aabb);
    static bool intersect(const MtRay& ray, const MtOBB& obb);
    static bool intersect(const MtRay& ray, const MtPlane& plane);
    static bool intersect(const MtRay& ray, const MtTriangle& tri);
    static bool intersect(const MtRay& ray, const MtPlane& plane, f32& t);
    static bool intersect(const MtRay&, const MtRect3D_XZ&, bool);
    static bool intersect(const MtRay&, const MtRect3D&, bool);
    static bool intersect(const MtRay&, const MtCollisionUtil::MtRect3DC&, bool);
    static bool intersect(const MtRay&, const MtRect3D_XZ&, MtVector3&, f32&, bool);
    static bool intersect(const MtRay&, const MtRect3D&, MtVector3&, f32&, bool);
    static bool intersect(const MtRay&, const MtCollisionUtil::MtRect3DC&, MtVector3&, f32&, bool);
    static bool intersect(const MtRayY& rayY, const MtAABB& aabb);
    static bool intersect(const MtRayY& rayY, const MtPlane& plane);
    static bool intersect(const MtRayY& rayY, const MtTriangle& triangle);
    static bool intersect(const MtLineSegment& ls, const MtVector3& pos, f32 epsilon);
    static bool intersect(const MtLineSegment& ls, const MtLine& line, f32 epsilon);
    static bool intersect(const MtLineSegment& ls, const MtRay& ray, f32 epsilon);
    static bool intersect(const MtLineSegment& ls0, const MtLineSegment& ls1, f32 epsilon);
    static bool intersect(const MtLineSegment& ls, const MtSphere& s0);
    static bool intersect(const MtLineSegment& ls, const MtCapsule& capsule);
    static bool intersect(const MtLineSegment& ls, const MtCylinder& cylinder);
    static bool intersect(const MtLineSegment& ls, const MtAABB& aabb);
    static bool intersect(const MtLineSegment&, const MtAABB&, f32*);
    static bool intersect(const MtLineSegment& ls, const MtOBB& obb);
    static bool intersect(const MtLineSegment& ls, const MtPlane& plane);
    static bool intersect(const MtLineSegment& ls, const MtTriangle& tri);
    static bool intersect(const MtLineSegment& ls, const MtPlane& plane, f32& t, const f32 Epsilon);
    static bool intersect(const MtLineSegment&, const MtRect3D_XZ&, bool);
    static bool intersect(const MtLineSegment&, const MtRect3D&, bool);
    static bool intersect(const MtLineSegment&, const MtCollisionUtil::MtRect3DC&, bool);
    static bool intersect(const MtLineSegment&, const MtRect3D_XZ&, MtVector3&, f32&, bool);
    static bool intersect(const MtLineSegment&, const MtRect3D&, MtVector3&, f32&, bool);
    static bool intersect(const MtLineSegment&, const MtCollisionUtil::MtRect3DC&, MtVector3&, f32&, bool);
    static bool intersect(const MtSphere& s0, const MtVector3& pos);
    static bool intersect(const MtSphere& s0, const MtLine& line);
    static bool intersect(const MtSphere& s0, const MtRay& ray);
    static bool intersect(const MtSphere& s0, const MtLineSegment& ls);
    static bool intersect(const MtSphere& s0, const MtSphere& s1);
    static bool intersect(const MtSphere& sphere, const MtCylinder& cylinder);
    static bool intersect(const MtSphere& s0, const MtCapsule& capsule);
    static bool intersect(const MtSphere& s0, const MtAABB& aabb);
    static bool intersect(const MtSphere& s, const MtOBB& obb);
    static bool intersect(const MtSphere& s0, const MtPlane& plane);
    static bool intersect(const MtSphere& s0, const MtPlaneXZ& planeXZ);
    static bool intersect(const MtSphere& s0, const MtTriangle& tri);
    static bool intersect(const MtCapsule& capsule, const MtVector3& pos);
    static bool intersect(const MtCapsule& capsule, const MtLine& line);
    static bool intersect(const MtCapsule& capsule, const MtRay& ray);
    static bool intersect(const MtCapsule& capsule, const MtLineSegment& ls);
    static bool intersect(const MtCapsule& capsule, const MtSphere& sphere);
    static bool intersect(const MtCapsule& capsule, const MtCylinder& cylinder);
    static bool intersect(const MtCapsule& capsule0, const MtCapsule& capsule1);
    static bool intersect(const MtCapsule& capsule, const MtAABB& aabb);
    static bool intersect(const MtCapsule& capsule, const MtOBB& obb);
    static bool intersect(const MtCapsule& capsule, const MtPlane& plane);
    static bool intersect(const MtCapsule& capsule, const MtTriangle& tri);
    static bool intersect(const MtAABB& aabb, const MtVector3& pos);
    static bool intersect(const MtAABB& aabb, const MtLine& line);
    static bool intersect(const MtAABB& aabb, const MtRay& ray);
    static bool intersect(const MtAABB& aabb, const MtRayY& rayY);
    static bool intersect(const MtAABB& aabb, const MtLineSegment& ls);
    static bool intersect(const MtAABB& aabb, const MtSphere& sphere);
    static bool intersect(const MtAABB& aabb, const MtCylinder& cylinder);
    static bool intersect(const MtAABB& aabb, const MtCapsule& capsule);
    static bool intersect(const MtAABB& aabb0, const MtAABB& aabb1);
    static bool intersect(const MtAABB& aabb, const MtOBB& obb);
    static bool intersect(const MtAABB& aabb, const MtPlane& plane);
    static bool intersect(const MtAABB& aabb, const MtTriangle& tri);
    static bool intersect(const MtAABB& aabb, const MtLine& line, f32* pLine_t);
    static bool intersect(const MtAABB& aabb, const MtRay& ray, f32* pRay_t);
    static bool intersect(const MtAABB& aabb, const MtLineSegment& ls, f32* pLS_t);
    static bool intersectFast(const MtAABB& aabb0, const MtAABB& aabb1);
    static bool intersect(const MtOBB& obb, const MtVector3& pos);
    static bool intersect(const MtOBB& obb, const MtLine& line);
    static bool intersect(const MtOBB& obb, const MtRay& ray);
    static bool intersect(const MtOBB& obb, const MtLineSegment& ls);
    static bool intersect(const MtOBB& obb, const MtSphere& sphere);
    static bool intersect(const MtOBB& obb, const MtCylinder& cylinder);
    static bool intersect(const MtOBB& obb, const MtCapsule& capsule);
    static bool intersect(const MtOBB& obb, const MtAABB& aabb);
    static bool intersect(const MtOBB& obb0, const MtOBB& obb1);
    static bool intersect(const MtOBB& obb, const MtPlane& plane);
    static bool intersect(const MtOBB& obb, const MtTriangle& tri);
    static bool intersect(const MtPlane&, const MtLine&);
    static bool intersect(const MtPlane&, const MtRay&);
    static bool intersect(const MtPlane&, const MtLineSegment&);
    static bool intersect(const MtPlane&, const MtSphere&);
    static bool intersect(const MtPlane&, const MtCapsule&);
    static bool intersect(const MtPlane&, const MtAABB&);
    static bool intersect(const MtPlane&, const MtOBB&);
    static bool intersect(const MtPlane&, const MtCylinder&);
    static bool intersect(const MtTriangle& tri, const MtVector3& pos, const bool FlgEnableDistanceCheck, const f32 HitDistanceEpsilon);
    static bool intersect(const MtTriangle& tri, const MtLine& line);
    static bool intersect(const MtTriangle& tri, const MtLine& line, MtVector3& pos, f32& t);
    static bool intersect(const MtTriangle& tri, const MtRay& ray);
    static bool intersect(const MtTriangle& tri, const MtRay& ray, MtVector3& pos, f32& t);
    static bool intersect(const MtTriangle& tri, const MtLineSegment& ls);
    static bool intersect(const MtTriangle& tri, const MtSphere& s);
    static bool intersect(const MtTriangle& tri, const MtCapsule& cap);
    static bool intersect(const MtTriangle& tri, const MtAABB& aabb);
    static bool intersect(const MtTriangle& tri, const MtOBB& obb);
    static bool intersect(const MtTriangle& tri0, const MtTriangle& tri1);
    static bool intersect(const MtTriangle& triangle, const MtCylinder& cylinder);
    static bool intersect(const MtTriangle& tri, const MtLineSegment& ls, MtVector3& pos);
    static bool intersect(const MtTriangle& tri, const MtLineSegment& ls, MtVector3& pos, f32& t);
    static bool intersectTriPiller(const MtTriangle& tri, const MtVector3& pos);
    static bool intersectFast(const MtTriangle&, const MtVector3&, f32);
    static bool intersectFast(const MtTriangle& tri, const MtVector3& triNormal, const MtVector3& pos, f32 epsilon);
    static bool intersectFast(const MtVector3& triPt0, const MtVector3& triPt1, const MtVector3& triPt2, const MtVector3& triNormal, const MtVector3& pos, f32 epsilon);
    static bool intersect(const MtCylinder& cylinder, const MtVector3& vertex);
    static bool intersect(const MtCylinder& cylinder, const MtLine& line);
    static bool intersect(const MtCylinder& cylinder, const MtRay& ray);
    static bool intersect(const MtCylinder& cylinder, const MtLineSegment& ls);
    static bool intersect(const MtCylinder& cylinder, const MtSphere& sphere);
    static bool intersect(const MtCylinder& cylinder, const MtCapsule& capsule);
    static bool intersect(const MtCylinder& cylinder, const MtAABB& aabb);
    static bool intersect(const MtCylinder& cylinder, const MtOBB& obb);
    static bool intersect(const MtCylinder& cylinder, const MtPlane& plane);
    static bool intersect(const MtCylinder& cylinder, const MtTriangle& triangle);
    static bool intersect(const MtCylinder& cylinder0, const MtCylinder& cylinder1);
    static bool intersect(const MtRect3D_XZ&, const MtLine&, bool);
    static bool intersect(const MtRect3D_XZ&, const MtRay&, bool);
    static bool intersect(const MtRect3D_XZ&, const MtLineSegment&, bool);
    static bool intersect(const MtRect3D_XZ&, const MtLine&, MtVector3&, f32&, bool);
    static bool intersect(const MtRect3D_XZ&, const MtRay&, MtVector3&, f32&, bool);
    static bool intersect(const MtRect3D_XZ&, const MtLineSegment&, MtVector3&, f32&, bool);
    static bool intersect(const MtRect3D&, const MtLine&, bool);
    static bool intersect(const MtRect3D&, const MtRay&, bool);
    static bool intersect(const MtRect3D&, const MtLineSegment&, bool);
    static bool intersect(const MtRect3D&, const MtLine&, MtVector3&, f32&, bool);
    static bool intersect(const MtRect3D&, const MtRay&, MtVector3&, f32&, bool);
    static bool intersect(const MtRect3D&, const MtLineSegment&, MtVector3&, f32&, bool);
    static bool intersect(const MtCollisionUtil::MtRect3DC&, const MtLine&, bool);
    static bool intersect(const MtCollisionUtil::MtRect3DC&, const MtRay&, bool);
    static bool intersect(const MtCollisionUtil::MtRect3DC&, const MtLineSegment&, bool);
    static bool intersect(const MtCollisionUtil::MtRect3DC&, const MtLine&, MtVector3&, f32&, bool);
    static bool intersect(const MtCollisionUtil::MtRect3DC&, const MtRay&, MtVector3&, f32&, bool);
    static bool intersect(const MtCollisionUtil::MtRect3DC&, const MtLineSegment&, MtVector3&, f32&, bool);
    static f32 distance(const MtPlane& plane, const MtVector3& pos);
    static MtVector4 distanceBq(const MtPlane&, const MtVector3&);
    static void distance3(const MtPlane& plane, const MtVector3& p0, const MtVector3& p1, const MtVector3& p2, MtVector3& result);
    static void distance4(const MtPlane&, const MtVector3&, const MtVector3&, const MtVector3&, const MtVector3&, MtVector4&);
    static void distance3(const MtVector3* planeNormals, const MtVector3& planeDists, const MtVector3& pos, MtVector3& result);
    static void distance4(const MtVector3* planeNormals, const MtVector4& planeDists, const MtVector3& pos, MtVector4& result);
    static f32 distance(const MtPlaneXZ& planeXZ, const MtVector3& pos);
    static f32 sqrDistance(const MtVector3& pos, const MtLine& line, f32* pLine_t);
    static f32 sqrDistance(const MtVector3& pos, const MtRay& ray, f32* pLine_t);
    static f32 sqrDistance(const MtVector3& pos, const MtLineSegment& ls, f32* pLs_t);
    static f32 sqrDistance(const MtVector3&, const MtAABB&);
    static f32 sqrDistance(const MtVector3&, const MtOBB&);
    static f32 sqrDistance(const MtVector3&, const MtTriangle&);
    static f32 sqrDistance(const MtVector3&, const MtAABB&, MtVector3&);
    static f32 sqrDistance(const MtLine& line, const MtVector3& pos, f32* pLine_t);
    static f32 sqrDistance(const MtLine& line0, const MtLine& line1, f32* pLine0_t, f32* pLine1_t, f32 FlatCheckEpsilon);
    static f32 sqrDistance(const MtLine& line, const MtRay& ray, f32* pLine_t, f32* pRay_t, f32 FlatCheckEpsilon);
    static f32 sqrDistance(const MtLine& line, const MtLineSegment& ls, f32* pLine_t, f32* pLS_t, f32 FlatCheckEpsilon);
    static f32 sqrDistance(const MtLine&, const MtAABB&, f32*);
    static f32 sqrDistance(const MtLine&, const MtOBB&, f32*);
    static f32 sqrDistance(const MtRay& ray, const MtVector3& pos, f32* pRay_t);
    static f32 sqrDistance(const MtRay& ray, const MtLine& line, f32* pRay_t, f32* pLine_t, f32 FlatCheckEpsilon);
    static f32 sqrDistance(const MtRay& ray0, const MtRay& ray1, f32* pRay0_t, f32* pRay1_t, f32 FlatCheckEpsilon);
    static f32 sqrDistance(const MtRay& ray, const MtLineSegment& ls, f32* pRay_t, f32* pLS_t, f32 FlatCheckEpsilon);
    static f32 sqrDistance(const MtRay&, const MtAABB&, f32*);
    static f32 sqrDistance(const MtRay&, const MtOBB&, f32*);
    static f32 sqrDistance(const MtLineSegment& ls, const MtVector3& pos, f32* pLS_t);
    static f32 sqrDistance(const MtLineSegment& ls, const MtLine& line, f32* pLS_t, f32* pLine_t, f32 FlatCheckEpsilon);
    static f32 sqrDistance(const MtLineSegment& ls, const MtRay& ray, f32* pLS_t, f32* pRay_t, f32 FlatCheckEpsilon);
    static f32 sqrDistance(const MtLineSegment& ls0, const MtLineSegment& ls1, f32* pLS0_t, f32* pLine1_t, f32 FlatCheckEpsilon);
    static f32 sqrDistance(const MtLineSegment& ls, const MtTriangle& tri, f32* pLS_t);
    static f32 sqrDistance(const MtLineSegment&, const MtAABB&, f32*);
    static f32 sqrDistance(const MtLineSegment&, const MtOBB&, f32*);
    static f32 sqrDistance(const MtLineSegment& ls, const MtVector3& pos, f32& LS_t);
    static f32 sqrDistance(const MtLineSegment& ls, const MtVector3& pos, MtVector3& NearestVec, MtVector3& NearestPt, f32& NearestLen);
    static f32 sqrDistance(const MtSegment& segment, const MtVector3& vertex, f32* segment_t);
    static f32 sqrDistance(const MtSegment& segment0, const MtSegment& segment1, f32* segment0_t, f32* segment1_t);
    static f32 sqrDistance(const MtAABB& aabb, const MtVector3& pos);
    static f32 sqrDistance(const MtAABB& aabb, const MtLine& line);
    static f32 sqrDistance(const MtAABB& aabb, const MtRay& ray);
    static f32 sqrDistance(const MtAABB& aabb, const MtLineSegment& ls);
    static f32 sqrDistance(const MtAABB& aabb0, const MtAABB& aabb1);
    static f32 sqrDistance(const MtAABB& aabb, const MtLine& line, f32* pLine_t);
    static f32 sqrDistance(const MtAABB& aabb, const MtRay& ray, f32* pRay_t);
    static f32 sqrDistance(const MtAABB& aabb, const MtLineSegment& ls, f32* pLS_t);
    static f32 sqrDistance(const MtAABB& aabb, const MtVector3& pos, MtVector3& NearPos);
    static f32 sqrDistance(const MtOBB& obb, const MtVector3& pos);
    static f32 sqrDistance(const MtOBB& obb, const MtLine& line, f32* pLine_t);
    static f32 sqrDistance(const MtOBB& obb, const MtRay& ray, f32* pRay_t);
    static f32 sqrDistance(const MtOBB& obb, const MtLineSegment& ls, f32* pLS_t);
    static f32 sqrDistance(const MtOBB& obb, const MtVector3& pos, MtVector3& NearPos);
    static f32 sqrDistance(const MtTriangle& tri, const MtVector3& pos);
    static f32 sqrDistance(const MtTriangle& tri, const MtLineSegment& ls, f32* pLS_t);
    static bool closest(const MtVector3& pos, const MtSphere& s, MtContact* pSphereContact);
    static bool closest(const MtVector3& pos, const MtCapsule& capsule, MtContact* pCapsuleContact);
    static bool closest(const MtVector3& pos, const MtAABB& aabb, MtContact* pAABBContact);
    static bool closest(const MtVector3&, const MtOBB&, MtContact*);
    static bool closest(const MtVector3&, const MtPlane&, MtContact*);
    static bool closest(const MtVector3&, const MtPlaneXZ&, MtContact*);
    static bool closest(const MtVector3& pos, const MtTriangle& tri, MtContact* pTriangleContact);
    static bool closest(const MtVector3&, const MtCylinder&, MtContact*);
    static bool closest(const MtLine& line, const MtSphere& sphere, f32* pLine_t, MtContact* pSphereContact);
    static bool closest(const MtLine& line, const MtCapsule& capsule, f32* pLine_t, MtContact* pCapsuleContact);
    static bool closest(const MtLine& line, const MtAABB& aabb, f32* pLine_t, MtContact* pAABBContact);
    static bool closest(const MtLine& line, const MtOBB& obb, f32* pLine_t, MtContact* pOBBClosest);
    static bool closest(const MtLine& line, const MtPlane& plane, f32* pLine_t, MtContact* pPlaneContact);
    static bool closest(const MtLine& line, const MtTriangle& tri, f32* pLine_t, MtContact* pTriangleContact);
    static bool closest(const MtLine&, const MtCylinder&, f32*, MtContact*);
    static bool closest(const MtRay& ray, const MtSphere& sphere, f32* pRay_t, MtContact* pSphereContact);
    static bool closest(const MtRay& ray, const MtCapsule& capsule, f32* pRay_t, MtContact* pCapsuleContact);
    static bool closest(const MtRay& ray, const MtAABB& aabb, f32* pRay_t, MtContact* pAABBContact);
    static bool closest(const MtRay& ray, const MtOBB& obb, f32* pRay_t, MtContact* pOBBClosest);
    static bool closest(const MtRay& ray, const MtPlane& plane, f32* pLine_t, MtContact* pPlaneContact);
    static bool closest(const MtRay& ray, const MtTriangle& tri, f32* pRay_t, MtContact* pTriangleContact);
    static bool closest(const MtRay&, const MtCylinder&, f32*, MtContact*);
    static bool closest(const MtLineSegment& ls, const MtSphere& sphere, f32* pLS_t, MtContact* pSphereContact);
    static bool closest(const MtLineSegment& ls, const MtCapsule& capsule, f32* pLS_t, MtContact* pCapsuleContact);
    static bool closest(const MtLineSegment& ls, const MtAABB& aabb, f32* pLS_t, MtContact* pAABBContact);
    static bool closest(const MtLineSegment& ls, const MtOBB& obb, f32* pLS_t, MtContact* pOBBClosest);
    static bool closest(const MtLineSegment& ls, const MtPlane& plane, f32* pLS_t, MtContact* pPlaneContact, bool FlgLegacyMode);
    static bool closest(const MtLineSegment& ls, const MtPlaneXZ& planeXZ, f32* pLS_t, MtContact* pPlaneContact);
    static bool closest(const MtLineSegment& ls, const MtTriangle& tri, f32* pLS_t, MtContact* pTriangleContact);
    static bool closest(const MtLineSegment& ls, const MtCylinder& cylinder, f32* pLS_t, MtContact* pCylinderContact);
    static bool closest(const MtLineSegment&, const MtRect3D_XZ&, f32*, MtContact*);
    static bool closest(const MtLineSegment&, const MtRect3D&, f32*, MtContact*);
    static bool closest(const MtLineSegment&, const MtCollisionUtil::MtRect3DC&, f32*, MtContact*);
    static bool closestCore(const MtLineSegment& ls, const MtRect3D_XZ& rect3dXZ, f32& t, MtContact& contact);
    static bool closestCore(const MtLineSegment& ls, const MtCollisionUtil::MtRect3DC& rect3D, f32& t, MtContact& contact);
    static bool closest(const MtSphere& s, const MtVector3& pos, MtContact* pSphereContact);
    static bool closest(const MtSphere& s, const MtLine& line, MtContact* pSphereContact, f32* pLine_t);
    static bool closest(const MtSphere& s, const MtRay& ray, MtContact* pSphereContact, f32* pLine_t);
    static bool closest(const MtSphere& s, const MtLineSegment& ls, MtContact* pSphereContact, f32* pLine_t);
    static bool closest(const MtSphere& s0, const MtSphere& s1, MtContact* pSphere0Contact, MtContact* pSphere1Contact);
    static bool closest(const MtSphere& sphere, const MtCylinder& cylinder, MtContact* sphere_closest, MtContact* cylinder_closest);
    static bool closest(const MtSphere& s, const MtCapsule& cap, MtContact* pSphereContact, MtContact* pCapsuleContact);
    static bool closest(const MtSphere& sphere, const MtAABB& aabb, MtContact* pSphereContact, MtContact* pAABBContact);
    static bool closest(const MtSphere& sphere, const MtOBB& obb, MtContact* pSphereContact, MtContact* pOBBClosest);
    static bool closest(const MtSphere& sphere, const MtPlane& plane, MtContact* pSphereContact, MtContact* pPlaneContact);
    static bool closest(const MtSphere& sphere, const MtPlaneXZ& planeXZ, MtContact* pSphereContact, MtContact* pPlaneContact);
    static bool closest(const MtSphere& sphere, const MtTriangle& tri, MtContact* pSphereContact, MtContact* pTriangleContact);
    static bool closestCore(const MtSphere& sphere, const MtCollisionUtil::MtRect3DC& rect3D, MtContact& contact, u32& vid);
    static bool closest(const MtCapsule& cap, const MtVector3& pos, MtContact* pCapsuleContact);
    static bool closest(const MtCapsule& cap, const MtLine& line, MtContact* pCapsuleContact, f32* pLine_t);
    static bool closest(const MtCapsule& cap, const MtRay& ray, MtContact* pCapsuleContact, f32* pLine_t);
    static bool closest(const MtCapsule& cap, const MtLineSegment& ls, MtContact* pCapsuleContact, f32* pLine_t);
    static bool closest(const MtCapsule& cap, const MtSphere& sphere, MtContact* pCapsuleContact, MtContact* pSphereContact);
    static bool closest(const MtCapsule&, const MtCylinder&, MtContact*, MtContact*);
    static bool closest(const MtCapsule& c0, const MtCapsule& c1, MtContact* pCapsule0Contact, MtContact* pCapsule1Contact);
    static bool closest(const MtCapsule& cap, const MtAABB& aabb, MtContact* pCapsule0Contact, MtContact* pAABBContact);
    static bool closest(const MtCapsule& cap, const MtOBB& obb, MtContact* pCapsule0Contact, MtContact* pOBBClosest);
    static bool closest(const MtCapsule& capsule, const MtPlane& plane, MtContact* pCapsuleContact, MtContact* pPlaneContact);
    static bool closest(const MtCapsule& capsule, const MtTriangle& tri, MtContact* pCapsuleContact, MtContact* pTriangleContact);
    static bool closest(const MtAABB& aabb, const MtVector3& pos, MtContact* pAABBContact);
    static bool closest(const MtAABB& aabb, const MtLine& line, MtContact* pAABBContact, f32* pLine_t);
    static bool closest(const MtAABB& aabb, const MtRay& ray, MtContact* pAABBContact, f32* pLine_t);
    static bool closest(const MtAABB& aabb, const MtLineSegment& ls, MtContact* pAABBContact, f32* pLine_t);
    static bool closest(const MtAABB& aabb, const MtLineSegment& ls, MtContact* pAABBContact, MtContact* pLsContact);
    static bool closest(const MtAABB& aabb, const MtSphere& s, MtContact* pAABBContact, MtContact* pSphereContact);
    static bool closest(const MtAABB&, const MtCylinder&, MtContact*, MtContact*);
    static bool closest(const MtAABB& aabb, const MtCapsule& cap, MtContact* pAABBContact, MtContact* pCapsuleContact);
    static bool closest(const MtAABB& aabb0, const MtAABB& aabb1, MtContact* pAABBContact0, MtContact* pAABBContact1, bool FlgOutputHitPos, bool FlgCheckNoHitResult);
    static bool closest(const MtAABB& aabb, const MtOBB& obb, MtContact* pAABBContact, MtContact* pObbContact);
    static bool closest(const MtAABB& aabb, const MtPlane& plane, MtContact* pAABBContact, MtContact* pPlaneContact, bool FlgForceNoHit);
    static bool closest(const MtAABB& aabb, const MtPlaneXZ& planeXZ, MtContact* pAABBContact, MtContact* pPlaneContact);
    static bool closest(const MtAABB& aabb, const MtTriangle& triangle, MtContact* pAABBContact, MtContact* pTriangleContact);
protected:
    static bool closestCommon(const MtAABB& aabb, const MtVector3& pos, MtContact* pAABBContact);
public:
    static bool closest(const MtOBB& obb, const MtVector3& pos, MtContact* pOBBContact);
    static bool closest(const MtOBB& obb, const MtLine& line, MtContact* pOBBContact, f32* pLine_t);
    static bool closest(const MtOBB& obb, const MtRay& ray, MtContact* pOBBContact, f32* pLine_t);
    static bool closest(const MtOBB& obb, const MtLineSegment& ls, MtContact* pOBBContact, f32* pLine_t);
    static bool closest(const MtOBB& obb, const MtSphere& sphere, MtContact* pOBBContact, MtContact* pSphereContact);
    static bool closest(const MtOBB&, const MtCylinder&, MtContact*, MtContact*);
    static bool closest(const MtOBB& obb, const MtCapsule& cap, MtContact* pOBBContact, MtContact* pCapsuleContact);
    static bool closest(const MtOBB& obb, const MtAABB& aabb, MtContact* pObbContact, MtContact* pAABBContact);
    static bool closest(const MtOBB& obb1, const MtOBB& obb2, MtContact* obb1_closest, MtContact* obb2_closest);
    static bool closest(const MtOBB& obb, const MtPlane& plane, MtContact* pOBBContact, MtContact* pPlaneContact);
    static bool closest(const MtOBB& obb, const MtPlaneXZ& planeXZ, MtContact* pOBBContact, MtContact* pPlaneContact);
    static bool closest(const MtOBB& obb, const MtTriangle& tri, MtContact* pContact0, MtContact* pContact1);
    static bool closestCore(const MtOBB& obb1, const MtOBB& obb2, MtContact& contact1, MtContact& contact2, bool FlgNoHitEnd, bool FlgEnableOutput);
    static bool closest(const MtPlane& plane, const MtVector3& pos, MtContact* pPlaneContact);
    static bool closest(const MtPlane&, const MtLine&, MtContact*, f32*);
    static bool closest(const MtPlane&, const MtRay&, MtContact*, f32*);
    static bool closest(const MtPlane& plane, const MtLineSegment& ls, MtContact* pPlaneContact, f32* pLine_t);
    static bool closest(const MtPlane&, const MtSphere&, MtContact*, MtContact*);
    static bool closest(const MtPlane&, const MtCapsule&, MtContact*, MtContact*);
    static bool closest(const MtPlane& plane, const MtAABB& aabb, MtContact* pPlaneContact, MtContact* pAABBContact, bool FlgForceNoHit);
    static bool closestExpansion(const MtPlane& plane, const MtLineSegment& ls, f32& dist0, f32& dist1, MtContact* pPlaneContact, f32* pLine_t, bool FlgLegacyMode);
    static bool closest(const MtPlaneXZ& planeXZ, const MtVector3& pos, MtContact* pPlaneContact);
    static bool closest(const MtTriangle& tri, const MtVector3& pos, MtContact* pTriangleContact);
    static bool closest(const MtTriangle& tri, const MtLine& line, MtContact* pTriangleContact, f32* pLine_t);
    static bool closest(const MtTriangle& tri, const MtRay& ray, MtContact* pTriangleContact, f32* pRay_t);
    static bool closest(const MtTriangle& tri, const MtLineSegment& ls, MtContact* pTriangleContact, f32* pLine_t);
    static bool closest(const MtTriangle& tri, const MtSphere& s, MtContact* pTriangleContact, MtContact* pSphereContact);
    static bool closest(const MtTriangle&, const MtCylinder&, MtContact*, MtContact*);
    static bool closest(const MtTriangle& tri, const MtCapsule& capsule, MtContact* pTriangleContact, MtContact* pCapsuleContact);
    static bool closest(const MtTriangle& triangle, const MtAABB& aabb, MtContact* pTriangleContact, MtContact* pAABBContact);
    static bool closest(const MtTriangle& triangle, const MtOBB& obb, MtContact* pTriangleContact, MtContact* pOBBContact);
    static bool closestExpansion(const MtTriangle& tri, const MtLineSegment& ls, MtVector3& triNormalOut, f32& dist0, f32& dist1, MtContact* pTriangleContact, f32* pLine_t, bool FlgAntiZeroNormalEnable);
protected:
    static bool closestCoreTriVsAABBForOutside(const MtTriangle& tri, const MtAABB& aabb, MtContact* pTriangleContact, MtContact* pAABBContact);
    static bool closestExpansionCoreTriVsLS_CaseFlat(const MtTriangle& tri, const MtLineSegment& ls, const MtVector3& triNormal, f32& dist0, f32& dist1, MtContact* pTriangleContact, f32* pLine_t, bool FlgAntiZeroNormalEnable);
    static bool closestExpansionCoreTriVsLS_CaseHit(const MtTriangle& tri, const MtLineSegment& ls, const MtVector3& triNormal, f32& dist0, f32& dist1, MtContact* pTriangleContact, f32* pLine_t, bool FlgAntiZeroNormalEnable);
    static bool closestExpansionCoreTriVsLS_CaseDefault(const MtTriangle& tri, const MtLineSegment& ls, const MtVector3& triNormal, f32& dist0, f32& dist1, MtContact* pTriangleContact, f32* pLine_t, bool FlgAntiZeroNormalEnable);
public:
    static bool closest(const MtCylinder& cylinder, const MtVector3& pos, MtContact* pCylinderContact);
    static bool closest(const MtCylinder& cylinder, const MtVector3& pos, MtContact& CylinderContact);
    static bool closest(const MtCylinder& cylinder, const MtLine& line, MtContact* pCylinderContact, f32* pLine_t);
    static bool closest(const MtCylinder& cylinder, const MtRay& ray, MtContact* pCylinderContact, f32* pRay_t);
    static bool closest(const MtCylinder& cylinder, const MtLineSegment& ls, MtContact* pCylinderContact, f32* pLS_t);
    static bool closest(const MtCylinder& cylinder, const MtSphere& sphere, MtContact* pCylinderContact, MtContact* pSphereContact);
    static bool closest(const MtCylinder& cylinder1, const MtCylinder& cylinder2, MtContact* cylinder_closest1, MtContact* cylinder_closest2);
    static bool closest(const MtCylinder& cylinder, const MtCapsule& capsule, MtContact* pCylinderContact, MtContact* pCapsuleContact);
    static bool closest(const MtCylinder& cylinder, const MtAABB& aabb, MtContact* pCylinderContact, MtContact* pAABBContact);
    static bool closest(const MtCylinder& cylinder, const MtOBB& obb, MtContact* pCylinderContact, MtContact* pOBBContact);
    static bool closest(const MtCylinder& cylinder, const MtTriangle& triangle, MtContact* cylinder_closest, MtContact* triangle_closest);
    static bool closest(const MtRect3D_XZ&, const MtLineSegment&, MtContact*, f32*);
    static bool closest(const MtRect3D&, const MtLineSegment&, MtContact*, f32*);
    static bool closest(const MtCollisionUtil::MtRect3DC&, const MtLineSegment&, MtContact*, f32*);
    static bool closestXZ(const MtVector3&, const MtCapsule&, MtContact*);
    static bool closestXZ(const MtVector3&, const MtSphere&, MtContact*);
    static bool closestXZ(const MtVector3&, const MtAABB&, MtContact*);
    static bool closestXZ(const MtVector3&, const MtOBB&, MtContact*);
    static bool closestXZ(const MtSphere& sphere, const MtVector3& pos, MtContact* pSphereContact);
    static bool closestXZ(const MtSphere& s0, const MtSphere& s1, MtContact* pSphere0Contact, MtContact* pSphere1Contact);
    static bool closestXZ(const MtSphere& sphere, const MtCapsule& capsule, MtContact* pSphereContact, MtContact* pCapsuleContact);
    static bool closestXZ(const MtSphere& sphere, const MtAABB& aabb, MtContact* pSphereContact, MtContact* pAABBContact);
    static bool closestXZ(const MtSphere& sphere, const MtOBB& obb, MtContact* pSphereContact, MtContact* pOBBContact);
    static bool closestXZ(const MtCapsule& capsule, const MtVector3& pos, MtContact* pCapsuleContact);
    static bool closestXZ(const MtCapsule& capsule, const MtSphere& sphere, MtContact* pCapsuleContact, MtContact* pSphereContact);
    static bool closestXZ(const MtCapsule& c0, const MtCapsule& c1, MtContact* pCapsule0Contact, MtContact* pCapsule1Contact);
    static bool closestXZ(const MtCapsule& capsule, const MtAABB& aabb, MtContact* pCapsuleContact, MtContact* pAABBContact);
    static bool closestXZ(const MtCapsule& capsule, const MtOBB& obb, MtContact* pCapsuleContact, MtContact* pOBBContact);
protected:
    static MtVector3 closestXZCapsule_CreateRepairNormalXZ(const MtLineSegment& capsuleAxis, const MtVector3& capsuleAxisVec, const MtVector3& BasePos);
public:
    static bool closestXZ(const MtAABB& aabb, const MtVector3& pos, MtContact* pAABBContact);
    static bool closestXZ(const MtAABB& aabb, const MtSphere& sphere, MtContact* pAABBContact, MtContact* pSphereContact);
    static bool closestXZ(const MtAABB& aabb, const MtCapsule& capsule, MtContact* pAABBContact, MtContact* pCapsuleContact);
    static bool closestXZ(const MtOBB& obb, const MtVector3& pos, MtContact* pOBBContact);
    static bool closestXZ(const MtOBB& obb, const MtSphere& sphere, MtContact* pOBBContact, MtContact* pSphereContact);
    static bool closestXZ(const MtOBB& obb, const MtCapsule& capsule, MtContact* pOBBContact, MtContact* pCapsuleContact);
    static bool find(const MtLine& line, const MtSphere& sphere, f32* pRay_t, MtContact* pLineContact, MtContact* pSphereContact);
    static bool find(const MtLine& line, const MtCapsule& capsule, f32* pRay_t, MtContact* pLineContact, MtContact* pCapsuleContact);
    static bool find(const MtLine& line, const MtAABB& aabb, f32* pRay_t, MtContact* pLineContact, MtContact* pAABBContact);
    static bool find(const MtLine& line, const MtOBB& obb, f32* pRay_t, MtContact* pLineContact, MtContact* pOBBContact);
    static bool find(const MtLine& line, const MtPlane& plane, f32* pRay_t, MtContact* pLineContact, MtContact* pPlaneContact);
    static bool find(const MtLine& line, const MtTriangle& tri, f32* pLine_t, MtContact* pLineContact, MtContact* pTriangleContact);
    static bool find(const MtRay& ray, const MtSphere& sphere, f32* pRay_t, MtContact* pRayContact, MtContact* pSphereContact);
    static bool find(const MtRay& ray, const MtCapsule& capsule, f32* pRay_t, MtContact* pRayContact, MtContact* pCapsuleContact);
    static bool find(const MtRay& ray, const MtAABB& aabb, f32* pRay_t, MtContact* pRayContact, MtContact* pAABBContact);
    static bool find(const MtRay& ray, const MtOBB& obb, f32* pRay_t, MtContact* pRayContact, MtContact* pOBBContact);
    static bool find(const MtRay& ray, const MtPlane& plane, f32* pRay_t, MtContact* pRayContact, MtContact* pPlaneContact);
    static bool find(const MtRay& ray, const MtPlaneXZ& planeXZ, f32* pRay_t, MtContact* pRayContact, MtContact* pPlaneContact);
    static bool find(const MtRay& ray, const MtTriangle& tri, f32* pRay_t, MtContact* pRayContact, MtContact* pTriangleContact);
    static bool find(const MtRay& ray, const MtCylinder& cylinder, f32* pRay_t, MtContact* pRayContact, MtContact* pCylinderContact);
protected:
    static bool findCylinderEdge(const MtLine& line, const MtSphere& sphere, bool bMirror, f32* pRay_t, MtContact* pRayContact, MtContact* pCapsuleSphereContact);
public:
    static bool find(const MtRayY& rayY, const MtSphere& sphere, f32* pRay_t, MtContact* pRayContact, MtContact* pSphereContact);
    static bool find(const MtRayY& rayY, const MtCapsule& capsule, f32* pRay_t, MtContact* pRayContact, MtContact* pCapsuleContact);
    static bool find(const MtRayY& rayY, const MtAABB& aabb, f32* pRay_t, MtContact* pRayContact, MtContact* pAABBContact);
    static bool find(const MtRayY& rayY, const MtOBB& obb, f32* pRay_t, MtContact* pRayContact, MtContact* pOBBContact);
    static bool find(const MtRayY& RayY, const MtPlane& plane, f32* pRayY_t, MtContact* pRayYContact, MtContact* pPlaneContact);
    static bool find(const MtRayY& rayY, const MtPlaneXZ& planeXZ, f32* pRay_t, MtContact* pRayContact, MtContact* pPlaneContact);
    static bool find(const MtRayY& RayY, const MtTriangle& tri, f32* pRayY_t, MtContact* pRayYContact, MtContact* pTriangleContact);
    static bool find(const MtRayY& rayY, const MtCylinder& cylinder, f32* pRay_t, MtContact* pRayContact, MtContact* pCylinderContact);
private:
    static bool findCylinderEdge(const MtRayY& rayY, const MtSphere& sphere, bool bMirror, f32* pRay_t, MtContact* pRayContact, MtContact* pCapsuleSphereContact);
    static f32 sqrDiststanceForInside(const MtRayY& rayY, const MtVector3& pos, f32& t);
    static f32 sqrDiststanceForInside(const MtRayY& rayY, const MtLine& line);
    static f32 sqrDiststanceForInside(const MtRayY& rayY, const MtLineSegment& ls, f32* pLS_t, f32* pLine_t);
public:
    static bool find(const MtLineSegment& ls, const MtSphere& sphere, f32* pLine_t, MtContact* pLSContact, MtContact* pSphereContact);
    static bool find(const MtLineSegment& ls, const MtCapsule& capsule, f32* pLine_t, MtContact* pLSContact, MtContact* pCapsuleContact);
    static bool find(const MtLineSegment& line, const MtAABB& aabb, f32* pLine_t, MtContact* pLSContact, MtContact* pAABBContact);
    static bool find(const MtLineSegment& line, const MtOBB& obb, f32* pLine_t, MtContact* pLSContact, MtContact* pOBBContact);
    static bool find(const MtLineSegment& ls, const MtPlane& plane, f32* pLS_t, MtContact* pLSContact, MtContact* pPlaneContact);
    static bool find(const MtLineSegment& ls, const MtPlaneXZ& planeXZ, f32* pLS_t, MtContact* pLSContact, MtContact* pPlaneContact);
    static bool find(const MtLineSegment& line, const MtTriangle& tri, f32* pLine_t, MtContact* pLSContact, MtContact* pTriangleContact);
    static bool find(const MtLineSegment& ls, const MtCylinder& cylinder, f32* pLS_t, MtContact* pLSContact, MtContact* pCylinderContact);
    static bool findCore(const MtLineSegment&, const MtTriangle&, MtContact&, bool, bool);
    static bool findCore(const MtLineSegment& ls, const MtTriangle& tri, const MtVector3& triNormal, MtContact& contact, bool FlgEnableFlatCheck, bool FlgEnableFrontCheck);
    static bool find(const MtLineSegment&, const MtRect3D_XZ&, f32*, MtContact*, bool);
    static bool find(const MtLineSegment&, const MtRect3D&, f32*, MtContact*, bool);
    static bool find(const MtLineSegment&, const MtCollisionUtil::MtRect3DC&, f32*, MtContact*, bool);
    static bool findCore(const MtLineSegment& ls, const MtRect3D_XZ& rect3dXZ, f32& t, MtContact& contact, bool FlgBackCulling);
    static bool findCore(const MtLineSegment&, const MtRect3D&, f32&, MtContact&, bool);
    static bool findCore(const MtLineSegment& ls, const MtCollisionUtil::MtRect3DC& rect3D, f32& t, MtContact& contact, bool FlgBackCulling);
    static bool find(const MtAABB& aabb, const MtLineSegment& ls, const MtVector3& v0, f32* pAABB_t, MtContact* pAABBContact, f32* pLsToi);
    static bool find(const MtAABB& aabb, const MtSphere& sphere, const MtVector3& v0, f32* pAABB0_t, MtContact* pAABBContact, MtContact* pSphereContact);
    static bool find(const MtAABB& aabb, const MtCapsule& capsule, const MtVector3& v0, f32* pAABB_t, MtContact* pAABBContact, MtContact* pCapsuleContact);
    static bool find(const MtAABB& aabb0, const MtAABB& aabb01, const MtVector3& v0, f32* pAABB0_t, MtContact* pAABB0Contact, MtContact* pAABB1Contact);
    static bool find(const MtAABB& aabb, const MtOBB& obb, const MtVector3& v0, f32* pAABB_t, MtContact* pAABBContact, MtContact* pOBBContact);
    static bool find(const MtAABB& aabb, const MtPlane& plane, const MtVector3& v0, f32* pAABB_t, MtContact* pAABBContact, MtContact* pPlaneContact);
    static bool find(const MtAABB& aabb, const MtPlaneXZ& planeXZ, const MtVector3& v0, f32* pAABB_t, MtContact* pAABBContact, MtContact* pPlaneContact);
    static bool find(const MtAABB& aabb, const MtTriangle& tri, const MtVector3& v0, f32* pAABB_t, MtContact* pAABBContact, MtContact* pTriangleContact, f32 epsilon, f32 GjkSolverEpsilon);
    static bool find(const MtSphere& sphere, const MtLineSegment& ls, const MtVector3& v0, f32* pSphere_t, MtContact* pSphereContact, f32* pLsToi);
    static bool find(const MtSphere& s0, const MtSphere& s1, const MtVector3& v0, f32* pSphere_t, MtContact* pSphere0Contact, MtContact* pSphere1Contact);
    static bool find(const MtSphere& sphere, const MtCapsule& capsule, const MtVector3& v0, f32* pSphere_t, MtContact* pSphereContact, MtContact* pCapsuleContact);
    static bool find(const MtSphere& sphere, const MtAABB& aabb, const MtVector3& v0, f32* pSphere_t, MtContact* pSphereContact, MtContact* pAABBContact);
    static bool find(const MtSphere& sphere, const MtOBB& obb, const MtVector3& v0, f32* pSphere_t, MtContact* pSphereContact, MtContact* pOBBContact);
    static bool find(const MtSphere& sphere, const MtPlane& plane, const MtVector3& v0, f32* pSphere_t, MtContact* pSphereContact, MtContact* pPlaneContact);
    static bool find(const MtSphere& sphere, const MtPlaneXZ& planeXZ, const MtVector3& v0, f32* pSphere_t, MtContact* pSphereContact, MtContact* pPlaneContact);
    static bool find(const MtSphere& sphere, const MtTriangle& tri, const MtVector3& v0, f32* pSphere_t, MtContact* pSphereContact, MtContact* pTriangleContact);
    static bool find(const MtSphere& sphere, const MtTriangle& tri, const MtVector3& triNormal, const MtVector3& v0, MtContact& contact, const bool FlgEdgeEnable0, const bool FlgEdgeEnable1, const bool FlgEdgeEnable2);
    static bool findAdjustExpansion(const MtSphere& s0, const MtSphere& s1, const MtVector3& v0, MtSphere& MovedSphere, f32* pSphere_t, MtContact* pSphere0Contact, MtContact* pSphere1Contact);
    static bool find(const MtCapsule&, const MtLineSegment&, f32*, MtContact*, f32*);
    static bool find(const MtCapsule&, const MtSphere&, f32*, MtContact*, MtContact*);
    static bool find(const MtCapsule&, const MtCapsule&, f32*, MtContact*, MtContact*);
    static bool find(const MtCapsule&, const MtAABB&, f32*, MtContact*, MtContact*);
    static bool find(const MtCapsule&, const MtOBB&, f32*, MtContact*, MtContact*);
    static bool find(const MtCapsule&, const MtPlane&, f32*, MtContact*, MtContact*);
    static bool find(const MtCapsule&, const MtTriangle&, f32*, MtContact*, MtContact*);
    static bool find(const MtSphere&, const MtRect3D_XZ&, const MtVector3&, f32*, MtContact*, bool);
    static bool find(const MtSphere&, const MtRect3D&, const MtVector3&, f32*, MtContact*, bool);
    static bool find(const MtSphere&, const MtCollisionUtil::MtRect3DC&, const MtVector3&, f32*, MtContact*, bool);
    static bool findCore(const MtSphere& sphere, const MtRect3D_XZ& rect3dXZ, const MtVector3& v, MtContact& contact, u32& vid, bool FlgBackCulling);
    static bool findCore(const MtSphere& sphere, const MtRect3D& rect3D, const MtVector3& v, MtContact& contact, u32& vid, bool FlgBackCulling);
    static bool findCore(const MtSphere& sphere, const MtCollisionUtil::MtRect3DC& rect3D, const MtVector3& v, MtContact& contact, u32& vid, bool FlgBackCulling);
    static bool find(const MtCapsule& capsule, const MtSphere& Sphere, const MtVector3& v0, f32* pCap_t, MtContact* pCapsuleContact, MtContact* pSphereContact);
    static bool find(const MtCapsule& capsule, const MtAABB& AABB, const MtVector3& v0, f32* pCap_t, MtContact* pCapsuleContact, MtContact* pAABBContact);
    static bool find(const MtCapsule& capsule, const MtOBB& OBB, const MtVector3& v0, f32* pCap_t, MtContact* pCapsuleContact, MtContact* pOBBContact);
    static bool find(const MtCapsule& capsule, const MtCapsule& Capsule, const MtVector3& v0, f32* pCap0_t, MtContact* pCapsule0Contact, MtContact* pCapsule1Contact);
    static bool find(const MtCapsule& capsule, const MtTriangle& Triangle, const MtVector3& v0, f32* pCap_t, MtContact* pCapsuleContact, MtContact* pTriangleContact);
    static bool find(const MtCapsule&, const MtRect3D_XZ&, const MtVector3&, f32*, MtContact*, bool);
    static bool find(const MtCapsule&, const MtRect3D&, const MtVector3&, f32*, MtContact*, bool);
    static bool find(const MtCapsule&, const MtCollisionUtil::MtRect3DC&, const MtVector3&, f32*, MtContact*, bool);
    static bool findCore(const MtCapsule& capsule, const MtRect3D_XZ& rect3dXZ, const MtVector3& v, MtContact& contact, u32& vid, bool FlgBackCulling);
    static bool findCore(const MtCapsule& capsule, const MtRect3D& rect3D, const MtVector3& v, MtContact& contact, u32& vid, bool FlgBackCulling);
    static bool findCore(const MtCapsule& capsule, const MtCollisionUtil::MtRect3DC& rect3D, const MtVector3& v, MtContact& contact, u32& vid, bool FlgBackCulling);
    static bool contact(const MtSphere& s0, const MtSphere& s1, const MtVector3& v0, const MtVector3& v1, f32* t, MtContact* pSphere0Contact, MtContact* pSphere1Contact);
    static bool contact(const MtSphere& sphere, const MtAABB& aabb, const MtVector3& v0, const MtVector3& v1, f32* t, MtContact* pSphereContact, MtContact* pAABBContact);
    static bool contact(const MtSphere& sphere, const MtOBB& obb, const MtVector3& v0, const MtVector3& v1, f32* t, MtContact* pSphereContact, MtContact* pOBBContact);
    static bool contact(const MtSphere& sphere, const MtCapsule& capsule, const MtVector3& v0, const MtVector3& v1, f32* t, MtContact* pSphereContact, MtContact* pCapsuleContact);
    static bool contact(const MtSphere& sphere, const MtTriangle& tri, const MtVector3& v0, const MtVector3& v1, f32* t, MtContact* pSphereContact, MtContact* pTriangleContact);
    static bool contact(const MtCapsule& capsule, const MtSphere& sphere, const MtVector3& v0, const MtVector3& v1, f32* t, MtContact* pCapsuleContact, MtContact* pSphereContact);
    static bool contact(const MtCapsule& capsule, const MtAABB& aabb, const MtVector3& v0, const MtVector3& v1, f32* t, MtContact* pCapsuleContact, MtContact* pAABBContact);
    static bool contact(const MtCapsule& capsule, const MtOBB& obb, const MtVector3& v0, const MtVector3& v1, f32* t, MtContact* pCapsuleContact, MtContact* pOBBContact);
    static bool contact(const MtCapsule& capsule0, const MtCapsule& capsule1, const MtVector3& v0, const MtVector3& v1, f32* t, MtContact* pCapsule0Contact, MtContact* pCapsule1Contact);
    static bool contact(const MtCapsule& capsule, const MtTriangle& tri, const MtVector3& v0, const MtVector3& v1, f32* t, MtContact* pCapsuleContact, MtContact* pTriangleContact);
    static MtCollisionUtil::MtVectorU4 intersect(const MtSphere& sphere, const MtCollisionUtil::MtSoaVector3& pos4);
    static MtCollisionUtil::MtVectorU4 intersect(const MtAABB&, const MtAABB4&);
    static MtCollisionUtil::MtVectorU4 intersect(const MtAABB4&, const MtAABB4&);
    static MtCollisionUtil::MtVectorU4 intersect(const MtLineSegment&, const MtAABB4&);
    static MtCollisionUtil::MtSoaVector1 sqrDistance4(const MtLine4& line4, const MtVector3& pos, MtCollisionUtil::MtSoaVector1& Line_t);
    static MtCollisionUtil::MtSoaVector1 sqrDistance4(const MtLine4& line4, const MtCollisionUtil::MtSoaVector3& pos4, MtCollisionUtil::MtSoaVector1& Line_t);
    static MtCollisionUtil::MtSoaVector1 distance4(const MtCollisionUtil::MtSoaVector3& pos4, const MtPlane4& plane4);
    static MtCollisionUtil::MtSoaVector1 distance4(const MtVector3& pos, const MtPlane4& plane4);
    static MtCollisionUtil::MtVectorU4 find4(const MtRay& ray, const MtVector3* PlaneNormals, const MtVector4& PlaneDistance4, MtVector4& toi4);
    static MtCollisionUtil::MtVectorU4 find4(const MtLineSegment& ls, const MtVector3& dir, const MtTriangle4& tri4, MtCollisionUtil::MtSoaVector3& hitPos4, MtCollisionUtil::MtSoaVector1& toi4);
    static MtCollisionUtil::MtVectorU4 find4(const MtLineSegment4& ls4, const MtTriangle4& tri4, MtCollisionUtil::MtSoaVector3& hitPos4, MtCollisionUtil::MtSoaVector1& toi4);
    static MtCollisionUtil::MtVectorU4 find4(const MtLineSegment4& ls4, const MtSphere& sphere, MtCollisionUtil::MtSoaVector3& hpos_out, MtCollisionUtil::MtSoaVector1& toi_out);
    static MtCollisionUtil::MtVectorU4 find4(const MtLineSegment4& ls4, const MtCapsule& capsule, MtCollisionUtil::MtSoaVector3& hpos_out, MtCollisionUtil::MtSoaVector1& toi_out);
    static MtCollisionUtil::MtVectorU4 find4(const MtLineSegment4& ls4, const MtAABB& aabb, MtCollisionUtil::MtSoaVector3& hpos_out, MtCollisionUtil::MtSoaVector1& toi_out);
    static MtCollisionUtil::MtVectorU4 find4(const MtLineSegment4& ls4, const MtOBB& obb, MtCollisionUtil::MtSoaVector3& hpos_out, MtCollisionUtil::MtSoaVector1& toi_out);
    static MtCollisionUtil::MtVectorU4 find4(const MtLineSegment4& ls4, const MtPlane& plane, MtCollisionUtil::MtSoaVector3& hitPos4, MtCollisionUtil::MtSoaVector1& toi4);
    static MtCollisionUtil::MtVectorU4 find4(const MtLineSegment4& ls4, const MtTriangle& tri, MtCollisionUtil::MtSoaVector3& hpos_out, MtCollisionUtil::MtSoaVector1& toi_out);
    static MtCollisionUtil::MtVectorU4 find4(const MtLineSegment4& ls4, const MtTriangle& tri, const MtCollisionUtil::MtSoaVector3& LsDir4, const MtCollisionUtil::MtSoaVector3& LsDir4N, const MtCollisionUtil::MtSoaVector1& LsDirLen4, MtCollisionUtil::MtSoaVector3& hpos_out, MtCollisionUtil::MtSoaVector1& toi_out);
    static bool intersect(const MtAABBCompress& aabb0, const MtAABBCompress& aabb1);
    static MtCollisionUtil::MtVectorU4 intersect(const MtAABBCompress& aabb, const MtAABB4Compress& aabb4);
    static bool intersect2D(const MtVector2&, const MtAABB2D&);
    static bool intersect2D(const MtVector2& pos, const MtTriangle2D& tri);
    static bool intersect2D(const MtAABB2D&, const MtAABB2D&);
    static f32 getLineRatio(const MtLineSegment& ls, const MtVector3& pos);
    static f32 getLineRatio(const MtSegment& segment, const MtVector3& vertex);
    static f32 getLineRatio(const MtRay& ray, const MtVector3& pos);
    static MtVector3 getLineRatioBq(const MtRay&, const MtVector3&);
    static bool find(const MtLine& line, const MtPlane& plane, const MtVector3& CircleCenter, const f32 CircleRadius);
    static bool find(const MtLine& line, const MtPlane& plane, const MtVector3& CircleCenter, const f32 CircleRadius, MtVector3& HitPosOut);
    static bool find(const MtLine& line, const MtPlane& plane, const MtVector3& CircleCenter, const f32 CircleRadius, f32& t, MtVector3& HitPosOut);
    static bool find(const MtRay& ray, const MtPlane& plane, const MtVector3& CircleCenter, const f32 CircleRadius);
    static bool find(const MtRay& ray, const MtPlane& plane, const MtVector3& CircleCenter, const f32 CircleRadius, MtVector3& HitPosOut);
    static bool find(const MtRay& ray, const MtPlane& plane, const MtVector3& CircleCenter, const f32 CircleRadius, f32& t, MtVector3& HitPosOut);
    static bool find(const MtLineSegment& ls, const MtPlane& plane, const MtVector3& CircleCenter, const f32 CircleRadius);
    static bool find(const MtLineSegment& ls, const MtPlane& plane, const MtVector3& CircleCenter, const f32 CircleRadius, MtVector3& HitPosOut);
    static bool find(const MtLineSegment& ls, const MtPlane& plane, const MtVector3& CircleCenter, const f32 CircleRadius, f32& t, MtVector3& HitPosOut, const f32 epsilon);
    static u32 getRect3dXZVoronoiID(const MtRect3D_XZ& rect3dXZ, const MtVector3& pos);
    static u32 getRect3DVoronoiID(const MtCollisionUtil::MtRect3DC& rect3D, const MtVector3& pos);
    static u32 clipObbByPlane(const MtOBB& obb, const MtPlane& plane, MtLineSegment* OutputEdge);
    static bool getCrossLine(const MtPlane& plane0, const MtPlane& plane1, MtLine& line);
    static bool getCrossLS(const MtTriangle& tri0, const MtTriangle& tri1, MtLineSegment& ls);
    static bool clipLineSegmentByPlane(const MtPlane& ClipPlane, const MtVector3* InputVertexArray, u32 InputVertexNum, MtVector3* OutputVertexArray, f32* OutputDepthArray, u32& OutputVertexNum);
    static void safeClosest(MtTriangle& tri, MtVector3& pos, MtContact& contact);
    static void safeClosest(MtTriangle& tri, MtLineSegment& ls, MtVector3& nposTri, MtVector3& nposLS, f32& NearestT);
    static bool safeClosest(MtTriangle& tri0, MtTriangle& tri1, MtContact* pContact0, MtContact* pContact1);
    static bool isBackFaceCullingTarget(const MtVector3& TargetPlaneNormal, const MtVector3& DirectionNormalized);
    static bool isFlatFaceCullingTarget(const MtVector3& TargetPlaneNormal, const MtVector3& DirectionNormalized);
    static u32 closestSeparateAxis(f32 MinA, f32 MaxA, f32 MinB, f32 MaxB, f32& depth, bool& FlgHitPlusDirection);
    static u32 getCoGId(const MtTriangle& tri, const MtVector3& pos, f32* pu, f32* pv, f32* pw);
    static u32 getCoGIdFast(const MtTriangle& tri, const MtVector3& pos);
    static u32 getCoGIdFast(const MtVector3& triPt0, const MtVector3& triPt1, const MtVector3& triPt2, const MtVector3& pos);
    static void getCoGId2(MtCollisionUtil::MtVectorU4& ret, const MtTriangle& tri, const MtVector3& pos0, const MtVector3& pos1);
    static void getCoGId3(MtCollisionUtil::MtVectorU4& ret, const MtTriangle& tri, const MtVector3& pos0, const MtVector3& pos1, const MtVector3& pos2);
    static void getCoGId4(MtCollisionUtil::MtVectorU4& ret, const MtTriangle& tri, const MtVector3& pos0, const MtVector3& pos1, const MtVector3& pos2, const MtVector3& pos3);
    static MtCollisionUtil::MtVectorU4 getCoGIdMultiple(const MtTriangle& tri, const MtVector3& pos0, const MtVector3& pos1, const MtVector3& pos2, const MtVector3& pos3, MtVector3* pOutputUVW);
protected:
    static f32 getCoGId_TriangleDenom(const MtTriangle&);
public:
    static u32 getVoronoiId(const MtAABB& aabb, const MtVector3& pos);
    static f32 getMinimumDistSq(const MtAABB& aabb, const MtLineSegment& ls, MtCollisionUtil::AABB_VORONOI_ID voronoi, f32* pLine_t);
    static f32 getMinimumDistSq(const MtAABB& aabb, const MtLine& line, MtCollisionUtil::AABB_VORONOI_ID voronoi, f32* pLine_t);
    static f32 getMinimumDistSq(const MtAABB& aabb, const MtRay& ray, MtCollisionUtil::AABB_VORONOI_ID voronoi, f32* pLine_t);
    static void getMinimumDistSqEdgeFlags(MtCollisionUtil::AABB_VORONOI_ID voronoi, bool* edge);
    static bool getMinimumDistSqEdge(const MtAABB& aabb, MtLineSegment& edge_ls, bool* edge, u32 index);
    static bool getAABBSurfaceRect(MtVector3& p0, MtVector3& p1, MtVector3& p2, MtVector3& p3, const MtAABB& aabb, u32 VoronoiID);
    static bool getAABBSurfaceTriangle(MtTriangle& tri0, MtTriangle& tri1, const MtAABB& aabb, u32 VoronoiID);
    static bool getAABBEdge(MtLineSegment& edge, const MtAABB& aabb, u32 VoronoiID);
    static u32 getAABBEdgeList(MtLineSegment* edge, const MtAABB& aabb, u32 VoronoiID);
    static bool getAABBVertex(MtVector3& pos, const MtAABB& aabb, u32 VoronoiID);
public:
    static const u32 AXIS_X = 0;
    static const u32 AXIS_Y = 1;
    static const u32 AXIS_Z = 2;
    static const u32 AXIS_W = 3;
    static const u32 AXIS_NUM = 4;
    static const f32 FINDCORE_CAPSULE_EPSILON;
    static const u32 FINDCORE_CAPSULE_ITERATION;
};

struct MtContact
{
public:
    MtContact();
    void initialize(const MtVector3& _pos, const MtVector3& _normal, f32 _distance, f32 _toi, bool _bFind);
    void initialize(const MtContact& src);
public:
    MtVector3 pos;  // offset: 0x0
    MtVector3 normal;  // offset: 0x10
    f32 distance;  // offset: 0x20
    f32 toi;  // offset: 0x24
    bool bFind;  // offset: 0x28
};
