// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include <string.h>
#include "MtFile.h"
#include "MtAllocator.h"
#include "MtDTI.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#include "MtString.h"
#include "MtSynchronize.h"
#include "MtTime.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* MtFile::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void MtFile::usage();

// Address: 0x01b4ecc0 - 0x01b4ecc8 (8 bytes)
const MtDTI& MtFile::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return MtFile::DTI;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtAllocator* MtFile::getAllocator();

// No out-of-line body: no code in the ELF
// void MtFile::setAllocator(u32);

// Address: 0x00dc3da0 - 0x00dc3de0 (64 bytes)
void* MtFile::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::MtMemoryAllocator::getAllocator(::MtFile::DTI)->memAlloc(sz, align, ::MtFile::DTI.::MtDTI::mID);
}

// Address: 0x00dc3df0 - 0x00dc3e30 (64 bytes)
void* MtFile::operator new[](size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::MtMemoryAllocator::getAllocator(::MtFile::DTI)->memAlloc(sz, align, ::MtFile::DTI.::MtDTI::mID);
}

// No out-of-line body: no code in the ELF
// void* MtFile::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* MtFile::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN6MtFileD0Ev at 0x00dc54bc-0x00dc54dd, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void MtFile::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::MtFile::DTI)->memFree(p_addr);
}

// Address: 0x00dc3e60 - 0x00dc3e8a (42 bytes)
void MtFile::operator delete[](void* p_addr) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    ::MtMemoryAllocator::getAllocator(::MtFile::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void MtFile::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void MtFile::operator delete[](void* p_addr, u32 align);

// Address: 0x00dc4470 - 0x00dc4ae0 (1648 bytes)
__attribute__((weak)) bool MtFile::findFile(MtFile::FileInfo& info, MT_CTSTR start) {
    // local: MT_CHAR path[1024];
    // local: s32 ret;
    // local: SceKernelStat status;
    // local: SceKernelDirent* dir;
    // local: MT_CHAR path[1024];
    // local: MT_STR ptr;
    // local: SceKernelStat d_status;
    // local: RealPath RPath;
    // local: SceKernelStat status;
    // local: MT_STR name;
    DDON_STUB("MtFile::findFile")
    return {};
}

// Address: 0x00dc3fd0 - 0x00dc4037 (103 bytes)
__attribute__((weak)) bool MtFile::createDirectory(MT_CTSTR path) {
    // local: s32 ret;
    DDON_STUB("MtFile::createDirectory")
    return {};
}

// Address: 0x00dc3eb0 - 0x00dc3fc6 (278 bytes)
__attribute__((weak)) bool MtFile::createDirectoryEx(MT_CTSTR dpath) {
    // local: MT_CHAR path[512];
    // local: bool cd;
    // local: MtFilePath fpath;
    // local: s32 len;
    DDON_STUB("MtFile::createDirectoryEx")
    return {};
}

// Address: 0x00dc4040 - 0x00dc40a2 (98 bytes)
__attribute__((weak)) bool MtFile::removeDirectory(MT_CTSTR path) {
    // local: s32 ret;
    DDON_STUB("MtFile::removeDirectory")
    return {};
}

// Address: 0x00dc40b0 - 0x00dc43ff (847 bytes)
__attribute__((weak)) bool MtFile::removeDirectoryEx(MT_CTSTR path) {
    // local: MT_CHAR spath[1024];
    // local: FileInfo info;
    // local: bool err;
    // local: MT_CTSTR name;
    DDON_STUB("MtFile::removeDirectoryEx")
    return {};
}

// Address: 0x00dc4b50 - 0x00dc4cde (398 bytes)
__attribute__((weak)) bool MtFile::move(MT_CTSTR srcpath, MT_CTSTR dstpath) {
    // local: s32 ret;
    DDON_STUB("MtFile::move")
    return {};
}

// Address: 0x00dc4d80 - 0x00dc5193 (1043 bytes)
__attribute__((weak)) bool MtFile::copy(MT_CTSTR src, MT_CTSTR dst) {
    // local: MtFile srcfile;
    // local: MtFile dstfile;
    // local: u8* buf;
    // local: u32 len;
    // local: u32 readsize;
    // local: u32 writesize;
    DDON_STUB("MtFile::copy")
    return {};
}

// Address: 0x00dc4ae0 - 0x00dc4b42 (98 bytes)
__attribute__((weak)) bool MtFile::remove(MT_CTSTR path) {
    // local: s32 ret;
    DDON_STUB("MtFile::remove")
    return {};
}

// No out-of-line body: no code in the ELF
// bool MtFile::rename(MT_CTSTR srcpath, MT_CTSTR dstpath);

// No out-of-line body: no code in the ELF
// bool MtFile::isReadonly(MT_CTSTR path);

// Address: 0x00dc4400 - 0x00dc4462 (98 bytes)
__attribute__((weak)) bool MtFile::isExist(MT_CTSTR path) {
    // local: s32 ret;
    DDON_STUB("MtFile::isExist")
    return {};
}

// Address: 0x00dc51b0 - 0x00dc51b8 (8 bytes)
MT_CTSTR MtFile::getCurrentPath() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::MtFile::mCurrentPath;
}

// Address: 0x00dc51c0 - 0x00dc51d2 (18 bytes)
void MtFile::setCurrentPath(MT_CTSTR path) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    ::strcpy(::MtFile::mCurrentPath, path);
}

// No out-of-line body: no code in the ELF
// MT_CTSTR MtFile::getCachePath();

// Address: 0x00dc5b40 - 0x00dc5b52 (18 bytes)
void MtFile::setCachePath(MT_CTSTR path) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    ::strcpy(::MtFile::mCachePath, path);
}

// No out-of-line body: no code in the ELF
// bool MtFile::setTime(MT_CTSTR path, u32 mode, MtTime time);

// No out-of-line body: no code in the ELF
// u32 MtFile::getCRC(MT_CTSTR path);

// Address: 0x00dc5360 - 0x00dc53c8 (104 bytes)
MtFile::MtFile(MT_CTSTR path, MtFile::MODE mode) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mHandle = static_cast<FILE_HANDLE>(-1);
    this->mMode = static_cast<MtFile::MODE>(16);
    this->mPath[0] = static_cast<char>(0);
    this->mSeekPt = static_cast<u32>(0);
    this->mSize = static_cast<u32>(0);
    this->mDLCHandle = static_cast<MtFile::DLC_HANDLE>(4294967295);
    this->mAsyncExec = false;
    if (path != static_cast<MT_CTSTR>(nullptr)) {
        this->::MtFile::open(path, mode, false);
    }
    this->mLastErrorCode = static_cast<MtFile::FileError>(0);
}

// Address: 0x00dc53d0 - 0x00dc5443 (115 bytes)
// Also emitted as: _ZN6MtFileD0Ev at 0x00dc5450
MtFile::~MtFile() {
    DDON_STUB("MtFile::~MtFile")
    /* stub */
}

// Address: 0x00dc55d0 - 0x00dc5706 (310 bytes)
__attribute__((weak)) bool MtFile::open(MT_CTSTR path, MtFile::MODE mode, bool interrupt) {
    // local: RealPath realpath;
    // local: s32 ret;
    // local: SceKernelStat status;
    // local: s32 openflags;
    DDON_STUB("MtFile::open")
    return {};
}

// No out-of-line body: no code in the ELF
// bool MtFile::open(MtFile::MODE);

// Address: 0x00dc57f0 - 0x00dc5855 (101 bytes)
__attribute__((weak)) void MtFile::close() {
    // local: s32 ret;
    DDON_STUB("MtFile::close")
    /* stub */
}

// Address: 0x00dc5270 - 0x00dc535f (239 bytes)
__attribute__((weak)) u32 MtFile::read(void* out, u32 bytes) {
    // local: ssize_t ret;
    // local: u64 readbytes;
    // local: ssize_t ret;
    DDON_STUB("MtFile::read")
    return {};
}

// Address: 0x00dc58f0 - 0x00dc5a2c (316 bytes)
__attribute__((weak)) u32 MtFile::readAsync(void* out, u32 bytes) {
    // local: u32 over;
    DDON_STUB("MtFile::readAsync")
    return {};
}

// Address: 0x00dc5860 - 0x00dc58af (79 bytes)
__attribute__((weak)) void MtFile::readWait() {
    DDON_STUB("MtFile::readWait")
    /* stub */
}

// Address: 0x00dc58c0 - 0x00dc58c7 (7 bytes)
bool MtFile::isAsyncReading() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mAsyncExec;
}

// Address: 0x00dc5710 - 0x00dc5769 (89 bytes)
__attribute__((weak)) u32 MtFile::write(const void* in, u32 bytes) {
    // local: ssize_t writebytes;
    DDON_STUB("MtFile::write")
    return {};
}

// Address: 0x00dc5a30 - 0x00dc5ac5 (149 bytes)
__attribute__((weak)) u32 MtFile::seek(s32 offset, MtFile::SEEKBASE base) {
    // local: ssize_t pos;
    DDON_STUB("MtFile::seek")
    return {};
}

// Address: 0x00dc5ad0 - 0x00dc5ad4 (4 bytes)
u32 MtFile::getPosition() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mSeekPt;
}

// Address: 0x00dc5200 - 0x00dc5261 (97 bytes)
__attribute__((weak)) u32 MtFile::length() {
    // local: SceKernelStat status;
    // local: s32 ret;
    DDON_STUB("MtFile::length")
    return {};
}

// Address: 0x00dc5780 - 0x00dc57a9 (41 bytes)
__attribute__((weak)) void MtFile::setLength(u32 len) {
    // local: s32 ret;
    DDON_STUB("MtFile::setLength")
    /* stub */
}

// Address: 0x00dc51f0 - 0x00dc51ff (15 bytes)
bool MtFile::isReadable() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->isReadableMode(this->mMode);
}

// Address: 0x00dc5af0 - 0x00dc5aff (15 bytes)
bool MtFile::isWritable() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->isWritableMode(this->mMode);
}

// Address: 0x00dc5ae0 - 0x00dc5aef (15 bytes)
bool MtFile::isAsyncReadable() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->isAsyncReadableMode(this->mMode);
}

// No out-of-line body: no code in the ELF
// MtTime MtFile::getTime(MtFile::TIME mode);

// No out-of-line body: no code in the ELF
// bool MtFile::setTime(MtFile::TIME mode, MtTime time);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MT_CTSTR MtFile::getPath();

// No out-of-line body: no code in the ELF
// void MtFile::setPath(MT_CTSTR szPath);

// Address: 0x00dc4ce0 - 0x00dc4d71 (145 bytes)
__attribute__((weak)) u32 MtFile::getDriveType(MT_CTSTR path) {
    // local: DRIVETYPE type;
    // local: u32 offset;
    // local: u32 src_offset;
    DDON_STUB("MtFile::getDriveType")
    return {};
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void MtFile::getDriveType(MT_CTSTR path, MtFile::DRIVETYPE& dst_dtype, u32& dst_prefixoffset, MT_STR dest_nativemountprefix);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void MtFile::setDriveTypeFunction(MtFile::PATH_DRIVETYPE_FUNC pFunc);

// No out-of-line body: no code in the ELF
// MtFile::FileError MtFile::getLastErrorCode() const;

// No out-of-line body: no code in the ELF
// MtFile::FileError MtFile::getLastError();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void MtFile::setLastErrorCode(MtFile::FileError error);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void MtFile::setLastError(MtFile::FileError error);

// Address: 0x00dc54e0 - 0x00dc55c6 (230 bytes)
__attribute__((weak)) bool MtFile::checkAcceptableName(MT_CTSTR filename, MT_CTSTR findName) {
    // local: MT_STR find;
    // local: MT_STR name;
    DDON_STUB("MtFile::checkAcceptableName")
    return {};
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// bool MtFile::startReadAsync();

// Address: 0x01b4ecd0 - 0x01b4ecd7 (7 bytes)
u32 MtFile::getAsyncTransferredSize() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mAsyncTransferredSize;
}

// Address: 0x00dc57b0 - 0x00dc57c5 (21 bytes)
__attribute__((weak)) bool MtFile::isReadableMode(MtFile::MODE mode) {
    DDON_STUB("MtFile::isReadableMode")
    return {};
}

// Address: 0x00dc57d0 - 0x00dc57da (10 bytes)
__attribute__((weak)) bool MtFile::isWritableMode(MtFile::MODE mode) {
    DDON_STUB("MtFile::isWritableMode")
    return {};
}

// Address: 0x00dc57e0 - 0x00dc57e7 (7 bytes)
bool MtFile::isAsyncReadableMode(MtFile::MODE mode) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return mode == static_cast<MtFile::MODE>(18);
}

// No out-of-line body: no code in the ELF
// void MtFile::setDLCisExistFunction(MtFile::DLC_ISEXIST_FUNC);

// No out-of-line body: no code in the ELF
// void MtFile::setDLCopenFunction(MtFile::DLC_OPEN_FUNC);

// No out-of-line body: no code in the ELF
// void MtFile::setDLCgetSizeFunction(MtFile::DLC_GET_SIZE_FUNC);

// No out-of-line body: no code in the ELF
// void MtFile::setDLCreadFunction(MtFile::DLC_READ_FUNC);

// No out-of-line body: no code in the ELF
// void MtFile::setDLCseekFunction(MtFile::DLC_SEEK_FUNC);

// No out-of-line body: no code in the ELF
// void MtFile::setDLCcloseFunction(MtFile::DLC_CLOSE_FUNC);

// No out-of-line body: no code in the ELF
// void MtFile::setDLCreadAsyncFunction(MtFile::DLC_READASYNC_FUNC);

// No out-of-line body: no code in the ELF
// void MtFile::setDLCreadWaitFunction(MtFile::DLC_READWAIT_FUNC);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// bool MtFile::isOpenedAsDLC() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtFile::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00dc3d20 - 0x00dc3d9b (123 bytes)
__attribute__((weak)) MtObject* MtFile::MyDTI::newInstance() const {
    DDON_STUB("MtFile::MyDTI::newInstance")
    return nullptr;
}

// Address: 0x00dc5b70 - 0x00dc5d37 (455 bytes)
MtFile::AsyncThreadPool::AsyncThreadPool() {
    // local: ScePthreadAttr attr;
    // local: u32 i;
    // local: Context* pctxt;
    DDON_STUB("MtFile::AsyncThreadPool::AsyncThreadPool")
    /* stub */
}

// Address: 0x00dc5dd0 - 0x00dc5e81 (177 bytes)
MtFile::AsyncThreadPool::~AsyncThreadPool() {
    // local: u32 i;
    // local: u32 i;
    // local: u32 i;
    DDON_STUB("MtFile::AsyncThreadPool::~AsyncThreadPool")
    /* stub */
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// s32 MtFile::AsyncThreadPool::requestReadAsync(MtFile* pfile);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void MtFile::AsyncThreadPool::waitReadAsync(s32 handle);

// Address: 0x00dc5d40 - 0x00dc5dcc (140 bytes)
__attribute__((weak)) void* MtFile::AsyncThreadPool::readAsyncProc(void* pArg) {
    // local: Context* pctxt;
    // local: MtFile* pFile;
    // local: void* out;
    // local: ssize_t readbytes;
    // local: u32 bytes;
    DDON_STUB("MtFile::AsyncThreadPool::readAsyncProc")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* MtFile::FileInfo::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void MtFile::FileInfo::usage();

// Address: 0x01b4ece0 - 0x01b4ece8 (8 bytes)
const MtDTI& MtFile::FileInfo::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return MtFile::FileInfo::DTI;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtAllocator* MtFile::FileInfo::getAllocator();

// No out-of-line body: no code in the ELF
// void MtFile::FileInfo::setAllocator(u32);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void* MtFile::FileInfo::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* MtFile::FileInfo::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* MtFile::FileInfo::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* MtFile::FileInfo::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN6MtFile8FileInfoD0Ev at 0x00dc360e-0x00dc362f, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void MtFile::FileInfo::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::MtFile::FileInfo::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void MtFile::FileInfo::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void MtFile::FileInfo::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void MtFile::FileInfo::operator delete[](void* p_addr, u32 align);

// Address: 0x00dc34a0 - 0x00dc34f6 (86 bytes)
MtFile::FileInfo::FileInfo() {
    DDON_STUB("MtFile::FileInfo::FileInfo")
    /* stub */
}

// Address: 0x00dc3500 - 0x00dc35f0 (240 bytes)
// Also emitted as: _ZN6MtFile8FileInfoD0Ev at 0x00dc3600
MtFile::FileInfo::~FileInfo() {
    DDON_STUB("MtFile::FileInfo::~FileInfo")
    /* stub */
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void MtFile::FileInfo::close();

// No out-of-line body: no code in the ELF
// bool MtFile::FileInfo::isDirectory() const;

// No out-of-line body: no code in the ELF
// bool MtFile::FileInfo::isReadonly() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MT_CTSTR MtFile::FileInfo::getName() const;

// Address: 0x00dc3630 - 0x00dc367f (79 bytes)
__attribute__((weak)) MT_CTSTR MtFile::FileInfo::getFileType() const {
    // local: MT_CTSTR str;
    // local: s32 p;
    // local: u32 len;
    // local: u32 i;
    DDON_STUB("MtFile::FileInfo::getFileType")
    return {};
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtTime MtFile::FileInfo::getCreation() const;

// No out-of-line body: no code in the ELF
// MtTime MtFile::FileInfo::getLastAccess() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtTime MtFile::FileInfo::getLastWrite() const;

// Address: 0x01b4ec80 - 0x01b4ec81 (1 bytes)
__attribute__((weak)) void MtFile::FileInfo::setFileType(MT_CTSTR) {
    // Empty in the binary (a single `ret`).
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// u32 MtFile::FileInfo::getAttr() const;

// No out-of-line body: no code in the ELF
// u64 MtFile::FileInfo::getSize() const;

// Address: 0x00dc3680 - 0x00dc3bcb (1355 bytes)
__attribute__((weak)) void MtFile::FileInfo::createProperty(MtPropertyList& s) {
    DDON_STUB("MtFile::FileInfo::createProperty")
    /* stub */
}

// Address: 0x00dc3bd0 - 0x00dc3bd5 (5 bytes)
MtUI* MtFile::FileInfo::createUI(MtProperty& prop) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->::MtObject::createUI(prop);
}

// No out-of-line body: no code in the ELF
// const MtFile::FileInfo& MtFile::FileInfo::operator=(const MtFile::FileInfo& lhs);

// No out-of-line body: no code in the ELF
// MtFile::FileInfo::FileError MtFile::FileInfo::getLastErrorCode() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void MtFile::FileInfo::setLastErrorCode(MtFile::FileInfo::FileError error);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtFile::FileInfo::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00dc33a0 - 0x00dc3427 (135 bytes)
__attribute__((weak)) MtObject* MtFile::FileInfo::MyDTI::newInstance() const {
    DDON_STUB("MtFile::FileInfo::MyDTI::newInstance")
    return nullptr;
}

// Address: 0x00dc3bf0 - 0x00dc3d08 (280 bytes)
MtFile::RealPath::RealPath(MT_CTSTR path) {
    // local: MT_CHAR* tmppath;
    // local: MT_CHAR* dst;
    // local: u32 offset;
    // local: DRIVETYPE dtype;
    // local: MT_CHAR* src;
    // local: MT_CTSTR pRef;
    // local: bool hasDuplicatedBackslash;
    // local: const size_t len;
    // local: size_t i;
    // local: const char c;
    // local: const char cn;
    DDON_STUB("MtFile::RealPath::RealPath")
    /* stub */
}

// No out-of-line body: no code in the ELF
// MtFile::RealPath::~RealPath();

// No out-of-line body: no code in the ELF
// MT_CTSTR MtFile::RealPath::getPath();

// No out-of-line body: no code in the ELF
// MtFile::RealPath::operator const char *() const;

// No out-of-line body: no code in the ELF
// bool MtFile::RealPath::isEnablePath() const;

