// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "nAI.h"
#include "MtDTI.h"
#include "MtObject.h"
#include "MtString.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* nAI::EnumProp::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void nAI::EnumProp::usage();

// Address: 0x01bd7320 - 0x01bd7328 (8 bytes)
const MtDTI& nAI::EnumProp::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return nAI::EnumProp::DTI;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtAllocator* nAI::EnumProp::getAllocator();

// No out-of-line body: no code in the ELF
// void nAI::EnumProp::setAllocator(u32);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void* nAI::EnumProp::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* nAI::EnumProp::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* nAI::EnumProp::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* nAI::EnumProp::operator new[](size_t sz, void* p_addr);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void nAI::EnumProp::operator delete(void* p_addr);

// No out-of-line body: no code in the ELF
// void nAI::EnumProp::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void nAI::EnumProp::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void nAI::EnumProp::operator delete[](void* p_addr, u32 align);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// nAI::EnumProp::EnumProp(s32 value);

// Address: 0x01bd7190 - 0x01bd7244 (180 bytes)
// Also emitted as: _ZN3nAI8EnumPropD0Ev at 0x01bd7250
nAI::EnumProp::~EnumProp() {
    DDON_STUB("nAI::EnumProp::~EnumProp")
    /* stub */
}

// Address: 0x01343dd0 - 0x01344031 (609 bytes)
__attribute__((weak)) void nAI::EnumProp::createProperty(MtPropertyList& s) {
    DDON_STUB("nAI::EnumProp::createProperty")
    /* stub */
}

// Address: 0x01344230 - 0x0134434e (286 bytes)
__attribute__((weak)) void nAI::EnumProp::open() {
    // local: const MtDTI* pdti;
    // local: EnumObject* pEnum;
    DDON_STUB("nAI::EnumProp::open")
    /* stub */
}

// No out-of-line body: no code in the ELF
// void nAI::EnumProp::setValue(s32);

// No out-of-line body: no code in the ELF
// u32 nAI::EnumProp::getValue() const;

// No out-of-line body: no code in the ELF
// MT_CTSTR nAI::EnumProp::getName() const;

// Address: 0x01344040 - 0x01344206 (454 bytes)
__attribute__((weak)) nAI::EnumProp& nAI::EnumProp::operator=(nAI::EnumProp& p) {
    DDON_STUB("nAI::EnumProp::operator=")
    __builtin_unreachable();
}

// No out-of-line body: no code in the ELF
// bool nAI::EnumProp::operator==(nAI::EnumProp& p);

// No out-of-line body: no code in the ELF
// bool nAI::EnumProp::operator!=(nAI::EnumProp& p);

// No out-of-line body: no code in the ELF
// s8 nAI::EnumProp::operator=(s8);

// No out-of-line body: no code in the ELF
// u8 nAI::EnumProp::operator=(u8);

// No out-of-line body: no code in the ELF
// s16 nAI::EnumProp::operator=(s16);

// No out-of-line body: no code in the ELF
// u16 nAI::EnumProp::operator=(u16);

// No out-of-line body: no code in the ELF
// s32 nAI::EnumProp::operator=(s32);

// No out-of-line body: no code in the ELF
// u32 nAI::EnumProp::operator=(u32);

// No out-of-line body: no code in the ELF
// s64 nAI::EnumProp::operator=(s64);

// No out-of-line body: no code in the ELF
// u64 nAI::EnumProp::operator=(u64);

// No out-of-line body: no code in the ELF
// nAI::EnumProp::operator signed char();

// No out-of-line body: no code in the ELF
// nAI::EnumProp::operator unsigned char();

// No out-of-line body: no code in the ELF
// nAI::EnumProp::operator short();

// No out-of-line body: no code in the ELF
// nAI::EnumProp::operator unsigned short();

// No out-of-line body: no code in the ELF
// nAI::EnumProp::operator int();

// No out-of-line body: no code in the ELF
// nAI::EnumProp::operator unsigned int();

// No out-of-line body: no code in the ELF
// nAI::EnumProp::operator long();

// No out-of-line body: no code in the ELF
// nAI::EnumProp::operator unsigned long();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// nAI::EnumProp::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x01343d00 - 0x01343d5f (95 bytes)
__attribute__((weak)) MtObject* nAI::EnumProp::MyDTI::newInstance() const {
    DDON_STUB("nAI::EnumProp::MyDTI::newInstance")
    return nullptr;
}

