// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "nDrawScene.h"
#include "MtAllocator.h"
#include "MtColor.h"
#include "MtDTI.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#include "MtPrimitive2D.h"
#include "nDraw.h"
#include "nDrawResource.h"
#include "nDrawTexture.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// nDraw::SCENE_DESC::SCENE_DESC();

// No out-of-line body: no code in the ELF
// MtDTI* nDraw::Scene::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void nDraw::Scene::usage();

// Address: 0x01b82e60 - 0x01b82e68 (8 bytes)
const MtDTI& nDraw::Scene::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return nDraw::Scene::DTI;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtAllocator* nDraw::Scene::getAllocator();

// No out-of-line body: no code in the ELF
// void nDraw::Scene::setAllocator(u32);

// Address: 0x0115e180 - 0x0115e1c0 (64 bytes)
void* nDraw::Scene::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::MtMemoryAllocator::getAllocator(::nDraw::Scene::DTI)->memAlloc(sz, align, ::nDraw::Scene::DTI.::MtDTI::mID);
}

// No out-of-line body: no code in the ELF
// void* nDraw::Scene::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* nDraw::Scene::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* nDraw::Scene::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN5nDraw5SceneD0Ev at 0x011600fe-0x0116011f, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void nDraw::Scene::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::nDraw::Scene::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void nDraw::Scene::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void nDraw::Scene::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void nDraw::Scene::operator delete[](void* p_addr, u32 align);

// Address: 0x0115e230 - 0x0115fc1c (6636 bytes)
nDraw::Scene::Scene(nDraw::SCENE_DESC desc) {
    // local: u32 w;
    // local: u32 h;
    // local: HDR_TYPE hdr;
    // local: ANTIALIAS_TYPE aa;
    // local: u32 scene_attr;
    // local: u32 misc_flags;
    // local: u32 misc_rop_alphatest;
    // local: u32 misc_flags2;
    // local: u32 auto_resize;
    // local: FORMAT_TYPE d_fmt;
    // local: FORMAT_TYPE fmt;
    // local: FORMAT_TYPE r_fmt;
    // local: FORMAT_TYPE p_fmt;
    // local: u32 misc_msaa;
    // local: Texture* pbkbuffer;
    // local: FORMAT_TYPE format;
    // local: u32 dlMiscFlags;
    // local: u32 wt;
    // local: u32 ht;
    // local: FORMAT_TYPE format;
    // local: u32 dlMiscFlags;
    // local: u32 i;
    DDON_STUB("nDraw::Scene::Scene")
    /* stub */
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// nDraw::RenderTargetView* nDraw::Scene::getRenderTargetView(nDraw::PASS_TYPE pass, u32 target) const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// nDraw::DepthStencilView* nDraw::Scene::getDepthStencilView(nDraw::PASS_TYPE pass) const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// nDraw::Texture* nDraw::Scene::getTexture(nDraw::PASS_TYPE pass) const;

// No out-of-line body: 1 inlined copy in 1 function (24 bytes)
//   in uSkyWaterModel::draw at 0x00d1f982-0x00d1f99a (called at uSkyWaterModel.cpp:409)
// nDraw::Texture* nDraw::Scene::getDepthTexture() const;

// No out-of-line body: no code in the ELF
// nDraw::Texture* nDraw::Scene::getBackFaceDepthTexture() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// nDraw::Texture* nDraw::Scene::getStencilTexture() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// nDraw::Texture* nDraw::Scene::getHDRTexture() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// nDraw::Texture* nDraw::Scene::getHDRQTexture() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// nDraw::Texture* nDraw::Scene::getTangentTexture() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtSize nDraw::Scene::getSize() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtColor nDraw::Scene::getClearColor() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void nDraw::Scene::setClearColor(MtColor c);

// Address: 0x01160120 - 0x0116137c (4700 bytes)
__attribute__((weak)) void nDraw::Scene::createProperty(MtPropertyList& s) {
    DDON_STUB("nDraw::Scene::createProperty")
    /* stub */
}

// Address: 0x01161380 - 0x01161385 (5 bytes)
MtUI* nDraw::Scene::createUI(MtProperty& prop) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->::MtObject::createUI(prop);
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void nDraw::Scene::setHDREmphasis(f32 v);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// f32 nDraw::Scene::getHDREmphasis();

// No out-of-line body: no code in the ELF
// nDraw::HDR_TYPE nDraw::Scene::getHDRType() const;

// No out-of-line body: no code in the ELF
// nDraw::ANTIALIAS_TYPE nDraw::Scene::getAntiAliasType() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// u32 nDraw::Scene::getAttributes() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// nDraw::DEFERRED_LIGHTING_LIGHT_TYPE nDraw::Scene::getDeferredLightingLightType() const;

// No out-of-line body: no code in the ELF
// nDraw::DEFERRED_LIGHTING_HDR_TYPE nDraw::Scene::getDeferredLightingHDRType() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// nDraw::DEFERRED_LIGHTING_TRANSPARENT_TYPE nDraw::Scene::getDeferredLightingTransparentType() const;

// No out-of-line body: no code in the ELF
// nDraw::Texture* nDraw::Scene::getSceneReductionTex() const;

// No out-of-line body: no code in the ELF
// nDraw::Texture* nDraw::Scene::getDepthReductionTex() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// bool nDraw::Scene::isUseReduction() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// nDraw::Texture* nDraw::Scene::getTempDistortionTex() const;

// Address: 0x0115fd60 - 0x011600e4 (900 bytes)
// Also emitted as: _ZN5nDraw5SceneD0Ev at 0x011600f0
nDraw::Scene::~Scene() {
    DDON_STUB("nDraw::Scene::~Scene")
    /* stub */
}

// Address: 0x0115fc30 - 0x0115fd5c (300 bytes)
__attribute__((weak)) void nDraw::Scene::getLightAccumulationFormat(nDraw::FORMAT_TYPE& format, u32& miscFlags) {
    // local: u32 rtf;
    DDON_STUB("nDraw::Scene::getLightAccumulationFormat")
    /* stub */
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// u32 nDraw::Scene::setupAntiAliasType(nDraw::ANTIALIAS_TYPE type, nDraw::FORMAT_TYPE format);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// nDraw::Scene::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x0115e0d0 - 0x0115e177 (167 bytes)
__attribute__((weak)) MtObject* nDraw::Scene::MyDTI::newInstance() const {
    DDON_STUB("nDraw::Scene::MyDTI::newInstance")
    return nullptr;
}

