// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "rMotionList.h"
#include "MtAllocator.h"
#include "MtDTI.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#include "cResource.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* rMotionList::getMyDTIPtr();

// Address: 0x011d8960 - 0x011d8961 (1 bytes)
__attribute__((weak)) void rMotionList::usage() {
    // Empty in the binary (a single `ret`).
}

// Address: 0x01b92da0 - 0x01b92da8 (8 bytes)
const MtDTI& rMotionList::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return rMotionList::DTI;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtAllocator* rMotionList::getAllocator();

// No out-of-line body: no code in the ELF
// void rMotionList::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
// inferred: operator new from _ZNK11rMotionList5MyDTI11newInstanceEv at 0x011d8900-0x011d892d, code DWARF attributes to no inlined copy; sz is the class's size (120), align the allocation's other whole constant (16)
inline void* rMotionList::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::rMotionList::DTI)->memAlloc(sz, align, ::rMotionList::DTI.::MtDTI::mID);
}

// No out-of-line body: no code in the ELF
// void* rMotionList::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* rMotionList::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* rMotionList::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN11rMotionListD0Ev at 0x011d8a62-0x011d8a83, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void rMotionList::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::rMotionList::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void rMotionList::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void rMotionList::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void rMotionList::operator delete[](void* p_addr, u32 align);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// rMotionList::rMotionList();

// Address: 0x01b92db0 - 0x01b92db8 (8 bytes)
MT_CTSTR rMotionList::getExt() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return "lmt";
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// u32 rMotionList::getMotionNum() const;

// Address: 0x011d8ad0 - 0x011d8aed (29 bytes)
__attribute__((weak)) nMotion::MOTION_INFO* rMotionList::getMotionInfo(u32 no) const {
    DDON_STUB("rMotionList::getMotionInfo")
    return nullptr;
}

// Address: 0x011d8af0 - 0x011d8cd4 (484 bytes)
__attribute__((weak)) bool rMotionList::load(MtStream& in) {
    // local: u32 len;
    // local: u32 i;
    // local: MOTION_INFO* pmot;
    // local: u32 j;
    // local: s32 j;
    // local: u32 j;
    DDON_STUB("rMotionList::load")
    return {};
}

// Address: 0x011d8ce0 - 0x011d8ce3 (3 bytes)
bool rMotionList::save(MtStream& out) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return false;
}

// Address: 0x011d8a90 - 0x011d8ac3 (51 bytes)
void rMotionList::clear() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    // inferred: a temporary for the value the load at 0x11d8a9a read, used once; no DWARF local holds it
    rMotionList::MOTION_LIST_HDR* t0 = this->mpHdr;
    // inferred: a temporary for the result of the call at 0x11d8aa5, used once; no DWARF local holds it
    MtAllocator* t1 = ::MtMemoryAllocator::getAllocator(::rMotionList::DTI);
    t1->memFree(static_cast<void*>(t0));
    this->mpHdr = static_cast<rMotionList::MOTION_LIST_HDR*>(nullptr);
}

// Address: 0x011d89e0 - 0x011d8a20 (64 bytes)
// Also emitted as: _ZN11rMotionListD0Ev at 0x011d8a20
rMotionList::~rMotionList() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    // inferred: a temporary for the value the load at 0x11d89f8 read, used once; no DWARF local holds it
    rMotionList::MOTION_LIST_HDR* t0 = this->mpHdr;
    // inferred: a temporary for the result of the call at 0x11d8a03, used once; no DWARF local holds it
    MtAllocator* t1 = ::MtMemoryAllocator::getAllocator(::rMotionList::DTI);
    t1->memFree(static_cast<void*>(t0));
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void* rMotionList::memAlloc(u32 size);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void rMotionList::memFree(void* p_addr);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// rMotionList::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x011d8900 - 0x011d895d (93 bytes)
MtObject* rMotionList::MyDTI::newInstance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return new (static_cast<u32>(16)) ::rMotionList;
}

