// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "rObjCollision.h"
#include "MtAllocator.h"
#include "MtDTI.h"
#include "MtDataWriter.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#include "cResource.h"
#include "rAttackParam.h"
#include "../rObjCollision/rCollIndex.h"
#include "rCollNode.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* rObjCollision::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void rObjCollision::usage();

// Address: 0x01aa0520 - 0x01aa0528 (8 bytes)
const MtDTI& rObjCollision::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return rObjCollision::DTI;
}

// No out-of-line body: 2 inlined copies in 2 functions (30 bytes)
//   in rObjCollision::MyDTI::newInstance at 0x006b0ab4-0x006b0ac6 (called at rObjCollision.cpp:39)
//   in rObjCollision::~rObjCollision at 0x006b0c77-0x006b0c83 (called at rObjCollision.cpp:39)
// MtAllocator* rObjCollision::getAllocator();

// No out-of-line body: no code in the ELF
// void rObjCollision::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
// inferred: parameters written where their values stand in every inlined copy
inline void* rObjCollision::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::rObjCollision::DTI)->memAlloc(sz, align, ::rObjCollision::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* rObjCollision::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* rObjCollision::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* rObjCollision::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void rObjCollision::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::rObjCollision::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void rObjCollision::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void rObjCollision::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void rObjCollision::operator delete[](void* p_addr, u32 align);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline rObjCollision::rObjCollision() {
    this->::cResource::setAttribute(static_cast<u32>(16));
    this->mpAttackParam = static_cast<rAttackParam*>(nullptr);
    this->mpCollNode = static_cast<rCollNode*>(nullptr);
    this->mpCollIndex = static_cast<rCollIndex*>(nullptr);
}

// Address: 0x006b0ba0 - 0x006b0c0d (109 bytes)
// Also emitted as: _ZN13rObjCollisionD0Ev at 0x006b0c10
rObjCollision::~rObjCollision() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpCollIndex != static_cast<rCollIndex*>(nullptr)) {
        this->mpCollIndex->::cResource::release();
        this->mpCollIndex = static_cast<rCollIndex*>(nullptr);
    }
    if (this->mpCollNode != static_cast<rCollNode*>(nullptr)) {
        this->mpCollNode->::cResource::release();
        this->mpCollNode = static_cast<rCollNode*>(nullptr);
    }
    if (this->mpAttackParam == static_cast<rAttackParam*>(nullptr)) {
        return;
    }
    this->mpAttackParam->::cResource::release();
    this->mpAttackParam = static_cast<rAttackParam*>(nullptr);
}

// Address: 0x01aa0530 - 0x01aa0538 (8 bytes)
MT_CTSTR rObjCollision::getExt() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return "col";
}

// Address: 0x006b0ca0 - 0x006b0f13 (627 bytes)
__attribute__((weak)) void rObjCollision::createProperty(MtPropertyList& s) {
    DDON_STUB("rObjCollision::createProperty")
    /* stub */
}

// Address: 0x006b0f20 - 0x006b122e (782 bytes)
__attribute__((weak)) bool rObjCollision::load(MtStream& in) {
    // local: u16 dmy;
    // local: u16 version;
    // local: u32 magic;
    // local: MtDataReader r;
    DDON_STUB("rObjCollision::load")
    return {};
}

// Address: 0x006b1230 - 0x006b12bd (141 bytes)
bool rObjCollision::save(MtStream& out) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    MtDataWriter w(out, static_cast<u32>(4096), static_cast<u32>(4096));
    (&w)->writeU32(static_cast<u32>(5001027));
    (&w)->writeU16(static_cast<u16>(110));
    (&w)->writeU16(static_cast<u16>(0));
    return true;
}

// No out-of-line body: 2 inlined copies in 1 function (132 bytes)
//   in _GLOBAL__sub_I_rObjCollision.cpp at 0x006b12c0-0x006b1302 (called at rObjCollision.cpp:39)
//   in _GLOBAL__sub_I_rObjCollision.cpp at 0x006b12c0-0x006b1302 (called at rObjCollision.h:31)
// rObjCollision::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x006b0ab0 - 0x006b0b20 (112 bytes)
MtObject* rObjCollision::MyDTI::newInstance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return new (static_cast<u32>(16)) ::rObjCollision;
}

