// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "rQuestMarkerInfo.h"
#include "MtAllocator.h"
#include "MtCollection.h"
#include "MtDTI.h"
#include "MtDataReader.h"
#include "MtMath.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#include "cResource.h"
#include "nDDOIO.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* rQuestMarkerInfo::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void rQuestMarkerInfo::usage();

// Address: 0x01aaf240 - 0x01aaf248 (8 bytes)
const MtDTI& rQuestMarkerInfo::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return rQuestMarkerInfo::DTI;
}

// No out-of-line body: 2 inlined copies in 2 functions (30 bytes)
//   in rQuestMarkerInfo::MyDTI::newInstance at 0x006e2244-0x006e2256 (called at rQuestMarkerInfo.cpp:31)
//   in rQuestMarkerInfo::~rQuestMarkerInfo at 0x006e24d0-0x006e24dc (called at rQuestMarkerInfo.cpp:31)
// MtAllocator* rQuestMarkerInfo::getAllocator();

// No out-of-line body: no code in the ELF
// void rQuestMarkerInfo::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined.
// inferred: parameters written where their values stand in every inlined copy; approximate: only approximate callers check this inline body
inline void* rQuestMarkerInfo::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::rQuestMarkerInfo::DTI)->memAlloc(sz, align, ::rQuestMarkerInfo::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* rQuestMarkerInfo::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* rQuestMarkerInfo::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* rQuestMarkerInfo::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void rQuestMarkerInfo::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::rQuestMarkerInfo::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void rQuestMarkerInfo::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void rQuestMarkerInfo::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void rQuestMarkerInfo::operator delete[](void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// MT_CTSTR rQuestMarkerInfo::getFileTitleSuffix(u32);

// No out-of-line body: no code in the ELF
// MT_CTSTR rQuestMarkerInfo::getFileResId(u32 type);

// No out-of-line body: no code in the ELF
// u32 rQuestMarkerInfo::getMagicHeader() const;

// No out-of-line body: no code in the ELF
// u32 rQuestMarkerInfo::getDataVersion() const;

// Address: 0x01aaf250 - 0x01aaf258 (8 bytes)
MT_CTSTR rQuestMarkerInfo::getExt() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return "qmi";
}

// Inline, no code of its own: checked where it is inlined.
// approximate: only approximate callers check this inline body
inline rQuestMarkerInfo::rQuestMarkerInfo() {
    this->mStageNo = static_cast<u32>(0);
    this->::cResource::setAttribute(static_cast<u32>(22));
    this->mInfoList.::MtArray::mAutoDelete = true;
}

// Address: 0x006e2360 - 0x006e241a (186 bytes)
// Also emitted as: _ZN16rQuestMarkerInfoD0Ev at 0x006e2420
rQuestMarkerInfo::~rQuestMarkerInfo() {
    DDON_STUB("rQuestMarkerInfo::~rQuestMarkerInfo")
    /* stub */
}

// Address: 0x006e2500 - 0x006e2692 (402 bytes)
__attribute__((weak)) void rQuestMarkerInfo::createProperty(MtPropertyList& s) {
    DDON_STUB("rQuestMarkerInfo::createProperty")
    /* stub */
}

// Address: 0x006e26a0 - 0x006e275b (187 bytes)
bool rQuestMarkerInfo::load(MtStream& in) {
    // local: u32 header;
    // local: MtDataReader r;
    // local: u32 dataVersion;
    // Proven from the ELF: the body oracle checks this body (022 D5).
    MtDataReader r(in, static_cast<u32>(4096));
    if ((&r)->readU32() == static_cast<u32>(4803921)) {
        if ((&r)->readU32() == static_cast<u32>(1)) {
            this->mStageNo = (&r)->readU32();
            ::nDDOIO::readMtArray(r, this->mInfoList);
            return true;
        }
    }
    return false;
}

// Address: 0x006e2760 - 0x006e2851 (241 bytes)
__attribute__((weak)) bool rQuestMarkerInfo::save(MtStream& out) {
    // local: MtDataWriter w;
    DDON_STUB("rQuestMarkerInfo::save")
    return {};
}

// No out-of-line body: 2 inlined copies in 1 function (132 bytes)
//   in _GLOBAL__sub_I_rQuestMarkerInfo.cpp at 0x006e2ce0-0x006e2d22 (called at rQuestMarkerInfo.cpp:31)
//   in _GLOBAL__sub_I_rQuestMarkerInfo.cpp at 0x006e2ce0-0x006e2d22 (called at rQuestMarkerInfo.h:30)
// rQuestMarkerInfo::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x006e2240 - 0x006e22d1 (145 bytes)
MtObject* rQuestMarkerInfo::MyDTI::newInstance() const {
    // Approximate from the ELF: stores ahead of a subobject's inlined constructor; the body oracle reports this body.
    return new (static_cast<u32>(16)) ::rQuestMarkerInfo;
}

// No out-of-line body: no code in the ELF
// MtDTI* rQuestMarkerInfo::cInfo::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void rQuestMarkerInfo::cInfo::usage();

// Address: 0x01aaf260 - 0x01aaf268 (8 bytes)
const MtDTI& rQuestMarkerInfo::cInfo::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return rQuestMarkerInfo::cInfo::DTI;
}

// No out-of-line body: 3 inlined copies in 3 functions (45 bytes)
//   in rQuestMarkerInfo::cInfo::MyDTI::newInstance at 0x006e2864-0x006e2876 (called at rQuestMarkerInfo.cpp:136)
//   in rQuestMarkerInfo::cInfo::~cInfo at 0x006e2979-0x006e2985 (called at rQuestMarkerInfo.cpp:136)
//   in _ZN6nDDOIO11readMtArrayIN16rQuestMarkerInfo5cInfoEEEvR12MtDataReaderR12MtTypedArrayIT_E at 0x01aaf0a3-0x01aaf0b2 (called at rQuestMarkerInfo.cpp:136)
// MtAllocator* rQuestMarkerInfo::cInfo::getAllocator();

// No out-of-line body: no code in the ELF
// void rQuestMarkerInfo::cInfo::setAllocator(u32);

// No out-of-line body: 2 inlined copies in 2 functions (82 bytes)
//   in rQuestMarkerInfo::cInfo::MyDTI::newInstance at 0x006e2864-0x006e288d (called at rQuestMarkerInfo.cpp:136)
//   in _ZN6nDDOIO11readMtArrayIN16rQuestMarkerInfo5cInfoEEEvR12MtDataReaderR12MtTypedArrayIT_E at 0x01aaf0a3-0x01aaf0cc (called at rQuestMarkerInfo.cpp:136)
// void* rQuestMarkerInfo::cInfo::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* rQuestMarkerInfo::cInfo::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* rQuestMarkerInfo::cInfo::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* rQuestMarkerInfo::cInfo::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline void rQuestMarkerInfo::cInfo::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::rQuestMarkerInfo::cInfo::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void rQuestMarkerInfo::cInfo::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void rQuestMarkerInfo::cInfo::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void rQuestMarkerInfo::cInfo::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 2 inlined copies in 2 functions (147 bytes)
//   in rQuestMarkerInfo::cInfo::MyDTI::newInstance at 0x006e288d-0x006e28ce (called at rQuestMarkerInfo.cpp:136)
//   in _ZN6nDDOIO11readMtArrayIN16rQuestMarkerInfo5cInfoEEEvR12MtDataReaderR12MtTypedArrayIT_E at 0x01aaf088-0x01aaf097, 0x01aaf0cc-0x01aaf10f (called at rQuestMarkerInfo.cpp:136)
// rQuestMarkerInfo::cInfo::cInfo();

// Address: 0x006e2960 - 0x006e2961 (1 bytes)
// Also emitted as: _ZN16rQuestMarkerInfo5cInfoD0Ev at 0x006e2970
rQuestMarkerInfo::cInfo::~cInfo() {
    // Empty in the binary (a single `ret`).
}

// Address: 0x006e29a0 - 0x006e2c01 (609 bytes)
__attribute__((weak)) void rQuestMarkerInfo::cInfo::createProperty(MtPropertyList& s) {
    DDON_STUB("rQuestMarkerInfo::cInfo::createProperty")
    /* stub */
}

// Address: 0x006e2c10 - 0x006e2c60 (80 bytes)
void rQuestMarkerInfo::cInfo::load(MtDataReader& r) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mPos = r.readV3();
    this->mGroupNo = r.readU32();
    this->mUniqueId = r.readU32();
}

// Address: 0x006e2c60 - 0x006e2cdd (125 bytes)
__attribute__((weak)) void rQuestMarkerInfo::cInfo::save(MtDataWriter& w) {
    DDON_STUB("rQuestMarkerInfo::cInfo::save")
    /* stub */
}

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_rQuestMarkerInfo.cpp at 0x006e2d22-0x006e2d5f (called at rQuestMarkerInfo.cpp:136)
//   in _GLOBAL__sub_I_rQuestMarkerInfo.cpp at 0x006e2d22-0x006e2d5f (called at rQuestMarkerInfo.h:152)
// rQuestMarkerInfo::cInfo::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x006e2860 - 0x006e28d3 (115 bytes)
__attribute__((weak)) MtObject* rQuestMarkerInfo::cInfo::MyDTI::newInstance() const {
    DDON_STUB("rQuestMarkerInfo::cInfo::MyDTI::newInstance")
    return nullptr;
}

// Instance at 0x01aaef70 - 0x01aaef75 (5 bytes) of the generic MtTypedArray<T>::~MtTypedArray
// Proven from the ELF: the body oracle checks this instance (022 D5).
template MtTypedArray<rQuestMarkerInfo::cInfo>::~MtTypedArray();

