// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "rWeatherScript.h"
#include "MtAllocator.h"
#include "MtCollection.h"
#include "MtDTI.h"
#include "MtDataReader.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#include "cResource.h"
#include "nDDOIO.h"
#include "nDDOUtility.h"
#include "nWeather.h"
#include "res_ptr.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* cWSCParam::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cWSCParam::usage();

// Address: 0x01abbe20 - 0x01abbe28 (8 bytes)
const MtDTI& cWSCParam::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cWSCParam::DTI;
}

// No out-of-line body: 3 inlined copies in 3 functions (45 bytes)
//   in cWSCParam::MyDTI::newInstance at 0x007167c4-0x007167d6 (called at rWeatherScript.cpp:57)
//   in cWSCParam::~cWSCParam at 0x00716956-0x00716962 (called at rWeatherScript.cpp:57)
//   in cWeatherScriptIO::getWSCParam at 0x00716b6c-0x00716b7b (called at rWeatherScript.cpp:57)
// MtAllocator* cWSCParam::getAllocator();

// No out-of-line body: no code in the ELF
// void cWSCParam::setAllocator(u32);

// No out-of-line body: 2 inlined copies in 2 functions (83 bytes)
//   in cWSCParam::MyDTI::newInstance at 0x007167c4-0x007167ed (called at rWeatherScript.cpp:57)
//   in cWeatherScriptIO::getWSCParam at 0x00716b6c-0x00716b96 (called at rWeatherScript.cpp:161)
// void* cWSCParam::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cWSCParam::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cWSCParam::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cWSCParam::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void cWSCParam::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cWSCParam::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cWSCParam::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cWSCParam::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cWSCParam::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 2 inlined copies in 2 functions (136 bytes)
//   in cWSCParam::MyDTI::newInstance at 0x007167ed-0x00716831 (called at rWeatherScript.cpp:57)
//   in cWeatherScriptIO::getWSCParam at 0x00716b96-0x00716bda (called at rWeatherScript.cpp:161)
// cWSCParam::cWSCParam();

// Address: 0x007168c0 - 0x0071690f (79 bytes)
// Also emitted as: _ZN9cWSCParamD0Ev at 0x00716910
cWSCParam::~cWSCParam() {
    DDON_STUB("cWSCParam::~cWSCParam")
    /* stub */
}

// No out-of-line body: 2 inlined copies in 1 function (128 bytes)
//   in _GLOBAL__sub_I_rWeatherScript.cpp at 0x007182c3-0x00718303 (called at rWeatherScript.cpp:57)
//   in _GLOBAL__sub_I_rWeatherScript.cpp at 0x007182c3-0x00718303 (called at rWeatherScript.h:35)
// cWSCParam::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x007167c0 - 0x00716836 (118 bytes)
__attribute__((weak)) MtObject* cWSCParam::MyDTI::newInstance() const {
    DDON_STUB("cWSCParam::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* cWeatherScriptCmd::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cWeatherScriptCmd::usage();

// Address: 0x01abbd50 - 0x01abbd58 (8 bytes)
const MtDTI& cWeatherScriptCmd::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cWeatherScriptCmd::DTI;
}

// No out-of-line body: 2 inlined copies in 2 functions (30 bytes)
//   in cWeatherScriptCmd::MyDTI::newInstance at 0x00716d54-0x00716d66 (called at rWeatherScript.cpp:239)
//   in cWeatherScriptCmd::~cWeatherScriptCmd at 0x01abbd29-0x01abbd35 (called at rWeatherScript.cpp:239)
// MtAllocator* cWeatherScriptCmd::getAllocator();

// No out-of-line body: no code in the ELF
// void cWeatherScriptCmd::setAllocator(u32);

// No out-of-line body: 1 inlined copy in 1 function (41 bytes)
//   in cWeatherScriptCmd::MyDTI::newInstance at 0x00716d54-0x00716d7d (called at rWeatherScript.cpp:239)
// void* cWeatherScriptCmd::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cWeatherScriptCmd::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cWeatherScriptCmd::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cWeatherScriptCmd::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline void cWeatherScriptCmd::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cWeatherScriptCmd::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cWeatherScriptCmd::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cWeatherScriptCmd::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cWeatherScriptCmd::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 7 inlined copies in 6 functions (532 bytes)
//   in cWeatherScriptCmd::MyDTI::newInstance at 0x00716d7d-0x00716dd3 (called at rWeatherScript.cpp:239)
//   in cWeatherScriptCmd::MyDTI::newInstance at 0x00716d7d-0x00716dd3 (called at rWeatherScript.h:145)
//   in cWSCEpv::MyDTI::newInstance at 0x0071737d-0x007173c5 (called at rWeatherScript.cpp:559)
//   and 4 more (every copy is in <bundle>.inlined.json)
// cWeatherScriptCmd::cWeatherScriptCmd();

// Defined in the class (its body was written in a header).
// cWeatherScriptCmd::~cWeatherScriptCmd();

// Address: 0x00716e50 - 0x00716e51 (1 bytes)
__attribute__((weak)) void cWeatherScriptCmd::setupCmd(cWeatherScriptIO& io) const {
    // Empty in the binary (a single `ret`).
}

// Address: 0x00716e60 - 0x00716e63 (3 bytes)
bool cWeatherScriptCmd::updateCmd(cWeatherScriptIO& io) const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return true;
}

// Address: 0x00716e70 - 0x00716ef4 (132 bytes)
__attribute__((weak)) void cWeatherScriptCmd::endCmd(cWeatherScriptIO& io) const {
    DDON_STUB("cWeatherScriptCmd::endCmd")
    /* stub */
}

// Address: 0x00716f00 - 0x00716f6b (107 bytes)
__attribute__((weak)) bool cWeatherScriptCmd::isUpdateForceEnd() const {
    DDON_STUB("cWeatherScriptCmd::isUpdateForceEnd")
    return {};
}

// No out-of-line body: 1 inlined copy in 1 function (103 bytes)
//   in cWeatherScriptCmd::isUpdateForceEnd at 0x00716f00-0x00716f67 (called at rWeatherScript.cpp:292)
// bool cWeatherScriptCmd::isEnableStage() const;

// Address: 0x00716f80 - 0x00717080 (256 bytes)
void cWeatherScriptCmd::load(MtDataReader& r) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mBeginFrame = r.readF32();
    this->mEndFrame = r.readF32();
    this->mEnableStageNo.elems[0] = r.readU32();
    this->mEnableStageNo.elems[1] = r.readU32();
    this->mEnableStageNo.elems[2] = r.readU32();
    this->mEnableStageNo.elems[3] = r.readU32();
    this->mEnableStageNo.elems[4] = r.readU32();
    this->mEnableStageNo.elems[5] = r.readU32();
    this->mEnableStageNo.elems[6] = r.readU32();
    this->mEnableStageNo.elems[7] = r.readU32();
    this->mDisableStageNo.elems[0] = r.readU32();
    this->mDisableStageNo.elems[1] = r.readU32();
    this->mDisableStageNo.elems[2] = r.readU32();
    this->mDisableStageNo.elems[3] = r.readU32();
    this->mDisableStageNo.elems[4] = r.readU32();
    this->mDisableStageNo.elems[5] = r.readU32();
    this->mDisableStageNo.elems[6] = r.readU32();
    this->mDisableStageNo.elems[7] = r.readU32();
}

// No out-of-line body: 2 inlined copies in 1 function (128 bytes)
//   in _GLOBAL__sub_I_rWeatherScript.cpp at 0x0071833c-0x0071837c (called at rWeatherScript.cpp:239)
//   in _GLOBAL__sub_I_rWeatherScript.cpp at 0x0071833c-0x0071837c (called at rWeatherScript.h:124)
// cWeatherScriptCmd::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00716d50 - 0x00716dd8 (136 bytes)
__attribute__((weak)) MtObject* cWeatherScriptCmd::MyDTI::newInstance() const {
    DDON_STUB("cWeatherScriptCmd::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* cWeatherScriptCmds::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cWeatherScriptCmds::usage();

// Address: 0x01abbe10 - 0x01abbe18 (8 bytes)
const MtDTI& cWeatherScriptCmds::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cWeatherScriptCmds::DTI;
}

// No out-of-line body: 2 inlined copies in 2 functions (30 bytes)
//   in cWeatherScriptCmds::MyDTI::newInstance at 0x00717084-0x00717096 (called at rWeatherScript.cpp:405)
//   in cWeatherScriptCmds::~cWeatherScriptCmds at 0x007172ef-0x007172fb (called at rWeatherScript.cpp:405)
// MtAllocator* cWeatherScriptCmds::getAllocator();

// No out-of-line body: no code in the ELF
// void cWeatherScriptCmds::setAllocator(u32);

// No out-of-line body: 1 inlined copy in 1 function (41 bytes)
//   in cWeatherScriptCmds::MyDTI::newInstance at 0x00717084-0x007170ad (called at rWeatherScript.cpp:405)
// void* cWeatherScriptCmds::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cWeatherScriptCmds::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cWeatherScriptCmds::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cWeatherScriptCmds::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void cWeatherScriptCmds::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cWeatherScriptCmds::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cWeatherScriptCmds::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cWeatherScriptCmds::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cWeatherScriptCmds::operator delete[](void* p_addr, u32 align);

// Address: 0x007171c0 - 0x00717255 (149 bytes)
cWeatherScriptCmds::cWeatherScriptCmds() {
    // local: u32 i;
    DDON_STUB("cWeatherScriptCmds::cWeatherScriptCmds")
    /* stub */
}

// Address: 0x00717260 - 0x007172a6 (70 bytes)
// Also emitted as: _ZN18cWeatherScriptCmdsD0Ev at 0x007172b0
cWeatherScriptCmds::~cWeatherScriptCmds() {
    DDON_STUB("cWeatherScriptCmds::~cWeatherScriptCmds")
    /* stub */
}

// Address: 0x00717310 - 0x00717345 (53 bytes)
void cWeatherScriptCmds::load(MtDataReader& r) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    ::nDDOIO::readMtArrayEx(r, this->mScripts.elems[1]);
    ::nDDOIO::readMtArrayEx(r, this->mScripts.elems[2]);
    ::nDDOIO::readMtArrayEx(r, this->mScripts.elems[3]);
}

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in _GLOBAL__sub_I_rWeatherScript.cpp at 0x0071837c-0x007183b5 (called at rWeatherScript.cpp:405)
//   in _GLOBAL__sub_I_rWeatherScript.cpp at 0x0071837c-0x007183b5 (called at rWeatherScript.h:196)
// cWeatherScriptCmds::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00717080 - 0x00717146 (198 bytes)
__attribute__((weak)) MtObject* cWeatherScriptCmds::MyDTI::newInstance() const {
    DDON_STUB("cWeatherScriptCmds::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* cWeatherScriptIO::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cWeatherScriptIO::usage();

// Address: 0x01a65a90 - 0x01a65a98 (8 bytes)
const MtDTI& cWeatherScriptIO::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cWeatherScriptIO::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* cWeatherScriptIO::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::cWeatherScriptIO::DTI);
}

// No out-of-line body: no code in the ELF
// void cWeatherScriptIO::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined.
// inferred: parameters written where their values stand in every inlined copy; approximate: only approximate callers check this inline body
inline void* cWeatherScriptIO::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::cWeatherScriptIO::DTI)->memAlloc(sz, align, ::cWeatherScriptIO::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* cWeatherScriptIO::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cWeatherScriptIO::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cWeatherScriptIO::operator new[](size_t sz, void* p_addr);

// Address: 0x00716a30 - 0x00716a5a (42 bytes)
__attribute__((weak)) void cWeatherScriptIO::operator delete(void* p_addr) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    ::cWeatherScriptIO::getAllocator()->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cWeatherScriptIO::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cWeatherScriptIO::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cWeatherScriptIO::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 6 inlined copies in 3 functions (448 bytes)
//   in cWeatherScript::MyDTI::newInstance at 0x0058eb5b-0x0058eba8 (called at cWeatherScript.cpp:215)
//   in cWeatherScript::MyDTI::newInstance at 0x0058eb5b-0x0058eba8 (called at rWeatherScript.h:89)
//   in cWeatherScript::cWeatherScript at 0x0058ecee-0x0058ed3b (called at cWeatherScript.cpp:215)
//   and 3 more (every copy is in <bundle>.inlined.json)
// cWeatherScriptIO::cWeatherScriptIO();

// Address: 0x01a65a00 - 0x01a65a17 (23 bytes)
// Also emitted as: _ZN16cWeatherScriptIOD0Ev at 0x01a65a60
cWeatherScriptIO::~cWeatherScriptIO() {
    DDON_STUB("cWeatherScriptIO::~cWeatherScriptIO")
    /* stub */
}

// Address: 0x00716a90 - 0x00716b16 (134 bytes)
__attribute__((weak)) void cWeatherScriptIO::updatePtr() {
    // local: u32 num;
    // local: u32 i;
    // local: cWSCParam* p_param;
    DDON_STUB("cWeatherScriptIO::updatePtr")
    /* stub */
}

// Address: 0x00716b20 - 0x00716c94 (372 bytes)
__attribute__((weak)) cWSCParam* cWeatherScriptIO::getWSCParam(const void* pOwner) {
    // local: u32 num;
    // local: cWSCParam* p_ret;
    // local: u32 i;
    // local: cWSCParam* p_param;
    DDON_STUB("cWeatherScriptIO::getWSCParam")
    return nullptr;
}

// No out-of-line body: 5 inlined copies in 5 functions (585 bytes)
//   in _ZNK17cWeatherScriptCmd6endCmdER16cWeatherScriptIO at 0x00716e7a-0x00716eef (called at rWeatherScript.cpp:277)
//   in cWSCEpv::endCmd at 0x0071766a-0x007176df (called at rWeatherScript.cpp:277)
//   in cWSCSound::endCmd at 0x00717a3a-0x00717aaf (called at rWeatherScript.cpp:277)
//   and 2 more (every copy is in <bundle>.inlined.json)
// void cWeatherScriptIO::releaseWSCParam(const void* pOwner);

// Address: 0x00716cb0 - 0x00716d41 (145 bytes)
__attribute__((weak)) void cWeatherScriptIO::releaseWSCParamAll() {
    // local: u32 num;
    // local: u32 i;
    // local: cWSCParam* p_param;
    DDON_STUB("cWeatherScriptIO::releaseWSCParamAll")
    /* stub */
}

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in _GLOBAL__sub_I_rWeatherScript.cpp at 0x00718303-0x0071833c (called at rWeatherScript.cpp:112)
//   in _GLOBAL__sub_I_rWeatherScript.cpp at 0x00718303-0x0071833c (called at rWeatherScript.h:66)
// cWeatherScriptIO::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00716980 - 0x007169f8 (120 bytes)
MtObject* cWeatherScriptIO::MyDTI::newInstance() const {
    // Approximate from the ELF: a base constructor inlined with no DWARF copy, which only the recompiles that inline this body check; the body oracle reports this body.
    return new (static_cast<u32>(16)) ::cWeatherScriptIO;
}

// Instance at 0x01abbf70 - 0x01abbf75 (5 bytes) of the generic MtTypedArray<T>::~MtTypedArray
// Proven from the ELF: the body oracle checks this instance (022 D5).
template MtTypedArray<cWeatherScriptCmd>::~MtTypedArray();

