// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "sCollisionExt.h"
#include "MtAllocator.h"
#include "MtDTI.h"
#include "MtMemoryAllocator.h"
#include "MtPrimitive3D.h"
#include "cSystem.h"
#include "rCollision.h"
#include "sCollision.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* sCollisionExt::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void sCollisionExt::usage();

// Address: 0x01ac1b50 - 0x01ac1b58 (8 bytes)
const MtDTI& sCollisionExt::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return sCollisionExt::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* sCollisionExt::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::sCollisionExt::DTI);
}

// No out-of-line body: no code in the ELF
// void sCollisionExt::setAllocator(u32);

// Address: 0x0074b560 - 0x0074b5a0 (64 bytes)
void* sCollisionExt::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::sCollisionExt::getAllocator()->memAlloc(sz, align, ::sCollisionExt::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* sCollisionExt::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* sCollisionExt::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* sCollisionExt::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void sCollisionExt::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::sCollisionExt::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void sCollisionExt::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void sCollisionExt::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void sCollisionExt::operator delete[](void* p_addr, u32 align);

// Omitted: mem-initializer not recorded in DWARF (base sCollision has no default constructor)
// sCollisionExt::sCollisionExt(sCollision::cSystemInitializeParam* pInitializeParam);

// Address: 0x0074b680 - 0x0074b685 (5 bytes)
// Also emitted as: _ZN13sCollisionExtD0Ev at 0x0074b690
sCollisionExt::~sCollisionExt() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
}

// Address: 0x0074b6c0 - 0x0074b6c5 (5 bytes)
void sCollisionExt::createProperty(MtPropertyList& s) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::sCollision::createProperty(s);
}

// Address: 0x0074b6d0 - 0x0074b6d5 (5 bytes)
MtUI* sCollisionExt::createUI(MtProperty& prop) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->::cSystem::createUI(prop);
}

// Address: 0x0074b6e0 - 0x0074b6e5 (5 bytes)
void sCollisionExt::move() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::sCollision::move();
}

// No out-of-line body: no code in the ELF
// sCollision::SBC_HANDLE sCollisionExt::registResourceSafe(rCollision* pResource, u32 type, u8 group, bool FlgForceRegist, bool FlgEnableMove);

// Address: 0x0074b700 - 0x0074b893 (403 bytes)
__attribute__((weak)) f32 sCollisionExt::checkHeight(const MtVector3& Pos, u32 CheckType, u32 CheckFilter, f32 CheckHeight) {
    // local: f32 height;
    // local: Param param;
    // local: TriangleInfo info;
    // local: MtLineSegment ls;
    DDON_STUB("sCollisionExt::checkHeight")
    return {};
}

// Address: 0x0074b8a0 - 0x0074b8ea (74 bytes)
u32 sCollisionExt::findIntersectionEx(const MtLineSegment& ls, const bool both_sides, sCollision::TriangleInfo* pTriInfo, const sCollision::Param& param) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (0.01f > ((((ls.p0.x - ls.p1.x) * (ls.p0.x - ls.p1.x)) + ((ls.p0.y - ls.p1.y) * (ls.p0.y - ls.p1.y))) + ((ls.p0.z - ls.p1.z) * (ls.p0.z - ls.p1.z)))) {
        return static_cast<u32>(0);
    } else {
        return this->::sCollision::findIntersection(ls, both_sides, pTriInfo, param);
    }
}

// Address: 0x0074b8f0 - 0x0074b93e (78 bytes)
bool sCollisionExt::isIntersectEx(const MtLineSegment& ls, const sCollision::Param& param) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (0.01f > ((((ls.p0.x - ls.p1.x) * (ls.p0.x - ls.p1.x)) + ((ls.p0.y - ls.p1.y) * (ls.p0.y - ls.p1.y))) + ((ls.p0.z - ls.p1.z) * (ls.p0.z - ls.p1.z)))) {
        return false;
    } else {
        return this->::sCollision::isIntersect(ls, param);
    }
}

// Address: 0x0074b940 - 0x0074b987 (71 bytes)
__attribute__((weak)) bool sCollisionExt::isTargetPolygon(u32 TargetPolygonAttribute, const rCollision::MaterialInfo& RSbcPolygonMaterial, u32 type) {
    // local: u32 attribute;
    // local: u32 stop_attr;
    // local: u32 through_filter;
    // local: u32 stop_filter;
    // local: u32 through_attr;
    DDON_STUB("sCollisionExt::isTargetPolygon")
    return {};
}

// Address: 0x0074b990 - 0x0074b991 (1 bytes)
__attribute__((weak)) void sCollisionExt::replaceAttribute(rCollision::MaterialInfo& material) {
    // Empty in the binary (a single `ret`).
}

// No out-of-line body: no code in the ELF
// u32 sCollisionExt::enumEffectAttr(rCollision* pSbc, u32* buff);

// No out-of-line body: 2 inlined copies in 1 function (132 bytes)
//   in _GLOBAL__sub_I_sCollisionExt.cpp at 0x0074ba40-0x0074ba82 (called at sCollisionExt.cpp:40)
//   in _GLOBAL__sub_I_sCollisionExt.cpp at 0x0074ba40-0x0074ba82 (called at sCollisionExt.h:29)
// sCollisionExt::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x0074b4d0 - 0x0074b55a (138 bytes)
__attribute__((weak)) MtObject* sCollisionExt::MyDTI::newInstance() const {
    DDON_STUB("sCollisionExt::MyDTI::newInstance")
    return nullptr;
}

