// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "uScrollCollisionGeometry.h"
#include "MtAllocator.h"
#include "MtCollection.h"
#include "MtDTI.h"
#include "MtGeometry3D.h"
#include "MtMath.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#include "MtPrimitive3D.h"
#include "nCollision.h"
#include "rCollision.h"
#include "sCollision.h"
#include "uScrollCollision.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* uScrollCollisionGeometry::getMyDTIPtr();

// Address: 0x00fdc450 - 0x00fdc451 (1 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::usage() {
    // Empty in the binary (a single `ret`).
}

// Address: 0x01b66db0 - 0x01b66db8 (8 bytes)
const MtDTI& uScrollCollisionGeometry::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uScrollCollisionGeometry::DTI;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtAllocator* uScrollCollisionGeometry::getAllocator();

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::setAllocator(u32);

// Address: 0x00fdc410 - 0x00fdc450 (64 bytes)
void* uScrollCollisionGeometry::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::MtMemoryAllocator::getAllocator(::uScrollCollisionGeometry::DTI)->memAlloc(sz, align, ::uScrollCollisionGeometry::DTI.::MtDTI::mID);
}

// No out-of-line body: no code in the ELF
// void* uScrollCollisionGeometry::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uScrollCollisionGeometry::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uScrollCollisionGeometry::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN24uScrollCollisionGeometryD0Ev at 0x00fdc90e-0x00fdc92f, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void uScrollCollisionGeometry::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uScrollCollisionGeometry::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::operator delete[](void* p_addr, u32 align);

// Address: 0x00fdc4c0 - 0x00fdc7c0 (768 bytes)
uScrollCollisionGeometry::uScrollCollisionGeometry() {
    DDON_STUB("uScrollCollisionGeometry::uScrollCollisionGeometry")
    /* stub */
}

// Address: 0x00fdc7c0 - 0x00fdc8f7 (311 bytes)
// Also emitted as: _ZN24uScrollCollisionGeometryD0Ev at 0x00fdc900
uScrollCollisionGeometry::~uScrollCollisionGeometry() {
    DDON_STUB("uScrollCollisionGeometry::~uScrollCollisionGeometry")
    /* stub */
}

// Address: 0x00fdc930 - 0x00fdd636 (3334 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::createProperty(MtPropertyList& s) {
    DDON_STUB("uScrollCollisionGeometry::createProperty")
    /* stub */
}

// Address: 0x00fdd8b0 - 0x00fdd8dd (45 bytes)
void uScrollCollisionGeometry::setup() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mpScrollRegisterInfo = (::sCollision::mpInstance)->::sCollision::registerScrollCollisionNode(*this);
    this->::uScrollCollisionGeometry::updateBoundingAABB();
}

// Address: 0x00fddbe0 - 0x00fddbe1 (1 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::draw(cDraw* pdraw) {
    // Empty in the binary (a single `ret`).
}

// Address: 0x00fddbf0 - 0x00fddc63 (115 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::kill() {
    DDON_STUB("uScrollCollisionGeometry::kill")
    /* stub */
}

// Address: 0x00fddc80 - 0x00fdde21 (417 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::applyWorldOffset(const MtVector3& offset, const MtVector3& absolute_offset) {
    // local: const u32 ImportResourceID;
    DDON_STUB("uScrollCollisionGeometry::applyWorldOffset")
    /* stub */
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void uScrollCollisionGeometry::removeFromCollisionSystem();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// uScrollCollisionGeometry::cGeometryInfo& uScrollCollisionGeometry::addGeometry(const MtGeomConvex& GeomConvex, const rCollision::MaterialInfo& Material);

// Address: 0x00fde020 - 0x00fde03e (30 bytes)
__attribute__((weak)) MtGeomConvex* uScrollCollisionGeometry::getGeometry(u32 GeometryIndex) {
    DDON_STUB("uScrollCollisionGeometry::getGeometry")
    return nullptr;
}

// Address: 0x00fde070 - 0x00fde086 (22 bytes)
__attribute__((weak)) const MtGeomConvex* uScrollCollisionGeometry::getGeometryConst(u32 GeometryIndex) const {
    // local: const cGeometryInfo& GeomInfo;
    DDON_STUB("uScrollCollisionGeometry::getGeometryConst")
    return nullptr;
}

// Address: 0x00fde0a0 - 0x00fde0b6 (22 bytes)
__attribute__((weak)) const MtAABB* uScrollCollisionGeometry::getGeometryBoundingAABBConst(u32 GeometryIndex) const {
    // local: const cGeometryInfo& GeomInfo;
    DDON_STUB("uScrollCollisionGeometry::getGeometryBoundingAABBConst")
    return nullptr;
}

// Address: 0x00fde050 - 0x00fde063 (19 bytes)
__attribute__((weak)) uScrollCollisionGeometry::cGeometryInfo& uScrollCollisionGeometry::getGeometryInfo(u32 GeometryIndex) {
    DDON_STUB("uScrollCollisionGeometry::getGeometryInfo")
    __builtin_unreachable();
}

// No out-of-line body: no code in the ELF
// uScrollCollisionGeometry::cGeometryInfo& uScrollCollisionGeometry::setGeometryInfo(const MtGeomConvex& GeomConvex, const rCollision::MaterialInfo& Material, u32 GeometryIndex);

// Address: 0x00fde0e0 - 0x00fde0eb (11 bytes)
__attribute__((weak)) const uScrollCollisionGeometry::cGeometryInfo& uScrollCollisionGeometry::getGeometryInfoConst(u32 GeometryIndex) const {
    DDON_STUB("uScrollCollisionGeometry::getGeometryInfoConst")
    __builtin_unreachable();
}

// Address: 0x00fde0f0 - 0x00fde10a (26 bytes)
__attribute__((weak)) bool uScrollCollisionGeometry::isGeometryActive(u32 GeometryIndex) const {
    // local: const cGeometryInfo& GeomInfo;
    DDON_STUB("uScrollCollisionGeometry::isGeometryActive")
    return {};
}

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::setGeometryActive(bool FlgActive, u32 GeometryIndex);

// Address: 0x00fde040 - 0x00fde044 (4 bytes)
u32 uScrollCollisionGeometry::getGeometryInfoNum() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mColliderGeometryArray.::MtArray::mLength;
}

// Address: 0x00fde120 - 0x00fde3b2 (658 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::setGeometryInfoNum(u32 NewGeometryNum) {
    // local: const u32 NowGeometryNum;
    // local: const u32 AvailLength;
    // local: u32 i;
    // local: const u32 TargetIndex;
    // local: const u32 AvailLength;
    // local: u32 i;
    DDON_STUB("uScrollCollisionGeometry::setGeometryInfoNum")
    /* stub */
}

// Address: 0x00fde3c0 - 0x00fde3d7 (23 bytes)
__attribute__((weak)) rCollision::MaterialInfo* uScrollCollisionGeometry::getGeometryMaterial(u32 GeometryIndex) {
    // local: cGeometryInfo& GeomInfo;
    DDON_STUB("uScrollCollisionGeometry::getGeometryMaterial")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// const rCollision::MaterialInfo* uScrollCollisionGeometry::getGeometryMaterialConst(u32 GeometryIndex) const;

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::setGeometryMaterial(const rCollision::MaterialInfo& Material, u32 GeometryIndex);

// Address: 0x00fde410 - 0x00fde417 (7 bytes)
bool uScrollCollisionGeometry::isMoveByScrMatrix() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mScrMatrix.mFlgMoveEnable;
}

// Address: 0x00fde420 - 0x00fde427 (7 bytes)
bool uScrollCollisionGeometry::isResetSetByScrMatrix() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mScrMatrix.mFlgMatResetSet;
}

// No out-of-line body: no code in the ELF
// bool uScrollCollisionGeometry::isEnableStopSetControl() const;

// Address: 0x00fde440 - 0x00fde448 (8 bytes)
void uScrollCollisionGeometry::setEnableStopSetControl(bool FlgStopSetControl) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mFlgStopSetControl = FlgStopSetControl;
}

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::setMatrix(const MtMatrix&, bool);

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::setScrMoveAndStopMatrix(const MtMatrix&);

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::setScrMovingMatrix(const MtMatrix&);

// Address: 0x00fde450 - 0x00fde498 (72 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::setScrMoveMatrix(const MtMatrix& MoveMatrix, bool FlgStopSet) {
    DDON_STUB("uScrollCollisionGeometry::setScrMoveMatrix")
    /* stub */
}

// Address: 0x00fdd790 - 0x00fdd8b0 (288 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::setScrMoveMatrixForUI(const MtMatrix& MoveMatrix) {
    DDON_STUB("uScrollCollisionGeometry::setScrMoveMatrixForUI")
    /* stub */
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// const MtMatrix& uScrollCollisionGeometry::getMatrix() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// const MtMatrix& uScrollCollisionGeometry::getScrMoveMatrixNow() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// const MtMatrix& uScrollCollisionGeometry::getScrMoveMatrixOld() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// const MtMatrix& uScrollCollisionGeometry::getScrMoveMatrixByID(u32 MoveMatrixID) const;

// No out-of-line body: no code in the ELF
// const MtMatrix& uScrollCollisionGeometry::getScrMoveMatrixInverseNow() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// const MtMatrix& uScrollCollisionGeometry::getScrMoveMatrixInverseOld() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// const MtMatrix& uScrollCollisionGeometry::getScrMoveMatrixInverseByID(u32 MoveMatrixID) const;

// Address: 0x00fdd750 - 0x00fdd781 (49 bytes)
__attribute__((weak)) MtMatrix uScrollCollisionGeometry::getMatrixForUI() {
    DDON_STUB("uScrollCollisionGeometry::getMatrixForUI")
    __builtin_unreachable();
}

// Address: 0x00fdd660 - 0x00fdd678 (24 bytes)
void uScrollCollisionGeometry::resetScrMoveMatrix() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mScrMatrix.::nCollision::cScrCollisionMoveMatrix::setMatrixForGame(static_cast<const MtMatrix*>(nullptr), true, true);
}

// No out-of-line body: no code in the ELF
// bool uScrollCollisionGeometry::isActiveGeomtry(u32 GeometryIndex);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void uScrollCollisionGeometry::setActiveGeomtry(bool set, u32 GeometryIndex);

// Address: 0x00fde4b0 - 0x00fde4bc (12 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::setScrFilter(const nCollision::cScrCommonFilter& ScrFilter) {
    DDON_STUB("uScrollCollisionGeometry::setScrFilter")
    /* stub */
}

// Address: 0x00fdd640 - 0x00fdd647 (7 bytes)
u32 uScrollCollisionGeometry::getScrType() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mScrFilter.mScrType;
}

// Address: 0x00fdd650 - 0x00fdd657 (7 bytes)
void uScrollCollisionGeometry::setScrType(u32 type) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mScrFilter.mScrType = type;
}

// No out-of-line body: no code in the ELF
// u32 uScrollCollisionGeometry::getScrGroup();

// Address: 0x00fde4d0 - 0x00fde4d8 (8 bytes)
u8 uScrollCollisionGeometry::getScrGroupIndex() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mScrFilter.mScrGroupIndex;
}

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::setScrGroup(u8 group);

// Address: 0x00fde4f0 - 0x00fde505 (21 bytes)
bool uScrollCollisionGeometry::isScrTarget(u32 TargetType, u32 TargetGroup) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if ((TargetType & this->mScrFilter.mScrType) != static_cast<u32>(0)) {
        return (TargetGroup & this->mScrFilter.mScrGroup) != static_cast<u32>(0);
    } else {
        return false;
    }
}

// No out-of-line body: no code in the ELF
// bool uScrollCollisionGeometry::importResource(rCollisionObj* pResourceObj);

// No out-of-line body: no code in the ELF
// bool uScrollCollisionGeometry::importResource(rGeometry2* pResourceGeometry);

// No out-of-line body: no code in the ELF
// bool uScrollCollisionGeometry::importResource(rGeometry3* pResourceGeometry, u32 index);

// No out-of-line body: no code in the ELF
// bool uScrollCollisionGeometry::exportResource(MT_CTSTR OutputFileName, u32 ExportType);

// No out-of-line body: no code in the ELF
// bool uScrollCollisionGeometry::isEnableOwner();

// Address: 0x00fde560 - 0x00fde5f7 (151 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::registOwner(MtObject* pOwner) {
    DDON_STUB("uScrollCollisionGeometry::registOwner")
    /* stub */
}

// Address: 0x00fde610 - 0x00fde619 (9 bytes)
void uScrollCollisionGeometry::unregistOwner() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mpOwner = nullptr;
}

// Address: 0x00fde600 - 0x00fde605 (5 bytes)
MtObject* uScrollCollisionGeometry::getOwner() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mpOwner;
}

// No out-of-line body: no code in the ELF
// bool uScrollCollisionGeometry::isEnablePlusData();

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::registPlusData(MtObject* pPlusData);

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::unregistPlusData();

// No out-of-line body: no code in the ELF
// MtObject* uScrollCollisionGeometry::getPlusData();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtAABB uScrollCollisionGeometry::getBoundingAABBLocal();

// No out-of-line body: no code in the ELF
// MtSphere uScrollCollisionGeometry::getBoundingSphereLocal();

// No out-of-line body: no code in the ELF
// MtCapsule uScrollCollisionGeometry::getBoundingCapsuleLocal();

// Address: 0x00fde670 - 0x00fde678 (8 bytes)
const MtAABB& uScrollCollisionGeometry::getBoundingAABB() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mBoundingAABB;
}

// Address: 0x00fdd8e0 - 0x00fddbd3 (755 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::updateBoundingAABB() {
    // local: const u32 GeometryNum;
    // local: MtOBB obb;
    // local: u32 i;
    // local: cGeometryInfo& NowGeometryInfo;
    DDON_STUB("uScrollCollisionGeometry::updateBoundingAABB")
    /* stub */
}

// Address: 0x00fdd680 - 0x00fdd687 (7 bytes)
bool uScrollCollisionGeometry::isEnableAutoSync() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mFlgAutoSync;
}

// Address: 0x00fdd690 - 0x00fdd749 (185 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::setEnableAutoSync(bool FlgEnableSet) {
    DDON_STUB("uScrollCollisionGeometry::setEnableAutoSync")
    /* stub */
}

// No out-of-line body: no code in the ELF
// bool uScrollCollisionGeometry::isEnableAutoSyncMove();

// Address: 0x00fde6b0 - 0x00fde6b8 (8 bytes)
void uScrollCollisionGeometry::setEnableAutoSyncMove(bool FlgEnableSet) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mFlgAutoSyncEnableMove = FlgEnableSet;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void* uScrollCollisionGeometry::memAlloc(size_t s);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void uScrollCollisionGeometry::memFree(void* padr);

// No out-of-line body: no code in the ELF
// size_t uScrollCollisionGeometry::memSize(void*);

// Address: 0x00fde6c0 - 0x00fde79b (219 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::moveForSystem() {
    // local: const u32 MoveCode;
    // local: cUnit* pOwnerUnit;
    DDON_STUB("uScrollCollisionGeometry::moveForSystem")
    /* stub */
}

// Address: 0x00fde7a0 - 0x00fdeae6 (838 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::syncOwner() {
    // local: uCoord* pOwnerCoord;
    // local: const MtVector3& NowOwnerPos;
    // local: const MtQuaternion& NowOwnerQt;
    // local: const MtVector4& NowOwnerQtV4;
    // local: const bool FlgOwnerPosChange;
    // local: const bool FlgOwnerQuatChange;
    // local: const u32 FlgOwnerPosZero;
    // local: const u32 FlgOwnerQuatZero;
    DDON_STUB("uScrollCollisionGeometry::syncOwner")
    /* stub */
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// u32 uScrollCollisionGeometry::setScrMoveMatrixForSystem();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// uScrollCollisionGeometry::cGeometryInfo& uScrollCollisionGeometry::getGeometryInfoCore(u32 GeometryIndex);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// const uScrollCollisionGeometry::cGeometryInfo& uScrollCollisionGeometry::getGeometryInfoCoreConst(u32 GeometryIndex) const;

// No out-of-line body: no code in the ELF
// uScrollCollisionGeometry::cGeometryInfo* uScrollCollisionGeometry::createNewGeometryInfo();

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void uScrollCollisionGeometry::saveImportResource(cResource& ImportResource);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void uScrollCollisionGeometry::applyWorldOffsetByAbsoluteWithCollisionObj(const MtVector3& absolute_offset);

// Address: 0x00fddf20 - 0x00fddfe6 (198 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::applyWorldOffsetByAbsoluteWithGeometry2(const MtVector3& absolute_offset) {
    // local: rGeometry2& src;
    // local: const u32 MyGeometryInfoNum;
    // local: const u32 ResourceGeometryInfoNum;
    // local: const cGeometryArray* pRGeometryArray;
    // local: const u32 LoopNum;
    // local: u32 i;
    // local: MtGeomConvex* pMyConvex;
    // local: const MtGeomConvex* pSrcConvex;
    // local: cGeometryInfo& NowGeometryInfo;
    DDON_STUB("uScrollCollisionGeometry::applyWorldOffsetByAbsoluteWithGeometry2")
    /* stub */
}

// Address: 0x00fdde40 - 0x00fddf16 (214 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::applyWorldOffsetByAbsoluteWithGeometry3(const MtVector3& absolute_offset) {
    // local: rGeometry3& src;
    // local: const u32 ResourceGroupNum;
    // local: cGeometryJointGroup* pResourceGroup;
    // local: const u32 MyGeometryInfoNum;
    // local: const u32 ResourceGeometryInfoNum;
    // local: const u32 LoopNum;
    // local: u32 i;
    // local: MtGeomConvex* pMyConvex;
    // local: const MtGeomConvex* pSrcConvex;
    // local: cGeometryInfo& NowGeometryInfo;
    DDON_STUB("uScrollCollisionGeometry::applyWorldOffsetByAbsoluteWithGeometry3")
    /* stub */
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void uScrollCollisionGeometry::applyWorldOffsetByDifference(const MtVector3& offset);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// uScrollCollisionGeometry::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00fdc3d0 - 0x00fdc410 (64 bytes)
__attribute__((weak)) MtObject* uScrollCollisionGeometry::MyDTI::newInstance() const {
    DDON_STUB("uScrollCollisionGeometry::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* uScrollCollisionGeometry::cGeometryInfo::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::cGeometryInfo::usage();

// Address: 0x01b66da0 - 0x01b66da8 (8 bytes)
const MtDTI& uScrollCollisionGeometry::cGeometryInfo::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uScrollCollisionGeometry::cGeometryInfo::DTI;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// MtAllocator* uScrollCollisionGeometry::cGeometryInfo::getAllocator();

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::cGeometryInfo::setAllocator(u32);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void* uScrollCollisionGeometry::cGeometryInfo::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uScrollCollisionGeometry::cGeometryInfo::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uScrollCollisionGeometry::cGeometryInfo::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uScrollCollisionGeometry::cGeometryInfo::operator new[](size_t sz, void* p_addr);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void uScrollCollisionGeometry::cGeometryInfo::operator delete(void* p_addr);

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::cGeometryInfo::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::cGeometryInfo::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::cGeometryInfo::operator delete[](void* p_addr, u32 align);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// uScrollCollisionGeometry::cGeometryInfo::cGeometryInfo(uScrollCollisionGeometry* pOwner, u32 ElementID);

// Address: 0x00fdb100 - 0x00fdb135 (53 bytes)
// Also emitted as: _ZN24uScrollCollisionGeometry13cGeometryInfoD0Ev at 0x00fdb140
uScrollCollisionGeometry::cGeometryInfo::~cGeometryInfo() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpGeomConvex == static_cast<MtGeomConvex*>(nullptr)) {
        return;
    }
    delete this->mpGeomConvex;
    this->mpGeomConvex = static_cast<MtGeomConvex*>(nullptr);
}

// Address: 0x00fdb190 - 0x00fdbd9b (3083 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::cGeometryInfo::createProperty(MtPropertyList& s) {
    DDON_STUB("uScrollCollisionGeometry::cGeometryInfo::createProperty")
    /* stub */
}

// Address: 0x00fdbdb0 - 0x00fdc298 (1256 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::cGeometryInfo::setGeomConvexType(u32 GeometryType) {
    // local: MtSphere s;
    // local: const u32 OldType;
    // local: const bool FlgEqualType;
    // local: const MtVector3 p0;
    // local: const MtVector3 p1;
    // local: const MtVector3 minpos;
    // local: const MtVector3 maxpos;
    // local: const MtVector3 r4;
    // local: MtMatrix mat;
    // local: MtOBB obb;
    // local: const MtVector3 p0;
    // local: const MtVector3 p1;
    // local: const MtVector3 p2;
    DDON_STUB("uScrollCollisionGeometry::cGeometryInfo::setGeomConvexType")
    /* stub */
}

// Address: 0x00fdbda0 - 0x00fdbda8 (8 bytes)
__attribute__((weak)) u32 uScrollCollisionGeometry::cGeometryInfo::getGeomConvexType() const {
    DDON_STUB("uScrollCollisionGeometry::cGeometryInfo::getGeomConvexType")
    return {};
}

// Address: 0x00fdc2c0 - 0x00fdc2c5 (5 bytes)
MtGeomConvex* uScrollCollisionGeometry::cGeometryInfo::getGeomConvex() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mpGeomConvex;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// const MtGeomConvex* uScrollCollisionGeometry::cGeometryInfo::getGeomConvexConst() const;

// Address: 0x00fdc2d0 - 0x00fdc302 (50 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::cGeometryInfo::setGeomConvex(MtGeomConvex* pNewGeomConvex) {
    DDON_STUB("uScrollCollisionGeometry::cGeometryInfo::setGeomConvex")
    /* stub */
}

// Address: 0x00fdc320 - 0x00fdc34a (42 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::cGeometryInfo::copyGeomConvex(MtGeomConvex& NewGeomConvex) {
    DDON_STUB("uScrollCollisionGeometry::cGeometryInfo::copyGeomConvex")
    /* stub */
}

// Address: 0x00fdc350 - 0x00fdc355 (5 bytes)
rCollision::MaterialInfo& uScrollCollisionGeometry::cGeometryInfo::getGeomConvexMaterial() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mGeomMaterialInfo;
}

// Address: 0x00fdc360 - 0x00fdc365 (5 bytes)
const rCollision::MaterialInfo& uScrollCollisionGeometry::cGeometryInfo::getGeomConvexMaterialConst() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mGeomMaterialInfo;
}

// Address: 0x00fdc370 - 0x00fdc384 (20 bytes)
__attribute__((weak)) void uScrollCollisionGeometry::cGeometryInfo::setGeomConvexMaterial(const rCollision::MaterialInfo& Material) {
    DDON_STUB("uScrollCollisionGeometry::cGeometryInfo::setGeomConvexMaterial")
    /* stub */
}

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::cGeometryInfo::registOwner(uScrollCollisionGeometry* pOwner, u32 ElementIndex);

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::cGeometryInfo::setElementIndex(u32);

// No out-of-line body: no code in the ELF
// u32 uScrollCollisionGeometry::cGeometryInfo::getElementIndex();

// Address: 0x00fdc2a0 - 0x00fdc2a4 (4 bytes)
bool uScrollCollisionGeometry::cGeometryInfo::isActive() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mFlgActive;
}

// Address: 0x00fdc2b0 - 0x00fdc2b5 (5 bytes)
void uScrollCollisionGeometry::cGeometryInfo::setActive(bool FlgActive) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mFlgActive = FlgActive;
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// const MtAABB& uScrollCollisionGeometry::cGeometryInfo::getBoundingAABB() const;

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// void uScrollCollisionGeometry::cGeometryInfo::updateBoundingAABB();

// No out-of-line body: no code in the ELF
// const uScrollCollisionGeometry::cGeometryInfo& uScrollCollisionGeometry::cGeometryInfo::operator=(const uScrollCollisionGeometry::cGeometryInfo& src);

// No out-of-line body: no code in the ELF
// void* uScrollCollisionGeometry::cGeometryInfo::memAlloc(size_t);

// No out-of-line body: no code in the ELF
// void uScrollCollisionGeometry::cGeometryInfo::memFree(void*);

// No out-of-line body: no code in the ELF
// size_t uScrollCollisionGeometry::cGeometryInfo::memSize(void*);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// uScrollCollisionGeometry::cGeometryInfo::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00fdaf60 - 0x00fdb07a (282 bytes)
__attribute__((weak)) MtObject* uScrollCollisionGeometry::cGeometryInfo::MyDTI::newInstance() const {
    DDON_STUB("uScrollCollisionGeometry::cGeometryInfo::MyDTI::newInstance")
    return nullptr;
}

// Instance at 0x01b66d70 - 0x01b66d75 (5 bytes) of the generic MtTypedArray<T>::~MtTypedArray
// Proven from the ELF: the body oracle checks this instance (022 D5).
template MtTypedArray<uScrollCollisionGeometry::cGeometryInfo>::~MtTypedArray();

