// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "uStageField.h"
#include "MtAllocator.h"
#include "MtCollection.h"
#include "MtDTI.h"
#include "MtMath.h"
#include "MtMemoryAllocator.h"
#include "MtObject.h"
#include "MtSynchronize.h"
#include "cSplitBase.h"
#include "cUnit.h"
#include "nStage.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* uStageFieldCtrl::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uStageFieldCtrl::usage();

// Address: 0x01b24be0 - 0x01b24be8 (8 bytes)
const MtDTI& uStageFieldCtrl::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uStageFieldCtrl::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* uStageFieldCtrl::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::uStageFieldCtrl::DTI);
}

// No out-of-line body: no code in the ELF
// void uStageFieldCtrl::setAllocator(u32);

// Address: 0x00d2c050 - 0x00d2c090 (64 bytes)
void* uStageFieldCtrl::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::uStageFieldCtrl::getAllocator()->memAlloc(sz, align, ::uStageFieldCtrl::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* uStageFieldCtrl::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uStageFieldCtrl::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uStageFieldCtrl::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void uStageFieldCtrl::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uStageFieldCtrl::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uStageFieldCtrl::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uStageFieldCtrl::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uStageFieldCtrl::operator delete[](void* p_addr, u32 align);

// Address: 0x00d2c100 - 0x00d2c286 (390 bytes)
uStageFieldCtrl::uStageFieldCtrl() {
    DDON_STUB("uStageFieldCtrl::uStageFieldCtrl")
    /* stub */
}

// Address: 0x01b24b20 - 0x01b24b6f (79 bytes)
// Also emitted as: _ZN15uStageFieldCtrlD0Ev at 0x01b24b70
uStageFieldCtrl::~uStageFieldCtrl() {
    DDON_STUB("uStageFieldCtrl::~uStageFieldCtrl")
    /* stub */
}

// Address: 0x00d2c290 - 0x00d2c317 (135 bytes)
__attribute__((weak)) void uStageFieldCtrl::setup() {
    DDON_STUB("uStageFieldCtrl::setup")
    /* stub */
}

// Address: 0x00d2c840 - 0x00d2cbb4 (884 bytes)
__attribute__((weak)) void uStageFieldCtrl::move() {
    // local: bool update;
    // local: uScheduler* pMdlSchdl;
    // local: u32 num;
    // local: MtVector3 ofsPos;
    // local: u32 i;
    // local: cUnit* punit;
    // local: uScheduler* pLightSchdl;
    // local: u32 num;
    // local: u32 i;
    // local: cUnit* punit;
    DDON_STUB("uStageFieldCtrl::move")
    /* stub */
}

// Address: 0x00d2d0a0 - 0x00d2d0a1 (1 bytes)
__attribute__((weak)) void uStageFieldCtrl::draw(cDraw* pDraw) {
    // Empty in the binary (a single `ret`).
}

// Address: 0x00d2d190 - 0x00d2d370 (480 bytes)
__attribute__((weak)) void uStageFieldCtrl::kill() {
    // local: u32 idx;
    // local: cSplitLot* pSplitLot;
    // local: cSplitArc* pSplitArc;
    DDON_STUB("uStageFieldCtrl::kill")
    /* stub */
}

// Address: 0x00d2d370 - 0x00d2d3ba (74 bytes)
void uStageFieldCtrl::updatePtr() {
    // DWARF local not rendered: cSplitLot* pSplitLot;
    // Approximate from the ELF: a cast to the other signedness; the body oracle reports this body.
    u32 idx = static_cast<u32>(0);
    if (this->mSplitLotAry.::MtArray::mLength != static_cast<u32>(0)) {
        do {
            if (this->mSplitLotAry.::MtArray::getBuffer()[static_cast<int>(idx)] != static_cast<MtObject*>(nullptr)) {
                static_cast<cSplitLot*>(this->mSplitLotAry.::MtArray::getBuffer()[static_cast<int>(idx)])->::cSplitLot::updatePtr();
            }
            idx += static_cast<u32>(1);
        } while (idx < this->mSplitLotAry.::MtArray::mLength);
    }
}

// Address: 0x00d2d0b0 - 0x00d2d12c (124 bytes)
void uStageFieldCtrl::initSplitData(s32 stageNo) {
    // DWARF local not rendered: const stStageSplitData* p;
    // Approximate from the ELF: a pointer stepped beside a counter; the body oracle reports this body.
    // inferred: DWARF's location-less 'i' (lexical block [0xd2d0b9, 0xd2d0de), [0xd2d0df, 0xd2d12b)) is the counter this loop steps (DWARF's stale constant 0)
    u32 i = static_cast<u32>(0);
    // inferred: the pointer this loop steps by one element; no location-less local in scope fits
    const stStageSplitData* p1 = ::uStageFieldCtrl::mSplitDataTbl;
    do {
        if (p1 != static_cast<const stStageSplitData*>(nullptr)) {
            if (stageNo >= p1->mStageNo) {
                if (stageNo >= (p1->mStageNo + static_cast<s32>(10))) {
                } else {
                    this->mSplitData.mStageNo = stageNo;
                    this->mSplitData.mStartPosX = ::uStageFieldCtrl::mSplitDataTbl[i].mStartPosX;
                    this->mSplitData.mStartPosZ = ::uStageFieldCtrl::mSplitDataTbl[i].mStartPosZ;
                    this->mSplitData.mSplitNumX = ::uStageFieldCtrl::mSplitDataTbl[i].mSplitNumX;
                    this->mSplitData.mSplitNumZ = ::uStageFieldCtrl::mSplitDataTbl[i].mSplitNumZ;
                    this->mSplitData.mLengthX = ::uStageFieldCtrl::mSplitDataTbl[i].mLengthX;
                    this->mSplitData.mLengthZ = ::uStageFieldCtrl::mSplitDataTbl[i].mLengthZ;
                    return;
                }
            }
        }
        i += static_cast<u32>(1);
        p1 += static_cast<int>(1);
    } while (i <= static_cast<u32>(1));
}

// No out-of-line body: no code in the ELF
// s32 uStageFieldCtrl::getNowX() const;

// No out-of-line body: no code in the ELF
// s32 uStageFieldCtrl::getNowZ() const;

// Address: 0x00d2d140 - 0x00d2d18f (79 bytes)
__attribute__((weak)) bool uStageFieldCtrl::calcFieldArea(const MtVector3& pos, s32& outX, s32& outZ) {
    DDON_STUB("uStageFieldCtrl::calcFieldArea")
    return {};
}

// No out-of-line body: 5 inlined copies in 5 functions (44 bytes)
//   in aStage::move_init at 0x0000cd05-0x0000cd0f (called at aStage.cpp:9057)
//   in aStage::move_warp at 0x000101ff-0x00010209 (called at aStage.cpp:9057)
//   in cLayoutSet::isSplitSbc at 0x002d339a-0x002d33a1 (called at cLayoutSet.cpp:508)
//   and 2 more (every copy is in <bundle>.inlined.json)
// bool uStageFieldCtrl::isSetup();

// Address: 0x00d2d3c0 - 0x00d2d648 (648 bytes)
__attribute__((weak)) void uStageFieldCtrl::sbcSetMatrix() {
    // local: MtMatrix wmat;
    // local: MtVector3 vec;
    // local: MtQuaternion quat;
    // local: u32 j;
    DDON_STUB("uStageFieldCtrl::sbcSetMatrix")
    /* stub */
}

// No out-of-line body: no code in the ELF
// const stStageSplitData* uStageFieldCtrl::getSplitData();

// No out-of-line body: no code in the ELF
// u32 uStageFieldCtrl::getSplitNumX() const;

// No out-of-line body: no code in the ELF
// u32 uStageFieldCtrl::getSplitNumZ() const;

// No out-of-line body: no code in the ELF
// f32 uStageFieldCtrl::getSplitLengthX() const;

// No out-of-line body: no code in the ELF
// f32 uStageFieldCtrl::getSplitLengthZ() const;

// No out-of-line body: 1 inlined copy in 1 function (6 bytes)
//   in sWorldOffset::calcOffsetEx at 0x00874687-0x0087468d (called at sWorldOffset.cpp:391)
// f32 uStageFieldCtrl::getSplitStartPosX() const;

// No out-of-line body: 1 inlined copy in 1 function (6 bytes)
//   in sWorldOffset::calcOffsetEx at 0x0087468d-0x00874693 (called at sWorldOffset.cpp:392)
// f32 uStageFieldCtrl::getSplitStartPosZ() const;

// Address: 0x00d2d9d0 - 0x00d2dc18 (584 bytes)
__attribute__((weak)) void uStageFieldCtrl::setBlockArcLoad(s32 stageNo, MtVector3& plPos) {
    // local: s32 nowZ;
    // local: s32 nowX;
    // local: s32 xmax;
    // local: s32 xmin;
    // local: s32 x;
    // local: s32 zmax;
    // local: s32 zmin;
    // local: s32 z;
    // local: cSplitArc* pSplitArc;
    DDON_STUB("uStageFieldCtrl::setBlockArcLoad")
    /* stub */
}

// Address: 0x00d2dc20 - 0x00d2dcaf (143 bytes)
__attribute__((weak)) bool uStageFieldCtrl::isBlockArcLoadOk() {
    // local: u32 i;
    // local: cSplitArc* pSplitArc;
    DDON_STUB("uStageFieldCtrl::isBlockArcLoadOk")
    return {};
}

// Address: 0x00d2cbc0 - 0x00d2ccd5 (277 bytes)
__attribute__((weak)) void uStageFieldCtrl::updateXZ() {
    // local: MtVector3 pos;
    DDON_STUB("uStageFieldCtrl::updateXZ")
    /* stub */
}

// No out-of-line body: no code in the ELF
// bool uStageFieldCtrl::isSplitLot(s32 x, s32 z);

// No out-of-line body: no code in the ELF
// s32 uStageFieldCtrl::getSplitLotStatus(s32 x, s32 z);

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// cSplitLot* uStageFieldCtrl::getSplitLot(s32 x, s32 z);

// No out-of-line body: 2 inlined copies in 2 functions (281 bytes)
//   in uStageFieldCtrl::updateXZ at 0x00d2cc09-0x00d2cc7d (called at uStageField.cpp:397)
//   in uStageFieldCtrl::checkPlayerRange at 0x00d2d699-0x00d2d73e (called at uStageField.cpp:628)
// MtVector3 uStageFieldCtrl::getMyPlayerPos();

// Address: 0x00d2d670 - 0x00d2d7ad (317 bytes)
__attribute__((weak)) bool uStageFieldCtrl::checkPlayerRange(s32 x, s32 z) {
    // local: MtVector3 plPos;
    DDON_STUB("uStageFieldCtrl::checkPlayerRange")
    return {};
}

// Address: 0x00d2d7b0 - 0x00d2d991 (481 bytes)
__attribute__((weak)) bool uStageFieldCtrl::checkPlayerRangePos(s32 x, s32 z, MtVector3& pos) const {
    // local: const MtVector3 split;
    // local: s32 splitX;
    // local: f32 enableLength;
    // local: f32 tc;
    // local: f32 rad_atc;
    // local: f32 ts;
    // local: f32 Compensation;
    // local: f32 ex;
    // local: const MtVector3 splitCenter;
    // local: f32 length;
    // local: const MtVector3 offset;
    // local: const MtVector3 plXZPos;
    // local: const MtVector3 plPos;
    // local: const MtVector3 splitPos;
    // local: const MtVector3 baseVector;
    // local: MtVector3 ar;
    // local: MtVector3 subvec;
    DDON_STUB("uStageFieldCtrl::checkPlayerRangePos")
    return {};
}

// No out-of-line body: 3 inlined copies in 3 functions (199 bytes)
//   in uStageFieldCtrl::updateLot at 0x00d2c33f-0x00d2c381 (called at uStageField.cpp:754)
//   in uStageFieldCtrl::updateArc at 0x00d2cd00-0x00d2cd45 (called at uStageField.cpp:970)
//   in uStageFieldCtrl::setBlockArcLoad at 0x00d2da47-0x00d2da87 (called at uStageField.cpp:1078)
// void uStageFieldCtrl::calcEnableSplitAreaRange(s32 areaX, s32 areaZ, s32& xmin, s32& xmax, s32& zmin, s32& zmax) const;

// Address: 0x00d2c320 - 0x00d2c821 (1281 bytes)
__attribute__((weak)) bool uStageFieldCtrl::updateLot(bool isBlocking, bool update) {
    // local: bool ans;
    // local: s32 xmax;
    // local: s32 xmin;
    // local: s32 zmax;
    // local: u32 idx;
    // local: s32 zmin;
    // local: s32 x;
    // local: s32 z;
    // local: cSplitLot* pSplitLot;
    // local: bool outside;
    // local: bool setEnable;
    // local: u32 i;
    DDON_STUB("uStageFieldCtrl::updateLot")
    return {};
}

// No out-of-line body: 1 inlined copy in 1 function (51 bytes)
//   in uStageFieldCtrl::setup at 0x00d2c2b2-0x00d2c2e5 (called at uStageField.cpp:148)
// void uStageFieldCtrl::setLotResource();

// No out-of-line body: no code in the ELF
// bool uStageFieldCtrl::isSetResourceSplitLot(s32 x, s32 z, bool update);

// Address: 0x00d2cce0 - 0x00d2d095 (949 bytes)
__attribute__((weak)) bool uStageFieldCtrl::updateArc(bool isBlocking, bool update) {
    // local: bool ans;
    // local: s32 xmax;
    // local: s32 xmin;
    // local: s32 zmax;
    // local: u32 idx;
    // local: s32 zmin;
    // local: s32 x;
    // local: s32 z;
    // local: cSplitArc* pSplitArc;
    // local: bool outside;
    // local: bool setEnable;
    // local: u32 i;
    DDON_STUB("uStageFieldCtrl::updateArc")
    return {};
}

// No out-of-line body: 1 inlined copy in 1 function (121 bytes)
//   in uStageFieldCtrl::updateLot at 0x00d2c560-0x00d2c57d, 0x00d2c5d1-0x00d2c62d (called at uStageField.cpp:852)
// bool uStageFieldCtrl::isBlockArcLoadOk(s32 x, s32 z);

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_uStageField.cpp at 0x00d2ddaf-0x00d2ddec (called at uStageField.cpp:43)
//   in _GLOBAL__sub_I_uStageField.cpp at 0x00d2ddaf-0x00d2ddec (called at uStageField.h:30)
// uStageFieldCtrl::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00d2c010 - 0x00d2c050 (64 bytes)
__attribute__((weak)) MtObject* uStageFieldCtrl::MyDTI::newInstance() const {
    DDON_STUB("uStageFieldCtrl::MyDTI::newInstance")
    return nullptr;
}

// Instance at 0x01b24bf0 - 0x01b24bf5 (5 bytes) of the generic MtTypedArray<T>::~MtTypedArray
// Proven from the ELF: the body oracle checks this instance (022 D5).
template MtTypedArray<cSplitArc>::~MtTypedArray();

// Instance at 0x01b24c20 - 0x01b24c25 (5 bytes) of the generic MtTypedArray<T>::~MtTypedArray
// Proven from the ELF: the body oracle checks this instance (022 D5).
template MtTypedArray<cSplitLot>::~MtTypedArray();

