// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "cpAltitudeFallCtrl.h"
#include "../shared/MtAllocator.h"
#include "../shared/MtDTI.h"
#include "../shared/MtMath.h"
#include "../shared/MtMemoryAllocator.h"
#include "../shared/cDelegate.h"
#include "../shared/cpComponent.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* cpAltitudeFallCtrl::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cpAltitudeFallCtrl::usage();

// Address: 0x01a55850 - 0x01a55858 (8 bytes)
const MtDTI& cpAltitudeFallCtrl::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cpAltitudeFallCtrl::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* cpAltitudeFallCtrl::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::cpAltitudeFallCtrl::DTI);
}

// No out-of-line body: no code in the ELF
// void cpAltitudeFallCtrl::setAllocator(u32);

// Address: 0x0042cf10 - 0x0042cf50 (64 bytes)
void* cpAltitudeFallCtrl::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::cpAltitudeFallCtrl::getAllocator()->memAlloc(sz, align, ::cpAltitudeFallCtrl::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* cpAltitudeFallCtrl::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cpAltitudeFallCtrl::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cpAltitudeFallCtrl::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void cpAltitudeFallCtrl::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cpAltitudeFallCtrl::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cpAltitudeFallCtrl::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cpAltitudeFallCtrl::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cpAltitudeFallCtrl::operator delete[](void* p_addr, u32 align);

// Address: 0x0042cfc0 - 0x0042d05c (156 bytes)
cpAltitudeFallCtrl::cpAltitudeFallCtrl() {
    DDON_STUB("cpAltitudeFallCtrl::cpAltitudeFallCtrl")
    /* stub */
}

// Address: 0x0042d060 - 0x0042d0bb (91 bytes)
// Also emitted as: _ZN18cpAltitudeFallCtrlD0Ev at 0x0042d0c0
cpAltitudeFallCtrl::~cpAltitudeFallCtrl() {
    DDON_STUB("cpAltitudeFallCtrl::~cpAltitudeFallCtrl")
    /* stub */
}

// Address: 0x0042d140 - 0x0042d263 (291 bytes)
__attribute__((weak)) void cpAltitudeFallCtrl::setup() {
    // local: f32 height;
    DDON_STUB("cpAltitudeFallCtrl::setup")
    /* stub */
}

// No out-of-line body: 1 inlined copy in 1 function (76 bytes)
//   in cpAltitudeFallCtrl::after at 0x0042d34b-0x0042d397 (called at cpAltitudeFallCtrl.cpp:145)
// void cpAltitudeFallCtrl::init();

// Address: 0x0042d610 - 0x0042d615 (5 bytes)
void cpAltitudeFallCtrl::updatePtr() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::cpComponent::updatePtr();
}

// Address: 0x0042d270 - 0x0042d5cc (860 bytes)
__attribute__((weak)) void cpAltitudeFallCtrl::after() {
    // local: bool isActiveAltitudeFall;
    // local: f32 damageHeight;
    DDON_STUB("cpAltitudeFallCtrl::after")
    /* stub */
}

// Address: 0x0042d5d0 - 0x0042d5ff (47 bytes)
__attribute__((weak)) void cpAltitudeFallCtrl::setCharParamEnemy(cCharParamEnemy* pParam) {
    DDON_STUB("cpAltitudeFallCtrl::setCharParamEnemy")
    /* stub */
}

// Address: 0x0042d630 - 0x0042da0f (991 bytes)
__attribute__((weak)) void cpAltitudeFallCtrl::callbackHitLand() {
    // local: bool invalid_land_action;
    // local: Param Param;
    // local: TriangleInfo HitInfo;
    // local: MtLineSegment sg;
    DDON_STUB("cpAltitudeFallCtrl::callbackHitLand")
    /* stub */
}

// Address: 0x0042da10 - 0x0042da61 (81 bytes)
__attribute__((weak)) void cpAltitudeFallCtrl::callbackFall() {
    DDON_STUB("cpAltitudeFallCtrl::callbackFall")
    /* stub */
}

// No out-of-line body: 1 inlined copy in 1 function (8 bytes)
//   in uHuman::callbackAltitudeFallLand at 0x00c86d31-0x00c86d39 (called at uHuman.cpp:8052)
// f32 cpAltitudeFallCtrl::getFallDistance();

// No out-of-line body: 3 inlined copies in 3 functions (24 bytes)
//   in cHumanActDashLand::move at 0x00233a55-0x00233a5d (called at cHumanAction.cpp:3457)
//   in cJob01Custom14Finish::init at 0x0027dea6-0x0027deae (called at cJob01Action.cpp:5493)
//   in cJob07Custom14Land::init at 0x002c4d58-0x002c4d60 (called at cJob07Action.cpp:3880)
// f32 cpAltitudeFallCtrl::getLastFallDistance();

// No out-of-line body: no code in the ELF
// f32 cpAltitudeFallCtrl::getDamageHeight();

// No out-of-line body: no code in the ELF
// bool cpAltitudeFallCtrl::getIsFalling();

// No out-of-line body: 6 inlined copies in 3 functions (254 bytes)
//   in cpAltitudeFallCtrl::after at 0x0042d2be-0x0042d2c6, 0x0042d2d0-0x0042d2ea, 0x0042d397-0x0042d3ae (called at cpAltitudeFallCtrl.cpp:153)
//   in cpAltitudeFallCtrl::after at 0x0042d308-0x0042d31b, 0x0042d3c9-0x0042d3e0 (called at cpAltitudeFallCtrl.cpp:139)
//   in cpAltitudeFallCtrl::after at 0x0042d3bd-0x0042d3c9, 0x0042d3f0-0x0042d407 (called at cpAltitudeFallCtrl.cpp:154)
//   and 3 more (every copy is in <bundle>.inlined.json)
// MtVector3 cpAltitudeFallCtrl::getPos();

// No out-of-line body: no code in the ELF
// void cpAltitudeFallCtrl::Invalidation();

// No out-of-line body: no code in the ELF
// void cpAltitudeFallCtrl::Activation();

// No out-of-line body: 10 inlined copies in 10 functions (217 bytes)
//   in cJob10AirAttackLLand::init at 0x000e20e3-0x000e20f5 (called at cJob10Action.cpp:594)
//   in cJob01AttackAirL01::move at 0x00274541-0x00274568 (called at cJob01Action.cpp:297)
//   in cJob02AttackAirLLand00::init at 0x00284402-0x00284411, 0x00284435-0x0028443b (called at cJob02Action.cpp:2411)
//   and 7 more (every copy is in <bundle>.inlined.json)
// s8 cpAltitudeFallCtrl::getLastHeigthLevel(f32 low, f32 middle);

// No out-of-line body: 1 inlined copy in 1 function (8 bytes)
//   in uHuman::setup at 0x00c734a5-0x00c734ad (called at uHuman.cpp:2851)
// void cpAltitudeFallCtrl::setDamageHeight(f32 height);

// No out-of-line body: no code in the ELF
// bool cpAltitudeFallCtrl::isAltitudeFall() const;

// No out-of-line body: 2 inlined copies in 2 functions (481 bytes)
//   in cpAltitudeFallCtrl::after at 0x0042d478-0x0042d53d (called at cpAltitudeFallCtrl.cpp:168)
//   in cpAltitudeFallCtrl::callbackHitLand at 0x0042d828-0x0042d944 (called at cpAltitudeFallCtrl.cpp:223)
// f32 cpAltitudeFallCtrl::getDamageHeightWithAbility();

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_cpAltitudeFallCtrl.cpp at 0x0042db6f-0x0042dbac (called at cpAltitudeFallCtrl.cpp:32)
//   in _GLOBAL__sub_I_cpAltitudeFallCtrl.cpp at 0x0042db6f-0x0042dbac (called at cpAltitudeFallCtrl.h:31)
// cpAltitudeFallCtrl::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x0042ce40 - 0x0042cf07 (199 bytes)
__attribute__((weak)) MtObject* cpAltitudeFallCtrl::MyDTI::newInstance() const {
    DDON_STUB("cpAltitudeFallCtrl::MyDTI::newInstance")
    return nullptr;
}

