// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "cEmWorkRateCtrl.h"
#include "../shared/MtAllocator.h"
#include "../shared/MtDTI.h"
#include "../shared/MtMemoryAllocator.h"
#include "../shared/MtObject.h"
#include "../shared/cResource.h"
#include "nStatusEnemy.h"
#include "../rEmWorkRateTable/rEmWorkRateTable.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* cEmWorkRateCtrl::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void cEmWorkRateCtrl::usage();

// Address: 0x0196d210 - 0x0196d218 (8 bytes)
const MtDTI& cEmWorkRateCtrl::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return cEmWorkRateCtrl::DTI;
}

// No out-of-line body: 2 inlined copies in 2 functions (30 bytes)
//   in cEmWorkRateCtrl::MyDTI::newInstance at 0x000b9be4-0x000b9bf6 (called at cEmWorkRateCtrl.cpp:28)
//   in cEmWorkRateCtrl::~cEmWorkRateCtrl at 0x000b9d4d-0x000b9d59 (called at cEmWorkRateCtrl.cpp:28)
// MtAllocator* cEmWorkRateCtrl::getAllocator();

// No out-of-line body: no code in the ELF
// void cEmWorkRateCtrl::setAllocator(u32);

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
// inferred: parameters written where their values stand in every inlined copy
inline void* cEmWorkRateCtrl::operator new(size_t sz, u32 align) {
    return ::MtMemoryAllocator::getAllocator(::cEmWorkRateCtrl::DTI)->memAlloc(sz, align, ::cEmWorkRateCtrl::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* cEmWorkRateCtrl::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* cEmWorkRateCtrl::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* cEmWorkRateCtrl::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void cEmWorkRateCtrl::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::cEmWorkRateCtrl::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void cEmWorkRateCtrl::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void cEmWorkRateCtrl::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void cEmWorkRateCtrl::operator delete[](void* p_addr, u32 align);

// Address: 0x000b9cb0 - 0x000b9cdf (47 bytes)
cEmWorkRateCtrl::cEmWorkRateCtrl() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mpEmWorkRateTableRes = static_cast<rEmWorkRateTable*>(nullptr);
    this->mpEnemy = static_cast<uEnemy*>(nullptr);
    this->mStatusNo = static_cast<u32>(4294967295);
    this->mStatusType = static_cast<nStatusEnemy::WORKRATE_STATUS_TYPE>(0);
    this->mStatusPriority = static_cast<u32>(1);
}

// Address: 0x000b9ce0 - 0x000b9d14 (52 bytes)
// Also emitted as: _ZN15cEmWorkRateCtrlD0Ev at 0x000b9d20
cEmWorkRateCtrl::~cEmWorkRateCtrl() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpEmWorkRateTableRes == static_cast<rEmWorkRateTable*>(nullptr)) {
        return;
    }
    this->mpEmWorkRateTableRes->::cResource::release();
    this->mpEmWorkRateTableRes = static_cast<rEmWorkRateTable*>(nullptr);
}

// No out-of-line body: no code in the ELF
// void cEmWorkRateCtrl::setup();

// Address: 0x000b9d90 - 0x000b9f22 (402 bytes)
__attribute__((weak)) void cEmWorkRateCtrl::createProperty(MtPropertyList& s) {
    DDON_STUB("cEmWorkRateCtrl::createProperty")
    /* stub */
}

// No out-of-line body: no code in the ELF
// void cEmWorkRateCtrl::updatePtr();

// Address: 0x000b9d80 - 0x000b9d85 (5 bytes)
void cEmWorkRateCtrl::setOwner(uEnemy* pEnemy) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mpEnemy = pEnemy;
}

// Address: 0x000ba060 - 0x000ba151 (241 bytes)
__attribute__((weak)) void cEmWorkRateCtrl::changeWorkRateNo(u32 statusNo, nStatusEnemy::WORKRATE_CHANGE_TYPE changeType) {
    // local: const cEmWorkRateTable* pWorkRateData;
    // local: WORKRATE_STATUS_TYPE statusType;
    // local: cpWorkRate* pCpWorkRate;
    // local: cEmWorkRateTable* pResDataWRate;
    DDON_STUB("cEmWorkRateCtrl::changeWorkRateNo")
    /* stub */
}

// Address: 0x000ba180 - 0x000ba1bd (61 bytes)
__attribute__((weak)) void cEmWorkRateCtrl::setEmWorkRateRes(rEmWorkRateTable* pRes) {
    DDON_STUB("cEmWorkRateCtrl::setEmWorkRateRes")
    /* stub */
}

// No out-of-line body: 1 inlined copy in 1 function (7 bytes)
//   in cpStatusChange::setToContextAllBit at 0x0053b66d-0x0053b674 (called at cpStatusChange.cpp:2338)
// u32 cEmWorkRateCtrl::getEmWorkRateStatusNo() const;

// Address: 0x000b9f30 - 0x000ba049 (281 bytes)
__attribute__((weak)) void cEmWorkRateCtrl::updateEmWorkRate() {
    // local: uEnemy* pEnemy;
    // local: u32 priority;
    // local: u32 statusNo;
    // local: u32 dataNum;
    // local: u32 i;
    // local: const cEmWorkRateTable* pData;
    // local: u32 checkPrioroty;
    // local: bool isApply;
    // local: WORKRATE_STATUS_TYPE statusType;
    DDON_STUB("cEmWorkRateCtrl::updateEmWorkRate")
    /* stub */
}

// No out-of-line body: 1 inlined copy in 1 function (17 bytes)
//   in cEmWorkRateCtrl::changeWorkRateNo at 0x000ba0d1-0x000ba0e2 (called at cEmWorkRateCtrl.cpp:255)
// nStatusEnemy::WORKRATE_STATUS_TYPE cEmWorkRateCtrl::getStatusType(nStatusEnemy::WORKRATE_CHANGE_TYPE changeType, const cEmWorkRateTable* pTableData) const;

// No out-of-line body: 1 inlined copy in 1 function (14 bytes)
//   in cEmWorkRateCtrl::updateEmWorkRate at 0x000b9fc4-0x000b9fc7, 0x000b9fcd-0x000b9fd8 (called at cEmWorkRateCtrl.cpp:175)
// u32 cEmWorkRateCtrl::getStatusPriority(nStatusEnemy::WORKRATE_STATUS_TYPE type) const;

// No out-of-line body: 1 inlined copy in 1 function (34 bytes)
//   in cEmWorkRateCtrl::changeWorkRateNo at 0x000ba0a5-0x000ba0c7 (called at cEmWorkRateCtrl.cpp:246)
// const cEmWorkRateTable* cEmWorkRateCtrl::findEmWorkRateData(u32 statusNo) const;

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_cEmWorkRateCtrl.cpp at 0x000ba2cf-0x000ba30c (called at cEmWorkRateCtrl.cpp:28)
//   in _GLOBAL__sub_I_cEmWorkRateCtrl.cpp at 0x000ba2cf-0x000ba30c (called at cEmWorkRateCtrl.h:34)
// cEmWorkRateCtrl::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x000b9be0 - 0x000b9c40 (96 bytes)
MtObject* cEmWorkRateCtrl::MyDTI::newInstance() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return new (static_cast<u32>(16)) ::cEmWorkRateCtrl;
}

