// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "MtCharset.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtCharset::MtCharset();

// No out-of-line body: no code in the ELF
// MtCharset::~MtCharset();

// Address: 0x00d78c50 - 0x00d78c55 (5 bytes)
__attribute__((weak)) u32 MtCharset::convertUTF8toSJIS(MT_CTSTR pUtf8Str, s32 nUtf8Len, char* pSjisBuffer, s32 nSjisLen) {
    DDON_STUB("MtCharset::convertUTF8toSJIS")
    return {};
}

// Address: 0x00d78c60 - 0x00d78c65 (5 bytes)
__attribute__((weak)) u32 MtCharset::convertSJIStoUTF8(const char* pSjisStr, s32 nSjisLen, MT_STR pUtf8Buffer, s32 nUtf8Len) {
    DDON_STUB("MtCharset::convertSJIStoUTF8")
    return {};
}

// No out-of-line body: no code in the ELF
// u32 MtCharset::convertSJIStoJIS(const char* pSjisStr, s32 nSjisLen, char* pJisBuffer, s32 nJisLen);

// Address: 0x00d78c80 - 0x00d79017 (919 bytes)
__attribute__((weak)) MtCharset::eEncodingType MtCharset::estimateCharEncoding(const void* pStringIn, s32 nLength) {
    // local: const u8 bom[3];
    // local: const u8* pString;
    // local: eEncodingType ret;
    // local: u32 sjis_byte;
    // local: u32 utf8_byte;
    // local: eSearchState state;
    // local: u32 sizeByte;
    // local: eElementType typeElement;
    // local: s32 i;
    // local: const u8 c;
    // local: const u8 c2;
    // local: u32 sizeByteOrigin;
    // local: u32 sizeByte;
    // local: eSearchState state;
    // local: const bool isFoundBom;
    // local: s32 i;
    // local: const u8 c;
    DDON_STUB("MtCharset::estimateCharEncoding")
    return {};
}

// Address: 0x00d79020 - 0x00d7906d (77 bytes)
__attribute__((weak)) bool MtCharset::isAsciiString(MT_CTSTR pString, s32 nLength) {
    // local: const u8* pCheck;
    // local: bool isConsistOfAscii;
    // local: const u8* pTail;
    DDON_STUB("MtCharset::isAsciiString")
    return {};
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// bool MtCharset::isSjisChar(MT_CTSTR p2byteStr);

// No out-of-line body: no code in the ELF
// bool MtCharset::isSjisChar(MT_CTSTR pSJISString, u32 pos);

// No out-of-line body: no code in the ELF
// s32 MtCharset::calcUTF8ByteInSJIS(MT_CTSTR pUtf8Str, s32 nPos);

// No out-of-line body: no code in the ELF
// s32 MtCharset::countCharBytesUTF8AsSJIS(MT_CTSTR pUtf8Str);

// No out-of-line body: no code in the ELF
// s32 MtCharset::validateUTF8(MT_CTSTR pUtf8Str, s32 nLength);

// Address: 0x00d785b0 - 0x00d78626 (118 bytes)
__attribute__((weak)) u32 MtCharset::getCharLengthUTF8(const u8 c) {
    // local: u32 nLegnth;
    DDON_STUB("MtCharset::getCharLengthUTF8")
    return {};
}

// Address: 0x00d78940 - 0x00d78a04 (196 bytes)
__attribute__((weak)) u32 MtCharset::getCharLengthSJIS(const u8 c, const u8 c2, MtCharset::eElementType* pType) {
    // local: u32 nLegnth;
    // local: eElementType type;
    DDON_STUB("MtCharset::getCharLengthSJIS")
    return {};
}

// No out-of-line body: compiled for inlining, but no inlined copy is in the ELF
// u32 MtCharset::getCharLengthUTF16(const u16 c, bool* pSurrogate);

// Address: 0x00d790b0 - 0x00d79189 (217 bytes)
__attribute__((weak)) u32 MtCharset::lengthUTF8(MT_CTSTR pUtf8Str, s32 nUtf8Len) {
    // local: const u8* ptr;
    // local: u32 count;
    // local: s32 pos;
    DDON_STUB("MtCharset::lengthUTF8")
    return {};
}

// Address: 0x00d79190 - 0x00d79282 (242 bytes)
__attribute__((weak)) u32 MtCharset::getCharUTF8(MT_STR pChar, MT_CTSTR pUtf8Str, u32 index) {
    // local: const u8* ptr;
    // local: u32 add;
    // local: u32 pos;
    // local: u32 count;
    // local: u32 length;
    // local: u32 i;
    DDON_STUB("MtCharset::getCharUTF8")
    return {};
}

// Address: 0x00d79290 - 0x00d793a7 (279 bytes)
__attribute__((weak)) u32 MtCharset::getUnicodeUTF8(MT_CTSTR pUtf8Str) {
    // local: const u8* ptr;
    // local: u32 ret;
    DDON_STUB("MtCharset::getUnicodeUTF8")
    return {};
}

// No out-of-line body: no code in the ELF
// u32 MtCharset::convertUTF8toUnicode(MT_CTSTR pUtf8Str, s32 nUtf8Len, u32* pUnicodeBuffer, s32 nUnicodeLen);

// No out-of-line body: no code in the ELF
// bool MtCharset::isUTF16hasSurrogatePairs(const void* pUtf16Str, s32 nUtf16Len, bool isBEIfNonBOM);

// Address: 0x00d793c0 - 0x00d793c9 (9 bytes)
__attribute__((weak)) u32 MtCharset::convertUTF16toUTF8(const void* pUtf16Str, s32 nUtf16Len, void* pUtf8Buffer, s32 nUtf8Len, bool isBEIfNonBOM) {
    DDON_STUB("MtCharset::convertUTF16toUTF8")
    return {};
}

// No out-of-line body: no code in the ELF
// u32 MtCharset::convertUTF8toUTF16(const void* pUtf8Str, s32 nUtf8Len, void* pUtf16Buffer, s32 nUtf16Len, MtCharset::eUTF16Type convTarget);

// Address: 0x00d78320 - 0x00d785a9 (649 bytes)
__attribute__((weak)) u32 MtCharset::fromUTF8toSJIS(const u8* pUTF8, const s32 nUTF8, char* pSJIS, const s32 nSJIS) {
    // local: s32 tmpSJIS;
    // local: bool isErrorOccurred;
    // local: s32 tmpUTF8;
    // local: const u8 c;
    // local: bool isFound;
    // local: const u32 byte;
    // local: u32 i;
    // local: const u32 wordCmp;
    // local: const u32 wordCmpr;
    // local: const code_mapper* pMapper;
    // local: const s32 nChar;
    // local: u8* pAsSJIS;
    DDON_STUB("MtCharset::fromUTF8toSJIS")
    return {};
}

// Address: 0x00d78630 - 0x00d7893b (779 bytes)
__attribute__((weak)) u32 MtCharset::fromSJIStoUTF8(const char* pSJIS, const s32 nSJIS, u8* pUTF8, const s32 nUTF8) {
    // local: s32 tmpUTF8;
    // local: bool isErrorOccurred;
    // local: s32 tmpSJIS;
    // local: u32 byte;
    // local: eElementType type;
    // local: const u8 c;
    // local: const u8 c2;
    // local: u32 i;
    // local: const u8* pAsSJIS;
    // local: const code_mapper* pMapper;
    // local: const s32 len;
    // local: u32 i;
    // local: const code_mapper* pMapper;
    // local: const u8* pAsSJIS;
    // local: const s32 len;
    DDON_STUB("MtCharset::fromSJIStoUTF8")
    return {};
}

// No out-of-line body: no code in the ELF
// u32 MtCharset::fromSJIStoJIS(const char* pSJIS, const s32 nSJIS, char* pJIS, const s32 nJISIn);

// No out-of-line body: no code in the ELF
// u32 MtCharset::fromJIStoSJIS(const char* pJIS, const s32 nJIS, char* pSJIS, const s32 nSJISIn);

// Address: 0x00d78a20 - 0x00d78c26 (518 bytes)
__attribute__((weak)) u32 MtCharset::fromUTF16toUTF8(const u16* pUTF16, const s32 nUTF16, u8* pUTF8, const s32 nUTF8, bool isBEIfNonBOM) {
    // local: s32 tmpUTF16;
    // local: s32 tmpUTF8;
    // local: bool isErrorOccurred;
    // local: bool isBE;
    // local: bool isLE;
    // local: const bool hasBOM;
    // local: const u16* p;
    // local: bool isSurrogate;
    // local: u32 byte;
    // local: const u16 c;
    DDON_STUB("MtCharset::fromUTF16toUTF8")
    return {};
}

// No out-of-line body: no code in the ELF
// u32 MtCharset::fromUTF8toUTF16(const u8* pUTF8, const s32 nUTF8, u16* pUTF16, const s32 nUTF16, const MtCharset::eUTF16Type convTarget);

// Address: 0x00d793e0 - 0x00d793ff (31 bytes)
MtCharset::cMultiByteSolver::cMultiByteSolver() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mLeadByte = static_cast<u8>(0);
    this->mCurrentByte = static_cast<u8>(0);
    this->mByteLength = static_cast<u32>(0);
    this->mEndIndex = static_cast<u32>(0);
}

// Address: 0x00d79430 - 0x00d79431 (1 bytes)
// Also emitted as: _ZN9MtCharset16cMultiByteSolverD0Ev at 0x00d79440
MtCharset::cMultiByteSolver::~cMultiByteSolver() {
    // Empty in the binary (a single `ret`).
}

// Address: 0x00d79400 - 0x00d79428 (40 bytes)
__attribute__((weak)) void MtCharset::cMultiByteSolver::init(MT_CTSTR str) {
    // local: const u8* cacheString;
    // local: const s32 cacheLength;
    DDON_STUB("MtCharset::cMultiByteSolver::init")
    /* stub */
}

// Address: 0x00d79450 - 0x00d79538 (232 bytes)
__attribute__((weak)) void MtCharset::cMultiByteSolver::solve(MT_CTSTR str, u32 at, u32 len) {
    // local: const u8 c;
    // local: const u32 size;
    DDON_STUB("MtCharset::cMultiByteSolver::solve")
    /* stub */
}

// Address: 0x00d79540 - 0x00d79548 (8 bytes)
bool MtCharset::cMultiByteSolver::isDividable() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mEndIndex == static_cast<u32>(0);
}

// Address: 0x00d79550 - 0x00d79585 (53 bytes)
__attribute__((weak)) bool MtCharset::cMultiByteSolver::isLeadByte() const {
    // local: bool isLB;
    DDON_STUB("MtCharset::cMultiByteSolver::isLeadByte")
    return {};
}

// Address: 0x00d79590 - 0x00d79594 (4 bytes)
u32 MtCharset::cMultiByteSolver::getRemainBytes() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mEndIndex;
}

// No out-of-line body: no code in the ELF
// MtCharset::cSolver::cSolver();

// Defined in the class as `{}`: no code anywhere in the ELF.
// MtCharset::cSolver::~cSolver();

