// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "sChat.h"
#include "../shared/Community.h"
#include "../shared/MtAllocator.h"
#include "../shared/MtDTI.h"
#include "../shared/MtMemoryAllocator.h"
#include "../shared/MtString.h"
#include "../shared/MtTime.h"
#include "../shared/cSystem.h"
#include "../shared/nGUIExt.h"
#include "../shared/sKeyboardInterface.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* sChat::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void sChat::usage();

// Address: 0x01ac1af0 - 0x01ac1af8 (8 bytes)
const MtDTI& sChat::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return sChat::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* sChat::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::sChat::DTI);
}

// No out-of-line body: no code in the ELF
// void sChat::setAllocator(u32);

// Address: 0x007469d0 - 0x00746a10 (64 bytes)
void* sChat::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::sChat::getAllocator()->memAlloc(sz, align, ::sChat::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* sChat::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* sChat::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* sChat::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void sChat::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::sChat::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void sChat::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void sChat::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void sChat::operator delete[](void* p_addr, u32 align);

// Address: 0x00746a80 - 0x0074708d (1549 bytes)
sChat::sChat() {
    DDON_STUB("sChat::sChat")
    /* stub */
}

// Address: 0x007471e0 - 0x00747496 (694 bytes)
// Also emitted as: _ZN5sChatD0Ev at 0x007474a0
sChat::~sChat() {
    DDON_STUB("sChat::~sChat")
    /* stub */
}

// Address: 0x007474d0 - 0x007474d5 (5 bytes)
MtUI* sChat::createUI(MtProperty& prop) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->::cSystem::createUI(prop);
}

// Address: 0x007474e0 - 0x0074767d (413 bytes)
__attribute__((weak)) void sChat::createProperty(MtPropertyList& s) {
    DDON_STUB("sChat::createProperty")
    /* stub */
}

// Address: 0x00747ca0 - 0x00747ce7 (71 bytes)
__attribute__((weak)) void sChat::move() {
    // local: const f32 delta_seconds;
    // local: f32 shout_wait_time;
    DDON_STUB("sChat::move")
    /* stub */
}

// Address: 0x00747cf0 - 0x00747cf1 (1 bytes)
__attribute__((weak)) void sChat::reset() {
    // Empty in the binary (a single `ret`).
}

// No out-of-line body: 257 inlined copies in 181 functions (2664 bytes)
//   in aGame::init at 0x00002147-0x00002151 (called at aGame.cpp:257)
//   in aGame::final at 0x00002558-0x00002562 (called at aGame.cpp:419)
//   in aMenu::move at 0x00005944-0x0000594e (called at aMenu.cpp:1117)
//   and 254 more (every copy is in <bundle>.inlined.json)
// sChat* sChat::getInstance();

// Address: 0x007476e0 - 0x007476f2 (18 bytes)
void sChat::init() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mIsChatEnable = true;
    this->mShoutWaitTime = 0.0f;
}

// Address: 0x00747700 - 0x00747a3a (826 bytes)
__attribute__((weak)) void sChat::final() {
    DDON_STUB("sChat::final")
    /* stub */
}

// No out-of-line body: 2 inlined copies in 2 functions (1215 bytes)
//   in sChat::sChat at 0x00746d5c-0x00746fb9 (called at sChat.cpp:176)
//   in sChat::final at 0x007477b7-0x00747a19 (called at sChat.cpp:438)
// void sChat::resetLog();

// Address: 0x00747a40 - 0x00747c98 (600 bytes)
__attribute__((weak)) void sChat::clearMsgQueue(sChat::stMsgQueue& MsgQue) {
    // local: u32 i;
    DDON_STUB("sChat::clearMsgQueue")
    /* stub */
}

// Address: 0x00747680 - 0x00747687 (7 bytes)
bool sChat::checkChatOk() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mIsChatEnable;
}

// Address: 0x00747690 - 0x007476be (46 bytes)
void sChat::setKeyboardSetting(MT_CTSTR pMsgDefault) {
    // local: s32 char_num;
    // Proven from the ELF: the body oracle checks this body (022 D5).
    ::sKeyboardInterface::getInstance()->::sKeyboardInterface::setKeyboardSetting(static_cast<sKeyboardInterface::KEYBOARD_TYPE>(2), "", (pMsgDefault == static_cast<MT_CTSTR>(nullptr)) ? "" : pMsgDefault, static_cast<s32>(32));
}

// No out-of-line body: no code in the ELF
// void sChat::requestSoftKeyboardChat();

// No out-of-line body: no code in the ELF
// u32 sChat::getChatState();

// No out-of-line body: 9 inlined copies in 3 functions (70 bytes)
//   in sChat::sendMessage at 0x007480d9-0x007480e2 (called at sChat.cpp:785)
//   in sChat::sendMessage at 0x00748100-0x0074810c (called at sChat.cpp:780)
//   in sChat::sendMessage at 0x0074814a-0x00748151 (called at sChat.cpp:819)
//   and 6 more (every copy is in <bundle>.inlined.json)
// MT_CHAR* sChat::getOutputText_utf8();

// No out-of-line body: no code in the ELF
// u32 sChat::getOutputTextLength();

// No out-of-line body: no code in the ELF
// void sChat::setOutputTextLength(u32);

// No out-of-line body: 3 inlined copies in 3 functions (126 bytes)
//   in sChat::sendMessage at 0x00747fb6-0x00747fc4, 0x00747fd0-0x00747fe8 (called at sChat.cpp:761)
//   in sChat::sendPawnMessage at 0x00748c73-0x00748c9f (called at sChat.cpp:879)
//   in sChat::sendClanNtcMessage at 0x00748d6b-0x00748d97 (called at sChat.cpp:915)
// void sChat::setOutputText_utf8(MT_CTSTR msg, u32 size);

// No out-of-line body: no code in the ELF
// MT_CTSTR sChat::getOutputTextDefault();

// No out-of-line body: no code in the ELF
// void sChat::setOutputTextDefault(MT_CTSTR);

// No out-of-line body: 14 inlined copies in 12 functions (175 bytes)
//   in sGUIExt::cChat::bootup at 0x007a4abf-0x007a4ac9 (called at sGUIExt.cpp:23067)
//   in sGUIExt::setupChatTell at 0x007a4e32-0x007a4e3c (called at sGUIExt.cpp:23067)
//   in sGUIExt::cSCM::execSCCPlt at 0x007b1dc5-0x007b1dcb (called at sGUIExt.cpp:22226)
//   and 11 more (every copy is in <bundle>.inlined.json)
// void sChat::setChatArea(s32 chatArea);

// No out-of-line body: 1 inlined copy in 1 function (6 bytes)
//   in sChat::sendMessage at 0x00747dbc-0x00747dc2 (called at sChat.cpp:727)
// s32 sChat::getChatArea();

// No out-of-line body: no code in the ELF
// void sChat::setDispFilterGroup(s32);

// No out-of-line body: 1 inlined copy in 1 function (89 bytes)
//   in sChat::analyzeMessage at 0x00748e95-0x00748ee7, 0x00748f4a-0x00748f51 (called at sChat.cpp:966)
// MT_CTSTR sChat::getFixedPhrase(u32 fixedPhrase);

// Address: 0x00747d00 - 0x0074844c (1868 bytes)
__attribute__((weak)) bool sChat::sendMessage(MT_CTSTR message) {
    // local: const s32 chat_area;
    // local: const MtString& send_msg;
    // local: const MT_CTSTR msg_not_speak_a_while;
    DDON_STUB("sChat::sendMessage")
    return {};
}

// Address: 0x00748ba0 - 0x00748c03 (99 bytes)
__attribute__((weak)) void sChat::sendFixedMessage(u32 fixedPhrase) {
    // local: MT_CHAR sendStr[20];
    DDON_STUB("sChat::sendFixedMessage")
    /* stub */
}

// Address: 0x00748c10 - 0x00748cf2 (226 bytes)
__attribute__((weak)) void sChat::sendPawnMessage(s32 pawnIndex, u32 msgNo) {
    // local: MT_CHAR sendStr[20];
    DDON_STUB("sChat::sendPawnMessage")
    /* stub */
}

// Address: 0x00748d00 - 0x00748dce (206 bytes)
__attribute__((weak)) bool sChat::sendClanNtcMessage(MT_CTSTR message) {
    DDON_STUB("sChat::sendClanNtcMessage")
    return {};
}

// Address: 0x00748de0 - 0x00748f99 (441 bytes)
__attribute__((weak)) bool sChat::analyzeMessage(MT_CHAR* dstMsg, MT_CTSTR srcMsg, u32 size, s32 memberIndex, s32 type) {
    // local: s32 pawnIndex;
    // local: u32 msgNo;
    // local: s32 fixedMsgNo;
    // local: bool is_request_voice;
    DDON_STUB("sChat::analyzeMessage")
    return {};
}

// Address: 0x00748450 - 0x00748b8e (1854 bytes)
__attribute__((weak)) void sChat::addMessage(const MT_CHAR* msg, s32 filterGroup, MT_CTSTR name, bool isUTF8, MT_CTSTR pAnalizerMsg0, MT_CTSTR pAnalizerMsg1, s32 pAnalizerNum0, s32 pAnalizerNum1, u32 msgAttr, u32 characterId, MT_CTSTR pLastName, MT_CTSTR pClanName, MT_CTSTR pAnalizerMsg2, s32 pAnalizerNum2) {
    // local: stMsgQueue queue;
    // local: u32 size;
    DDON_STUB("sChat::addMessage")
    /* stub */
}

// Address: 0x00748fa0 - 0x007492d7 (823 bytes)
__attribute__((weak)) void sChat::addMsgQueue(sChat::stMsgQueue& queue) {
    // local: bool is_my_message;
    // local: u32 uSEId;
    DDON_STUB("sChat::addMsgQueue")
    /* stub */
}

// Address: 0x00749740 - 0x00749821 (225 bytes)
__attribute__((weak)) u32 sChat::getMsgQueue(sChat::stMsgQueue* * queueArray, u32 filterBit, s32 msgNum, s32 msgStart) {
    // local: s32 retNum;
    // local: s32 index;
    // local: u32 i;
    // local: stMsgQueue* pMsg;
    // local: s32 i;
    DDON_STUB("sChat::getMsgQueue")
    return {};
}

// No out-of-line body: no code in the ELF
// u32 sChat::getMsgQueueNum(sChat::stMsgQueue* * queueArray);

// Address: 0x00749830 - 0x00749837 (7 bytes)
__attribute__((weak)) bool sChat::checkFilter(s32 filterGroup, s32 filterBit) {
    // local: u32 checkBit;
    DDON_STUB("sChat::checkFilter")
    return {};
}

// No out-of-line body: 1 inlined copy in 1 function (92 bytes)
//   in sChat::addMsgQueue at 0x0074910b-0x00749115, 0x0074911a-0x0074916c (called at sChat.cpp:1124)
// void sChat::addMsgFilterGroup(sChat::stMsgQueue& msg);

// No out-of-line body: 1 inlined copy in 1 function (137 bytes)
//   in sChat::addMsgQueue at 0x00748ff3-0x0074907c (called at sChat.cpp:1113)
// void sChat::removeMsgFilterGroup(sChat::stMsgQueue& msg);

// Address: 0x007470a0 - 0x007471db (315 bytes)
__attribute__((weak)) void sChat::clearTellChat() {
    DDON_STUB("sChat::clearTellChat")
    /* stub */
}

// Address: 0x007499e0 - 0x00749a7a (154 bytes)
__attribute__((weak)) void sChat::setTellChat(u32 characterId, MT_CTSTR firstName, MT_CTSTR lastName, MT_CTSTR clanName) {
    // local: cAutoCriticalSection cs;
    DDON_STUB("sChat::setTellChat")
    /* stub */
}

// Address: 0x00749f20 - 0x00749f27 (7 bytes)
u32 sChat::getTellCharacterId() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mTellCharacter.m_unCharacterID;
}

// Address: 0x00749ca0 - 0x00749cea (74 bytes)
__attribute__((weak)) void sChat::makeTellCharacterName(MtString& rStr, nGUIExt::NAME_TYPE type) {
    DDON_STUB("sChat::makeTellCharacterName")
    /* stub */
}

// Address: 0x00749850 - 0x007499dd (397 bytes)
__attribute__((weak)) void sChat::clearTellCharacterHistory() {
    // local: s32 i;
    // local: CCommunityCharacterBaseInfo& tell_character;
    DDON_STUB("sChat::clearTellCharacterHistory")
    /* stub */
}

// Address: 0x007492f0 - 0x00749730 (1088 bytes)
__attribute__((weak)) void sChat::addTellCharacterHistory(u32 characterId, MT_CTSTR firstName, MT_CTSTR lastName, MT_CTSTR clanName, bool isLock) {
    // local: CCommunityCharacterBaseInfo* tell_character;
    // local: s32 history_index;
    // local: s32 i;
    // local: CCommunityCharacterBaseInfo* const char_info;
    // local: s32 empty_index;
    // local: const s32 last_index;
    // local: s32 i;
    DDON_STUB("sChat::addTellCharacterHistory")
    /* stub */
}

// No out-of-line body: no code in the ELF
// s32 sChat::getTellCharacterHistoryNum() const;

// Address: 0x00749a80 - 0x00749c9a (538 bytes)
__attribute__((weak)) bool sChat::setLastTellCharacterHistory(bool isLock) {
    // local: bool is_change_tell_character;
    // local: const CCommunityCharacterBaseInfo* const last_tell_character;
    // local: const u32 character_id;
    DDON_STUB("sChat::setLastTellCharacterHistory")
    return {};
}

// Address: 0x00749cf0 - 0x00749f1a (554 bytes)
__attribute__((weak)) bool sChat::setNextTellCharacterHistory(bool isLock) {
    // local: bool is_change_tell_character;
    // local: const s32 history_num;
    // local: const CCommunityCharacterBaseInfo* const tell_character;
    // local: const s32 history_index;
    // local: const u32 character_id;
    DDON_STUB("sChat::setNextTellCharacterHistory")
    return {};
}

// No out-of-line body: 1 inlined copy in 1 function (10 bytes)
//   in sChat::addMsgQueue at 0x0074928a-0x00749294 (called at sChat.cpp:1210)
// void sChat::setChatView();

// No out-of-line body: no code in the ELF
// MT_CTSTR sChat::getChatAreaStr(s32);

// No out-of-line body: no code in the ELF
// MT_CTSTR sChat::getChatFilterGroupStr(s32);

// No out-of-line body: no code in the ELF
// s32 sChat::getChatAreaFromFilterGroup(s32);

// No out-of-line body: no code in the ELF
// u32 sChat::getShoutIntervalTime() const;

// No out-of-line body: 2 inlined copies in 2 functions (30 bytes)
//   in aMenu::move at 0x0000594e-0x00005958 (called at aMenu.cpp:1117)
//   in sChat::sChat at 0x00747068-0x0074707c (called at sChat.cpp:211)
// void sChat::setShoutIntervalTime(u32 time);

// No out-of-line body: 1 inlined copy in 1 function (12 bytes)
//   in uGUIChat::updateDisp at 0x00a25c8a-0x00a25c96 (called at uGUIChat.cpp:3134)
// f32 sChat::getShoutWaitTime() const;

// No out-of-line body: no code in the ELF
// void sChat::setStrMessageSet(nCharacterData::stMessageSet& msgSet, MT_CTSTR str, s32 index);

// No out-of-line body: no code in the ELF
// MT_CTSTR sChat::getStrMessageSet(nCharacterData::stMessageSet& msgSet, s32 index);

// No out-of-line body: no code in the ELF
// void sChat::setNameMessageSet(nCharacterData::stMessageSet& msgSet, MT_CTSTR str);

// No out-of-line body: no code in the ELF
// MT_CTSTR sChat::getNameMessageSet(nCharacterData::stMessageSet& msgSet);

// No out-of-line body: no code in the ELF
// void sChat::putMessageSet(nCharacterData::stMessageSet& msgSet, s32 index);

// No out-of-line body: no code in the ELF
// void sChat::setMessageSetKeyboardSetting(MT_CTSTR defStr);

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_sChat.cpp at 0x0074a0b8-0x0074a0f5 (called at sChat.cpp:161)
//   in _GLOBAL__sub_I_sChat.cpp at 0x0074a0b8-0x0074a0f5 (called at sChat.h:200)
// sChat::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00746990 - 0x007469d0 (64 bytes)
__attribute__((weak)) MtObject* sChat::MyDTI::newInstance() const {
    DDON_STUB("sChat::MyDTI::newInstance")
    return nullptr;
}

