// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "uGUIPhotoAlbum.h"
#include "../shared/MtAllocator.h"
#include "../shared/MtCollection.h"
#include "../shared/MtDTI.h"
#include "../shared/MtMath.h"
#include "../shared/MtMemoryAllocator.h"
#include "../shared/MtObject.h"
#include "../shared/cControl.h"
#include "../shared/cGUIInstance.h"
#include "cGUIObjTextureRef.h"
#include "../shared/cResource.h"
#include "../shared/rArchiveListArray.h"
#include "../rGUI/rGUI.h"
#include "../shared/rGUIMessage.h"
#include "sScreenShot.h"
#include "../shared/uGUIBase.h"
#include "uGUIPhotoUpload.h"
#include "uGUISystemMsg.h"
#include "uGUIsMenuBase.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* uGUIPhotoAlbum::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uGUIPhotoAlbum::usage();

// Address: 0x01afad10 - 0x01afad18 (8 bytes)
const MtDTI& uGUIPhotoAlbum::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uGUIPhotoAlbum::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* uGUIPhotoAlbum::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::uGUIPhotoAlbum::DTI);
}

// No out-of-line body: no code in the ELF
// void uGUIPhotoAlbum::setAllocator(u32);

// Address: 0x00b3f710 - 0x00b3f750 (64 bytes)
void* uGUIPhotoAlbum::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::uGUIPhotoAlbum::getAllocator()->memAlloc(sz, align, ::uGUIPhotoAlbum::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* uGUIPhotoAlbum::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPhotoAlbum::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uGUIPhotoAlbum::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void uGUIPhotoAlbum::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uGUIPhotoAlbum::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uGUIPhotoAlbum::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uGUIPhotoAlbum::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uGUIPhotoAlbum::operator delete[](void* p_addr, u32 align);

// Omitted: mem-initializer not recorded in DWARF (base uGUIsMenuBase has no default constructor)
// uGUIPhotoAlbum::uGUIPhotoAlbum();

// Address: 0x00b3fc40 - 0x00b3fcc7 (135 bytes)
// Also emitted as: _ZN14uGUIPhotoAlbumD0Ev at 0x00b3fcd0
uGUIPhotoAlbum::~uGUIPhotoAlbum() {
    DDON_STUB("uGUIPhotoAlbum::~uGUIPhotoAlbum")
    /* stub */
}

// Address: 0x00b3fd80 - 0x00b3fe2f (175 bytes)
bool uGUIPhotoAlbum::loadResource() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpGUIRes == static_cast<rGUI*>(nullptr)) {
        if ((this->mpGUIRes = static_cast<rGUI*>(this->::uGUIBase::uiCreateResource(this->::uGUIBase::getArcTag(static_cast<u32>(0)), ::rArchiveListArray::convSearchId("RES_ID_PHOTO_ALBUM_GUI"), static_cast<u32>(129), static_cast<t64>(1435891201)))) != static_cast<rGUI*>(nullptr)) {
            if (this->mpGMDRes == static_cast<rGUIMessage*>(nullptr)) {
                if ((this->mpGMDRes = static_cast<rGUIMessage*>(this->::uGUIBase::uiCreateResource(this->::uGUIBase::getArcTag(static_cast<u32>(0)), ::rArchiveListArray::convSearchId("RES_ID_PHOTO_ALBUM_GMD"), static_cast<u32>(129), static_cast<t64>(0)))) != static_cast<rGUIMessage*>(nullptr)) {
                    this->mpGMDRes;
                    return true;
                } else {
                    return false;
                }
            } else {
                return true;
            }
        } else {
            return false;
        }
    } else {
        if (this->mpGMDRes == static_cast<rGUIMessage*>(nullptr)) {
            if ((this->mpGMDRes = static_cast<rGUIMessage*>(this->::uGUIBase::uiCreateResource(this->::uGUIBase::getArcTag(static_cast<u32>(0)), ::rArchiveListArray::convSearchId("RES_ID_PHOTO_ALBUM_GMD"), static_cast<u32>(129), static_cast<t64>(0)))) != static_cast<rGUIMessage*>(nullptr)) {
                this->mpGMDRes;
                return true;
            } else {
                return false;
            }
        } else {
            return true;
        }
    }
}

// Address: 0x00b3fe30 - 0x00b40b9f (3439 bytes)
__attribute__((weak)) void uGUIPhotoAlbum::setup() {
    // local: MtStringEx<128> tmp;
    // local: cGUIInstance* pInst;
    // local: cGUIInstance* pInst;
    // local: const f32 offset_list_y;
    // local: const f32 base_pos;
    // local: cGUIInstNull* pInstOrigin;
    // local: s32 i;
    // local: stCategory& list;
    // local: const MtFloat2 size;
    // local: cControl* pCtrl;
    // local: cHorizontalList* pCtrl;
    // local: cVerticalList* pCtrl;
    // local: s32 i;
    DDON_STUB("uGUIPhotoAlbum::setup")
    /* stub */
}

// Address: 0x00b40cf0 - 0x00b40d9b (171 bytes)
void uGUIPhotoAlbum::kill() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::uGUIBase::kill();
    if (this->mAlbum.mpObjTexRefSamnail != static_cast<cGUIObjTextureRef*>(nullptr)) {
        this->mAlbum.mpObjTexRefSamnail->::cGUIObjTextureRef::setReferenceTexture(static_cast<rTexture*>(nullptr));
    }
    if (this->mFull.mpObjTexRefSamnailFull != static_cast<cGUIObjTextureRef*>(nullptr)) {
        this->mFull.mpObjTexRefSamnailFull->::cGUIObjTextureRef::setReferenceTexture(static_cast<rTexture*>(nullptr));
    }
    if (::sScreenShot::getInstance() != static_cast<sScreenShot*>(nullptr)) {
        ::sScreenShot::getInstance()->::sScreenShot::releaseScreenShotTexture();
    }
    if (this->mpGUISystemMsg != static_cast<uGUISystemMsg*>(nullptr)) {
        this->mpGUISystemMsg->kill();
        this->mpGUISystemMsg = static_cast<uGUISystemMsg*>(nullptr);
    }
    if (this->mpGUIPhotoUpload != static_cast<uGUIPhotoUpload*>(nullptr)) {
        this->mpGUIPhotoUpload->kill();
        this->mpGUIPhotoUpload = static_cast<uGUIPhotoUpload*>(nullptr);
    }
    if (this->mpGUIRes == static_cast<rGUI*>(nullptr)) {
        return;
    }
    this->mpGUIRes->::cResource::release();
    this->mpGUIRes = static_cast<rGUI*>(nullptr);
}

// No out-of-line body: no code in the ELF
// bool uGUIPhotoAlbum::isDecide();

// No out-of-line body: no code in the ELF
// bool uGUIPhotoAlbum::isCancel();

// No out-of-line body: no code in the ELF
// void uGUIPhotoAlbum::clearButton();

// Address: 0x00b40da0 - 0x00b40da1 (1 bytes)
__attribute__((weak)) void uGUIPhotoAlbum::updatePtr() {
    // Empty in the binary (a single `ret`).
}

// Address: 0x00b40db0 - 0x00b40e69 (185 bytes)
__attribute__((weak)) void uGUIPhotoAlbum::updateInit() {
    DDON_STUB("uGUIPhotoAlbum::updateInit")
    /* stub */
}

// Address: 0x00b41200 - 0x00b4129b (155 bytes)
__attribute__((weak)) void uGUIPhotoAlbum::updateWait() {
    DDON_STUB("uGUIPhotoAlbum::updateWait")
    /* stub */
}

// Address: 0x00b41780 - 0x00b418e6 (358 bytes)
__attribute__((weak)) void uGUIPhotoAlbum::updateUpload() {
    DDON_STUB("uGUIPhotoAlbum::updateUpload")
    /* stub */
}

// Address: 0x00b418f0 - 0x00b418f9 (9 bytes)
void uGUIPhotoAlbum::updateExit() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->end();
}

// Address: 0x00b41900 - 0x00b41a01 (257 bytes)
__attribute__((weak)) void uGUIPhotoAlbum::moveInput() {
    DDON_STUB("uGUIPhotoAlbum::moveInput")
    /* stub */
}

// Address: 0x00b41a20 - 0x00b41b48 (296 bytes)
__attribute__((weak)) void uGUIPhotoAlbum::moveEvent() {
    DDON_STUB("uGUIPhotoAlbum::moveEvent")
    /* stub */
}

// Address: 0x00b40e70 - 0x00b411f8 (904 bytes)
__attribute__((weak)) void uGUIPhotoAlbum::init() {
    // local: s32 saveMaxPage;
    // local: MtStringEx<128> tmp;
    // local: MtColor color;
    // local: s32 i;
    DDON_STUB("uGUIPhotoAlbum::init")
    /* stub */
}

// No out-of-line body: 3 inlined copies in 3 functions (458 bytes)
//   in uGUIPhotoAlbum::setup at 0x00b40acb-0x00b40b6b (called at uGUIPhotoAlbum.cpp:369)
//   in uGUIPhotoAlbum::moveEvent at 0x00b41a6b-0x00b41acf, 0x00b41b02-0x00b41b28 (called at uGUIPhotoAlbum.cpp:918)
//   in uGUIPhotoAlbum::evDecide at 0x00b41c0c-0x00b41c7a, 0x00b41cc9-0x00b41cfb (called at uGUIPhotoAlbum.cpp:872)
// void uGUIPhotoAlbum::selectFlow(u32 flowID);

// Address: 0x00b41460 - 0x00b4177c (796 bytes)
__attribute__((weak)) bool uGUIPhotoAlbum::changePhoto() {
    // local: rTexture* const pTex;
    // local: f32 tex_ratio;
    // local: f32 rate;
    // local: f32 window_w;
    // local: MtFloat2 size;
    // local: MtFloat2 baseSize;
    // local: MtFloat4 rect;
    // local: MtFloat2 fullSize;
    // local: MtFloat4 fullRect;
    // local: f32 tex_h;
    // local: f32 tex_w;
    // local: MtFloat2 limitSize;
    DDON_STUB("uGUIPhotoAlbum::changePhoto")
    return {};
}

// Address: 0x00b412a0 - 0x00b41446 (422 bytes)
__attribute__((weak)) void uGUIPhotoAlbum::updateAlpha() {
    DDON_STUB("uGUIPhotoAlbum::updateAlpha")
    /* stub */
}

// No out-of-line body: 2 inlined copies in 2 functions (38 bytes)
//   in uGUIPhotoAlbum::updateInit at 0x00b40e08-0x00b40e1b (called at uGUIPhotoAlbum.cpp:452)
//   in uGUIPhotoAlbum::updateWait at 0x00b41253-0x00b41266 (called at uGUIPhotoAlbum.cpp:452)
// void uGUIPhotoAlbum::changeCategoryEnable();

// Address: 0x00b41b60 - 0x00b41d6e (526 bytes)
__attribute__((weak)) void uGUIPhotoAlbum::evDecide() {
    // local: const u32 select;
    // local: bool focusOn;
    DDON_STUB("uGUIPhotoAlbum::evDecide")
    /* stub */
}

// No out-of-line body: 1 inlined copy in 1 function (174 bytes)
//   in uGUIPhotoAlbum::moveEvent at 0x00b41a60-0x00b41acf, 0x00b41adf-0x00b41af8, 0x00b41b02-0x00b41b28 (called at uGUIPhotoAlbum.cpp:583)
// void uGUIPhotoAlbum::evCancel();

// No out-of-line body: 1 inlined copy in 1 function (11 bytes)
//   in uGUIPhotoAlbum::moveEvent at 0x00b41acf-0x00b41ada (called at uGUIPhotoAlbum.cpp:586)
// void uGUIPhotoAlbum::evStart();

// No out-of-line body: 2 inlined copies in 1 function (20 bytes)
//   in uGUIPhotoAlbum::moveEvent at 0x00b41a4c-0x00b41a54 (called at uGUIPhotoAlbum.cpp:579)
//   in uGUIPhotoAlbum::moveEvent at 0x00b41b28-0x00b41b34 (called at uGUIPhotoAlbum.cpp:589)
// void uGUIPhotoAlbum::evAdjustCursor();

// Address: 0x00b41da0 - 0x00b41ee4 (324 bytes)
__attribute__((weak)) void uGUIPhotoAlbum::adjustCategory() {
    // local: const u32 select;
    // local: u32 i;
    DDON_STUB("uGUIPhotoAlbum::adjustCategory")
    /* stub */
}

// No out-of-line body: no code in the ELF
// void uGUIPhotoAlbum::evAdjustSideCursor();

// No out-of-line body: no code in the ELF
// void uGUIPhotoAlbum::adjustPage();

// Address: 0x00b40ba0 - 0x00b40c18 (120 bytes)
__attribute__((weak)) u32 uGUIPhotoAlbum::evCtrlDecide(cControl::Message* msg) {
    // local: const u32 select;
    DDON_STUB("uGUIPhotoAlbum::evCtrlDecide")
    return {};
}

// Address: 0x01afaca0 - 0x01afacb2 (18 bytes)
u32 uGUIPhotoAlbum::evCtrlCancel(cControl::Message* msg) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::uGUIBase::setInputEvent(static_cast<u32>(67));
    return static_cast<u32>(0);
}

// Address: 0x01afacc0 - 0x01afacd2 (18 bytes)
u32 uGUIPhotoAlbum::evCtrlStart(cControl::Message* msg) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::uGUIBase::setInputEvent(static_cast<u32>(70));
    return static_cast<u32>(0);
}

// Address: 0x01aface0 - 0x01afacf2 (18 bytes)
u32 uGUIPhotoAlbum::evCtrlAdjustCursor(cControl::Message* msg) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::uGUIBase::setInputEvent(static_cast<u32>(68));
    return static_cast<u32>(0);
}

// Address: 0x00b40c20 - 0x00b40c42 (34 bytes)
u32 uGUIPhotoAlbum::evCtrlAdjustSideCursor(cControl::Message* msg) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mFlowId != static_cast<u32>(7)) {
        if (this->mFlowId == static_cast<u32>(3)) {
            this->::uGUIBase::setInputEvent(static_cast<u32>(69));
        }
    } else {
        this->::uGUIBase::setInputEvent(static_cast<u32>(69));
    }
    return static_cast<u32>(0);
}

// Address: 0x00b40c50 - 0x00b40cdf (143 bytes)
u32 uGUIPhotoAlbum::evCtrlMouse(cControl::Message* msg) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (msg->reason == static_cast<nGUIExt::MSG_REASON>(37)) {
        if (msg->mouse_hit_id <= static_cast<s32>(1)) {
            if (this->mpVCtrl != static_cast<uGUIBase::cVerticalList*>(nullptr)) {
                if (msg != static_cast<cControl::Message*>(nullptr)) {
                    msg->changeSE = static_cast<u32>(4);
                    if (this->mFlowId == static_cast<u32>(3)) {
                        if (this->mpVCtrl->::cControl::mCurrentPos != static_cast<s32>(0)) {
                            if (::sScreenShot::getInstance()->::sScreenShot::isExistsScreenShot() != false) {
                                if (this->mbSetupPhoto == false) {
                                    msg->changeSE = static_cast<u32>(0);
                                } else {
                                    this->::uGUIBase::setInputEvent(static_cast<u32>(66));
                                }
                            } else {
                                this->::uGUIBase::setInputEvent(static_cast<u32>(66));
                            }
                        } else {
                            if (this->mMaxPage > static_cast<s32>(0)) {
                                this->::uGUIBase::setInputEvent(static_cast<u32>(66));
                            }
                        }
                    } else {
                        msg->changeSE = static_cast<u32>(0);
                    }
                } else {
                    if (this->mFlowId == static_cast<u32>(3)) {
                        if (this->mpVCtrl->::cControl::mCurrentPos != static_cast<s32>(0)) {
                            if (::sScreenShot::getInstance()->::sScreenShot::isExistsScreenShot() != false) {
                                if (this->mbSetupPhoto == false) {
                                    msg->changeSE = static_cast<u32>(0);
                                } else {
                                    this->::uGUIBase::setInputEvent(static_cast<u32>(66));
                                }
                            } else {
                                this->::uGUIBase::setInputEvent(static_cast<u32>(66));
                            }
                        } else {
                            if (this->mMaxPage > static_cast<s32>(0)) {
                                this->::uGUIBase::setInputEvent(static_cast<u32>(66));
                            }
                        }
                    }
                }
            }
        }
    }
    return static_cast<u32>(0);
}

// No out-of-line body: 3 inlined copies in 3 functions (20 bytes)
//   in _ZN14uGUIPhotoAlbum12evCtrlDecideEPN8cControl7MessageE at 0x00b40bbb-0x00b40bc1 (called at uGUIPhotoAlbum.cpp:813)
//   in uGUIPhotoAlbum::evDecide at 0x00b41b82-0x00b41b89 (called at uGUIPhotoAlbum.cpp:859)
//   in uGUIPhotoAlbum::adjustCategory at 0x00b41dbc-0x00b41dc3 (called at uGUIPhotoAlbum.cpp:960)
// s32 uGUIPhotoAlbum::getCtrlPos(cControl* pCtrl);

// No out-of-line body: 1 inlined copy in 1 function (109 bytes)
//   in uGUIPhotoAlbum::moveInput at 0x00b41916-0x00b41983 (called at uGUIPhotoAlbum.cpp:542)
// bool uGUIPhotoAlbum::updateSysMsg();

// Address: 0x00b41f00 - 0x00b4200a (266 bytes)
void uGUIPhotoAlbum::adjustScale() {
    // Approximate from the ELF: a temporary declared in several branches; the body oracle reports this body.
    if (this->mpInstNullAlbum == static_cast<cGUIInstNull*>(nullptr)) {
        return;
    }
    if (this->mpInstNullRBottom == static_cast<cGUIInstNull*>(nullptr)) {
        return;
    }
    if (this->mpInstNullLTop == static_cast<cGUIInstNull*>(nullptr)) {
        return;
    }
    f32 fScaleRate = this->getScaleForDefaultResolution(1.0f);
    // inferred: a temporary for the value the load at 0xb41f4c read, used 4 times; no DWARF local holds it
    cGUIInstNull* t1 = this->mpInstNullAlbum;
    if (t1 != static_cast<cGUIInstNull*>(nullptr)) {
        t1->::cGUIInstNull::setScaleX(fScaleRate);
        t1->::cGUIInstNull::setScaleY(fScaleRate);
        t1->::cGUIInstNull::setScaleZ(fScaleRate);
        // inferred: a temporary for the value the load at 0xb41f89 read, used 4 times; no DWARF local holds it
        cGUIInstNull* t3 = this->mpInstNullRBottom;
        if (t3 != static_cast<cGUIInstNull*>(nullptr)) {
            t3->::cGUIInstNull::setScaleX(fScaleRate);
            t3->::cGUIInstNull::setScaleY(fScaleRate);
            t3->::cGUIInstNull::setScaleZ(fScaleRate);
            // inferred: a temporary for the value the load at 0xb41fc6 read, used 4 times; no DWARF local holds it
            cGUIInstNull* t5 = this->mpInstNullLTop;
            if (t5 != static_cast<cGUIInstNull*>(nullptr)) {
                t5->::cGUIInstNull::setScaleX(fScaleRate);
                t5->::cGUIInstNull::setScaleY(fScaleRate);
                t5->::cGUIInstNull::setScaleZ(fScaleRate);
            }
        } else {
            // inferred: a temporary for the value the load at 0xb41fc6 read, used 4 times; no DWARF local holds it
            cGUIInstNull* t5 = this->mpInstNullLTop;
            if (t5 != static_cast<cGUIInstNull*>(nullptr)) {
                t5->::cGUIInstNull::setScaleX(fScaleRate);
                t5->::cGUIInstNull::setScaleY(fScaleRate);
                t5->::cGUIInstNull::setScaleZ(fScaleRate);
            }
        }
    } else {
        // inferred: a temporary for the value the load at 0xb41f89 read, used 4 times; no DWARF local holds it
        cGUIInstNull* t3 = this->mpInstNullRBottom;
        if (t3 != static_cast<cGUIInstNull*>(nullptr)) {
            t3->::cGUIInstNull::setScaleX(fScaleRate);
            t3->::cGUIInstNull::setScaleY(fScaleRate);
            t3->::cGUIInstNull::setScaleZ(fScaleRate);
            // inferred: a temporary for the value the load at 0xb41fc6 read, used 4 times; no DWARF local holds it
            cGUIInstNull* t5 = this->mpInstNullLTop;
            if (t5 != static_cast<cGUIInstNull*>(nullptr)) {
                t5->::cGUIInstNull::setScaleX(fScaleRate);
                t5->::cGUIInstNull::setScaleY(fScaleRate);
                t5->::cGUIInstNull::setScaleZ(fScaleRate);
            }
        } else {
            // inferred: a temporary for the value the load at 0xb41fc6 read, used 4 times; no DWARF local holds it
            cGUIInstNull* t5 = this->mpInstNullLTop;
            if (t5 != static_cast<cGUIInstNull*>(nullptr)) {
                t5->::cGUIInstNull::setScaleX(fScaleRate);
                t5->::cGUIInstNull::setScaleY(fScaleRate);
                t5->::cGUIInstNull::setScaleZ(fScaleRate);
            }
        }
    }
}

// Address: 0x00b42010 - 0x00b4204d (61 bytes)
__attribute__((weak)) bool uGUIPhotoAlbum::isForceSamplerLinear(cGUIObject* pObj) const {
    DDON_STUB("uGUIPhotoAlbum::isForceSamplerLinear")
    return {};
}

// No out-of-line body: 2 inlined copies in 1 function (142 bytes)
//   in _GLOBAL__sub_I_uGUIPhotoAlbum.cpp at 0x00b4214f-0x00b42196 (called at uGUIPhotoAlbum.cpp:29)
//   in _GLOBAL__sub_I_uGUIPhotoAlbum.cpp at 0x00b4214f-0x00b42196 (called at uGUIPhotoAlbum.h:26)
// uGUIPhotoAlbum::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00b3f6d0 - 0x00b3f710 (64 bytes)
__attribute__((weak)) MtObject* uGUIPhotoAlbum::MyDTI::newInstance() const {
    DDON_STUB("uGUIPhotoAlbum::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* uGUIPhotoAlbum::cItem::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// const MtDTI& uGUIPhotoAlbum::cItem::getDTI() const;

// No out-of-line body: no code in the ELF
// MtAllocator* uGUIPhotoAlbum::cItem::getAllocator();

// No out-of-line body: no code in the ELF
// void uGUIPhotoAlbum::cItem::setAllocator(u32);

// No out-of-line body: no code in the ELF
// void uGUIPhotoAlbum::cItem::operator delete(void*);

// No out-of-line body: no code in the ELF
// uGUIPhotoAlbum::cItem::cItem();

// No out-of-line body: no code in the ELF
// uGUIPhotoAlbum::cItem::MyDTI::MyDTI(MT_CTSTR, MtDTI*, size_t, u32, u32);

// No out-of-line body: 2 inlined copies in 1 function (584 bytes)
//   in uGUIPhotoAlbum::uGUIPhotoAlbum at 0x00b3f823-0x00b3f947 (called at uGUIPhotoAlbum.cpp:60)
//   in uGUIPhotoAlbum::uGUIPhotoAlbum at 0x00b3f823-0x00b3f947 (called at uGUIPhotoAlbum.h:81)
// uGUIPhotoAlbum::stAlbum::stAlbum();

// No out-of-line body: 2 inlined copies in 1 function (722 bytes)
//   in uGUIPhotoAlbum::uGUIPhotoAlbum at 0x00b3f947-0x00b3fab0 (called at uGUIPhotoAlbum.cpp:60)
//   in uGUIPhotoAlbum::uGUIPhotoAlbum at 0x00b3f947-0x00b3fab0 (called at uGUIPhotoAlbum.h:126)
// uGUIPhotoAlbum::stFull::stFull();

// No out-of-line body: 2 inlined copies in 1 function (272 bytes)
//   in uGUIPhotoAlbum::uGUIPhotoAlbum at 0x00b3fab0-0x00b3fb38 (called at uGUIPhotoAlbum.cpp:60)
//   in uGUIPhotoAlbum::uGUIPhotoAlbum at 0x00b3fab0-0x00b3fb38 (called at uGUIPhotoAlbum.h:168)
// uGUIPhotoAlbum::stCategoryList::stCategoryList();

// No out-of-line body: 2 inlined copies in 1 function (176 bytes)
//   in uGUIPhotoAlbum::uGUIPhotoAlbum at 0x00b3fab0-0x00b3fb08 (called at uGUIPhotoAlbum.h:168)
//   in uGUIPhotoAlbum::uGUIPhotoAlbum at 0x00b3fab0-0x00b3fb08 (called at uGUIPhotoAlbum.h:155)
// uGUIPhotoAlbum::stCategory::stCategory();

// Instance at 0x01afac90 - 0x01afac95 (5 bytes) of the generic MtTypedArray<T>::~MtTypedArray
// Proven from the ELF: the body oracle checks this instance (022 D5).
template MtTypedArray<uGUIPhotoAlbum::cItem>::~MtTypedArray();

