// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "uGUIPopDetail01.h"
#include "../shared/MtAllocator.h"
#include "../shared/MtCollection.h"
#include "../shared/MtDTI.h"
#include "../shared/MtMemoryAllocator.h"
#include "../shared/MtObject.h"
#include "../shared/MtString.h"
#include "../shared/cControl.h"
#include "../shared/cEquipData.h"
#include "../shared/cItemParam.h"
#include "../shared/cNetGameServer.h"
#include "../shared/cResource.h"
#include "../shared/cUnit.h"
#include "../shared/nCharacterData.h"
#include "../shared/nDDOUtility.h"
#include "../shared/nGUIExt.h"
#include "../shared/nGUIItem.h"
#include "../shared/rArchiveListArray.h"
#include "../rGUI/rGUI.h"
#include "../shared/rItemList.h"
#include "../shared/sNetwork.h"
#include "../shared/sNetworkExt.h"
#include "../shared/uGUIBase.h"
#include "uGUIPopBase.h"
#include "uGUIPopCraftDetail.h"
#include "uUIMockUp.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* uGUIPopDetail01::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::usage();

// Address: 0x01afc8a0 - 0x01afc8a8 (8 bytes)
const MtDTI& uGUIPopDetail01::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uGUIPopDetail01::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* uGUIPopDetail01::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::uGUIPopDetail01::DTI);
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::setAllocator(u32);

// Address: 0x00b9f5e0 - 0x00b9f620 (64 bytes)
void* uGUIPopDetail01::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::uGUIPopDetail01::getAllocator()->memAlloc(sz, align, ::uGUIPopDetail01::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void uGUIPopDetail01::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uGUIPopDetail01::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::operator delete[](void* p_addr, u32 align);

// Omitted: mem-initializer not recorded in DWARF (base uGUIPopBase has no default constructor)
// uGUIPopDetail01::uGUIPopDetail01(uGUIBase* owner, bool isChatSubMenu);

// Address: 0x00ba0330 - 0x00ba04f9 (457 bytes)
// Also emitted as: _ZN15uGUIPopDetail01D0Ev at 0x00ba0500
uGUIPopDetail01::~uGUIPopDetail01() {
    DDON_STUB("uGUIPopDetail01::~uGUIPopDetail01")
    /* stub */
}

// Address: 0x00ba0530 - 0x00ba062e (254 bytes)
bool uGUIPopDetail01::loadResource() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpGUIRes == static_cast<rGUI*>(nullptr)) {
        if ((this->mpGUIRes = static_cast<rGUI*>(this->::uGUIBase::uiCreateResource(this->::uGUIBase::getArcTag(static_cast<u32>(0)), ::rArchiveListArray::convSearchId("RES_ID_POP_DETAIL01_GUI"), static_cast<u32>(129), static_cast<t64>(1460101462)))) != static_cast<rGUI*>(nullptr)) {
            if (this->::uGUIBase::loadGMDarc(this->::uGUIBase::getArcTag(static_cast<u32>(0)), "RES_ID_POPDETAIL01_RES_GMD", static_cast<u32>(0)) != false) {
                if (this->::uGUIBase::loadGMDarc(this->::uGUIBase::getArcTag(static_cast<u32>(0)), "RES_ID_PARAMETER_GMD", static_cast<u32>(1)) != false) {
                    if (this->::uGUIBase::loadGMDarc(this->::uGUIBase::getArcTag(static_cast<u32>(0)), "RES_ID_ITEM_WORK_GMD", static_cast<u32>(2)) != false) {
                        return this->::uGUIBase::loadGMDarc(this->::uGUIBase::getArcTag(static_cast<u32>(0)), "RES_ID_JEWELRY_CTGR_GMD", static_cast<u32>(3));
                    }
                }
            }
        }
    } else {
        if (this->::uGUIBase::loadGMDarc(this->::uGUIBase::getArcTag(static_cast<u32>(0)), "RES_ID_POPDETAIL01_RES_GMD", static_cast<u32>(0)) != false) {
            if (this->::uGUIBase::loadGMDarc(this->::uGUIBase::getArcTag(static_cast<u32>(0)), "RES_ID_PARAMETER_GMD", static_cast<u32>(1)) != false) {
                if (this->::uGUIBase::loadGMDarc(this->::uGUIBase::getArcTag(static_cast<u32>(0)), "RES_ID_ITEM_WORK_GMD", static_cast<u32>(2)) != false) {
                    return this->::uGUIBase::loadGMDarc(this->::uGUIBase::getArcTag(static_cast<u32>(0)), "RES_ID_JEWELRY_CTGR_GMD", static_cast<u32>(3));
                }
            }
        }
    }
    return false;
}

// Address: 0x00ba0630 - 0x00ba1e4a (6170 bytes)
__attribute__((weak)) void uGUIPopDetail01::setup() {
    // local: u32 pop_detail01_window_ObjectIdTable[11];
    // local: const s32 offset;
    // local: cGUIInstAnimation* pInstOrigin;
    // local: u32 i;
    // local: cReferenceUIIconJob& icon;
    // local: u32 i;
    // local: cDupParam* p;
    // local: u32 i;
    // local: cDupCraftParam* p;
    DDON_STUB("uGUIPopDetail01::setup")
    /* stub */
}

// Address: 0x00ba23b0 - 0x00ba23ed (61 bytes)
void uGUIPopDetail01::kill() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::uGUIBase::kill();
    this->updatePtr();
    if (this->mpGUIRes == static_cast<rGUI*>(nullptr)) {
        return;
    }
    this->mpGUIRes->::cResource::release();
    this->mpGUIRes = static_cast<rGUI*>(nullptr);
}

// Address: 0x00ba23f0 - 0x00ba2471 (129 bytes)
void uGUIPopDetail01::updatePtr() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::uGUIPopBase::updatePtr();
    if (this->mpOwner != static_cast<uGUIBase*>(nullptr)) {
        if (this->mpOwner->::cUnit::isEnable() == false) {
            this->mpOwner = static_cast<uGUIBase*>(nullptr);
        }
    }
    if (this->mpCraftDetail != static_cast<uGUIPopCraftDetail*>(nullptr)) {
        if (this->mpCraftDetail->::cUnit::isEnable() == false) {
            this->mpCraftDetail = static_cast<uGUIPopCraftDetail*>(nullptr);
        }
    }
    if (this->mpMockUp == static_cast<uUIMockUp*>(nullptr)) {
        return;
    }
    if (this->mpMockUp->::cUnit::isEnable() != false) {
        return;
    }
    this->mpMockUp = static_cast<uUIMockUp*>(nullptr);
}

// Address: 0x00ba2480 - 0x00ba25e3 (355 bytes)
__attribute__((weak)) void uGUIPopDetail01::move() {
    // local: MtSize size;
    DDON_STUB("uGUIPopDetail01::move")
    /* stub */
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::setPopDetailPriority();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::resetPopDetailPriority();

// No out-of-line body: no code in the ELF
// u32 uGUIPopDetail01::getPopDetailPriority();

// Address: 0x00ba5cd0 - 0x00ba5d80 (176 bytes)
void uGUIPopDetail01::setItemParam(nGUIItem::cItem* p, nCharacterData::EQUIP_SLOT_TYPE equipSlotType) {
    // DWARF local not rendered: bool rebuild;
    // Approximate from the ELF: code after a join copied into the arms; the body oracle reports this body.
    this->mEquipSlotType = equipSlotType;
    if (p != static_cast<nGUIItem::cItem*>(nullptr)) {
        if (this->mItem.::nGUIItem::cItem::isSameData(*p) != false) {
            // inferred: a temporary for the result of the call at 0xba5d06, used once; no DWARF local holds it
            u32 t0 = this->mItem.::nGUIItem::cItem::getNum();
            if (t0 != p->::nGUIItem::cItem::getNum()) {
                this->mItem.::nGUIItem::cItem::copy(*p);
                this->mItemParam.::cItemParam::init(static_cast<u32>(0));
                cItemParam* const item_param = p->::nGUIItem::cItem::getItemParam();
                if (item_param != static_cast<cItemParam* const>(nullptr)) {
                    this->mItemParam.::cItemParam::copyParam(item_param);
                    this->mItem.::nGUIItem::cItem::setItemParam(&this->mItemParam);
                } else {
                    this->mItem.::nGUIItem::cItem::setItemParam(static_cast<cItemParam*>(nullptr));
                }
                this->::uGUIPopDetail01::updateEquipData();
                this->mRequestRefresh = static_cast<uGUIPopDetail01::REFRESH_MODE>(1);
            }
        } else {
            this->mItem.::nGUIItem::cItem::copy(*p);
            this->mItemParam.::cItemParam::init(static_cast<u32>(0));
            cItemParam* const item_param = p->::nGUIItem::cItem::getItemParam();
            if (item_param != static_cast<cItemParam* const>(nullptr)) {
                this->mItemParam.::cItemParam::copyParam(item_param);
                this->mItem.::nGUIItem::cItem::setItemParam(&this->mItemParam);
            } else {
                this->mItem.::nGUIItem::cItem::setItemParam(static_cast<cItemParam*>(nullptr));
            }
            this->::uGUIPopDetail01::updateEquipData();
            this->mRequestRefresh = static_cast<uGUIPopDetail01::REFRESH_MODE>(1);
        }
    } else {
        this->mItem.::nGUIItem::cItem::init();
        this->mRequestRefresh = static_cast<uGUIPopDetail01::REFRESH_MODE>(1);
    }
}

// Address: 0x00ba5f70 - 0x00ba6021 (177 bytes)
__attribute__((weak)) void uGUIPopDetail01::setItemParam(cItemParam* pItemParam, rItemList::rItemParam* prItemParam, nCharacterData::EQUIP_SLOT_TYPE equipSlotType) {
    // local: const u32 item_num;
    DDON_STUB("uGUIPopDetail01::setItemParam")
    /* stub */
}

// Address: 0x00ba6030 - 0x00ba603b (11 bytes)
void uGUIPopDetail01::reqRefresh() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mRequestRefresh = static_cast<uGUIPopDetail01::REFRESH_MODE>(1);
}

// No out-of-line body: no code in the ELF
// nGUIItem::cItem& uGUIPopDetail01::getItemParam();

// No out-of-line body: 94 inlined copies in 62 functions (707 bytes)
//   in uGUIAreaMaster::setup at 0x00929f3b-0x00929f42 (called at uGUIAreaMaster.cpp:988)
//   in uGUIAreaMaster::setFlowId at 0x0092b82e-0x0092b835 (called at uGUIAreaMaster.cpp:5624)
//   in uGUIAreaMaster::updateDetail at 0x0092c9fc-0x0092ca03 (called at uGUIAreaMaster.cpp:5605)
//   and 91 more (every copy is in <bundle>.inlined.json)
// void uGUIPopDetail01::setDraw(bool b);

// No out-of-line body: no code in the ELF
// bool uGUIPopDetail01::isDrawLocal();

// No out-of-line body: 5 inlined copies in 2 functions (493 bytes)
//   in uGUIPopDetail01::setup at 0x00ba1d53-0x00ba1d5b, 0x00ba1d64-0x00ba1dcd (called at uGUIPopDetail01.cpp:496)
//   in uGUIPopDetail01::setup at 0x00ba1dd2-0x00ba1e1f (called at uGUIPopDetail01.cpp:498)
//   in uGUIPopDetail01::refresh at 0x00ba21eb-0x00ba2246 (called at uGUIPopDetail01.cpp:2522)
//   and 2 more (every copy is in <bundle>.inlined.json)
// bool uGUIPopDetail01::setProc(uGUIPopDetail01::PR proc, bool force);

// No out-of-line body: no code in the ELF
// s32 uGUIPopDetail01::getPageNum();

// No out-of-line body: no code in the ELF
// s32 uGUIPopDetail01::getMaxPageNum();

// No out-of-line body: 26 inlined copies in 4 functions (274 bytes)
//   in uGUIPopDetail01::setupEquipMainParam at 0x00ba53e7-0x00ba53ed (called at uGUIPopDetail01.cpp:648)
//   in uGUIPopDetail01::setupEquipMainParam at 0x00ba5476-0x00ba5483 (called at uGUIPopDetail01.cpp:2451)
//   in uGUIPopDetail01::setupEquipElementParam at 0x00ba554a-0x00ba555c (called at uGUIPopDetail01.cpp:2469)
//   and 23 more (every copy is in <bundle>.inlined.json)
// bool uGUIPopDetail01::isUseCompare(s32 param1, s32 param2) const;

// No out-of-line body: 11 inlined copies in 7 functions (146 bytes)
//   in uGUICharacter::updateEquipSelect at 0x009f1475-0x009f148b, 0x009f1546-0x009f154f (called at uGUICharacter.cpp:2792)
//   in uGUICharacter::updateItemDetail at 0x009f1bdf-0x009f1be6 (called at uGUICharacter.cpp:2792)
//   in uGUICharacter::updateItemDetail at 0x009f1ce5-0x009f1cec (called at uGUICharacter.cpp:2792)
//   and 8 more (every copy is in <bundle>.inlined.json)
// void uGUIPopDetail01::setUseCompare(bool b);

// No out-of-line body: 17 inlined copies in 2 functions (587 bytes)
//   in uGUIPopDetail01::setupEquipMainParam at 0x00ba53e7-0x00ba540a (called at uGUIPopDetail01.cpp:2445)
//   in uGUIPopDetail01::setupParamWeapon at 0x00ba984e-0x00ba985d, 0x00ba98fc-0x00ba9901 (called at uGUIPopDetail01.cpp:2366)
//   in uGUIPopDetail01::setupParamWeapon at 0x00ba98c3-0x00ba98e1, 0x00ba9f87-0x00ba9f8c (called at uGUIPopDetail01.cpp:2382)
//   and 14 more (every copy is in <bundle>.inlined.json)
// const MtColor& uGUIPopDetail01::getStatusColor(s32 val1, s32 val2);

// Address: 0x00ba0320 - 0x00ba032c (12 bytes)
__attribute__((weak)) void uGUIPopDetail01::setCompereEquipData(cEquipData& source) {
    DDON_STUB("uGUIPopDetail01::setCompereEquipData")
    /* stub */
}

// No out-of-line body: 8 inlined copies in 5 functions (58 bytes)
//   in uGUICharacter::updateEquipSelect at 0x009f146e-0x009f1475 (called at uGUICharacter.cpp:2790)
//   in uGUICharacter::updateItemDetail at 0x009f1bd8-0x009f1bdf (called at uGUICharacter.cpp:2790)
//   in uGUICharacter::updateItemDetail at 0x009f1cde-0x009f1ce5 (called at uGUICharacter.cpp:2790)
//   and 5 more (every copy is in <bundle>.inlined.json)
// void uGUIPopDetail01::setOwner(uGUIBase* owner);

// Address: 0x00ba2610 - 0x00ba267e (110 bytes)
__attribute__((weak)) void uGUIPopDetail01::setContext(cContextInstHm* pContext, bool isSetupEquip) {
    DDON_STUB("uGUIPopDetail01::setContext")
    /* stub */
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::setMockupModel(uGUIPopDetail01::MOCKUP_MODEL);

// No out-of-line body: 9 inlined copies in 6 functions (182 bytes)
//   in uGUIPopDetail01::evCtrlTop at 0x00ba1e91-0x00ba1e9e (called at uGUIPopDetail01.cpp:717)
//   in uGUIPopDetail01::refresh at 0x00ba20d6-0x00ba20e3, 0x00ba21b3-0x00ba21ca (called at uGUIPopDetail01.cpp:2520)
//   in uGUIPopDetail01::refresh at 0x00ba20f7-0x00ba2104 (called at uGUIPopDetail01.cpp:2623)
//   and 6 more (every copy is in <bundle>.inlined.json)
// bool uGUIPopDetail01::isUseMockup();

// No out-of-line body: 5 inlined copies in 5 functions (43 bytes)
//   in uGUIAreaMaster::setup at 0x00929f42-0x00929f49 (called at uGUIAreaMaster.cpp:989)
//   in uGUIArisenCard::initItemDetail at 0x0093a175-0x0093a17c (called at uGUIArisenCard.cpp:5066)
//   in uGUICharacter::setup at 0x009ee9c2-0x009ee9cf (called at uGUICharacter.cpp:1161)
//   and 2 more (every copy is in <bundle>.inlined.json)
// void uGUIPopDetail01::setUseMockup(bool b);

// No out-of-line body: 4 inlined copies in 4 functions (93 bytes)
//   in uGUIPopDetail01::evCtrlTop at 0x00ba1e91-0x00ba1ea3 (called at uGUIPopDetail01.cpp:3089)
//   in uGUIPopDetail01::updateInit at 0x00ba2749-0x00ba2761 (called at uGUIPopDetail01.cpp:1579)
//   in uGUIPopDetail01::updateWait at 0x00ba3e0e-0x00ba3e26 (called at uGUIPopDetail01.cpp:1579)
//   and 1 more (every copy is in <bundle>.inlined.json)
// bool uGUIPopDetail01::isUseMockupOnly();

// No out-of-line body: 2 inlined copies in 1 function (28 bytes)
//   in uGUICraft::setupItemDetail at 0x00a5f40a-0x00a5f41d (called at uGUICraft.cpp:9358)
//   in uGUICraft::setupItemDetail at 0x00a5f518-0x00a5f521 (called at uGUICraft.cpp:9389)
// void uGUIPopDetail01::setUseMockupOnly(bool b);

// Address: 0x00ba6040 - 0x00ba611b (219 bytes)
__attribute__((weak)) void uGUIPopDetail01::initMockUp() {
    // local: TEXTURE* ptex;
    DDON_STUB("uGUIPopDetail01::initMockUp")
    /* stub */
}

// Address: 0x00ba3ea0 - 0x00ba3ff8 (344 bytes)
__attribute__((weak)) void uGUIPopDetail01::refreshMockUp() {
    // local: u32 itemNo;
    // local: s8 colorNo;
    // local: rItemParam* pParam;
    DDON_STUB("uGUIPopDetail01::refreshMockUp")
    /* stub */
}

// Address: 0x00ba6120 - 0x00ba6175 (85 bytes)
void uGUIPopDetail01::setTargetChara(nGUIExt::TARGET target, u32 id, bool isRequestServer) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (target == static_cast<nGUIExt::TARGET>(1)) {
        if (isRequestServer != false) {
            if (this->mTarget != static_cast<nGUIExt::TARGET>(1)) {
                static_cast<sNetworkExt*>(::sNetwork::getInstance())->::sNetworkExt::getGameServer()->::cNetGameServer::getMyPawnList();
            }
        }
    }
    this->mTarget = target;
    this->mTargetId = id;
}

// No out-of-line body: 1 inlined copy in 1 function (10 bytes)
//   in uGUIPopDetail01::uGUIPopDetail01 at 0x00ba0268-0x00ba0272 (called at uGUIPopDetail01.cpp:154)
// void uGUIPopDetail01::setPageType(uGUIPopDetail01::PAGE_TYPE type);

// No out-of-line body: 4 inlined copies in 3 functions (42 bytes)
//   in uGUIPopDetail01::evCtrlTop at 0x00ba1e87-0x00ba1e91 (called at uGUIPopDetail01.cpp:3089)
//   in uGUIPopDetail01::refresh at 0x00ba2164-0x00ba2177 (called at uGUIPopDetail01.cpp:2507)
//   in uGUIPopDetail01::refresh at 0x00ba2283-0x00ba2287 (called at uGUIPopDetail01.cpp:2529)
//   and 1 more (every copy is in <bundle>.inlined.json)
// bool uGUIPopDetail01::isUseCraftMode();

// Address: 0x00ba26b0 - 0x00ba26ff (79 bytes)
__attribute__((weak)) void uGUIPopDetail01::setCraftMode(bool b) {
    DDON_STUB("uGUIPopDetail01::setCraftMode")
    /* stub */
}

// Address: 0x00ba2700 - 0x00ba2729 (41 bytes)
__attribute__((weak)) void uGUIPopDetail01::resetPageType() {
    DDON_STUB("uGUIPopDetail01::resetPageType")
    /* stub */
}

// No out-of-line body: 1 inlined copy in 1 function (7 bytes)
//   in uGUICraft::setup at 0x00a563c7-0x00a563ce (called at uGUICraft.cpp:1692)
// void uGUIPopDetail01::setCraftDetail(uGUIPopCraftDetail* pCraftDetail);

// No out-of-line body: 1 inlined copy in 1 function (10 bytes)
//   in uGUIPopDetail01::createPartsItemNum at 0x00ba4519-0x00ba4523 (called at uGUIPopDetail01.cpp:1861)
// bool uGUIPopDetail01::isAddBaggageItemNum() const;

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::setAddBaggageItemNum(bool);

// Address: 0x00ba2740 - 0x00ba27cd (141 bytes)
__attribute__((weak)) void uGUIPopDetail01::updateInit() {
    DDON_STUB("uGUIPopDetail01::updateInit")
    /* stub */
}

// Address: 0x00ba3da0 - 0x00ba3e77 (215 bytes)
__attribute__((weak)) void uGUIPopDetail01::updateWait() {
    DDON_STUB("uGUIPopDetail01::updateWait")
    /* stub */
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::updateExit();

// No out-of-line body: 2 inlined copies in 2 functions (180 bytes)
//   in uGUIPopDetail01::updateInit at 0x00ba2749-0x00ba2761, 0x00ba2766-0x00ba27a5 (called at uGUIPopDetail01.cpp:810)
//   in uGUIPopDetail01::updateWait at 0x00ba3e0e-0x00ba3e26, 0x00ba3e2b-0x00ba3e70 (called at uGUIPopDetail01.cpp:833)
// void uGUIPopDetail01::executeWindow();

// Address: 0x00ba27e0 - 0x00ba3da0 (5568 bytes)
__attribute__((weak)) void uGUIPopDetail01::buildParts() {
    // local: rItemParam* const pParamDisp;
    // local: u32 i;
    // local: const bool isCheck;
    // local: u32 i;
    // local: const s32 initFrame;
    // local: u32 infoStartPage;
    // local: StringItemCategoryName category_name;
    // local: MtString price_str;
    // local: MtString infoStr;
    // local: const EQUIP_SLOT_TYPE equip_slot_type;
    // local: const bool is_main;
    // local: const u32 physical_attack_base;
    // local: const u32 physical_attack_disp;
    // local: const s32 frame_disp;
    // local: const s32 frame_base;
    // local: const u32 magic_attack_base;
    // local: const u32 magic_attack_disp;
    // local: const s32 frame_disp;
    // local: const s32 frame_base;
    // local: const u32 physical_defense_base;
    // local: const u32 physical_defense_disp;
    // local: const u32 magic_defense_base;
    // local: const u32 magic_defense_disp;
    // local: const SP_ITEM* pSpData;
    DDON_STUB("uGUIPopDetail01::buildParts")
    /* stub */
}

// No out-of-line body: 5 inlined copies in 5 functions (83 bytes)
//   in uGUIPopDetail01::refresh at 0x00ba210e-0x00ba211b (called at uGUIPopDetail01.cpp:2626)
//   in uGUIPopDetail01::createPartsCraft at 0x00ba5819-0x00ba5829 (called at uGUIPopDetail01.cpp:2412)
//   in uGUIPopDetail01::setupParamRegist at 0x00ba670f-0x00ba6724, 0x00ba6730-0x00ba6739 (called at uGUIPopDetail01.cpp:2167)
//   and 2 more (every copy is in <bundle>.inlined.json)
// bool uGUIPopDetail01::isDouble();

// No out-of-line body: 2 inlined copies in 1 function (40 bytes)
//   in uGUIPopDetail01::createPartsItemGrade at 0x00ba474f-0x00ba4765 (called at uGUIPopDetail01.cpp:1748)
//   in uGUIPopDetail01::createPartsItemGrade at 0x00ba478f-0x00ba47a1 (called at uGUIPopDetail01.cpp:1753)
// u8 uGUIPopDetail01::getGrade();

// No out-of-line body: 3 inlined copies in 2 functions (115 bytes)
//   in uGUIPopDetail01::refresh at 0x00ba206f-0x00ba2099 (called at uGUIPopDetail01.cpp:2422)
//   in uGUIPopDetail01::createPartsCraft at 0x00ba57a5-0x00ba57c6 (called at uGUIPopDetail01.cpp:1617)
//   in uGUIPopDetail01::createPartsCraft at 0x00ba5877-0x00ba589f (called at uGUIPopDetail01.cpp:2422)
// u8 uGUIPopDetail01::getElementNum();

// Address: 0x00ba61a0 - 0x00ba62c9 (297 bytes)
__attribute__((weak)) void uGUIPopDetail01::setupParam(u32& idx, bool isCompere, MT_CTSTR name, MT_CTSTR param1, MT_CTSTR param2, const MtColor& col) {
    DDON_STUB("uGUIPopDetail01::setupParam")
    /* stub */
}

// No out-of-line body: 3 inlined copies in 1 function (195 bytes)
//   in uGUIPopDetail01::setupParamWepItem2 at 0x00ba65bf-0x00ba65d0, 0x00ba6606-0x00ba6686 (called at uGUIPopDetail01.cpp:2140)
//   in uGUIPopDetail01::setupParamWepItem2 at 0x00ba65d0-0x00ba65df, 0x00ba65f6-0x00ba65fe (called at uGUIPopDetail01.cpp:2132)
//   in uGUIPopDetail01::setupParamWepItem2 at 0x00ba65df-0x00ba65f6, 0x00ba6692-0x00ba6696 (called at uGUIPopDetail01.cpp:2146)
// bool uGUIPopDetail01::setupParam2(u32& idx, bool isCompere, MT_CTSTR name, s32 param1, s32 param2, const MtColor& col, bool isUse);

// Address: 0x00ba62d0 - 0x00ba63d5 (261 bytes)
__attribute__((weak)) void uGUIPopDetail01::setupParamSt(u32& idx, MT_CTSTR name, MT_CTSTR param1, MT_CTSTR param2, const MtColor& col) {
    DDON_STUB("uGUIPopDetail01::setupParamSt")
    /* stub */
}

// Address: 0x00ba63e0 - 0x00ba6522 (322 bytes)
__attribute__((weak)) void uGUIPopDetail01::setupParamStatus(u32& idx, u32 start, u32 end, MT_CTSTR name, MT_CTSTR val, bool isUse) {
    // local: u32 num;
    // local: MtColor col;
    DDON_STUB("uGUIPopDetail01::setupParamStatus")
    /* stub */
}

// No out-of-line body: 70 inlined copies in 1 function (4878 bytes)
//   in uGUIPopDetail01::setupParamRegist at 0x00ba6770-0x00ba6775, 0x00ba6778-0x00ba67bb (called at uGUIPopDetail01.cpp:2223)
//   in uGUIPopDetail01::setupParamRegist at 0x00ba67d9-0x00ba67de, 0x00ba67e1-0x00ba6824 (called at uGUIPopDetail01.cpp:2224)
//   in uGUIPopDetail01::setupParamRegist at 0x00ba6842-0x00ba6847, 0x00ba684a-0x00ba688d (called at uGUIPopDetail01.cpp:2225)
//   and 67 more (every copy is in <bundle>.inlined.json)
// void uGUIPopDetail01::setupParamStatus(u32& idx, u32 start, u32 end, MT_CTSTR name, s32 val, bool isUse);

// No out-of-line body: 36 inlined copies in 1 function (3476 bytes)
//   in uGUIPopDetail01::setupParamRegist at 0x00ba745f-0x00ba74bf (called at uGUIPopDetail01.cpp:2266)
//   in uGUIPopDetail01::setupParamRegist at 0x00ba7516-0x00ba7568, 0x00ba756c-0x00ba757e (called at uGUIPopDetail01.cpp:2271)
//   in uGUIPopDetail01::setupParamRegist at 0x00ba75a3-0x00ba7603 (called at uGUIPopDetail01.cpp:2275)
//   and 33 more (every copy is in <bundle>.inlined.json)
// void uGUIPopDetail01::setupParamUseItem(u32& idx, u32 start, u32 end, MT_CTSTR name, rItemList::rParam* pParam, bool isUse);

// No out-of-line body: 6 inlined copies in 1 function (1231 bytes)
//   in uGUIPopDetail01::setupParamWeapon at 0x00ba9911-0x00ba99ea (called at uGUIPopDetail01.cpp:2366)
//   in uGUIPopDetail01::setupParamWeapon at 0x00ba9a46-0x00ba9b0f (called at uGUIPopDetail01.cpp:2367)
//   in uGUIPopDetail01::setupParamWeapon at 0x00ba9b6b-0x00ba9c34 (called at uGUIPopDetail01.cpp:2368)
//   and 3 more (every copy is in <bundle>.inlined.json)
// void uGUIPopDetail01::setupParamWepItem(u32& idx, u32 start, u32 end, MT_CTSTR name, s32 param1, s32 param2, const MtColor& col, bool isUse);

// Address: 0x00ba6560 - 0x00ba66bc (348 bytes)
__attribute__((weak)) void uGUIPopDetail01::setupParamWepItem2(u32& idx, u32 start, u32 end, MT_CTSTR name, s32 param1, s32 param2, const MtColor& col, bool isUse) {
    // local: const bool is_use_compare;
    // local: u32 num;
    // local: u32 num;
    // local: u32 num;
    DDON_STUB("uGUIPopDetail01::setupParamWepItem2")
    /* stub */
}

// Address: 0x00ba66c0 - 0x00ba9705 (12357 bytes)
__attribute__((weak)) u32 uGUIPopDetail01::setupParamRegist(u32 startIdx, u32 page, bool isUse) {
    // local: u32 use;
    // local: u32 VisibleRegistOldNum;
    // local: const u32 add;
    // local: u32 start;
    // local: u32 end;
    // local: u32 lineNum;
    // local: rItemParam* pParam;
    // local: rParam* pRParam;
    // local: MtStringEx<64> tmp;
    DDON_STUB("uGUIPopDetail01::setupParamRegist")
    return {};
}

// Address: 0x00ba9710 - 0x00baa4d6 (3526 bytes)
__attribute__((weak)) u32 uGUIPopDetail01::setupParamWeapon(u32 startIdx, u32 page, bool isUse) {
    // local: u32 use;
    // local: rItemParam* pParamDisp;
    // local: const u32 add;
    // local: u32 start;
    // local: u32 end;
    // local: const EQUIP_SLOT_TYPE equip_slot_type;
    // local: const cItemParam* pItemParamBase;
    // local: const rItemParam* pParamBase;
    DDON_STUB("uGUIPopDetail01::setupParamWeapon")
    return {};
}

// No out-of-line body: 2 inlined copies in 2 functions (270 bytes)
//   in uGUIPopDetail01::refresh at 0x00ba2042-0x00ba204f, 0x00ba2057-0x00ba20a7 (called at uGUIPopDetail01.cpp:2498)
//   in uGUIPopDetail01::createPartsCraft at 0x00ba57d2-0x00ba57e2, 0x00ba5819-0x00ba584a, 0x00ba5860-0x00ba58b6, 0x00ba5c45-0x00ba5c5f (called at uGUIPopDetail01.cpp:1628)
// bool uGUIPopDetail01::setupParamCraft(u32 startIdx, u32 page);

// Address: 0x00ba53a0 - 0x00ba5521 (385 bytes)
__attribute__((weak)) void uGUIPopDetail01::setupEquipMainParam(s32 paramDisp, s32 paramBase, cGUIObjNull* objNullCompare, cGUIObjMessage* objMsgNumDisp, cGUIObjMessage* objMsgNumBase, cGUIObjTexture* objTexArrow) {
    // local: const s32 current_frame;
    DDON_STUB("uGUIPopDetail01::setupEquipMainParam")
    /* stub */
}

// Address: 0x00ba5530 - 0x00ba5612 (226 bytes)
__attribute__((weak)) void uGUIPopDetail01::setupEquipElementParam(s32 frameDisp, s32 frameBase, cGUIObjNull* objNullElement, cGUIObjNull* objNullCompare, cGUIObjTexture* objTexDisp, cGUIObjTexture* objTexBase, cGUIObjTexture* objTexArrow) {
    // local: const bool current_frame;
    DDON_STUB("uGUIPopDetail01::setupEquipElementParam")
    /* stub */
}

// Address: 0x00ba1f40 - 0x00ba23b0 (1136 bytes)
__attribute__((weak)) void uGUIPopDetail01::refresh(bool isChangeItem) {
    // local: bool change;
    DDON_STUB("uGUIPopDetail01::refresh")
    /* stub */
}

// No out-of-line body: 1 inlined copy in 1 function (157 bytes)
//   in uGUIPopDetail01::refresh at 0x00ba1f54-0x00ba1f6a, 0x00ba1f72-0x00ba1ff9 (called at uGUIPopDetail01.cpp:2487)
// uGUIPopDetail01::ITEM_TYPE uGUIPopDetail01::getItemType(nGUIItem::cItem& item);

// No out-of-line body: 115 inlined copies in 8 functions (2838 bytes)
//   in uGUIPopDetail01::buildParts at 0x00ba3004-0x00ba3022 (called at uGUIPopDetail01.cpp:1001)
//   in uGUIPopDetail01::buildParts at 0x00ba3086-0x00ba30a4 (called at uGUIPopDetail01.cpp:1013)
//   in uGUIPopDetail01::buildParts at 0x00ba318f-0x00ba31af, 0x00ba3665-0x00ba366c (called at uGUIPopDetail01.cpp:1121)
//   and 112 more (every copy is in <bundle>.inlined.json)
// MT_CTSTR uGUIPopDetail01::getMsgParam(u32 id);

// No out-of-line body: 34 inlined copies in 1 function (986 bytes)
//   in uGUIPopDetail01::setupParamRegist at 0x00ba757e-0x00ba759b (called at uGUIPopDetail01.cpp:2275)
//   in uGUIPopDetail01::setupParamRegist at 0x00ba7603-0x00ba7620 (called at uGUIPopDetail01.cpp:2276)
//   in uGUIPopDetail01::setupParamRegist at 0x00ba7688-0x00ba76a5 (called at uGUIPopDetail01.cpp:2277)
//   and 31 more (every copy is in <bundle>.inlined.json)
// MT_CTSTR uGUIPopDetail01::getMsgItemWork(u32 id);

// No out-of-line body: no code in the ELF
// MT_CTSTR uGUIPopDetail01::getMsgJewelryCategory(u32);

// No out-of-line body: 1 inlined copy in 1 function (140 bytes)
//   in uGUIPopDetail01::refresh at 0x00ba20bc-0x00ba20d6, 0x00ba20e3-0x00ba2104, 0x00ba210e-0x00ba215f (called at uGUIPopDetail01.cpp:2506)
// u32 uGUIPopDetail01::calcPageNum();

// Address: 0x00baa4f0 - 0x00baa5f2 (258 bytes)
__attribute__((weak)) void uGUIPopDetail01::updatePageDotNum() {
    // local: s32 num;
    // local: s32 add;
    // local: const u32 div;
    DDON_STUB("uGUIPopDetail01::updatePageDotNum")
    /* stub */
}

// No out-of-line body: 3 inlined copies in 3 functions (121 bytes)
//   in uGUIPopDetail01::createPartsRegist at 0x00ba4cd6-0x00ba4cf8 (called at uGUIPopDetail01.cpp:2766)
//   in uGUIPopDetail01::createPartsStatus at 0x00ba564b-0x00ba566d (called at uGUIPopDetail01.cpp:2731)
//   in uGUIPopDetail01::createPartsCraft at 0x00ba57f6-0x00ba5819, 0x00ba584a-0x00ba585c (called at uGUIPopDetail01.cpp:1628)
// u32 uGUIPopDetail01::getDispInfoPage();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::createParamList();

// No out-of-line body: 1 inlined copy in 1 function (24 bytes)
//   in uGUIPopDetail01::buildParts at 0x00ba3270-0x00ba3288 (called at uGUIPopDetail01.cpp:1057)
// const uGUIPopDetail01::SP_ITEM* uGUIPopDetail01::getSpItem(u32 itemNo);

// No out-of-line body: 1 inlined copy in 1 function (39 bytes)
//   in uGUIPopDetail01::buildParts at 0x00ba3447-0x00ba346e (called at uGUIPopDetail01.cpp:1063)
// bool uGUIPopDetail01::isMoneyItem(rItemList::rItemParam* pParam);

// Address: 0x00ba5d80 - 0x00ba5f64 (484 bytes)
__attribute__((weak)) void uGUIPopDetail01::updateEquipData() {
    // local: rItemParam* const item_param_resource;
    // local: cItemParam* const item_param;
    // local: const EQUIP_SLOT_TYPE equip_slot_type;
    // local: const cItemParam* const item_param_equip;
    // local: cItemParam item;
    DDON_STUB("uGUIPopDetail01::updateEquipData")
    /* stub */
}

// No out-of-line body: 3 inlined copies in 3 functions (216 bytes)
//   in uGUIPopDetail01::buildParts at 0x00ba313f-0x00ba3188 (called at uGUIPopDetail01.cpp:1113)
//   in uGUIPopDetail01::updateEquipData at 0x00ba5e06-0x00ba5e4c (called at uGUIPopDetail01.cpp:3235)
//   in uGUIPopDetail01::setupParamWeapon at 0x00ba9795-0x00ba97de (called at uGUIPopDetail01.cpp:2358)
// nCharacterData::EQUIP_SLOT_TYPE uGUIPopDetail01::getEquipSlotType();

// No out-of-line body: 1 inlined copy in 1 function (60 bytes)
//   in uGUIPopDetail01::buildParts at 0x00ba3968-0x00ba39a4 (called at uGUIPopDetail01.cpp:1160)
// void uGUIPopDetail01::createPartsParam();

// Address: 0x00ba5770 - 0x00ba5c87 (1303 bytes)
__attribute__((weak)) void uGUIPopDetail01::createPartsCraft() {
    // local: rItemParam* pParam;
    // local: cItemParam* pItemParam;
    // local: const u32 element_num;
    // local: s32 elemet_offset_y;
    // local: u32 element_i;
    // local: bool is_visible;
    // local: cDupCraftParam* const dup_craft_param;
    // local: rItemParam* element_param;
    // local: const s32 pos_y;
    // local: const u32 instruction_num;
    // local: const MT_CTSTR element_name;
    // local: const f32 crest_icon_frame;
    // local: MtStringEx<256> replace_name;
    // local: u32 instruction_i;
    // local: rParam* const instruction_param;
    // local: const s32 element_param_kind;
    // local: MtStringEx<128> tmp;
    DDON_STUB("uGUIPopDetail01::createPartsCraft")
    /* stub */
}

// No out-of-line body: 6 inlined copies in 1 function (345 bytes)
//   in uGUIPopDetail01::buildParts at 0x00ba3381-0x00ba33be (called at uGUIPopDetail01.cpp:1257)
//   in uGUIPopDetail01::buildParts at 0x00ba39a4-0x00ba39e0 (called at uGUIPopDetail01.cpp:1161)
//   in uGUIPopDetail01::buildParts at 0x00ba3a88-0x00ba3ac0 (called at uGUIPopDetail01.cpp:1016)
//   and 3 more (every copy is in <bundle>.inlined.json)
// void uGUIPopDetail01::createPartsItemRank();

// Address: 0x00ba46f0 - 0x00ba47e8 (248 bytes)
__attribute__((weak)) void uGUIPopDetail01::createPartsItemGrade() {
    // local: cGUIInstAnimation* pGradeInst[4];
    // local: u32 i;
    DDON_STUB("uGUIPopDetail01::createPartsItemGrade")
    /* stub */
}

// Address: 0x00ba42a0 - 0x00ba46dc (1084 bytes)
__attribute__((weak)) void uGUIPopDetail01::createPartsItemNum(rItemList::rItemParam* pParam) {
    // local: ItemBagPtr bag_pl;
    // local: bool isMoney;
    // local: u32 msgNo;
    // local: rParam* pKindParam;
    // local: const E_WALLET_POINT_TYPE wallet_point_type;
    // local: u32 storageTotal;
    // local: ItemBagPtr bag_storage;
    // local: ItemBagPtr bag_storage_ex;
    // local: ItemBagPtr bag_baggage_free;
    // local: ItemBagPtr bag_baggage_rental;
    // local: MtString tmpStr;
    DDON_STUB("uGUIPopDetail01::createPartsItemNum")
    /* stub */
}

// Address: 0x00ba4e00 - 0x00ba50e0 (736 bytes)
__attribute__((weak)) void uGUIPopDetail01::createPartsSpItemNum(const uGUIPopDetail01::SP_ITEM* pSp) {
    // local: bool isNumView;
    // local: MtString rStr;
    // local: MtString tmpStr;
    DDON_STUB("uGUIPopDetail01::createPartsSpItemNum")
    /* stub */
}

// Address: 0x00ba5630 - 0x00ba5769 (313 bytes)
__attribute__((weak)) void uGUIPopDetail01::createPartsStatus() {
    // local: bool isTitle;
    // local: const u32 startNum;
    // local: u32 i;
    DDON_STUB("uGUIPopDetail01::createPartsStatus")
    /* stub */
}

// Address: 0x00ba4cb0 - 0x00ba4df0 (320 bytes)
__attribute__((weak)) void uGUIPopDetail01::createPartsRegist() {
    // local: bool isTitle;
    // local: rItemParam* pParam;
    // local: u32 i;
    DDON_STUB("uGUIPopDetail01::createPartsRegist")
    /* stub */
}

// No out-of-line body: 5 inlined copies in 1 function (306 bytes)
//   in uGUIPopDetail01::buildParts at 0x00ba3a38-0x00ba3a79 (called at uGUIPopDetail01.cpp:1258)
//   in uGUIPopDetail01::buildParts at 0x00ba3acb-0x00ba3b07 (called at uGUIPopDetail01.cpp:1018)
//   in uGUIPopDetail01::buildParts at 0x00ba3bc8-0x00ba3c09 (called at uGUIPopDetail01.cpp:1249)
//   and 2 more (every copy is in <bundle>.inlined.json)
// void uGUIPopDetail01::createPartsCaption();

// Address: 0x00ba4a30 - 0x00ba4b6f (319 bytes)
__attribute__((weak)) void uGUIPopDetail01::createPartsFooter() {
    // local: rItemParam* pParam;
    // local: s32 texSize;
    // local: s32 pos;
    // local: cGUIObjTexture* pTex;
    DDON_STUB("uGUIPopDetail01::createPartsFooter")
    /* stub */
}

// Address: 0x00ba4b70 - 0x00ba4ca1 (305 bytes)
__attribute__((weak)) void uGUIPopDetail01::createPartsJob() {
    // local: rItemParam* pParam;
    // local: MT_CTSTR gender_limit;
    DDON_STUB("uGUIPopDetail01::createPartsJob")
    /* stub */
}

// Address: 0x00ba4000 - 0x00ba4296 (662 bytes)
__attribute__((weak)) void uGUIPopDetail01::createEquipIcon() {
    // local: bool is_visible_m_num03;
    // local: bool is_visible_icon_equip02;
    // local: bool is_visible_icon_equip01;
    // local: bool is_visible_m_num02;
    // local: bool is_visible_icon_equip;
    // local: rItemParam* pParam;
    // local: cItemBag* pBagPL;
    // local: cItemParam tmpItemParam;
    // local: u32 total;
    // local: u32 myTotal;
    DDON_STUB("uGUIPopDetail01::createEquipIcon")
    /* stub */
}

// Address: 0x00ba4800 - 0x00ba4a23 (547 bytes)
__attribute__((weak)) void uGUIPopDetail01::createPartsCrest() {
    // local: rItemParam* const item_param;
    // local: const MATERIAL_CATEGORY material_category;
    // local: const u32 element_num;
    // local: const u32 param_index_start;
    // local: u32 param_index;
    // local: const u32 param_index_end;
    // local: u32 line_num;
    // local: MtStringEx<128> formatted_str;
    // local: const bool is_title;
    // local: u32 i;
    // local: u32 i;
    DDON_STUB("uGUIPopDetail01::createPartsCrest")
    /* stub */
}

// Address: 0x00ba50f0 - 0x00ba5383 (659 bytes)
__attribute__((weak)) void uGUIPopDetail01::createPartsPoint() {
    // local: rItemParam* const item_param;
    // local: const u32 param_num;
    // local: const u32 param_index_start;
    // local: u32 param_index;
    // local: const u32 param_index_end;
    // local: u32 line_num;
    // local: const bool is_title;
    // local: u32 i;
    // local: rParam* const param;
    // local: u32 point;
    // local: MT_CTSTR name;
    // local: const PARAM_KIND param_kind;
    // local: const u32 area_id;
    // local: const u32 job_id;
    // local: MtStringEx<128> formatted_str;
    // local: u32 i;
    DDON_STUB("uGUIPopDetail01::createPartsPoint")
    /* stub */
}

// No out-of-line body: no code in the ELF
// MT_CTSTR uGUIPopDetail01::getEquipCategoryName();

// Address: 0x00ba1e50 - 0x00ba1f2f (223 bytes)
__attribute__((weak)) u32 uGUIPopDetail01::evCtrlTop(cControl::Message* msg) {
    // local: const bool isDrawCraftDetail;
    DDON_STUB("uGUIPopDetail01::evCtrlTop")
    return {};
}

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa723-0x00baa760 (called at uGUIPopDetail01.cpp:42)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa723-0x00baa760 (called at uGUIPopDetail01.h:22)
// uGUIPopDetail01::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00b9f590 - 0x00b9f5d4 (68 bytes)
__attribute__((weak)) MtObject* uGUIPopDetail01::MyDTI::newInstance() const {
    DDON_STUB("uGUIPopDetail01::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* uGUIPopDetail01::cDupParam::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cDupParam::usage();

// Address: 0x01afc9a0 - 0x01afc9a8 (8 bytes)
const MtDTI& uGUIPopDetail01::cDupParam::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uGUIPopDetail01::cDupParam::DTI;
}

// No out-of-line body: 2 inlined copies in 2 functions (33 bytes)
//   in uGUIPopDetail01::cDupParam::MyDTI::newInstance at 0x00b9fd94-0x00b9fda6 (called at uGUIPopDetail01.cpp:51)
//   in uGUIPopDetail01::setup at 0x00ba1644-0x00ba1653 (called at uGUIPopDetail01.cpp:51)
// MtAllocator* uGUIPopDetail01::cDupParam::getAllocator();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cDupParam::setAllocator(u32);

// No out-of-line body: 2 inlined copies in 2 functions (82 bytes)
//   in uGUIPopDetail01::cDupParam::MyDTI::newInstance at 0x00b9fd94-0x00b9fdbd (called at uGUIPopDetail01.cpp:51)
//   in uGUIPopDetail01::setup at 0x00ba1644-0x00ba166d (called at uGUIPopDetail01.cpp:438)
// void* uGUIPopDetail01::cDupParam::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cDupParam::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cDupParam::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cDupParam::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN15uGUIPopDetail019cDupParamD0Ev at 0x01afc970-0x01afc99a, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void uGUIPopDetail01::cDupParam::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uGUIPopDetail01::cDupParam::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cDupParam::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cDupParam::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cDupParam::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 4 inlined copies in 2 functions (402 bytes)
//   in uGUIPopDetail01::cDupParam::MyDTI::newInstance at 0x00b9fdbd-0x00b9fe16 (called at uGUIPopDetail01.cpp:51)
//   in uGUIPopDetail01::cDupParam::MyDTI::newInstance at 0x00b9fdbd-0x00b9fe16 (called at uGUIPopDetail01.h:222)
//   in uGUIPopDetail01::setup at 0x00ba15fd-0x00ba161d, 0x00ba166d-0x00ba16bd (called at uGUIPopDetail01.cpp:438)
//   and 1 more (every copy is in <bundle>.inlined.json)
// uGUIPopDetail01::cDupParam::cDupParam();

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa92f-0x00baa968 (called at uGUIPopDetail01.cpp:51)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa92f-0x00baa968 (called at uGUIPopDetail01.h:219)
// uGUIPopDetail01::cDupParam::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00b9fd90 - 0x00b9fe1b (139 bytes)
__attribute__((weak)) MtObject* uGUIPopDetail01::cDupParam::MyDTI::newInstance() const {
    DDON_STUB("uGUIPopDetail01::cDupParam::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* uGUIPopDetail01::cDupCraftParam::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cDupCraftParam::usage();

// Address: 0x01afc950 - 0x01afc958 (8 bytes)
const MtDTI& uGUIPopDetail01::cDupCraftParam::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uGUIPopDetail01::cDupCraftParam::DTI;
}

// No out-of-line body: 2 inlined copies in 2 functions (41 bytes)
//   in uGUIPopDetail01::cDupCraftParam::MyDTI::newInstance at 0x00b9fe94-0x00b9fea6 (called at uGUIPopDetail01.cpp:52)
//   in uGUIPopDetail01::setup at 0x00ba19c8-0x00ba19df (called at uGUIPopDetail01.cpp:52)
// MtAllocator* uGUIPopDetail01::cDupCraftParam::getAllocator();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cDupCraftParam::setAllocator(u32);

// No out-of-line body: 2 inlined copies in 2 functions (90 bytes)
//   in uGUIPopDetail01::cDupCraftParam::MyDTI::newInstance at 0x00b9fe94-0x00b9febd (called at uGUIPopDetail01.cpp:52)
//   in uGUIPopDetail01::setup at 0x00ba19c8-0x00ba19f9 (called at uGUIPopDetail01.cpp:459)
// void* uGUIPopDetail01::cDupCraftParam::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cDupCraftParam::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cDupCraftParam::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cDupCraftParam::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN15uGUIPopDetail0114cDupCraftParamD0Ev at 0x01afc920-0x01afc94a, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void uGUIPopDetail01::cDupCraftParam::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uGUIPopDetail01::cDupCraftParam::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cDupCraftParam::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cDupCraftParam::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cDupCraftParam::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 4 inlined copies in 2 functions (308 bytes)
//   in uGUIPopDetail01::cDupCraftParam::MyDTI::newInstance at 0x00b9febd-0x00b9ff06 (called at uGUIPopDetail01.cpp:52)
//   in uGUIPopDetail01::cDupCraftParam::MyDTI::newInstance at 0x00b9febd-0x00b9ff06 (called at uGUIPopDetail01.h:244)
//   in uGUIPopDetail01::setup at 0x00ba19ac-0x00ba19bd, 0x00ba19f9-0x00ba1a39 (called at uGUIPopDetail01.cpp:459)
//   and 1 more (every copy is in <bundle>.inlined.json)
// uGUIPopDetail01::cDupCraftParam::cDupCraftParam();

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa968-0x00baa9a1 (called at uGUIPopDetail01.cpp:52)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa968-0x00baa9a1 (called at uGUIPopDetail01.h:241)
// uGUIPopDetail01::cDupCraftParam::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00b9fe90 - 0x00b9ff0b (123 bytes)
__attribute__((weak)) MtObject* uGUIPopDetail01::cDupCraftParam::MyDTI::newInstance() const {
    DDON_STUB("uGUIPopDetail01::cDupCraftParam::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* uGUIPopDetail01::cPartsBase::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsBase::usage();

// Address: 0x01afca40 - 0x01afca48 (8 bytes)
const MtDTI& uGUIPopDetail01::cPartsBase::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uGUIPopDetail01::cPartsBase::DTI;
}

// No out-of-line body: 1 inlined copy in 1 function (18 bytes)
//   in uGUIPopDetail01::cPartsBase::MyDTI::newInstance at 0x00b9f694-0x00b9f6a6 (called at uGUIPopDetail01.cpp:43)
// MtAllocator* uGUIPopDetail01::cPartsBase::getAllocator();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsBase::setAllocator(u32);

// No out-of-line body: 1 inlined copy in 1 function (41 bytes)
//   in uGUIPopDetail01::cPartsBase::MyDTI::newInstance at 0x00b9f694-0x00b9f6bd (called at uGUIPopDetail01.cpp:43)
// void* uGUIPopDetail01::cPartsBase::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsBase::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsBase::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsBase::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN15uGUIPopDetail0110cPartsBaseD0Ev at 0x01afca10-0x01afca3a, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void uGUIPopDetail01::cPartsBase::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uGUIPopDetail01::cPartsBase::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsBase::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsBase::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsBase::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 9 inlined copies in 8 functions (415 bytes)
//   in uGUIPopDetail01::cPartsBase::MyDTI::newInstance at 0x00b9f6bd-0x00b9f6f6 (called at uGUIPopDetail01.cpp:43)
//   in uGUIPopDetail01::cPartsBase::MyDTI::newInstance at 0x00b9f6bd-0x00b9f6f6 (called at uGUIPopDetail01.h:132)
//   in uGUIPopDetail01::cPartsCraft::MyDTI::newInstance at 0x00b9f79d-0x00b9f7c8 (called at uGUIPopDetail01.h:145)
//   and 6 more (every copy is in <bundle>.inlined.json)
// uGUIPopDetail01::cPartsBase::cPartsBase();

// No out-of-line body: 2 inlined copies in 1 function (128 bytes)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa760-0x00baa7a0 (called at uGUIPopDetail01.cpp:43)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa760-0x00baa7a0 (called at uGUIPopDetail01.h:129)
// uGUIPopDetail01::cPartsBase::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00b9f690 - 0x00b9f6fb (107 bytes)
__attribute__((weak)) MtObject* uGUIPopDetail01::cPartsBase::MyDTI::newInstance() const {
    DDON_STUB("uGUIPopDetail01::cPartsBase::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* uGUIPopDetail01::cPartsCraft::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsCraft::usage();

// Address: 0x01afcc20 - 0x01afcc28 (8 bytes)
const MtDTI& uGUIPopDetail01::cPartsCraft::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uGUIPopDetail01::cPartsCraft::DTI;
}

// No out-of-line body: 1 inlined copy in 1 function (18 bytes)
//   in uGUIPopDetail01::cPartsCraft::MyDTI::newInstance at 0x00b9f774-0x00b9f786 (called at uGUIPopDetail01.cpp:44)
// MtAllocator* uGUIPopDetail01::cPartsCraft::getAllocator();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsCraft::setAllocator(u32);

// No out-of-line body: 1 inlined copy in 1 function (41 bytes)
//   in uGUIPopDetail01::cPartsCraft::MyDTI::newInstance at 0x00b9f774-0x00b9f79d (called at uGUIPopDetail01.cpp:44)
// void* uGUIPopDetail01::cPartsCraft::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsCraft::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsCraft::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsCraft::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN15uGUIPopDetail0111cPartsCraftD0Ev at 0x01afcbf0-0x01afcc1a, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void uGUIPopDetail01::cPartsCraft::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uGUIPopDetail01::cPartsCraft::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsCraft::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsCraft::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsCraft::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in uGUIPopDetail01::cPartsCraft::MyDTI::newInstance at 0x00b9f79d-0x00b9f7d6 (called at uGUIPopDetail01.cpp:44)
//   in uGUIPopDetail01::cPartsCraft::MyDTI::newInstance at 0x00b9f79d-0x00b9f7d6 (called at uGUIPopDetail01.h:145)
// uGUIPopDetail01::cPartsCraft::cPartsCraft();

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa7a0-0x00baa7d9 (called at uGUIPopDetail01.cpp:44)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa7a0-0x00baa7d9 (called at uGUIPopDetail01.h:142)
// uGUIPopDetail01::cPartsCraft::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00b9f770 - 0x00b9f7db (107 bytes)
__attribute__((weak)) MtObject* uGUIPopDetail01::cPartsCraft::MyDTI::newInstance() const {
    DDON_STUB("uGUIPopDetail01::cPartsCraft::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* uGUIPopDetail01::cPartsParam::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsParam::usage();

// Address: 0x01afcbd0 - 0x01afcbd8 (8 bytes)
const MtDTI& uGUIPopDetail01::cPartsParam::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uGUIPopDetail01::cPartsParam::DTI;
}

// No out-of-line body: 1 inlined copy in 1 function (18 bytes)
//   in uGUIPopDetail01::cPartsParam::MyDTI::newInstance at 0x00b9f854-0x00b9f866 (called at uGUIPopDetail01.cpp:45)
// MtAllocator* uGUIPopDetail01::cPartsParam::getAllocator();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsParam::setAllocator(u32);

// No out-of-line body: 1 inlined copy in 1 function (41 bytes)
//   in uGUIPopDetail01::cPartsParam::MyDTI::newInstance at 0x00b9f854-0x00b9f87d (called at uGUIPopDetail01.cpp:45)
// void* uGUIPopDetail01::cPartsParam::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsParam::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsParam::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsParam::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN15uGUIPopDetail0111cPartsParamD0Ev at 0x01afcba0-0x01afcbca, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void uGUIPopDetail01::cPartsParam::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uGUIPopDetail01::cPartsParam::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsParam::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsParam::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsParam::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in uGUIPopDetail01::cPartsParam::MyDTI::newInstance at 0x00b9f87d-0x00b9f8b6 (called at uGUIPopDetail01.cpp:45)
//   in uGUIPopDetail01::cPartsParam::MyDTI::newInstance at 0x00b9f87d-0x00b9f8b6 (called at uGUIPopDetail01.h:156)
// uGUIPopDetail01::cPartsParam::cPartsParam();

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa7d9-0x00baa812 (called at uGUIPopDetail01.cpp:45)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa7d9-0x00baa812 (called at uGUIPopDetail01.h:153)
// uGUIPopDetail01::cPartsParam::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00b9f850 - 0x00b9f8bb (107 bytes)
__attribute__((weak)) MtObject* uGUIPopDetail01::cPartsParam::MyDTI::newInstance() const {
    DDON_STUB("uGUIPopDetail01::cPartsParam::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* uGUIPopDetail01::cPartsItemRank::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsItemRank::usage();

// Address: 0x01afcb80 - 0x01afcb88 (8 bytes)
const MtDTI& uGUIPopDetail01::cPartsItemRank::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uGUIPopDetail01::cPartsItemRank::DTI;
}

// No out-of-line body: 1 inlined copy in 1 function (18 bytes)
//   in uGUIPopDetail01::cPartsItemRank::MyDTI::newInstance at 0x00b9f934-0x00b9f946 (called at uGUIPopDetail01.cpp:46)
// MtAllocator* uGUIPopDetail01::cPartsItemRank::getAllocator();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsItemRank::setAllocator(u32);

// No out-of-line body: 1 inlined copy in 1 function (41 bytes)
//   in uGUIPopDetail01::cPartsItemRank::MyDTI::newInstance at 0x00b9f934-0x00b9f95d (called at uGUIPopDetail01.cpp:46)
// void* uGUIPopDetail01::cPartsItemRank::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsItemRank::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsItemRank::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsItemRank::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN15uGUIPopDetail0114cPartsItemRankD0Ev at 0x01afcb50-0x01afcb7a, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void uGUIPopDetail01::cPartsItemRank::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uGUIPopDetail01::cPartsItemRank::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsItemRank::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsItemRank::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsItemRank::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in uGUIPopDetail01::cPartsItemRank::MyDTI::newInstance at 0x00b9f95d-0x00b9f996 (called at uGUIPopDetail01.cpp:46)
//   in uGUIPopDetail01::cPartsItemRank::MyDTI::newInstance at 0x00b9f95d-0x00b9f996 (called at uGUIPopDetail01.h:167)
// uGUIPopDetail01::cPartsItemRank::cPartsItemRank();

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa812-0x00baa84b (called at uGUIPopDetail01.cpp:46)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa812-0x00baa84b (called at uGUIPopDetail01.h:164)
// uGUIPopDetail01::cPartsItemRank::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00b9f930 - 0x00b9f99b (107 bytes)
__attribute__((weak)) MtObject* uGUIPopDetail01::cPartsItemRank::MyDTI::newInstance() const {
    DDON_STUB("uGUIPopDetail01::cPartsItemRank::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* uGUIPopDetail01::cPartsStatus::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsStatus::usage();

// Address: 0x01afcb30 - 0x01afcb38 (8 bytes)
const MtDTI& uGUIPopDetail01::cPartsStatus::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uGUIPopDetail01::cPartsStatus::DTI;
}

// No out-of-line body: 1 inlined copy in 1 function (18 bytes)
//   in uGUIPopDetail01::cPartsStatus::MyDTI::newInstance at 0x00b9fa14-0x00b9fa26 (called at uGUIPopDetail01.cpp:47)
// MtAllocator* uGUIPopDetail01::cPartsStatus::getAllocator();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsStatus::setAllocator(u32);

// No out-of-line body: 1 inlined copy in 1 function (41 bytes)
//   in uGUIPopDetail01::cPartsStatus::MyDTI::newInstance at 0x00b9fa14-0x00b9fa3d (called at uGUIPopDetail01.cpp:47)
// void* uGUIPopDetail01::cPartsStatus::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsStatus::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsStatus::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsStatus::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN15uGUIPopDetail0112cPartsStatusD0Ev at 0x01afcb00-0x01afcb2a, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void uGUIPopDetail01::cPartsStatus::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uGUIPopDetail01::cPartsStatus::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsStatus::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsStatus::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsStatus::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in uGUIPopDetail01::cPartsStatus::MyDTI::newInstance at 0x00b9fa3d-0x00b9fa76 (called at uGUIPopDetail01.cpp:47)
//   in uGUIPopDetail01::cPartsStatus::MyDTI::newInstance at 0x00b9fa3d-0x00b9fa76 (called at uGUIPopDetail01.h:178)
// uGUIPopDetail01::cPartsStatus::cPartsStatus();

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa84b-0x00baa884 (called at uGUIPopDetail01.cpp:47)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa84b-0x00baa884 (called at uGUIPopDetail01.h:175)
// uGUIPopDetail01::cPartsStatus::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00b9fa10 - 0x00b9fa7b (107 bytes)
__attribute__((weak)) MtObject* uGUIPopDetail01::cPartsStatus::MyDTI::newInstance() const {
    DDON_STUB("uGUIPopDetail01::cPartsStatus::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* uGUIPopDetail01::cPartsCaption::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsCaption::usage();

// Address: 0x01afcae0 - 0x01afcae8 (8 bytes)
const MtDTI& uGUIPopDetail01::cPartsCaption::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uGUIPopDetail01::cPartsCaption::DTI;
}

// No out-of-line body: 1 inlined copy in 1 function (18 bytes)
//   in uGUIPopDetail01::cPartsCaption::MyDTI::newInstance at 0x00b9faf4-0x00b9fb06 (called at uGUIPopDetail01.cpp:48)
// MtAllocator* uGUIPopDetail01::cPartsCaption::getAllocator();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsCaption::setAllocator(u32);

// No out-of-line body: 1 inlined copy in 1 function (41 bytes)
//   in uGUIPopDetail01::cPartsCaption::MyDTI::newInstance at 0x00b9faf4-0x00b9fb1d (called at uGUIPopDetail01.cpp:48)
// void* uGUIPopDetail01::cPartsCaption::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsCaption::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsCaption::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsCaption::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN15uGUIPopDetail0113cPartsCaptionD0Ev at 0x01afcab0-0x01afcada, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void uGUIPopDetail01::cPartsCaption::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uGUIPopDetail01::cPartsCaption::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsCaption::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsCaption::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsCaption::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in uGUIPopDetail01::cPartsCaption::MyDTI::newInstance at 0x00b9fb1d-0x00b9fb56 (called at uGUIPopDetail01.cpp:48)
//   in uGUIPopDetail01::cPartsCaption::MyDTI::newInstance at 0x00b9fb1d-0x00b9fb56 (called at uGUIPopDetail01.h:189)
// uGUIPopDetail01::cPartsCaption::cPartsCaption();

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa884-0x00baa8bd (called at uGUIPopDetail01.cpp:48)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa884-0x00baa8bd (called at uGUIPopDetail01.h:186)
// uGUIPopDetail01::cPartsCaption::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00b9faf0 - 0x00b9fb5b (107 bytes)
__attribute__((weak)) MtObject* uGUIPopDetail01::cPartsCaption::MyDTI::newInstance() const {
    DDON_STUB("uGUIPopDetail01::cPartsCaption::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* uGUIPopDetail01::cPartsFooter::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsFooter::usage();

// Address: 0x01afca90 - 0x01afca98 (8 bytes)
const MtDTI& uGUIPopDetail01::cPartsFooter::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uGUIPopDetail01::cPartsFooter::DTI;
}

// No out-of-line body: 1 inlined copy in 1 function (18 bytes)
//   in uGUIPopDetail01::cPartsFooter::MyDTI::newInstance at 0x00b9fbd4-0x00b9fbe6 (called at uGUIPopDetail01.cpp:49)
// MtAllocator* uGUIPopDetail01::cPartsFooter::getAllocator();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsFooter::setAllocator(u32);

// No out-of-line body: 1 inlined copy in 1 function (41 bytes)
//   in uGUIPopDetail01::cPartsFooter::MyDTI::newInstance at 0x00b9fbd4-0x00b9fbfd (called at uGUIPopDetail01.cpp:49)
// void* uGUIPopDetail01::cPartsFooter::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsFooter::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsFooter::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsFooter::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN15uGUIPopDetail0112cPartsFooterD0Ev at 0x01afca60-0x01afca8a, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void uGUIPopDetail01::cPartsFooter::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uGUIPopDetail01::cPartsFooter::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsFooter::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsFooter::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsFooter::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in uGUIPopDetail01::cPartsFooter::MyDTI::newInstance at 0x00b9fbfd-0x00b9fc36 (called at uGUIPopDetail01.cpp:49)
//   in uGUIPopDetail01::cPartsFooter::MyDTI::newInstance at 0x00b9fbfd-0x00b9fc36 (called at uGUIPopDetail01.h:200)
// uGUIPopDetail01::cPartsFooter::cPartsFooter();

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa8bd-0x00baa8f6 (called at uGUIPopDetail01.cpp:49)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa8bd-0x00baa8f6 (called at uGUIPopDetail01.h:197)
// uGUIPopDetail01::cPartsFooter::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00b9fbd0 - 0x00b9fc3b (107 bytes)
__attribute__((weak)) MtObject* uGUIPopDetail01::cPartsFooter::MyDTI::newInstance() const {
    DDON_STUB("uGUIPopDetail01::cPartsFooter::MyDTI::newInstance")
    return nullptr;
}

// No out-of-line body: no code in the ELF
// MtDTI* uGUIPopDetail01::cPartsJob::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsJob::usage();

// Address: 0x01afc9f0 - 0x01afc9f8 (8 bytes)
const MtDTI& uGUIPopDetail01::cPartsJob::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uGUIPopDetail01::cPartsJob::DTI;
}

// No out-of-line body: 1 inlined copy in 1 function (18 bytes)
//   in uGUIPopDetail01::cPartsJob::MyDTI::newInstance at 0x00b9fcb4-0x00b9fcc6 (called at uGUIPopDetail01.cpp:50)
// MtAllocator* uGUIPopDetail01::cPartsJob::getAllocator();

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsJob::setAllocator(u32);

// No out-of-line body: 1 inlined copy in 1 function (41 bytes)
//   in uGUIPopDetail01::cPartsJob::MyDTI::newInstance at 0x00b9fcb4-0x00b9fcdd (called at uGUIPopDetail01.cpp:50)
// void* uGUIPopDetail01::cPartsJob::operator new(size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsJob::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsJob::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uGUIPopDetail01::cPartsJob::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// inferred: operator delete from _ZN15uGUIPopDetail019cPartsJobD0Ev at 0x01afc9c0-0x01afc9ea, its tail after the complete destructor, code DWARF attributes to no inlined copy; p_addr is its this; approximate: the deleting destructor's compare, which the body oracle reports, checks it
inline void uGUIPopDetail01::cPartsJob::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uGUIPopDetail01::cPartsJob::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsJob::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsJob::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uGUIPopDetail01::cPartsJob::operator delete[](void* p_addr, u32 align);

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in uGUIPopDetail01::cPartsJob::MyDTI::newInstance at 0x00b9fcdd-0x00b9fd16 (called at uGUIPopDetail01.cpp:50)
//   in uGUIPopDetail01::cPartsJob::MyDTI::newInstance at 0x00b9fcdd-0x00b9fd16 (called at uGUIPopDetail01.h:211)
// uGUIPopDetail01::cPartsJob::cPartsJob();

// No out-of-line body: 2 inlined copies in 1 function (114 bytes)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa8f6-0x00baa92f (called at uGUIPopDetail01.cpp:50)
//   in _GLOBAL__sub_I_uGUIPopDetail01.cpp at 0x00baa8f6-0x00baa92f (called at uGUIPopDetail01.h:208)
// uGUIPopDetail01::cPartsJob::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00b9fcb0 - 0x00b9fd1b (107 bytes)
__attribute__((weak)) MtObject* uGUIPopDetail01::cPartsJob::MyDTI::newInstance() const {
    DDON_STUB("uGUIPopDetail01::cPartsJob::MyDTI::newInstance")
    return nullptr;
}

// Instance at 0x01afc5e0 - 0x01afc5e5 (5 bytes) of the generic MtTypedArray<T>::~MtTypedArray
// Proven from the ELF: the body oracle checks this instance (022 D5).
template MtTypedArray<uGUIPopDetail01::cDupCraftParam>::~MtTypedArray();

// Instance at 0x01afc5f0 - 0x01afc5f5 (5 bytes) of the generic MtTypedArray<T>::~MtTypedArray
// Proven from the ELF: the body oracle checks this instance (022 D5).
template MtTypedArray<uGUIPopDetail01::cDupParam>::~MtTypedArray();

// Instance at 0x01afc5d0 - 0x01afc5d5 (5 bytes) of the generic MtTypedArray<T>::~MtTypedArray
// Proven from the ELF: the body oracle checks this instance (022 D5).
template MtTypedArray<uGUIPopDetail01::cPartsBase>::~MtTypedArray();

