// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "uGUINpcWindow.h"
#include "../shared/MtAllocator.h"
#include "../shared/MtCollection.h"
#include "../shared/MtDTI.h"
#include "../shared/MtMath.h"
#include "../shared/MtMemoryAllocator.h"
#include "../shared/MtObject.h"
#include "../shared/MtString.h"
#include "../shared/cControl.h"
#include "../shared/cResource.h"
#include "../shared/rArchiveListArray.h"
#include "../rGUI/rGUI.h"
#include "../shared/rGUIMessage.h"
#include "../shared/uGUIBase.h"
#include "uGUISystemMsg.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* uGUINpcWindow::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uGUINpcWindow::usage();

// Address: 0x01b09370 - 0x01b09378 (8 bytes)
const MtDTI& uGUINpcWindow::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uGUINpcWindow::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* uGUINpcWindow::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::uGUINpcWindow::DTI);
}

// No out-of-line body: no code in the ELF
// void uGUINpcWindow::setAllocator(u32);

// Address: 0x00ca8620 - 0x00ca8660 (64 bytes)
void* uGUINpcWindow::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::uGUINpcWindow::getAllocator()->memAlloc(sz, align, ::uGUINpcWindow::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* uGUINpcWindow::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUINpcWindow::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uGUINpcWindow::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void uGUINpcWindow::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uGUINpcWindow::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uGUINpcWindow::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uGUINpcWindow::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uGUINpcWindow::operator delete[](void* p_addr, u32 align);

// Omitted: mem-initializer not recorded in DWARF (base uGUISystemMsg has no default constructor)
// uGUINpcWindow::uGUINpcWindow();

// Address: 0x00ca8880 - 0x00ca88dd (93 bytes)
// Also emitted as: _ZN13uGUINpcWindowD0Ev at 0x00ca88e0
uGUINpcWindow::~uGUINpcWindow() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpGUIMsg != static_cast<rGUIMessage*>(nullptr)) {
        this->mpGUIMsg->::cResource::release();
        this->mpGUIMsg = static_cast<rGUIMessage*>(nullptr);
    }
    if (this->mpGUIRes == static_cast<rGUI*>(nullptr)) {
        return;
    }
    this->mpGUIRes->::cResource::release();
    this->mpGUIRes = static_cast<rGUI*>(nullptr);
}

// Address: 0x00ca8960 - 0x00ca8a0f (175 bytes)
bool uGUINpcWindow::loadResource() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpGUIRes == static_cast<rGUI*>(nullptr)) {
        if ((this->mpGUIRes = static_cast<rGUI*>(this->::uGUIBase::uiCreateResource(this->::uGUIBase::getArcTag(static_cast<u32>(0)), ::rArchiveListArray::convSearchId("RES_ID_NPCWINDOW04_GUI"), static_cast<u32>(129), static_cast<t64>(1432186983)))) != static_cast<rGUI*>(nullptr)) {
            if (this->mpGUIMsg == static_cast<rGUIMessage*>(nullptr)) {
                if ((this->mpGUIMsg = static_cast<rGUIMessage*>(this->::uGUIBase::uiCreateResource(this->::uGUIBase::getArcTag(static_cast<u32>(0)), ::rArchiveListArray::convSearchId("RES_ID_NPCWINDOW_RES_GMD"), static_cast<u32>(129), static_cast<t64>(0)))) != static_cast<rGUIMessage*>(nullptr)) {
                    this->mpGUIMsg;
                    return true;
                } else {
                    return false;
                }
            } else {
                return true;
            }
        } else {
            return false;
        }
    } else {
        if (this->mpGUIMsg == static_cast<rGUIMessage*>(nullptr)) {
            if ((this->mpGUIMsg = static_cast<rGUIMessage*>(this->::uGUIBase::uiCreateResource(this->::uGUIBase::getArcTag(static_cast<u32>(0)), ::rArchiveListArray::convSearchId("RES_ID_NPCWINDOW_RES_GMD"), static_cast<u32>(129), static_cast<t64>(0)))) != static_cast<rGUIMessage*>(nullptr)) {
                this->mpGUIMsg;
                return true;
            } else {
                return false;
            }
        } else {
            return true;
        }
    }
}

// Address: 0x00ca8a10 - 0x00ca8fe9 (1497 bytes)
__attribute__((weak)) void uGUINpcWindow::setup() {
    // local: f32 fCursorW;
    // local: f32 fCursorH;
    // local: cGUIInstAnimation* pInstNullChoiceOrg;
    // local: u32 i;
    // local: cGUIInstAnimation* inst_choice;
    // local: cGUIInstance* pInstIconQuestDupli;
    // local: cGUIInstance* pInstIconJobDupli;
    DDON_STUB("uGUINpcWindow::setup")
    /* stub */
}

// Address: 0x00ca9480 - 0x00ca94b1 (49 bytes)
void uGUINpcWindow::kill() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::uGUISystemMsg::kill();
    if (this->mpGUIRes == static_cast<rGUI*>(nullptr)) {
        return;
    }
    this->mpGUIRes->::cResource::release();
    this->mpGUIRes = static_cast<rGUI*>(nullptr);
}

// Address: 0x00ca9870 - 0x00ca987f (15 bytes)
void uGUINpcWindow::draw(cDraw* pDraw) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mIsDraw == false) {
        return;
    }
    this->::uGUIBase::draw(pDraw);
}

// Address: 0x00caa580 - 0x00caa670 (240 bytes)
void uGUINpcWindow::restart() {
    // Approximate from the ELF: loops the one-loop renderer refuses, rendered through regions; the body oracle reports this body.
    this->mRequestRestart = true;
    this->mIsMessageWait = true;
    this->::uGUISystemMsg::mMode = static_cast<u32>(0);
    if (this->::uGUISystemMsg::mArrayPageInfo.::MtArray::mLength != static_cast<u32>(0)) {
        // inferred: the value the loop at 0xcaa5c0 carries; DWARF names no local for it
        u32 v0_0 = this->::uGUISystemMsg::mArrayPageInfo.::MtArray::mLength;
        // inferred: the counter this loop steps; DWARF names no local for it
        for (unsigned int i0_3 = static_cast<unsigned int>(0);;) {
            if (this->::uGUISystemMsg::mArrayPageInfo.::MtArray::mpArray[i0_3] != static_cast<MtObject*>(nullptr)) {
                delete this->::uGUISystemMsg::mArrayPageInfo.::MtArray::mpArray[i0_3];
                if ((i0_3 + static_cast<unsigned int>(1)) < this->::uGUISystemMsg::mArrayPageInfo.::MtArray::mLength) {
                    v0_0 = this->::uGUISystemMsg::mArrayPageInfo.::MtArray::mLength;
                    i0_3 += static_cast<unsigned int>(1);
                } else {
                    break;
                }
            } else {
                if ((i0_3 + static_cast<unsigned int>(1)) < v0_0) {
                    i0_3 += static_cast<unsigned int>(1);
                } else {
                    break;
                }
            }
        }
    }
    if (this->::uGUISystemMsg::mArrayPageInfo.::MtArray::mpArray != static_cast<MtObject* *>(nullptr)) {
        ::MtMemoryAllocator::getAllocator(::MtArray::DTI)->memFree(static_cast<void*>(this->::uGUISystemMsg::mArrayPageInfo.::MtArray::mpArray));
    }
    this->::uGUISystemMsg::mArrayPageInfo.::MtArray::mpArray = static_cast<MtObject* *>(nullptr);
    this->::uGUISystemMsg::mArrayPageInfo.::MtArray::mBufsiz = static_cast<u32>(0);
    this->::uGUISystemMsg::mArrayPageInfo.::MtArray::mLength = static_cast<u32>(0);
    this->::uGUISystemMsg::mCurrentPage = static_cast<u32>(0);
    if (this->::uGUISystemMsg::mpCtrl != static_cast<cControl*>(nullptr)) {
        this->::uGUISystemMsg::mpCtrl->setPresetSE(static_cast<u32>(4), static_cast<u32>(8));
    }
    this->::uGUISystemMsg::mScrollList.::uGUIBase::cScrollList::clearInfo();
    this->::uGUIBase::setWindowActive(true);
}

// Address: 0x00caa670 - 0x00caa6a1 (49 bytes)
__attribute__((weak)) void uGUINpcWindow::finish() {
    DDON_STUB("uGUINpcWindow::finish")
    /* stub */
}

// Address: 0x00ca96e0 - 0x00ca9768 (136 bytes)
__attribute__((weak)) void uGUINpcWindow::move() {
    DDON_STUB("uGUINpcWindow::move")
    /* stub */
}

// No out-of-line body: no code in the ELF
// void uGUINpcWindow::setTextFromTextOld();

// Address: 0x00ca94d0 - 0x00ca95d2 (258 bytes)
__attribute__((weak)) void uGUINpcWindow::setNpcName(MT_CTSTR name) {
    // local: bool bEnable;
    DDON_STUB("uGUINpcWindow::setNpcName")
    /* stub */
}

// No out-of-line body: 1 inlined copy in 1 function (7 bytes)
//   in sGUIExt::setNpcWindowInfo at 0x007acea5-0x007aceac (called at sGUIExt.cpp:17674)
// void uGUINpcWindow::setNpcGender(u32 uGender);

// No out-of-line body: 1 inlined copy in 1 function (9 bytes)
//   in sGUIExt::setNpcWindowInfo at 0x007aceb3-0x007acebc (called at sGUIExt.cpp:17676)
// void uGUINpcWindow::setNpcEnjoymentDisp(bool bDisp);

// No out-of-line body: 1 inlined copy in 1 function (7 bytes)
//   in sGUIExt::setNpcWindowInfo at 0x007aceac-0x007aceb3 (called at sGUIExt.cpp:17675)
// void uGUINpcWindow::setNpcEnjoyment(u32 uNpcEnj);

// Address: 0x00ca95e0 - 0x00ca96d7 (247 bytes)
__attribute__((weak)) MtVector2 uGUINpcWindow::getChoiceWindowPos() {
    // local: MtVector2 vRet;
    // local: const MtVector2& alignmentPos;
    DDON_STUB("uGUINpcWindow::getChoiceWindowPos")
    __builtin_unreachable();
}

// Address: 0x01b09380 - 0x01b09387 (7 bytes)
bool uGUINpcWindow::isMessageWait() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return this->mIsMessageWait;
}

// No out-of-line body: 2 inlined copies in 2 functions (14 bytes)
//   in sGUIExt::setNpcWindowChoiceTitle at 0x007acfbf-0x007acfc6 (called at sGUIExt.cpp:17735)
//   in sGUIExt::addNpcWindowChoiceInfo at 0x007ad058-0x007ad05f (called at sGUIExt.cpp:17761)
// void uGUINpcWindow::reqUpdateDisp();

// Address: 0x00ca9880 - 0x00ca9885 (5 bytes)
void uGUINpcWindow::moveInput() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::uGUISystemMsg::moveInput();
}

// Address: 0x00ca9890 - 0x00ca98e2 (82 bytes)
void uGUINpcWindow::moveEvent() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->::uGUISystemMsg::mScrollList.::uGUIBase::cScrollList::moveEvent() != false) {
        this->::uGUINpcWindow::updateQuestGuide();
        this->::uGUISystemMsg::moveEvent();
    } else {
        if (this->::uGUIBase::mInputEventId == static_cast<u32>(68)) {
            this->::uGUISystemMsg::mScrollList.::uGUIBase::cScrollList::setListPos(false);
            this->::uGUINpcWindow::updateQuestGuide();
        } else {
            this->::uGUISystemMsg::moveEvent();
        }
    }
}

// Address: 0x00caa3e0 - 0x00caa544 (356 bytes)
__attribute__((weak)) void uGUINpcWindow::updateWait() {
    DDON_STUB("uGUINpcWindow::updateWait")
    /* stub */
}

// Address: 0x00ca9b00 - 0x00caa0a9 (1449 bytes)
__attribute__((weak)) void uGUINpcWindow::updateDisp(bool bInit) {
    // local: u32 uChoiceInfoDispNum;
    // local: cPageInfo* pPage;
    // local: MtSize sizeObjText;
    // local: f32 fListSizeSum;
    // local: f32 fWndwPosY;
    // local: f32 fPosYListInit;
    // local: f32 fPosYChoice;
    // local: f32 fPosYAddNpcEnjDisp;
    // local: MtSize sizeSum;
    // local: MtSize sizeWndwOut;
    // local: MtSize sizeWndwFrm;
    // local: f32 fMaskH;
    // local: f32 fPosYMaskOfs;
    // local: MtFloat2 sizeMask;
    // local: u32 i;
    DDON_STUB("uGUINpcWindow::updateDisp")
    /* stub */
}

// Address: 0x00ca9770 - 0x00ca9863 (243 bytes)
__attribute__((weak)) void uGUINpcWindow::updateInit() {
    // local: u32 i;
    // local: cPageInfo* pPage;
    DDON_STUB("uGUINpcWindow::updateInit")
    /* stub */
}

// Address: 0x00caa3b0 - 0x00caa3d7 (39 bytes)
__attribute__((weak)) void uGUINpcWindow::updateIn() {
    DDON_STUB("uGUINpcWindow::updateIn")
    /* stub */
}

// Address: 0x00ca92b0 - 0x00ca946e (446 bytes)
__attribute__((weak)) void uGUINpcWindow::updateOutStart() {
    // local: u32 i;
    DDON_STUB("uGUINpcWindow::updateOutStart")
    /* stub */
}

// Address: 0x00caa560 - 0x00caa56a (10 bytes)
void uGUINpcWindow::updateOut() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->mIsFinish = true;
    this->mIsDraw = false;
}

// Address: 0x00ca9470 - 0x00ca9471 (1 bytes)
__attribute__((weak)) void uGUINpcWindow::updateEnd() {
    // Empty in the binary (a single `ret`).
}

// No out-of-line body: no code in the ELF
// void uGUINpcWindow::updateExit();

// Address: 0x00ca8ff0 - 0x00ca92a6 (694 bytes)
__attribute__((weak)) void uGUINpcWindow::initScrollList() {
    // local: f32 fCursorW;
    // local: f32 fCursorH;
    // local: const MtFloat2 Rect;
    // local: u32 idx;
    // local: cScrollListItemBase& item;
    DDON_STUB("uGUINpcWindow::initScrollList")
    /* stub */
}

// Address: 0x00caa0b0 - 0x00caa3a5 (757 bytes)
__attribute__((weak)) void uGUINpcWindow::updateScrollList() {
    // local: s32 top;
    // local: cPageInfo* pPage;
    // local: MtVector4 cursorPos;
    // local: u32 uListNum;
    // local: u32 idx;
    // local: cScrollListInfoBase* plist;
    // local: f32 bar_length;
    // local: f32 disp_range;
    // local: f32 visible_top;
    // local: f32 visible_bottom;
    // local: cGUIObjPolygon* ppoly;
    DDON_STUB("uGUINpcWindow::updateScrollList")
    /* stub */
}

// Address: 0x00ca98f0 - 0x00ca9b00 (528 bytes)
__attribute__((weak)) void uGUINpcWindow::updateQuestGuide() {
    // local: cPageInfo* pPage;
    // local: cChoiceInfo* pChoiceInfo;
    // local: MtString str;
    DDON_STUB("uGUINpcWindow::updateQuestGuide")
    /* stub */
}

// Address: 0x00caa6b0 - 0x00caa81d (365 bytes)
__attribute__((weak)) void uGUINpcWindow::updateScrollListDisp(uGUIBase::cScrollListItemBase* pDispItem, uGUIBase::cScrollListInfoBase* pListItem, u32 Index) {
    // local: u32 dispIndex;
    // local: MtString str;
    // local: cPageInfo* pPage;
    // local: cChoiceInfo* pChoiceInfo;
    DDON_STUB("uGUINpcWindow::updateScrollListDisp")
    /* stub */
}

// Address: 0x00caa820 - 0x00caa821 (1 bytes)
__attribute__((weak)) void uGUINpcWindow::updateScrollListHide(uGUIBase::cScrollListItemBase* pDispItem) {
    // Empty in the binary (a single `ret`).
}

// No out-of-line body: 2 inlined copies in 2 functions (144 bytes)
//   in uGUINpcWindow::updateQuestGuide at 0x00ca9a50-0x00ca9a88, 0x00ca9a94-0x00ca9aa4 (called at uGUINpcWindow.cpp:978)
//   in uGUINpcWindow::updateWait at 0x00caa4e9-0x00caa531 (called at uGUINpcWindow.cpp:748)
// f32 uGUINpcWindow::getGuideMsgPosY();

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_uGUINpcWindow.cpp at 0x00caa92f-0x00caa96c (called at uGUINpcWindow.cpp:24)
//   in _GLOBAL__sub_I_uGUINpcWindow.cpp at 0x00caa92f-0x00caa96c (called at uGUINpcWindow.h:21)
// uGUINpcWindow::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00ca85e0 - 0x00ca8620 (64 bytes)
__attribute__((weak)) MtObject* uGUINpcWindow::MyDTI::newInstance() const {
    DDON_STUB("uGUINpcWindow::MyDTI::newInstance")
    return nullptr;
}

