// Generated by ddon-dwarf-reconstructor (Rust)
#include <new>
#include "uGUITutorialAnnounce.h"
#include "../shared/MtAllocator.h"
#include "../shared/MtDTI.h"
#include "../shared/MtMemoryAllocator.h"
#include "../shared/cGUIObject.h"
#include "../shared/cResource.h"
#include "../shared/rArchiveListArray.h"
#include "../rGUI/rGUI.h"
#include "../shared/sGUIExt.h"
#include "../shared/uGUI.h"
#include "../shared/uGUIBase.h"
#ifndef DDON_STUB
#define DDON_STUB(name)
#endif

// No out-of-line body: no code in the ELF
// MtDTI* uGUITutorialAnnounce::getMyDTIPtr();

// No out-of-line body: no code in the ELF
// void uGUITutorialAnnounce::usage();

// Address: 0x01b07db0 - 0x01b07db8 (8 bytes)
const MtDTI& uGUITutorialAnnounce::getDTI() const {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return uGUITutorialAnnounce::DTI;
}

// Inline, no code of its own: checked where it is inlined (rendered.json inline_proofs).
inline MtAllocator* uGUITutorialAnnounce::getAllocator() {
    return ::MtMemoryAllocator::getAllocator(::uGUITutorialAnnounce::DTI);
}

// No out-of-line body: no code in the ELF
// void uGUITutorialAnnounce::setAllocator(u32);

// Address: 0x00c63f60 - 0x00c63fa0 (64 bytes)
void* uGUITutorialAnnounce::operator new(size_t sz, u32 align) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    return ::uGUITutorialAnnounce::getAllocator()->memAlloc(sz, align, ::uGUITutorialAnnounce::DTI.::MtDTI::getID());
}

// No out-of-line body: no code in the ELF
// void* uGUITutorialAnnounce::operator new[](size_t sz, u32 align);

// No out-of-line body: no code in the ELF
// void* uGUITutorialAnnounce::operator new(size_t sz, void* p_addr);

// No out-of-line body: no code in the ELF
// void* uGUITutorialAnnounce::operator new[](size_t sz, void* p_addr);

// Inline, no code of its own: checked where it is inlined.
// approximate: from its inlined copy in the deleting destructor, whose compare the body oracle reports
inline void uGUITutorialAnnounce::operator delete(void* p_addr) {
    ::MtMemoryAllocator::getAllocator(::uGUITutorialAnnounce::DTI)->memFree(p_addr);
}

// No out-of-line body: no code in the ELF
// void uGUITutorialAnnounce::operator delete[](void* p_addr);

// No out-of-line body: no code in the ELF
// void uGUITutorialAnnounce::operator delete(void* p_addr, u32 align);

// No out-of-line body: no code in the ELF
// void uGUITutorialAnnounce::operator delete[](void* p_addr, u32 align);

// Address: 0x00c64910 - 0x00c649d7 (199 bytes)
void uGUITutorialAnnounce::ctrlVisible() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpObj_Null_icon == static_cast<cGUIObject*>(nullptr)) {
    } else {
        this->mpObj_Null_icon->::cGUIObject::setVisible(this->mDispObjIcon);
    }
    if (this->mpObj_Null_icon_pt == static_cast<cGUIObject*>(nullptr)) {
    } else {
        this->mpObj_Null_icon_pt->::cGUIObject::setVisible(this->mDispObjIconPt);
    }
    if (this->mpObj_Null_icon_entry == static_cast<cGUIObject*>(nullptr)) {
    } else {
        this->mpObj_Null_icon_entry->::cGUIObject::setVisible(this->mDispObjIconEntry);
    }
    if (this->mpObj_Null_icon_matching == static_cast<cGUIObject*>(nullptr)) {
    } else {
        this->mpObj_Null_icon_matching->::cGUIObject::setVisible(this->mDispObjIconMatching);
    }
    if (this->mpObj_Null_msg == static_cast<cGUIObject*>(nullptr)) {
    } else {
        this->mpObj_Null_msg->::cGUIObject::setVisible(this->mDispObjMsg);
    }
    if (this->mpObj_Null_msg_pt == static_cast<cGUIObject*>(nullptr)) {
    } else {
        this->mpObj_Null_msg_pt->::cGUIObject::setVisible(this->mDispObjMsgPt);
    }
    if (this->mpObj_Null_entry == static_cast<cGUIObject*>(nullptr)) {
    } else {
        this->mpObj_Null_entry->::cGUIObject::setVisible(this->mDispObjMsgEntry);
    }
    this->::uGUITutorialAnnounce::setLineFrame(this->mLineFrame);
}

// Address: 0x00c64c10 - 0x00c64d3f (303 bytes)
__attribute__((weak)) void uGUITutorialAnnounce::setLineFrame(f32 frame) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpObj_line_top00 == static_cast<cGUIObject*>(nullptr)) {
    } else {
        this->mpObj_line_top00->::cGUIObject::setCurrentFrame(frame, true);
    }
    if (this->mpObj_line_top01 == static_cast<cGUIObject*>(nullptr)) {
    } else {
        this->mpObj_line_top01->::cGUIObject::setCurrentFrame(frame, true);
    }
    if (this->mpObj_line_top02 == static_cast<cGUIObject*>(nullptr)) {
    } else {
        this->mpObj_line_top02->::cGUIObject::setCurrentFrame(frame, true);
    }
    if (this->mpObj_line_top03 == static_cast<cGUIObject*>(nullptr)) {
    } else {
        this->mpObj_line_top03->::cGUIObject::setCurrentFrame(frame, true);
    }
    if (this->mpObj_line_top10 == static_cast<cGUIObject*>(nullptr)) {
    } else {
        this->mpObj_line_top10->::cGUIObject::setCurrentFrame(frame, true);
    }
    if (this->mpObj_line_top11 == static_cast<cGUIObject*>(nullptr)) {
    } else {
        this->mpObj_line_top11->::cGUIObject::setCurrentFrame(frame, true);
    }
    if (this->mpObj_line_top12 == static_cast<cGUIObject*>(nullptr)) {
    } else {
        this->mpObj_line_top12->::cGUIObject::setCurrentFrame(frame, true);
    }
    if (this->mpObj_line_top13 == static_cast<cGUIObject*>(nullptr)) {
        return;
    }
    this->mpObj_line_top13->::cGUIObject::setCurrentFrame(frame, true);
}

// Omitted: mem-initializer not recorded in DWARF (base uGUIBase has no default constructor)
// uGUITutorialAnnounce::uGUITutorialAnnounce();

// Address: 0x00c640a0 - 0x00c640ff (95 bytes)
// Also emitted as: _ZN20uGUITutorialAnnounceD0Ev at 0x00c64100
uGUITutorialAnnounce::~uGUITutorialAnnounce() {
    DDON_STUB("uGUITutorialAnnounce::~uGUITutorialAnnounce")
    /* stub */
}

// Address: 0x00c64180 - 0x00c64185 (5 bytes)
void uGUITutorialAnnounce::createProperty(MtPropertyList& s) {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::uGUI::createProperty(s);
}

// Address: 0x00c64190 - 0x00c641f8 (104 bytes)
bool uGUITutorialAnnounce::loadResource() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    if (this->mpGUIRes == static_cast<rGUI*>(nullptr)) {
        if ((this->mpGUIRes = static_cast<rGUI*>(this->::uGUIBase::uiCreateResource(this->::uGUIBase::getArcTag(static_cast<u32>(0)), ::rArchiveListArray::convSearchId("RES_ID_TUTORIAL_ANNOUNCE_GUI"), static_cast<u32>(129), static_cast<t64>(1439441373)))) != static_cast<rGUI*>(nullptr)) {
            this->mpGUIRes;
            return true;
        } else {
            return false;
        }
    } else {
        return true;
    }
}

// Address: 0x00c64200 - 0x00c64904 (1796 bytes)
__attribute__((weak)) void uGUITutorialAnnounce::setup() {
    // local: MtString charName;
    // local: CClientPartyListInfo& partyInfo;
    // local: const stEntryInvitedInfo* pInfo;
    // local: MtString charName;
    DDON_STUB("uGUITutorialAnnounce::setup")
    /* stub */
}

// Address: 0x00c64a00 - 0x00c64a31 (49 bytes)
void uGUITutorialAnnounce::kill() {
    // Proven from the ELF: the body oracle checks this body (022 D5).
    this->::uGUIBase::kill();
    if (this->mpGUIRes == static_cast<rGUI*>(nullptr)) {
        return;
    }
    this->mpGUIRes->::cResource::release();
    this->mpGUIRes = static_cast<rGUI*>(nullptr);
}

// Address: 0x00c64a40 - 0x00c64ab6 (118 bytes)
__attribute__((weak)) void uGUITutorialAnnounce::move() {
    // local: MtVector4 v4ColScale;
    DDON_STUB("uGUITutorialAnnounce::move")
    /* stub */
}

// No out-of-line body: 1 inlined copy in 1 function (7 bytes)
//   in sGUIExt::setReqTutorialAnnounce at 0x0079c4a3-0x0079c4aa (called at sGUIExt.cpp:11753)
// void uGUITutorialAnnounce::setAnnounceType(sGUIExt::ANNOUNCE_TYPE type);

// No out-of-line body: 2 inlined copies in 2 functions (12 bytes)
//   in sGUIExt::setReqTutorialAnnounce at 0x0079c437-0x0079c43d (called at sGUIExt.cpp:11736)
//   in sGUIExt::getReqTutorialAnnounceType at 0x007a4897-0x007a489d (called at sGUIExt.cpp:11785)
// sGUIExt::ANNOUNCE_TYPE uGUITutorialAnnounce::getAnnounceType() const;

// Address: 0x00c649e0 - 0x00c649fa (26 bytes)
__attribute__((weak)) void uGUITutorialAnnounce::updateInit() {
    DDON_STUB("uGUITutorialAnnounce::updateInit")
    /* stub */
}

// Address: 0x00c64ac0 - 0x00c64bf2 (306 bytes)
__attribute__((weak)) void uGUITutorialAnnounce::updateWait() {
    // local: bool bDrawOld;
    // local: bool bDraw;
    DDON_STUB("uGUITutorialAnnounce::updateWait")
    /* stub */
}

// No out-of-line body: no code in the ELF
// void uGUITutorialAnnounce::updateExit();

// No out-of-line body: 2 inlined copies in 1 function (122 bytes)
//   in _GLOBAL__sub_I_uGUITutorialAnnounce.cpp at 0x00c64e3f-0x00c64e7c (called at uGUITutorialAnnounce.cpp:50)
//   in _GLOBAL__sub_I_uGUITutorialAnnounce.cpp at 0x00c64e3f-0x00c64e7c (called at uGUITutorialAnnounce.h:22)
// uGUITutorialAnnounce::MyDTI::MyDTI(MT_CTSTR class_name, MtDTI* ps, size_t size, u32 id, u32 attr);

// Address: 0x00c63ea0 - 0x00c63f57 (183 bytes)
__attribute__((weak)) MtObject* uGUITutorialAnnounce::MyDTI::newInstance() const {
    DDON_STUB("uGUITutorialAnnounce::MyDTI::newInstance")
    return nullptr;
}

